import type{CanonicalDeurEvent,DeurCompletionEvidence,DeurCorrectionReasonCode,DeurOdometerCheckpoint,DeurQuantityEvidence,DeurRecord}from"../../types";
import{canCreateDeurCorrection}from"./canCreateDeurCorrection";import{resolveEffectiveDeurRevision}from"./resolveEffectiveDeurRevision";import{buildDeurOdometerTripEvidence}from"../buildDeurOdometerTripEvidence";import{normalizeCompletionEvidence,normalizeQuantityEvidence}from"../deurEvidence";import{deriveDeurEventState}from"../deriveDeurEventState";import{calculateDeurTotals}from"../calculateDeurTotals";
import{isCalendarDate}from"../../expectation/dateRules";
const reasons=new Set<DeurCorrectionReasonCode>(["INCORRECT_TIME_ENTRY","MISSING_TIME_ENTRY","INCORRECT_ACTIVITY","INCORRECT_WORK_DESCRIPTION","INCORRECT_COST_CODE","INCORRECT_ODOMETER","INCORRECT_TRIP_CHECKPOINT","INCORRECT_QUANTITY","INCORRECT_OPERATOR","INCORRECT_PROJECT","INCORRECT_EQUIPMENT","INCORRECT_COMMERCIAL_REFERENCE","CUSTOMER_REQUESTED_CORRECTION","DATA_ENCODING_ERROR","OTHER"]);
export interface CreateCorrectionInput{source:DeurRecord;chain:DeurRecord[];reasonCode:DeurCorrectionReasonCode;reasonDetails?:string;actor:{id?:string;name:string;role?:string;permissionGranted?:boolean};timestamp:string;newId:string;newDeurNumber?:string;changes?:{workDate?:string;shift?:DeurRecord["shift"];events?:CanonicalDeurEvent[];odometerCheckpoints?:DeurOdometerCheckpoint[];quantityEvidence?:DeurQuantityEvidence;completionEvidence?:DeurCompletionEvidence;operationalRemarks?:string}}
export type CreateCorrectionResult={success:true;sourceRevision:DeurRecord;revision:DeurRecord}|{success:false;code:string;message:string};
export function createDeurCorrectionRevision(input:CreateCorrectionInput):CreateCorrectionResult{
 const{source,actor}=input,details=input.reasonDetails?.trim();if(!canCreateDeurCorrection(actor))return{success:false,code:"NOT_AUTHORIZED",message:"Only an Admin can create a DEUR correction."};if(!reasons.has(input.reasonCode))return{success:false,code:"CORRECTION_REASON_REQUIRED",message:"A controlled correction reason is required."};if(input.reasonCode==="OTHER"&&!details)return{success:false,code:"CORRECTION_DETAILS_REQUIRED",message:"Correction details are required for Other."};if(!actor.name.trim()||!Number.isFinite(Date.parse(input.timestamp))||!input.newId.trim())return{success:false,code:"INVALID_CORRECTION",message:"Correction identity, actor, and timestamp are required."};if(source.billingLocked||source.billingStatementId||source.billId||source.status==="Billed")return{success:false,code:"CORRECTION_NOT_ALLOWED_AFTER_BILLING",message:"A billed or locked DEUR cannot be corrected."};if(source.revision?.supersededByRevisionId)return{success:false,code:"REVISION_ALREADY_SUPERSEDED",message:"A superseded revision cannot be corrected."};
 const resolution=resolveEffectiveDeurRevision(input.chain);if(!resolution.valid)return{success:false,code:"REVISION_CHAIN_INVALID",message:resolution.issues[0].message};if(resolution.pendingCorrection)return{success:false,code:"CORRECTION_ALREADY_PENDING",message:"A correction is already pending."};if(resolution.currentEffective&&resolution.currentEffective.id!==source.id)return{success:false,code:"REVISION_NOT_EFFECTIVE",message:"Only the effective revision can be corrected."};
 const chainId=source.revision?.chainId??source.id,originalDeurId=source.revision?.originalDeurId??source.id,nextNumber=Math.max(...input.chain.map(r=>r.revision?.revisionNumber??1))+1;
 const sourceRevision=structuredClone(source);sourceRevision.revision??={chainId,revisionNumber:1,originalDeurId};
 const revision=structuredClone(source);revision.id=input.newId;revision.deurNumber=input.newDeurNumber;revision.status="Draft";revision.createdAt=input.timestamp;revision.updatedAt=input.timestamp;revision.submittedAt=undefined;revision.submittedBy=undefined;revision.acknowledgedAt=undefined;revision.acknowledgedBy=undefined;revision.acknowledgedByUserId=undefined;revision.acknowledgementRemarks=undefined;revision.rejectedAt=undefined;revision.rejectedBy=undefined;revision.rejectedByUserId=undefined;revision.rejectionReason=undefined;revision.billingLocked=false;revision.billingStatementId=undefined;revision.billId=undefined;revision.reviewHistory=[];
 revision.revision={chainId,revisionNumber:nextNumber,originalDeurId,previousRevisionId:source.id,correctionReasonCode:input.reasonCode,...(details?{correctionReasonDetails:details}:{}),correctedByName:actor.name.trim(),...(actor.id?.trim()?{correctedByUserId:actor.id.trim()}:{}),correctedAt:new Date(input.timestamp).toISOString()};
 const changes=input.changes;if(changes?.operationalRemarks!==undefined)revision.operationalRemarks=changes.operationalRemarks.trim()||undefined;
 if(changes?.workDate!==undefined){if(!isCalendarDate(changes.workDate))return{success:false,code:"WORK_DATE_INVALID",message:"Corrected work date is invalid."};revision.workDate=changes.workDate;revision.reportDate=changes.workDate}
 if(changes?.shift!==undefined)revision.shift=changes.shift;
 if(changes?.events){const state=deriveDeurEventState({...revision,events:changes.events}),calc=calculateDeurTotals(changes.events);if(state.structuralIssues.length||calc.calculationIssues.length)return{success:false,code:"INVALID_EVENT_HISTORY",message:"Corrected timeline evidence is invalid."};revision.events=structuredClone(changes.events);revision.totals=calc.totals;revision.totalOperatingMinutes=calc.totals.operationMinutes;revision.totalIdleMinutes=calc.totals.idleMinutes;revision.totalMealBreakMinutes=calc.totals.mealBreakMinutes;revision.totalMaintenanceMinutes=calc.totals.breakdownMinutes}
 if(changes?.odometerCheckpoints){const built=buildDeurOdometerTripEvidence(changes.odometerCheckpoints);if(!built.success)return{success:false,code:"ODOMETER_EVIDENCE_INVALID",message:built.issues[0]};revision.odometerTripEvidence=built.evidence}
 if(changes?.quantityEvidence){const quantity=normalizeQuantityEvidence(changes.quantityEvidence);if(!quantity)return{success:false,code:"QUANTITY_INVALID",message:"Corrected quantity evidence is invalid."};revision.quantityEvidence=quantity}
 if(changes?.completionEvidence){const completion=normalizeCompletionEvidence(changes.completionEvidence);if(!completion)return{success:false,code:"COMPLETION_EVIDENCE_INVALID",message:"Corrected completion evidence is invalid."};revision.completionEvidence=completion}
 return{success:true,sourceRevision,revision};
}
