import type {ReactNode} from "react";
import {Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import type {CustomReportSection} from "../services/customReportWorkspace";
import {buildModernReportViewModel,reportTheme,type ReportMetricPresentation} from "../services/reportPresentation";
import type {ReportReviewMode} from "../services/reportComposition";

export default function ModernReportDocument({name,mode,period,comparisonPeriod,generatedAt,preparedBy,sections,analysis}:{name:string;mode:ReportReviewMode;period:string;comparisonPeriod?:string;generatedAt:Date;preparedBy:string;sections:readonly CustomReportSection[];analysis?:ReactNode}){const view=buildModernReportViewModel(sections);return <article className="report-document min-h-[700px] overflow-hidden rounded-xl bg-white text-slate-900 shadow-xl [print-color-adjust:exact] [-webkit-print-color-adjust:exact]"><header className="relative overflow-hidden border-b-2 border-blue-600 bg-gradient-to-r from-white via-white to-blue-50 px-6 py-6 sm:px-9"><div className="absolute -right-12 -top-20 h-56 w-56 rounded-full bg-blue-100/70"/><div className="absolute right-12 top-3 h-32 w-32 rounded-full bg-blue-50"/><div className="relative"><div className="flex items-center gap-3"><img className="h-10 w-10 object-contain" src="/branding/primary-structures-corporation-logo.png" alt="Primary Structures Corporation logo"/><div className="text-sm font-extrabold leading-tight text-[#0f2346]">PRIMARY STRUCTURES<br/>CORPORATION</div></div><p className="mt-4 text-xs font-semibold text-blue-700">Equipment Department</p><h2 className="mt-1 text-2xl font-bold text-[#0f2346]">{name}</h2><p className="mt-2 text-xs text-slate-600">{mode==="executive"?"Executive Review":"Technical Review"} · Period: {period}{comparisonPeriod?` · Previous: ${comparisonPeriod}`:""}</p><p className="mt-1 text-[11px] text-slate-500">Generated {generatedAt.toLocaleString()} · Prepared by {preparedBy}</p></div></header><div className="space-y-5 px-6 py-5 sm:px-9"><ReportSection title="Executive Summary"><MetricGrid metrics={view.executiveMetrics} columns="grid-cols-2 sm:grid-cols-4 xl:grid-cols-7"/></ReportSection>{analysis}{view.sections.map(section=><ReportSection title={section.title} key={section.id}><div className={section.utilization===undefined?"":"grid gap-4 lg:grid-cols-[minmax(0,1fr)_170px]"}><MetricGrid metrics={section.metrics}/>{section.utilization!==undefined&&<UtilizationGauge value={section.utilization}/>}</div>{section.reportType!=="assignments"&&section.metrics.some(item=>item.metric.numericValue!==undefined)&&<ComparisonChart title={`${section.title} Comparison`} metrics={section.metrics}/>} {mode==="technical"&&section.rows.length>0&&<div className="mt-4 overflow-x-auto"><table className="w-full border-collapse text-[10px]"><thead className="bg-slate-100"><tr>{section.columns.map(column=><th className="p-2 text-left" key={column}>{column}</th>)}</tr></thead><tbody>{section.rows.map((row,index)=><tr className="border-b" key={index}>{row.map((cell,i)=><td className="p-2" key={i}>{cell}</td>)}</tr>)}</tbody></table></div>}</ReportSection>)}</div><footer className="flex items-center justify-between bg-blue-700 px-8 py-4 text-[10px] text-white"><span>Generated {generatedAt.toLocaleString()}</span><span>Prepared by {preparedBy}</span></footer></article>}

export function ReportSection({title,children}:{title:string;children:ReactNode}){return <section className="break-inside-avoid"><h3 className="mb-3 border-l-[3px] border-blue-600 pl-2 text-sm font-bold text-[#0f2346]">{title}</h3>{children}</section>}
export function MetricGrid({metrics,columns="grid-cols-2 lg:grid-cols-4"}:{metrics:readonly ReportMetricPresentation[];columns?:string}){return <div className={`grid gap-2 ${columns}`}>{metrics.map((item,index)=><MetricCard item={item} key={`${item.metric.label}-${index}`}/>)}</div>}
export function MetricCard({item}:{item:ReportMetricPresentation}){const styles={blue:"bg-blue-100 text-blue-700",green:"bg-green-100 text-green-700",purple:"bg-purple-100 text-purple-700",red:"bg-red-100 text-red-700",orange:"bg-amber-100 text-amber-700"};return <article className="flex min-w-0 items-center gap-2 rounded-lg border border-slate-200 bg-white p-3 shadow-sm"><span aria-hidden="true" className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold ${styles[item.accent]}`}>{item.symbol}</span><div className="min-w-0"><p className="truncate text-[10px] text-slate-500">{item.metric.label}</p><p className="truncate text-sm font-bold text-[#0f2346]">{item.metric.value}</p></div></article>}
export function UtilizationGauge({value}:{value:number}){return <div className="grid place-items-center rounded-lg border border-slate-200 bg-white p-3 shadow-sm"><div aria-label={`${Math.round(value)} percent utilization rate`} className="grid h-28 w-28 place-items-center rounded-full" style={{background:`conic-gradient(${reportTheme.primary} ${value*3.6}deg,#e2e8f0 0)`}}><div className="grid h-20 w-20 place-items-center rounded-full bg-white text-center"><div><b className="text-xl text-[#0f2346]">{Math.round(value)}%</b><span className="block text-[9px] text-slate-500">Utilization Rate</span></div></div></div></div>}
export function ComparisonChart({title,metrics}:{title:string;metrics:readonly ReportMetricPresentation[]}){const chart=metrics.filter(item=>item.metric.numericValue!==undefined).map(item=>({name:item.metric.label,Current:item.metric.numericValue??0,Previous:item.metric.previousValue??0})),empty=chart.every(item=>item.Current===0&&item.Previous===0);return <div className="mt-4 break-inside-avoid"><h4 className="mb-2 border-l-[3px] border-blue-600 pl-2 text-xs font-bold text-[#0f2346]">{title}</h4><div className="relative h-40 rounded-lg border border-slate-200 bg-white p-2 shadow-sm" aria-label={`${title}, current versus previous period`}><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="name" tick={{fontSize:8}}/><YAxis domain={empty?[0,1]:undefined} tick={{fontSize:8}}/><Tooltip/><Legend wrapperStyle={{fontSize:9}}/><Bar dataKey="Current" name="Current Period" fill={reportTheme.primary} radius={[3,3,0,0]}/><Bar dataKey="Previous" name="Previous Period" fill={reportTheme.previous} radius={[3,3,0,0]}/></BarChart></ResponsiveContainer>{empty&&<p className="pointer-events-none absolute inset-x-0 top-1/2 text-center text-[10px] text-slate-400">No activity recorded for the selected periods.</p>}</div></div>}
