import type { User } from "@/features/auth/domain/user";
import type { AuthorizationAuditEvent, AdminRole } from "../domain/contracts";

export const auditActionLabels:Readonly<Record<string,string>>={ROLE_PERMISSION_ADDED:"Permission Added to Role",ROLE_PERMISSION_REMOVED:"Permission Removed from Role",ROLE_PERMISSIONS_RESET:"Role Permissions Reset",USER_CREATED:"User Created",USER_UPDATED:"User Updated",USER_ACTIVATED:"User Activated",USER_DEACTIVATED:"User Deactivated",USER_ROLE_ASSIGNED:"Role Assigned to User",USER_ROLE_REMOVED:"Role Removed from User",USER_OPERATOR_LINKED:"Operator Linked",USER_OPERATOR_UNLINKED:"Operator Unlinked",USER_ACCESS_RESET:"User Access Reset",USER_DELETED:"User Deleted",ROLE_CLONED:"Role Cloned",CUSTOM_ROLE_CREATED:"Role Created",CUSTOM_ROLE_UPDATED:"Role Updated",CUSTOM_ROLE_DEACTIVATED:"Role Deactivated"};
export interface AuditIdentityPresentation{primary:string;secondary:string;technicalId:string}
export interface AuditEventPresentation{actionLabel:string;actor:AuditIdentityPresentation;target:AuditIdentityPresentation;details:string[];searchText:string}
const words=(value:string)=>value.replaceAll(/[._-]+/g," ").replace(/\b\w/g,x=>x.toUpperCase());
const meta=(event:AuthorizationAuditEvent,key:string)=>{const value=event.metadata?.[key];return typeof value==="string"?value:undefined};
const identity=(id:string,user:User|undefined,snapshotName?:string,snapshotUsername?:string):AuditIdentityPresentation=>user?{primary:user.displayName,secondary:user.username,technicalId:id}:snapshotName||snapshotUsername?{primary:snapshotName??snapshotUsername!,secondary:snapshotUsername??"Historical account",technicalId:id}:{primary:"Deleted / unavailable user",secondary:"Identity snapshot unavailable",technicalId:id};
export function presentAuditEvent(event:AuthorizationAuditEvent,users:readonly User[],roles:readonly Pick<AdminRole,"code"|"name">[]):AuditEventPresentation{
 const actor=identity(event.actorId,users.find(x=>x.id===event.actorId),meta(event,"actorDisplayName"),meta(event,"actorUsername"));
 const role=event.targetType==="ROLE"?roles.find(x=>x.code===event.targetId):undefined;
 const target=event.targetType==="ROLE"?{primary:role?.name??words(event.targetId),secondary:event.targetId,technicalId:event.targetId}:identity(event.targetId,users.find(x=>x.id===event.targetId),meta(event,"targetDisplayName")??meta(event,"displayName"),meta(event,"targetUsername")??meta(event,"username"));
 const roleNames=(codes:readonly string[]|undefined)=>codes?.map(code=>roles.find(x=>x.code===code)?.name??words(code)).join(", ")??"None";const permission=meta(event,"permissionCode");let details:string[];
 switch(event.action){case"USER_ACTIVATED":details=["Account status changed to Active."];break;case"USER_DEACTIVATED":details=["Account status changed to Inactive."];break;case"USER_CREATED":details=[`Roles: ${roleNames(event.afterRoleCodes)}`];break;case"USER_DELETED":details=["User account deleted; audit evidence retained.",`Previous roles: ${roleNames(event.beforeRoleCodes)}`];break;case"USER_ACCESS_RESET":details=["Account access credentials were reset. Secret values are not recorded."];break;case"USER_UPDATED":details=JSON.stringify(event.beforeRoleCodes)!==JSON.stringify(event.afterRoleCodes)?[`Roles changed from ${roleNames(event.beforeRoleCodes)} to ${roleNames(event.afterRoleCodes)}.`]:["User profile updated."];break;case"USER_ROLE_ASSIGNED":details=[`Role assigned: ${roleNames([meta(event,"role")??event.afterRoleCodes?.at(-1)??""])}`];break;case"USER_ROLE_REMOVED":details=[`Role removed: ${roleNames([meta(event,"role")??event.beforeRoleCodes?.at(-1)??""])}`];break;case"USER_OPERATOR_LINKED":details=[`Operator linked${meta(event,"operatorId")?`: ${meta(event,"operatorId")}`:"."}`];break;case"USER_OPERATOR_UNLINKED":details=["Operator link removed."];break;case"ROLE_PERMISSION_ADDED":details=[`Permission added: ${permission?words(permission):"Unspecified permission"}`,permission??""];break;case"ROLE_PERMISSION_REMOVED":details=[`Permission removed: ${permission?words(permission):"Unspecified permission"}`,permission??""];break;case"ROLE_PERMISSIONS_RESET":details=["Role permissions reset to the protected catalog default."];break;case"CUSTOM_ROLE_CREATED":case"ROLE_CLONED":details=["Role configuration created."];break;case"CUSTOM_ROLE_UPDATED":details=["Role configuration updated."];break;case"CUSTOM_ROLE_DEACTIVATED":details=["Role status changed to Inactive."];break;default:details=[permission?`Permission: ${permission}`:"Administrative change recorded."]}
 details=details.filter(Boolean);const actionLabel=auditActionLabels[event.action]??words(event.action);return{actionLabel,actor,target,details,searchText:[actionLabel,event.action,actor.primary,actor.secondary,actor.technicalId,target.primary,target.secondary,target.technicalId,...details,Object.values(event.metadata??{})].join(" ").toLowerCase()};
}
