import { Link } from "react-router-dom";
import DetailsDrawer from "@/components/ui/DetailsDrawer";
import type { EquipmentRecord } from "@/features/equipment/types";
import { meterRequirementForMaintenanceType } from "@/features/equipment/services/maintenanceMeterPolicy";

export default function LocalEquipmentQuickDetails({ equipment, onClose, assignment }: { equipment?: EquipmentRecord; onClose: () => void; assignment?: { operator?: string; project?: string; assignedDate?: string; expectedReturn?: string; rentalNumber?: string; rentalStatus?: string } }) {
  const row = (label: string, value?: string | number) => <div className="flex justify-between gap-4 border-b border-slate-100 py-2 text-sm dark:border-slate-800"><dt className="text-slate-500">{label}</dt><dd className="text-right font-medium">{value || value === 0 ? value : "—"}</dd></div>;
  return <DetailsDrawer open={Boolean(equipment)} title={equipment ? `${equipment.assetNo} · ${equipment.equipmentName}` : "Equipment details"} onClose={onClose}>{equipment && <div className="space-y-5"><section><h3 className="font-semibold">Identity</h3><dl>{row("Category", equipment.category)}{row("Subcategory", equipment.subcategoryName)}{row("Status", equipment.status)}{row("Condition", equipment.condition)}{row("Location", equipment.location)}</dl></section><section><h3 className="font-semibold">Allocation</h3><dl>{row("Operator", assignment?.operator)}{row("Project", assignment?.project)}{row("Assigned", assignment?.assignedDate)}{row("Expected return", assignment?.expectedReturn)}</dl></section><section><h3 className="font-semibold">Rental</h3><dl>{row("Rental", assignment?.rentalNumber)}{row("Status", assignment?.rentalStatus)}</dl></section><section><h3 className="font-semibold">Maintenance</h3><dl>{row("Type", equipment.maintenanceType)}{row("Meter requirement", meterRequirementForMaintenanceType(equipment.maintenanceType))}{row("Current reading", equipment.currentReading)}</dl></section><Link className="inline-flex rounded bg-slate-900 px-3 py-2 text-sm font-medium text-white dark:bg-slate-100 dark:text-slate-900" to={`/equipment/${equipment.id}`}>View full equipment</Link></div>}</DetailsDrawer>;
}
