import type { CustomerRecord } from "@/features/customer/types";
import { createEquipmentWithCategoryAssetNumber, normalizeEquipmentCategory } from "@/features/equipment/services/categoryAssetNumber";
import type { EquipmentRecord, EquipmentStatus } from "@/features/equipment/types";
import type { Operator } from "@/features/operators/types";
import type { ProjectRecord, ProjectStatus } from "@/features/project/types";
import type { PrefixRecord } from "@/features/settings/types";
import type { MigrationCompletion, MigrationEntitySheet, MigrationIssue, MigrationPlan, MigrationWorkbookRows } from "./types";

export interface MigrationReferences {
  equipment: EquipmentRecord[]; operators: Operator[]; customers: CustomerRecord[]; projects: ProjectRecord[]; prefixes: PrefixRecord[];
  categories: Array<{ id: string; name: string; active: boolean }>;
  subcategories: Array<{ id: string; categoryId: string; name: string; active: boolean }>;
  costCodes: Array<{ id: string; code: string; active: boolean }>;
}
const statuses: EquipmentStatus[] = ["Available", "Assigned", "Rented", "Maintenance"];
const operatorStatuses: Operator["status"][] = ["Active", "On Leave", "Suspended"];
const certificationTypes: Operator["certificationType"][] = ["Heavy Machinery", "Forklift", "Crane Logistics", "None"];
const projectStatuses: ProjectStatus[] = ["Planning", "Active", "Completed", "On Hold"];
const text = (row: Record<string, unknown>, field: string) => String(row[field] ?? "").trim();
const normalized = (value: string) => value.trim().toLocaleLowerCase();
const validDate = (value: string) => !value || /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
const issue = (issues: MigrationIssue[], sheet: MigrationEntitySheet, row: number, field: string, value: string, message: string, suggestion?: string, severity: MigrationIssue["severity"] = "Error") => issues.push({ sheet, row, field, value, message, suggestion, severity });
const duplicateRows = (rows: Record<string, unknown>[], field: string) => { const seen = new Set<string>(); const duplicates = new Set<number>(); rows.forEach((row, index) => { const key = normalized(text(row, field)); if (key && seen.has(key)) duplicates.add(index); seen.add(key); }); return duplicates; };

export function validateInitialMigration(rows: MigrationWorkbookRows, references: MigrationReferences, fileName: string, now = new Date().toISOString()): MigrationPlan {
  const issues: MigrationIssue[] = [], customers: CustomerRecord[] = [], projects: ProjectRecord[] = [], operators: Operator[] = [], equipment: EquipmentRecord[] = [];
  const customerDuplicates = duplicateRows(rows.Customers, "Customer Code");
  rows.Customers.forEach((row, index) => { const rowNumber=index+2, code=text(row,"Customer Code"), name=text(row,"Customer Name *"); let invalid=false;
    if(!name){issue(issues,"Customers",rowNumber,"Customer Name *","","Customer Name is required.");invalid=true} if(!code){issue(issues,"Customers",rowNumber,"Customer Code","","Customer Code is required for relationship resolution.");invalid=true}
    if(customerDuplicates.has(index)){issue(issues,"Customers",rowNumber,"Customer Code",code,"Duplicate Customer Code in workbook.");invalid=true} if(references.customers.some(item=>normalized(item.customerCode)===normalized(code))){issue(issues,"Customers",rowNumber,"Customer Code",code,"Customer Code already exists.","Use a new code; CREATE NEW ONLY does not overwrite records.");invalid=true}
    const status=normalized(text(row,"Status")||"active");if(!["active","inactive"].includes(status)){issue(issues,"Customers",rowNumber,"Status",text(row,"Status"),"Status must be Active or Inactive.");invalid=true} if(!invalid)customers.push({id:crypto.randomUUID(),customerCode:code,companyName:name,contactPerson:text(row,"Contact Person"),contactNumber:text(row,"Phone"),email:text(row,"Email"),address:text(row,"Address"),active:status==="active"});
  });
  const allCustomers=[...references.customers,...customers], projectDuplicates=duplicateRows(rows.Projects,"Project Code *");
  rows.Projects.forEach((row,index)=>{const rowNumber=index+2,code=text(row,"Project Code *"),name=text(row,"Project Name *"),customerCode=text(row,"Customer Code *"),status=(text(row,"Status")||"Planning") as ProjectStatus,start=text(row,"Start Date"),end=text(row,"End Date");let invalid=false;
    if(!code||!name||!customerCode){issue(issues,"Projects",rowNumber,!code?"Project Code *":!name?"Project Name *":"Customer Code *","","Project Code, Project Name, and Customer Code are required.");invalid=true} if(projectDuplicates.has(index)||references.projects.some(item=>normalized(item.projectCode)===normalized(code))){issue(issues,"Projects",rowNumber,"Project Code *",code,"Project Code is duplicated or already exists.");invalid=true}
    const customer=allCustomers.find(item=>normalized(item.customerCode)===normalized(customerCode));if(!customer){issue(issues,"Projects",rowNumber,"Customer Code *",customerCode,"Customer Code does not resolve.","Add the Customer to the Customers sheet or use an existing code.");invalid=true} if(!projectStatuses.includes(status)){issue(issues,"Projects",rowNumber,"Status",status,"Invalid Project status.",projectStatuses.join(", "));invalid=true} if(!validDate(start)||!validDate(end)||Boolean(start&&end&&end<start)){issue(issues,"Projects",rowNumber,"Start Date / End Date",`${start} / ${end}`,"Dates must use YYYY-MM-DD and End Date cannot precede Start Date.");invalid=true}
    if(!invalid&&customer)projects.push({id:crypto.randomUUID(),projectCode:code,projectName:name,customerId:customer.id,client:customer.companyName,location:text(row,"Location"),projectManager:text(row,"Project Manager"),startDate:start||undefined,targetCompletion:end||undefined,status});
  });
  const operatorDuplicates=duplicateRows(rows.Operators,"Operator Code / Employee ID *");
  rows.Operators.forEach((row,index)=>{const rowNumber=index+2,code=text(row,"Operator Code / Employee ID *"),name=text(row,"Operator Name *"),status=(text(row,"Status")||"Active") as Operator["status"],joined=text(row,"Joined Date");let invalid=false;
    const certification=(text(row,"Certification Type")||"None") as Operator["certificationType"];if(!code||!name){issue(issues,"Operators",rowNumber,!code?"Operator Code / Employee ID *":"Operator Name *","","Operator Code and Operator Name are required.");invalid=true} if(operatorDuplicates.has(index)||references.operators.some(item=>normalized(item.licenseNumber)===normalized(code))){issue(issues,"Operators",rowNumber,"Operator Code / Employee ID *",code,"Operator Code already exists or is duplicated in the workbook.");invalid=true} if(!operatorStatuses.includes(status)){issue(issues,"Operators",rowNumber,"Status",status,"Invalid Operator status.",operatorStatuses.join(", "));invalid=true} if(!certificationTypes.includes(certification)){issue(issues,"Operators",rowNumber,"Certification Type",certification,"Invalid Certification Type.",certificationTypes.join(", "));invalid=true} if(!validDate(joined)){issue(issues,"Operators",rowNumber,"Joined Date",joined,"Date must use YYYY-MM-DD.");invalid=true}
    if(!invalid)operators.push({id:crypto.randomUUID(),name,email:text(row,"Email"),licenseNumber:code,certificationType:certification,status,joinedDate:joined});
  });
  const equipmentDuplicates=duplicateRows(rows.Equipment,"Equipment Code *"); let planned=[...references.equipment];
  rows.Equipment.forEach((row,index)=>{const rowNumber=index+2,code=text(row,"Equipment Code *"),categoryInput=text(row,"Equipment Category *"),category=normalizeEquipmentCategory(categoryInput),status=(text(row,"Current Status")||"Available") as EquipmentStatus;let invalid=false;
    if(!code||!categoryInput){issue(issues,"Equipment",rowNumber,!code?"Equipment Code *":"Equipment Category *","","Equipment Code and Equipment Category are required.");invalid=true} if(equipmentDuplicates.has(index)||references.equipment.some(item=>normalized(item.equipmentName)===normalized(code))){issue(issues,"Equipment",rowNumber,"Equipment Code *",code,"Equipment Code already exists or is duplicated in the workbook.");invalid=true} if(!category||!references.categories.some(item=>item.active&&normalizeEquipmentCategory(item.name)===category)){issue(issues,"Equipment",rowNumber,"Equipment Category *",categoryInput,"Unknown or inactive Equipment Category.","Use a value from the reference sheet.");invalid=true} const subName=text(row,"Equipment Sub-category");const categoryRef=references.categories.find(item=>normalizeEquipmentCategory(item.name)===category);const sub=references.subcategories.find(item=>item.active&&normalized(item.name)===normalized(subName));if(subName&&(!sub||sub.categoryId!==categoryRef?.id)){issue(issues,"Equipment",rowNumber,"Equipment Sub-category",subName,"Unknown Sub-category or it does not belong to the selected Category.");invalid=true} if(!statuses.includes(status)){issue(issues,"Equipment",rowNumber,"Current Status",status,"Invalid Equipment status.",statuses.join(", "));invalid=true} const year=text(row,"Year");if(year&&(!/^\d{4}$/.test(year)||Number(year)<1900)){issue(issues,"Equipment",rowNumber,"Year",year,"Year must be a four-digit value of 1900 or later.");invalid=true}
    const acquisition=text(row,"Acquisition Date");if(!validDate(acquisition)){issue(issues,"Equipment",rowNumber,"Acquisition Date",acquisition,"Date must use YYYY-MM-DD.");invalid=true}const costCode=text(row,"Cost Code");const cost=references.costCodes.find(item=>item.active&&normalized(item.code)===normalized(costCode));if(costCode&&!cost){issue(issues,"Equipment",rowNumber,"Cost Code",costCode,"Unknown or inactive Cost Code.");invalid=true} if(invalid||!category)return; const base:EquipmentRecord={id:crypto.randomUUID(),prefixId:"",assetNo:"",equipmentName:code,category,categoryId:categoryRef?.id,subcategoryId:sub?.id,subcategoryName:sub?.name,costCodeId:cost?.id,manufacturer:text(row,"Manufacturer"),model:text(row,"Model"),location:text(row,"Initial Location"),ownership:text(row,"Ownership"),serialNumber:text(row,"Serial Number"),plateNumber:text(row,"Plate Number"),yearModel:year?Number(year):undefined,remarks:[text(row,"Legacy / Existing Company Identifier")?`Legacy identifier: ${text(row,"Legacy / Existing Company Identifier")}`:"",acquisition?`Acquisition date: ${acquisition}`:""].filter(Boolean).join("; ")||undefined,maintenanceType:"Engine Hours",currentReading:0,projectId:"",operatorId:"",status,deleted:false};const generated=createEquipmentWithCategoryAssetNumber(base,references.prefixes,planned);if(!generated.success){issue(issues,"Equipment",rowNumber,"Equipment Category *",categoryInput,generated.message);return} equipment.push(generated.record);planned=[...planned,generated.record];if(status==="Assigned"||status==="Rented")issue(issues,"Equipment",rowNumber,"Current Status",status,"Imported without fabricated Assignment or Rental history; post-import reconciliation is required.",undefined,"Warning");
  });
  const invalidRows=new Set(issues.filter(item=>item.severity==="Error").map(item=>`${item.sheet}:${item.row}`));const warningRows=new Set(issues.filter(item=>item.severity==="Warning").map(item=>`${item.sheet}:${item.row}`));const total=Object.values(rows).reduce((sum,value)=>sum+value.length,0);
  return {fileName,validatedAt:now,issues,records:{equipment,operators,customers,projects},counts:{valid:Math.max(0,total-invalidRows.size-warningRows.size),warning:warningRows.size,invalid:invalidRows.size},canImport:invalidRows.size===0};
}

export interface MigrationWriters { Customers:{create(value:CustomerRecord):void;delete(id:string):void};Projects:{create(value:ProjectRecord):void;delete(id:string):void};Operators:{create(value:Operator):void;delete(id:string):void};Equipment:{create(value:EquipmentRecord):void;delete(id:string):void} }
export function executeInitialMigration(plan:MigrationPlan,writers:MigrationWriters,authorization:{canManageMasterData:boolean}):MigrationCompletion {if(!authorization.canManageMasterData)throw new Error("You do not have permission to import master data.");if(!plan.canImport)throw new Error("Import cannot run until all validation errors are corrected.");const created:Array<{sheet:MigrationEntitySheet;id:string}>=[];const entities={Equipment:0,Operators:0,Customers:0,Projects:0};try{for(const [sheet,records] of [["Customers",plan.records.customers],["Projects",plan.records.projects],["Operators",plan.records.operators],["Equipment",plan.records.equipment]] as const)for(const record of records){writers[sheet].create(record as never);created.push({sheet,id:record.id});entities[sheet]+=1}return{imported:created.length,skipped:0,failed:0,rolledBack:0,entities,outcome:"Completed"}}catch(error){for(const entry of [...created].reverse())try{writers[entry.sheet].delete(entry.id)}catch{}return{imported:0,skipped:0,failed:1,rolledBack:created.length,entities:{Equipment:0,Operators:0,Customers:0,Projects:0},outcome:"RolledBack"}}
}
