import ExcelJS from "exceljs";
import { downloadWorkbook, getWorksheetRecords } from "@/shared/import-export/excelWorkbook";
import { validateImportFile } from "@/shared/import-export/fileValidation";
import type { MigrationIssue, MigrationWorkbookRows } from "./types";
import { MIGRATION_SHEETS } from "./types";

const headers:Record<keyof MigrationWorkbookRows,string[]>={
  Equipment:["Equipment Category *","Equipment Sub-category","Equipment Code *","Cost Code","Manufacturer","Model","Initial Location","Ownership","Current Status","Serial Number","Plate Number","Year","Acquisition Date","Legacy / Existing Company Identifier"],
  Operators:["Operator Code / Employee ID *","Operator Name *","Email","License Number","Certification Type","Joined Date","Status"],
  Customers:["Customer Code","Customer Name *","Address","Contact Person","Phone","Email","Status"],
  Projects:["Project Code *","Project Name *","Customer Code *","Location","Project Manager","Start Date","End Date","Status"],
};
const safe=(value:unknown)=>{const text=String(value??"");return /^[=+\-@]/.test(text)?`'${text}`:text};
function styleSheet(sheet:ExcelJS.Worksheet, columns:string[]){sheet.views=[{state:"frozen",ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:columns.length}};const row=sheet.getRow(1);row.font={bold:true,color:{argb:"FFFFFFFF"}};row.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF1D4ED8"}};row.height=24;columns.forEach((column,index)=>{sheet.getColumn(index+1).width=Math.min(38,Math.max(15,column.length+3))});}
export function buildMigrationWorkbook(input?:{equipment?:Record<string,unknown>[];operators?:Record<string,unknown>[];customers?:Record<string,unknown>[];projects?:Record<string,unknown>[];categories?:string[];subcategories?:string[];costCodes?:string[]}){const workbook=new ExcelJS.Workbook();workbook.creator="Equipment Rental Management System";const readme=workbook.addWorksheet("README");readme.columns=[{width:28},{width:100}];readme.addRows([["INITIAL DATA MIGRATION","Complete the four data sheets, then upload this workbook on the Data Migration page."],["Workflow","Upload → Validate → Preview → Confirm → Import. File selection never changes application data."],["Required fields","Columns marked with * are required."],["Dates","Use YYYY-MM-DD."],["Credentials","Do not enter passwords or PINs. Operator import creates operational identities only."],["Equipment numbers","Asset Numbers are generated from the approved Equipment Category prefix. Use the legacy identifier column only for a company reference."],["Deployment state","Assigned and Rented statuses are imported without fabricated lifecycle history and require reconciliation."],["Import mode","CREATE NEW ONLY. Existing business identifiers are conflicts and are never overwritten."]]);readme.getRow(1).font={bold:true,size:14,color:{argb:"FFFFFFFF"}};readme.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF1E3A8A"}};readme.getColumn(2).alignment={wrapText:true,vertical:"top"};
  for(const name of ["Equipment","Operators","Customers","Projects"] as const){const sheet=workbook.addWorksheet(name);sheet.addRow(headers[name]);for(const row of input?.[name.toLowerCase() as "equipment"|"operators"|"customers"|"projects"]??[])sheet.addRow(headers[name].map(header=>safe(row[header])));styleSheet(sheet,headers[name]);}
  for(const [name,values] of [["Equipment Categories",input?.categories??[]],["Equipment Sub-categories",input?.subcategories??[]],["Cost Codes",input?.costCodes??[]]] as const){const sheet=workbook.addWorksheet(name);sheet.addRow([name.slice(0,-1)]);values.forEach(value=>sheet.addRow([safe(value)]));styleSheet(sheet,[name.slice(0,-1)]);}
  return workbook;}
export async function downloadMigrationWorkbook(fileName:string,input?:Parameters<typeof buildMigrationWorkbook>[0]){await downloadWorkbook(buildMigrationWorkbook(input),fileName)}
export async function parseMigrationWorkbook(file:File):Promise<MigrationWorkbookRows>{const fileCheck=validateImportFile(file,{allowedExtensions:[".xlsx"],allowedMimeTypes:["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]});if(!fileCheck.valid)throw new Error(fileCheck.errors.join(" "));const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await file.arrayBuffer() as never);for(const name of MIGRATION_SHEETS)if(!workbook.getWorksheet(name))throw new Error(`Required worksheet is missing: ${name}.`);const result={} as MigrationWorkbookRows;for(const name of ["Equipment","Operators","Customers","Projects"] as const){const sheet=workbook.getWorksheet(name)!;const actual=sheet.getRow(1).values as unknown[];for(const required of headers[name].filter(value=>value.endsWith("*")))if(!actual.map(value=>String(value??"").trim()).includes(required))throw new Error(`${name} is missing required column: ${required}.`);result[name]=getWorksheetRecords<Record<string,unknown>>(sheet)}return result;}
export async function downloadMigrationIssues(issues:MigrationIssue[]){const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet("Validation Errors");const columns=["Sheet","Row","Field","Value","Severity","Message","Suggested Correction"];sheet.addRow(columns);issues.forEach(item=>sheet.addRow([item.sheet,item.row,item.field,safe(item.value),item.severity,item.message,item.suggestion??""]));styleSheet(sheet,columns);await downloadWorkbook(workbook,"initial-migration-validation-errors")}
export { headers as MIGRATION_WORKBOOK_HEADERS };
