import { useEffect, useState } from "react";

import { useApplicationDependenciesCompatibility } from "@/app/composition";
import { MasterDrawer, MasterFormActions } from "@/components/master-data";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";

import type { CanonicalEquipmentCategory, CanonicalEquipmentSubcategory } from "./canonical";

const friendlyError = (code?: string) => ({ EQUIPMENT_SUBCATEGORY_CONFLICT: "A sub-category with this name or code already exists for this Category.", EQUIPMENT_SUBCATEGORY_NOT_SELECTABLE: "The selected Equipment Category is no longer available.", NOT_FOUND: "The selected Equipment Category is no longer available.", CONFLICT: "This sub-category was changed by another user. Refresh and try again.", FORBIDDEN: "You do not have permission to manage Equipment Sub-Categories." }[code ?? ""] ?? "The sub-category could not be saved. Refresh and try again.");

export function EquipmentSubcategoryDrawer({ open, onClose, categories, editing, initialCategoryId, onSaved }: { open: boolean; onClose: () => void; categories: CanonicalEquipmentCategory[]; editing?: CanonicalEquipmentSubcategory | null; initialCategoryId?: string; onSaved: () => Promise<void> | void }) {
  const { commandRepositories } = useApplicationDependenciesCompatibility(); const [categoryId, setCategoryId] = useState(""); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!open) return; setMessage(""); setCategoryId(editing?.categoryId ?? initialCategoryId ?? ""); setName(editing?.name ?? ""); setCode(editing?.code ?? ""); }, [editing, initialCategoryId, open]);
  const close = () => { setMessage(""); onClose(); };
  async function save() { const repository = commandRepositories.equipmentSubcategories; if (!repository) return; if (!editing && !categoryId) { setMessage("Category is required."); return; } if (!name.trim()) { setMessage("Sub-Category Name is required."); return; } const commandId = crypto.randomUUID(); const result = editing ? await repository.update({ commandId, idempotencyKey: commandId, equipmentSubcategoryId: editing.id, name: name.trim(), code: code.trim() || undefined, expectedRowVersion: editing.rowVersion }) : await repository.create({ commandId, idempotencyKey: commandId, equipmentSubcategoryId: crypto.randomUUID(), categoryId, name: name.trim(), code: code.trim() || undefined }); if (!result.success) { setMessage(friendlyError(result.code)); return; } close(); await onSaved(); }
  return <MasterDrawer open={open} title={editing ? "Edit Equipment Sub-Category" : "Add Equipment Sub-Category"} onClose={close}>{!categories.length && !editing ? <div className="space-y-4"><p className="text-sm text-amber-800 dark:text-amber-200">Create or activate an Equipment Category before adding a Sub-Category.</p><Button variant="secondary" onClick={close}>Close</Button></div> : <div className="space-y-5"><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Category<span aria-hidden="true" className="text-red-600"> *</span><select aria-label="Sub-Category Category" disabled={!!editing} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-900 disabled:opacity-60" value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Select a Category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><Input label="Sub-Category Name" required value={name} onChange={(event) => setName(event.target.value)} /><Input label="Code" value={code} onChange={(event) => setCode(event.target.value)} helperText="Optional; unique within the selected Category." />{message && <p className="text-sm text-red-700 dark:text-red-300" role="alert">{message}</p>}<MasterFormActions isEditing={!!editing} onSave={() => void save()} onCancel={close} /></div>}</MasterDrawer>;
}
