import { useCallback, useEffect, useMemo, useState } from "react";
import { useApplicationDependenciesCompatibility, PersistenceMode } from "@/app/composition";
import { useAuth } from "@/features/auth/AuthContext";
import { MasterPageLayout, MasterStatusBadge } from "@/components/master-data";
import { LoadingState, ErrorState, EmptyDataState } from "@/components/ui/AsyncState";
import Button from "@/components/ui/Button";
import type { CanonicalEquipmentCategory, CanonicalEquipmentSubcategory } from "./canonical";
import { EquipmentSubcategoryDrawer } from "./EquipmentSubcategoryDrawer";

export default function EquipmentSubcategoryPage() {
  const deps = useApplicationDependenciesCompatibility(); const { hasPermission } = useAuth(); const remote = deps.configuration.persistenceMode === PersistenceMode.Remote;
  const [items, setItems] = useState<CanonicalEquipmentSubcategory[]>([]); const [categories, setCategories] = useState<CanonicalEquipmentCategory[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [query, setQuery] = useState(""); const [categoryFilter, setCategoryFilter] = useState(""); const [editing, setEditing] = useState<CanonicalEquipmentSubcategory | null>(null); const [drawerOpen, setDrawerOpen] = useState(false);
  const refresh = useCallback(async () => { setState("loading"); setError(""); const [listResult, categoryResult] = await Promise.all([deps.readRepositories.equipmentSubcategories.list(), deps.readRepositories.equipmentCategories.list()]); if (!listResult.success) { setState("error"); setError(listResult.error.message); return; } setItems(listResult.value.items); setCategories(categoryResult.success ? categoryResult.value.items : []); setState("ready"); }, [deps]);
  useEffect(() => { void refresh(); }, [refresh]);
  const categoryNames = useMemo(() => new Map(categories.map((category) => [category.id, category.name])), [categories]); const visible = items.filter((item) => (!categoryFilter || item.categoryId === categoryFilter) && `${item.name} ${item.code ?? ""}`.toLowerCase().includes(query.trim().toLowerCase()));
  const close = () => { setDrawerOpen(false); setEditing(null); }; const openAdd = () => { setMessage(""); setEditing(null); setDrawerOpen(true); }; const openEdit = (item: CanonicalEquipmentSubcategory) => { setMessage(""); setEditing(item); setDrawerOpen(true); };
  async function setActive(item: CanonicalEquipmentSubcategory, active: boolean) { const repository = deps.commandRepositories.equipmentSubcategories; if (!repository) return; if (!active && !window.confirm("This sub-category will no longer be available for new Equipment selection. Existing Equipment references will remain visible.")) return; const commandId = crypto.randomUUID(); const result = await repository.setActive({ commandId, idempotencyKey: commandId, equipmentSubcategoryId: item.id, expectedRowVersion: item.rowVersion }, active); if (!result.success) setMessage("The sub-category could not be saved. Refresh and try again."); else await refresh(); }
  const canCreate = hasPermission("masterData.create"); const canUpdate = hasPermission("masterData.update");
  const table = <><div className="app-card flex flex-wrap items-end gap-4 p-4"><label className="min-w-56 flex-1 text-sm font-medium text-slate-700 dark:text-slate-200">Search<input aria-label="Search Sub-Categories" className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-900" placeholder="Search by name or code" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label className="min-w-56 flex-1 text-sm font-medium text-slate-700 dark:text-slate-200">Category<select aria-label="Filter by Category" className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-900" value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option value="">All Categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div>{state === "loading" ? <LoadingState label="Loading equipment sub-categories…" /> : state === "error" ? <ErrorState message={error} onRetry={() => void refresh()} /> : !visible.length ? <EmptyDataState title="No equipment sub-categories have been set up yet." description="Create or activate an Equipment Category before adding a Sub-Category." action={canCreate ? <Button onClick={openAdd}>Add Sub-Category</Button> : undefined} /> : <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><table className="min-w-full text-sm"><thead className="bg-slate-100 dark:bg-slate-800"><tr><th className="p-3 text-left">Category</th><th className="p-3 text-left">Sub-Category Name</th><th className="p-3 text-left">Code</th><th className="p-3 text-left">Status</th><th className="p-3 text-right">Usage Count</th><th className="p-3 text-left">Updated Date</th>{canUpdate && <th className="p-3 text-right">Actions</th>}</tr></thead><tbody>{visible.map((item) => <tr key={item.id} className="border-t border-slate-200 dark:border-slate-700"><td className="p-3">{categoryNames.get(item.categoryId) ?? "Equipment Category"}</td><td className="p-3 font-medium">{item.name}</td><td className="p-3">{item.code ?? "—"}</td><td className="p-3"><MasterStatusBadge active={item.active} /></td><td className="p-3 text-right">{item.usageCount}</td><td className="p-3">{new Date(item.updatedAt).toLocaleDateString()}</td>{canUpdate && <td className="p-3 text-right"><Button size="sm" variant="secondary" onClick={() => openEdit(item)}>Edit</Button>{" "}<Button size="sm" variant="secondary" onClick={() => void setActive(item, !item.active)}>{item.active ? "Deactivate" : "Activate"}</Button></td>}</tr>)}</tbody></table></div>}</>;
  return <div className="p-4 sm:p-8"><MasterPageLayout title="Equipment Sub-Categories" toolbar={<div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500 dark:text-slate-400">Manage tenant-specific sub-categories for canonical Equipment.</p>{remote && !categories.length && <p className="mt-1 text-sm text-amber-700 dark:text-amber-300">Create or activate an Equipment Category before adding a Sub-Category.</p>}</div>{canCreate && <Button onClick={openAdd}>Add Sub-Category</Button>}</div>} table={table} />{message && <p className="mt-3 text-sm text-red-700 dark:text-red-300" role="alert">{message}</p>}{!remote && <p className="mt-3 text-sm text-slate-500">Canonical sub-category administration is available in remote mode.</p>}<EquipmentSubcategoryDrawer open={drawerOpen} onClose={close} categories={categories} editing={editing} onSaved={refresh} /></div>;
}
