import {organizationBranding} from "@/shared/branding/organizationBranding";
import type {CustomReportSection} from "./customReportWorkspace";
import {AI_ANALYSIS_DISCLAIMER,type ExecutiveAnalysisRecord} from "./executiveReportAnalysis";
import {composeCustomReport,type ReportReviewMode} from "./reportComposition";
import {buildModernReportViewModel,compactChartMaximum,type ReportAccent,type ReportMetricPresentation} from "./reportPresentation";
import {reportPdfFilename} from "./reportPdfExport";

const colors={blue:[8,101,217],navy:[15,35,70],text:[23,35,59],muted:[100,116,139],border:[219,228,239],surface:[248,250,252],green:[22,163,74],purple:[124,58,237],red:[239,68,68],orange:[245,158,11],previous:[148,163,184]} as const;
const accent=(name:ReportAccent)=>colors[name];

export async function exportCustomReportPdf(input:{name:string;sections:readonly CustomReportSection[];generatedAt:Date;generatedBy:string;mode?:ReportReviewMode;analysis?:ExecutiveAnalysisRecord}):Promise<void>{
 if(!input.sections.length)throw new Error("Add at least one section before exporting the Custom Report.");
 const{jsPDF}=await import("jspdf"),mode=input.mode??"executive",composition=composeCustomReport(input.name,input.sections,mode),view=buildModernReportViewModel(input.sections),pdf=new jsPDF({orientation:"landscape",unit:"pt",format:"a4"}),pageWidth=pdf.internal.pageSize.getWidth(),pageHeight=pdf.internal.pageSize.getHeight(),margin=28,contentWidth=pageWidth-margin*2,bottom=pageHeight-42;let y=126;
 const textColor=()=>pdf.setTextColor(...colors.text),muted=()=>pdf.setTextColor(...colors.muted);
 const continuationHeader=()=>{pdf.setFont("helvetica","bold");pdf.setFontSize(7.5);muted();pdf.text(`${organizationBranding.companyName} · ${input.name}`,margin,22);pdf.setDrawColor(...colors.border);pdf.line(margin,29,pageWidth-margin,29)};
 const nextPage=()=>{pdf.addPage();continuationHeader();y=43};
 const ensure=(height:number)=>{if(y+height>bottom)nextPage()};
 drawCorporateHeader();
 drawSectionHeading("Executive Summary");drawMetricGrid(view.executiveMetrics,7);y+=8;
 if(input.analysis?.included)drawAiAnalysis(input.analysis);
 for(const section of view.sections){const chartMetrics=section.reportType==="assignments"?[]:section.metrics.filter(item=>item.metric.numericValue!==undefined);const metricRows=Math.ceil(section.metrics.length/(section.utilization===undefined?4:3)),estimated=27+metricRows*49+(chartMetrics.length?125:0);ensure(Math.min(estimated,bottom-43));drawSectionHeading(section.title);drawMetricGrid(section.metrics,section.utilization===undefined?4:3,section.utilization===undefined?undefined:{value:section.utilization});if(chartMetrics.length)drawComparisonChart(`${section.title} Comparison`,chartMetrics);if(mode==="technical"&&section.rows.length)drawTechnicalTable(`${section.title} Details`,section.columns,section.rows)}
 const total=pdf.getNumberOfPages();for(let page=1;page<=total;page++){pdf.setPage(page);if(page>1){pdf.setFont("helvetica","normal");pdf.setFontSize(7);muted();pdf.text(`Page ${page} of ${total}`,pageWidth-margin,22,{align:"right"})}if(page===total){pdf.setFillColor(...colors.blue);pdf.rect(0,pageHeight-30,pageWidth,30,"F");pdf.setTextColor(255,255,255);pdf.setFontSize(7);pdf.text(`Generated ${input.generatedAt.toLocaleString()}`,margin,pageHeight-12);pdf.text(`Prepared by ${input.generatedBy}`,pageWidth-margin,pageHeight-12,{align:"right"})}else{pdf.setFontSize(7);muted();pdf.text(`Page ${page} of ${total}`,pageWidth-margin,pageHeight-14,{align:"right"})}}
 pdf.save(reportPdfFilename(input.name,input.generatedAt));

 function drawCorporateHeader(){pdf.setFillColor(247,251,255);pdf.rect(0,0,pageWidth,110,"F");pdf.setDrawColor(...colors.blue);pdf.setLineWidth(1.4);pdf.line(0,109,pageWidth,109);pdf.setLineWidth(2);pdf.setDrawColor(...colors.blue);pdf.line(margin+5,25,margin+17,37);pdf.line(margin+17,37,margin+5,49);pdf.line(margin+5,49,margin-7,37);pdf.line(margin-7,37,margin+5,25);pdf.setFont("helvetica","bold");pdf.setFontSize(11);textColor();pdf.text("PRIMARY STRUCTURES",margin+26,31);pdf.text("CORPORATION",margin+26,43);pdf.setFontSize(8);pdf.setTextColor(...colors.blue);pdf.text(organizationBranding.departmentName,margin,62);pdf.setFontSize(19);textColor();pdf.text(input.name,margin,82);pdf.setFont("helvetica","normal");pdf.setFontSize(7.5);muted();pdf.text(`${mode==="executive"?"Executive Review":"Technical Review"} · Period: ${composition.period}${composition.comparisonPeriod?` · Previous: ${composition.comparisonPeriod}`:""}`,margin,96);pdf.text(`Generated ${input.generatedAt.toLocaleString()} · Prepared by ${input.generatedBy}`,margin,105);pdf.setFillColor(226,238,255);pdf.circle(pageWidth-76,32,58,"F");pdf.setFillColor(205,226,255);pdf.circle(pageWidth-28,12,64,"F");pdf.setDrawColor(...colors.blue);pdf.setLineWidth(2);pdf.line(pageWidth-116,66,pageWidth-96,51);pdf.line(pageWidth-96,51,pageWidth-78,58);pdf.line(pageWidth-78,58,pageWidth-58,34);pdf.line(pageWidth-58,34,pageWidth-39,44)}
 function drawSectionHeading(title:string){ensure(22);pdf.setFillColor(...colors.blue);pdf.rect(margin,y,2.5,14,"F");pdf.setFont("helvetica","bold");pdf.setFontSize(10);textColor();pdf.text(title,margin+9,y+10);y+=23}
 function drawMetricGrid(metrics:readonly ReportMetricPresentation[],columns:number,gauge?:{value:number}){if(!metrics.length){pdf.setFontSize(8);muted();pdf.text("No report metrics are available for this section.",margin,y+12);y+=28;return}const gaugeWidth=gauge?125:0,gap=7,gridWidth=contentWidth-gaugeWidth-(gauge?12:0),cardWidth=(gridWidth-gap*(columns-1))/columns,rows=Math.ceil(metrics.length/columns);metrics.forEach((item,index)=>{const row=Math.floor(index/columns),col=index%columns,x=margin+col*(cardWidth+gap),cy=y+row*49;drawMetricCard(x,cy,cardWidth,item)});if(gauge)drawGauge(margin+gridWidth+18,y+6,gaugeWidth-16,gauge.value);y+=rows*49+(gauge&&rows<2?49:0)}
 function drawMetricCard(x:number,top:number,width:number,item:ReportMetricPresentation){pdf.setFillColor(255,255,255);pdf.setDrawColor(...colors.border);pdf.roundedRect(x,top,width,41,5,5,"FD");const tone=accent(item.accent);pdf.setFillColor(tone[0],tone[1],tone[2]);pdf.circle(x+17,top+20,10,"F");pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(8);pdf.text(item.symbol,x+17,top+23,{align:"center"});pdf.setFont("helvetica","normal");pdf.setFontSize(6.5);muted();pdf.text(item.metric.label,x+32,top+15,{maxWidth:width-38});pdf.setFont("helvetica","bold");pdf.setFontSize(String(item.metric.value).length>16?9:11);textColor();pdf.text(String(item.metric.value),x+32,top+31,{maxWidth:width-38})}
 function drawGauge(x:number,top:number,width:number,value:number){const cx=x+width/2,cy=top+34,r=27;pdf.setDrawColor(226,232,240);pdf.setLineWidth(7);pdf.circle(cx,cy,r,"S");pdf.setDrawColor(...colors.blue);const segments=Math.max(0,Math.round(value/4));let previous:{x:number;y:number}|undefined;for(let i=0;i<=segments;i++){const angle=(-90+i/25*360)*Math.PI/180,current={x:cx+Math.cos(angle)*r,y:cy+Math.sin(angle)*r};if(previous)pdf.line(previous.x,previous.y,current.x,current.y);previous=current}pdf.setFont("helvetica","bold");pdf.setFontSize(15);textColor();pdf.text(`${Math.round(value)}%`,cx,cy+3,{align:"center"});pdf.setFont("helvetica","normal");pdf.setFontSize(6);muted();pdf.text("Utilization Rate",cx,cy+14,{align:"center"})}
 function drawComparisonChart(title:string,metrics:readonly ReportMetricPresentation[]){ensure(116);drawSectionHeading(title);const top=y,height=88;pdf.setFillColor(255,255,255);pdf.setDrawColor(...colors.border);pdf.roundedRect(margin,top,contentWidth,height,5,5,"FD");pdf.setFontSize(6.5);muted();pdf.setFillColor(...colors.blue);pdf.circle(margin+contentWidth/2-60,top+10,3,"F");pdf.text("Current Period",margin+contentWidth/2-53,top+12);pdf.setFillColor(...colors.previous);pdf.circle(margin+contentWidth/2+24,top+10,3,"F");pdf.text("Previous Period",margin+contentWidth/2+31,top+12);const max=compactChartMaximum(metrics),base=top+67,plotTop=top+24,slot=contentWidth/Math.max(metrics.length,1);pdf.setDrawColor(226,232,240);for(let line=0;line<3;line++)pdf.line(margin+30,plotTop+line*20,pageWidth-margin-12,plotTop+line*20);metrics.forEach((item,index)=>{const x=margin+slot*index+slot/2,available=35,current=Math.max(1,available*Math.abs(item.metric.numericValue??0)/max),previous=Math.max(1,available*Math.abs(item.metric.previousValue??0)/max);pdf.setFillColor(...colors.blue);pdf.rect(x-8,base-current,6,current,"F");pdf.setFillColor(...colors.previous);pdf.rect(x+2,base-previous,6,previous,"F");pdf.setFontSize(6);muted();pdf.text(item.metric.label,x,top+80,{align:"center",maxWidth:slot-6})});if(metrics.every(item=>(item.metric.numericValue??0)===0&&(item.metric.previousValue??0)===0)){pdf.setFontSize(7);muted();pdf.text("No activity recorded for the selected periods.",pageWidth/2,top+47,{align:"center"})}y+=height+10}
 function drawTechnicalTable(title:string,columns:string[],rows:(string|number)[][]){ensure(55);drawSectionHeading(title);const colWidth=contentWidth/Math.max(columns.length,1),header=()=>{pdf.setFillColor(232,238,246);pdf.rect(margin,y,contentWidth,18,"F");pdf.setFont("helvetica","bold");pdf.setFontSize(6.5);textColor();columns.forEach((column,index)=>pdf.text(column,margin+index*colWidth+3,y+12,{maxWidth:colWidth-6}));y+=18};header();for(const row of rows){if(y+17>bottom){nextPage();pdf.setFont("helvetica","bold");pdf.setFontSize(8);textColor();pdf.text(`${title} (continued)`,margin,y);y+=12;header()}pdf.setFont("helvetica","normal");pdf.setFontSize(6.5);row.forEach((cell,index)=>pdf.text(String(cell??""),margin+index*colWidth+3,y+11,{maxWidth:colWidth-6}));y+=17}y+=8}
 function drawAiAnalysis(analysis:ExecutiveAnalysisRecord){const result=analysis.result,summary=pdf.splitTextToSize(result.executiveSummary,contentWidth-20).slice(0,3),findings=result.keyFindings.slice(0,3),actions=result.recommendations.slice(0,3),height=70+Math.max(findings.length,actions.length)*13;ensure(height+25);drawSectionHeading(`AI-Assisted ${mode==="executive"?"Executive":"Technical"} Analysis`);const top=y;pdf.setFillColor(239,246,255);pdf.setDrawColor(191,219,254);pdf.roundedRect(margin,top,contentWidth,height,5,5,"FD");pdf.setFont("helvetica","normal");pdf.setFontSize(7.5);textColor();pdf.text(summary,margin+10,top+14);pdf.setFont("helvetica","bold");pdf.text("Key Findings",margin+10,top+37);pdf.text("Management Action Plan",margin+contentWidth/2,top+37);pdf.setFont("helvetica","normal");findings.forEach((item,index)=>pdf.text(`${item.kind} · ${item.priority}: ${item.text}`,margin+10,top+50+index*13,{maxWidth:contentWidth/2-25}));actions.forEach((item,index)=>pdf.text(`${item.priority} · ${item.responsibleFunction}: ${item.text}`,margin+contentWidth/2,top+50+index*13,{maxWidth:contentWidth/2-20}));pdf.setFontSize(6);muted();pdf.text(AI_ANALYSIS_DISCLAIMER,margin+10,top+height-7,{maxWidth:contentWidth-20});y+=height+9}
}
