import { organizationBranding } from "@/shared/branding/organizationBranding";

export interface ReportPdfModel {
  title: string;
  period: string;
  filters: readonly string[];
  columns: readonly string[];
  rows: readonly (readonly (string | number)[])[];
  generatedAt: Date;
  generatedBy: string;
  summary?: readonly { label: string; value: string | number }[];
}

export function reportPdfFilename(title: string, date = new Date()): string {
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  return `equipment-rental-${slug}-${date.toISOString().slice(0, 10)}.pdf`;
}

export async function exportReportPdf(model: ReportPdfModel): Promise<void> {
  if (!model.rows.length && !model.summary?.length) throw new Error("No report rows or summary metrics are available to export.");
  const { jsPDF } = await import("jspdf");
  const wide = model.columns.length > 4;
  const pdf = new jsPDF({ orientation: wide ? "landscape" : "portrait", unit: "pt", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth(), pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 40, contentWidth = pageWidth - margin * 2;
  const widths = model.columns.map(() => contentWidth / model.columns.length);
  let page = 1, y = 40;
  const header = () => {
    pdf.setTextColor(15, 23, 42); pdf.setFont("helvetica", "bold"); pdf.setFontSize(13);
    pdf.text(organizationBranding.companyName.toUpperCase(), margin, y); y += 15;
    pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.text(organizationBranding.departmentName, margin, y); y += 22;
    pdf.setFontSize(16); pdf.setFont("helvetica", "bold"); pdf.text(model.title, margin, y); y += 18;
    pdf.setFontSize(8); pdf.setFont("helvetica", "normal");
    pdf.text(`Period: ${model.period}`, margin, y); y += 11;
    pdf.text(`Generated: ${model.generatedAt.toLocaleString()}  |  Generated by: ${model.generatedBy}`, margin, y); y += 11;
    if (model.filters.length) { pdf.text(`Filters: ${model.filters.join("; ")}`, margin, y); y += 11; }
    if (model.summary?.length) { pdf.text(`Summary: ${model.summary.map(item => `${item.label}: ${item.value}`).join("  |  ")}`, margin, y, { maxWidth: contentWidth }); y += 18; }
  };
  const tableHeader = () => {
    pdf.setFillColor(226, 232, 240); pdf.rect(margin, y, contentWidth, 22, "F");
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(7); pdf.setTextColor(30, 41, 59);
    model.columns.forEach((column, index) => pdf.text(String(column), margin + widths.slice(0, index).reduce((a, b) => a + b, 0) + 4, y + 14, { maxWidth: widths[index] - 8 }));
    y += 22;
  };
  const footer = () => { pdf.setFontSize(8); pdf.setTextColor(100); pdf.text(`Page ${page}`, pageWidth - margin, pageHeight - 20, { align: "right" }); };
  header(); tableHeader();
  for (const row of model.rows) {
    const lines = row.map((cell, index) => pdf.splitTextToSize(String(cell ?? ""), widths[index] - 8));
    const height = Math.max(22, Math.max(...lines.map((item) => item.length)) * 9 + 8);
    if (y + height > pageHeight - 38) { footer(); pdf.addPage(); page += 1; y = 40; header(); tableHeader(); }
    pdf.setDrawColor(226, 232, 240); pdf.line(margin, y + height, margin + contentWidth, y + height);
    pdf.setFont("helvetica", "normal"); pdf.setFontSize(7); pdf.setTextColor(30, 41, 59);
    lines.forEach((cellLines, index) => pdf.text(cellLines, margin + widths.slice(0, index).reduce((a, b) => a + b, 0) + 4, y + 12));
    y += height;
  }
  footer(); pdf.save(reportPdfFilename(model.title, model.generatedAt));
}
