export type ReportPeriodPreset = "TODAY"|"YESTERDAY"|"THIS_WEEK"|"LAST_WEEK"|"LAST_7_DAYS"|"LAST_30_DAYS"|"LAST_90_DAYS"|"THIS_MONTH"|"LAST_MONTH"|"THIS_QUARTER"|"LAST_QUARTER"|"YTD"|"THIS_YEAR"|"LAST_YEAR"|"MONTH"|"QUARTER"|"ANNUAL"|"CUSTOM";
export type ReportComparison = "NONE"|"PREVIOUS_PERIOD"|"PREVIOUS_MONTH"|"PREVIOUS_QUARTER"|"PREVIOUS_YEAR";
export interface ReportPeriodInput {preset:ReportPeriodPreset;now:Date;customStart?:string;customEnd?:string;year?:number;month?:number;quarter?:1|2|3|4;comparison?:ReportComparison}
export interface ReportPeriodRange {startDate:string;endDate:string;comparisonStartDate?:string;comparisonEndDate?:string;label:string}
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const date=(y:number,m:number,d:number)=>new Date(y,m,d);
const addDays=(value:Date,days:number)=>date(value.getFullYear(),value.getMonth(),value.getDate()+days);
const daysBetween=(a:Date,b:Date)=>Math.round((date(b.getFullYear(),b.getMonth(),b.getDate()).getTime()-date(a.getFullYear(),a.getMonth(),a.getDate()).getTime())/86400000)+1;
const parse=(value:string)=>{const [y,m,d]=value.split("-").map(Number);return date(y,m-1,d)};
export function resolveReportPeriod(input:ReportPeriodInput):ReportPeriodRange{
 const now=date(input.now.getFullYear(),input.now.getMonth(),input.now.getDate()),y=now.getFullYear(),m=now.getMonth();let start=now,end=now,label=input.preset.replaceAll("_"," ");
 switch(input.preset){case"YESTERDAY":start=end=addDays(now,-1);break;case"THIS_WEEK":start=addDays(now,-((now.getDay()+6)%7));break;case"LAST_WEEK":{const monday=addDays(now,-((now.getDay()+6)%7));start=addDays(monday,-7);end=addDays(monday,-1);break}case"LAST_7_DAYS":start=addDays(now,-6);break;case"LAST_30_DAYS":start=addDays(now,-29);break;case"LAST_90_DAYS":start=addDays(now,-89);break;case"THIS_MONTH":start=date(y,m,1);break;case"LAST_MONTH":start=date(y,m-1,1);end=date(y,m,0);break;case"THIS_QUARTER":{const q=Math.floor(m/3)*3;start=date(y,q,1);break}case"LAST_QUARTER":{const q=Math.floor(m/3)*3;start=date(y,q-3,1);end=date(y,q,0);break}case"YTD":start=date(y,0,1);break;case"THIS_YEAR":start=date(y,0,1);end=date(y,11,31);break;case"LAST_YEAR":start=date(y-1,0,1);end=date(y-1,11,31);break;case"MONTH":{const year=input.year??y,month=(input.month??m+1)-1;start=date(year,month,1);end=date(year,month+1,0);label=start.toLocaleString("en",{month:"long",year:"numeric"});break}case"QUARTER":{const year=input.year??y,q=input.quarter??1;start=date(year,(q-1)*3,1);end=date(year,q*3,0);label=`Q${q} ${year}`;break}case"ANNUAL":{const year=input.year??y;start=date(year,0,1);end=date(year,11,31);label=String(year);break}case"CUSTOM":{if(!input.customStart||!input.customEnd)throw new Error("Custom report dates are required.");start=parse(input.customStart);end=parse(input.customEnd);if(start>end)throw new Error("Custom report start date must not be after the end date.");label="CUSTOM RANGE";break}default:break}
 const result:ReportPeriodRange={startDate:iso(start),endDate:iso(end),label:`${label}: ${iso(start)} to ${iso(end)}`};
 const comparison=input.comparison??"NONE";if(comparison!=="NONE"){let cs:Date,ce:Date;if(comparison==="PREVIOUS_YEAR"){cs=date(start.getFullYear()-1,start.getMonth(),start.getDate());ce=date(end.getFullYear()-1,end.getMonth(),end.getDate())}else if(comparison==="PREVIOUS_MONTH"){cs=date(start.getFullYear(),start.getMonth()-1,start.getDate());ce=date(end.getFullYear(),end.getMonth()-1,Math.min(end.getDate(),date(end.getFullYear(),end.getMonth(),0).getDate()))}else if(comparison==="PREVIOUS_QUARTER"){cs=date(start.getFullYear(),start.getMonth()-3,start.getDate());ce=date(end.getFullYear(),end.getMonth()-3,end.getDate())}else{const length=daysBetween(start,end);ce=addDays(start,-1);cs=addDays(ce,-length+1)}result.comparisonStartDate=iso(cs);result.comparisonEndDate=iso(ce)}return result;
}
