import type { AssignmentRecord } from "@/features/assignment/types";
import type { EquipmentRecord } from "@/features/equipment/types";
import { calculateFleetUtilization } from "@/features/dashboard/services/fleetUtilization";
import type { MaintenanceRecord } from "@/features/maintenance/types";
import type { RentalRecord } from "@/features/rental/types";
import type { BillingStatement } from "@/features/rental/billingstatement/types";
import type { CollectionTransaction } from "@/features/rental/collections/types";
import { reconcileStatementCollections } from "@/features/rental/collections/collectionService";
import type { ReportPeriodRange } from "./reportPeriod";

export type ReportType="rentals"|"assignments"|"equipment"|"revenue"|"collections"|"maintenance";
export type ReportGroup="none"|"status"|"customer"|"project"|"month";
export interface ReportDataSource {rentals:readonly RentalRecord[];assignments:readonly AssignmentRecord[];equipment:readonly EquipmentRecord[];maintenance:readonly MaintenanceRecord[];statements:readonly BillingStatement[];collections:CollectionTransaction[]}
export interface ReportBuilderConfig {type:ReportType;period:ReportPeriodRange;status?:string;customer?:string;project?:string;groupBy:ReportGroup}
export interface ReportMetric {label:string;value:string|number;numericValue?:number;previousValue?:number;variance?:number;variancePercent?:number}
export interface BuiltReport {title:string;period:string;filters:string[];columns:string[];rows:(string|number)[][];metrics:ReportMetric[];groupBy:ReportGroup}
export function buildComparisonChartData(report:BuiltReport){return report.metrics.filter(metric=>metric.numericValue!==undefined).map(metric=>({name:metric.label,Current:metric.numericValue!,Previous:metric.previousValue}))}
export function formatMetricChange(metric:ReportMetric):string{if(metric.previousValue===undefined)return"No comparison";if(metric.variancePercent===undefined)return"Not comparable";if(/utilization|rate/i.test(metric.label))return`${metric.variance!>0?"+":""}${metric.variance} pts`;return`${metric.variancePercent>0?"+":""}${metric.variancePercent}%`}
export const php=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const within=(value:string|undefined,range:ReportPeriodRange,comparison=false)=>Boolean(value)&&value!.slice(0,10)>=(comparison?range.comparisonStartDate??range.startDate:range.startDate)&&value!.slice(0,10)<=(comparison?range.comparisonEndDate??range.endDate:range.endDate);
const variance=(label:string,current:number,previous?:number,format:(n:number)=>string|number=n=>n):ReportMetric=>({label,value:format(current),numericValue:current,previousValue:previous,variance:previous===undefined?undefined:current-previous,variancePercent:previous===undefined||previous===0?undefined:Math.round((current-previous)/previous*10000)/100});
const groupValue=(group:ReportGroup,input:{status?:string;customer?:string;project?:string;date?:string})=>group==="status"?input.status??"Unspecified":group==="customer"?input.customer??"Unspecified":group==="project"?input.project??"Unspecified":group==="month"?input.date?.slice(0,7)??"Unspecified":"";
const grouped=(report:BuiltReport)=>report.groupBy==="none"?report:{...report,columns:["Group",...report.columns],rows:report.rows.map((row,index)=>[report.filters[index]??"Unspecified",...row]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))),filters:report.filters.slice(report.rows.length)};

export function buildReport(source:ReportDataSource,config:ReportBuilderConfig):BuiltReport{
 const applied=[`Period: ${config.period.startDate} to ${config.period.endDate}`,...(config.period.comparisonStartDate?[`Comparison: ${config.period.comparisonStartDate} to ${config.period.comparisonEndDate}`]:[]),...(config.status?[`Status: ${config.status}`]:[]),...(config.customer?[`Customer: ${config.customer}`]:[]),...(config.project?[`Project: ${config.project}`]:[]),...(config.groupBy!=="none"?[`Group by: ${config.groupBy}`]:[])];
 const filterCommon=<T extends {status?:string;customer?:string;project?:string}>(items:T[])=>items.filter(x=>(!config.status||x.status===config.status)&&(!config.customer||x.customer===config.customer)&&(!config.project||x.project===config.project));
 if(config.type==="rentals"){const current=filterCommon(source.rentals.filter(r=>within(r.dateOut,config.period)).map(r=>({record:r,status:r.status,customer:r.customer,project:r.project})));const previous=config.period.comparisonStartDate?filterCommon(source.rentals.filter(r=>within(r.dateOut,config.period,true)).map(r=>({record:r,status:r.status,customer:r.customer,project:r.project}))).length:undefined;const report:BuiltReport={title:"Rental Activity Report",period:config.period.label,filters:current.map(x=>groupValue(config.groupBy,{status:x.status,customer:x.customer,project:x.project,date:x.record.dateOut})).concat(applied),columns:["Rental","Customer","Project","Date Out","Expected Return","Status","Billing Method"],rows:current.map(x=>[x.record.rentalNumber??"Rental transaction",x.customer,x.project,x.record.dateOut,x.record.expectedReturn??"Not specified",x.status,x.record.billingMethod??"Not configured"]),metrics:[variance("Total Rentals",current.length,previous),{label:"Active",value:current.filter(x=>["Released","Active"].includes(x.status)).length},{label:"Closed",value:current.filter(x=>x.status==="Closed").length},{label:"Cancelled",value:current.filter(x=>x.status==="Cancelled").length}],groupBy:config.groupBy};return grouped(report)}
 if(config.type==="assignments"){const current=source.assignments.filter(a=>within(a.assignedDate,config.period)&&(!config.status||a.status===config.status));return{title:"Assignment Activity Report",period:config.period.label,filters:applied,columns:["Assigned Date","Expected Return","Status","Equipment Reference"],rows:current.map(a=>[a.assignedDate,a.expectedReturn,a.status,source.equipment.find(e=>e.id===a.equipmentId)?.assetNo??"Unavailable"]),metrics:[{label:"Assignments",value:current.length},{label:"Active",value:current.filter(x=>x.status==="Active").length},{label:"Completed",value:current.filter(x=>x.status==="Completed").length}],groupBy:config.groupBy}}
 if(config.type==="equipment"){const current=source.equipment.filter(e=>e.active!==false&&!e.deleted&&(!config.status||e.status===config.status));const fleet=calculateFleetUtilization(current);return{title:"Equipment and Fleet Utilization Report",period:"Current fleet snapshot",filters:applied,columns:["Asset No.","Equipment","Category","Status","Ownership","Location","Reading"],rows:current.map(e=>[e.assetNo,e.equipmentName,e.category,e.status==="Rented"?"Deployed":e.status,e.ownership??"—",e.location??"—",e.currentReading]),metrics:[{label:"Total Equipment",value:fleet.total},{label:"Available",value:fleet.available},{label:"Assigned",value:fleet.assigned},{label:"Deployed",value:fleet.deployed},{label:"Maintenance",value:fleet.maintenance},{label:"Utilization",value:`${fleet.rate}%`,numericValue:fleet.rate}],groupBy:config.groupBy}}
 if(config.type==="revenue"){const eligible=(comparison=false)=>source.statements.filter(s=>s.invoiceStatus!=="Cancelled"&&s.invoiceStatus!=="Not Invoiced"&&within(s.createdAt,config.period,comparison)&&(!config.status||s.invoiceStatus===config.status)&&(!config.customer||s.customer===config.customer)&&(!config.project||s.project===config.project));const current=eligible(),previous=config.period.comparisonStartDate?eligible(true):undefined;const totals=(items:readonly BillingStatement[])=>items.map(s=>reconcileStatementCollections(s,source.collections)).reduce((a,x)=>({billed:a.billed+x.invoiceTotal,collected:a.collected+x.totalCollected,outstanding:a.outstanding+x.outstandingBalance}),{billed:0,collected:0,outstanding:0});const now=totals(current),before=previous?totals(previous):undefined;return{title:"Revenue and Outstanding Receivables Report",period:config.period.label,filters:applied,columns:["Invoice","Customer","Project","Billing Period","Invoice Status","Billed","Collected","Outstanding"],rows:current.map(s=>{const t=reconcileStatementCollections(s,source.collections);return[s.invoiceNumber??s.statementNo,s.customer,s.project,`${s.billingFrom} to ${s.billingTo}`,s.invoiceStatus,php.format(t.invoiceTotal),php.format(t.totalCollected),php.format(t.outstandingBalance)]}),metrics:[variance("Billed",now.billed,before?.billed,n=>php.format(n)),variance("Collected",now.collected,before?.collected,n=>php.format(n)),variance("Outstanding",now.outstanding,before?.outstanding,n=>php.format(n)),{label:"Collection Rate",value:`${now.billed?Math.round(now.collected/now.billed*10000)/100:0}%`}],groupBy:config.groupBy}}
 if(config.type==="collections"){const current=source.collections.filter(c=>within(c.paymentDate,config.period)&&(!config.status||c.paymentMethod===config.status));const previous=config.period.comparisonStartDate?source.collections.filter(c=>within(c.paymentDate,config.period,true)):undefined;const total=current.reduce((s,x)=>s+x.amount,0),previousTotal=previous?.reduce((s,x)=>s+x.amount,0);return{title:"Collections Report",period:config.period.label,filters:applied,columns:["Payment Date","Reference","Invoice","Method","Amount","Recorded By"],rows:current.map(c=>[c.paymentDate,c.referenceNumber,source.statements.find(s=>s.id===c.statementId)?.invoiceNumber??source.statements.find(s=>s.id===c.statementId)?.statementNo??"Unavailable",c.paymentMethod??"Not specified",php.format(c.amount),c.recordedBy]),metrics:[variance("Total Collected",total,previousTotal,n=>php.format(n)),{label:"Payments",value:current.length},{label:"Outstanding Receivables",value:php.format(source.statements.reduce((sum,s)=>sum+reconcileStatementCollections(s,source.collections).outstandingBalance,0))}],groupBy:config.groupBy}}
 const current=source.maintenance.filter(m=>within(m.scheduledDate,config.period)&&(!config.status||m.status===config.status));return{title:"Maintenance Activity Report",period:config.period.label,filters:applied,columns:["Scheduled Date","Equipment","Maintenance Type","Technician","Status","Completed Date"],rows:current.map(m=>[m.scheduledDate,source.equipment.find(e=>e.id===m.equipmentId)?.assetNo??"Unavailable",m.maintenanceType,m.technician,m.status,m.completedDate??"—"]),metrics:[{label:"Maintenance Events",value:current.length},{label:"Scheduled",value:current.filter(x=>x.status==="Scheduled").length},{label:"In Progress",value:current.filter(x=>x.status==="In Progress").length},{label:"Completed",value:current.filter(x=>x.status==="Completed").length}],groupBy:config.groupBy};
}

export function exportReportCsv(report:BuiltReport):void{if(!report.rows.length)throw new Error("No report rows are available to export.");const escape=(v:string|number)=>`"${String(v).replaceAll('"','""')}"`;const csv=[report.columns,...report.rows].map(row=>row.map(escape).join(",")).join("\r\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`equipment-rental-${report.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}
