import { useState, type ReactNode } from "react";
import Button from "@/components/ui/Button";
import { useApplicationDependenciesCompatibility } from "@/app/composition";
import { PersistenceMode } from "@/app/composition/ApplicationDependencies";
import { useAuth } from "@/features/auth/AuthContext";
import { customerRepository } from "@/features/customer/repository";
import { equipmentCategoryRepository } from "@/features/masters/equipment-category";
import { equipmentSubcategoryRepository } from "@/features/masters/equipment-subcategory/repository";
import { operatorRepository } from "@/features/operators/repository";
import { projectRepository } from "@/features/project/repository";
import { migrationAuditRepository } from "@/features/data-migration/repository/migrationAuditRepository";
import { executeInitialMigration, validateInitialMigration } from "@/features/data-migration/migrationService";
import type { MigrationCompletion, MigrationPlan } from "@/features/data-migration/types";
import { downloadMigrationIssues, downloadMigrationWorkbook, parseMigrationWorkbook } from "@/features/data-migration/migrationWorkbook";
import { loadAuthorizedCurrentMasterData } from "@/features/data-migration/currentDataExport";

export default function DataMigrationPage(){const dependencies=useApplicationDependenciesCompatibility();const auth=useAuth();const[plan,setPlan]=useState<MigrationPlan>();const[completion,setCompletion]=useState<MigrationCompletion>();const[busy,setBusy]=useState(false);const remote=dependencies.configuration.persistenceMode!==PersistenceMode.Local;
  const referenceInput=()=>{const categories=equipmentCategoryRepository.seedDefaults();const subcategories=equipmentSubcategoryRepository.seedDefaults(categories.map(item=>({id:item.id,category:item.category})));return{equipment:dependencies.repositories.equipment.getAll(),operators:operatorRepository.getAll(),customers:customerRepository.getAll(),projects:projectRepository.getAll(),prefixes:dependencies.repositories.prefix.getAll(),categories:categories.filter(item=>!item.deleted).map(item=>({id:item.id,name:item.category,active:item.active})),subcategories,costCodes:dependencies.repositories.costCode.getAll().filter(item=>!item.deleted).map(item=>({id:item.id,code:item.code,active:item.active}))}};
  async function template(current=false){const refs=referenceInput();const exported=current?await loadAuthorizedCurrentMasterData(dependencies.readRepositories,auth.hasPermission("masterData.manage")):undefined;await downloadMigrationWorkbook(current?"equipment-rental-current-master-data":"equipment-rental-initial-migration-template",current&&exported?{equipment:exported.equipment.map(item=>({"Equipment Category *":item.category,"Equipment Sub-category":item.subcategoryName,"Equipment Code *":item.equipmentName,"Cost Code":refs.costCodes.find(value=>value.id===item.costCodeId)?.code,"Manufacturer":item.manufacturer,"Model":item.model,"Initial Location":item.location,"Ownership":item.ownership,"Current Status":item.status,"Serial Number":item.serialNumber,"Plate Number":item.plateNumber,"Year":item.yearModel})),operators:exported.operators.map(item=>({"Operator Code / Employee ID *":item.licenseNumber,"Operator Name *":item.name,"Email":item.email,"Certification Type":item.certificationType,"Joined Date":item.joinedDate,"Status":item.status})),customers:exported.customers.map(item=>({"Customer Code":item.customerCode,"Customer Name *":item.companyName,"Address":item.address,"Contact Person":item.contactPerson,"Phone":item.contactNumber,"Email":item.email,"Status":item.active?"Active":"Inactive"})),projects:exported.projects.map(item=>({"Project Code *":item.projectCode,"Project Name *":item.projectName,"Customer Code *":exported.customers.find(value=>value.id===item.customerId)?.customerCode,"Location":item.location,"Project Manager":item.projectManager,"Start Date":item.startDate,"End Date":item.targetCompletion,"Status":item.status})),categories:refs.categories.filter(item=>item.active).map(item=>item.name),subcategories:refs.subcategories.filter(item=>item.active).map(item=>item.name),costCodes:refs.costCodes.filter(item=>item.active).map(item=>item.code)}:{categories:refs.categories.filter(item=>item.active).map(item=>item.name),subcategories:refs.subcategories.filter(item=>item.active).map(item=>item.name),costCodes:refs.costCodes.filter(item=>item.active).map(item=>item.code)})}
  async function select(file:File){setBusy(true);setCompletion(undefined);try{const rows=await parseMigrationWorkbook(file);setPlan(validateInitialMigration(rows,referenceInput(),file.name))}catch(error){alert(error instanceof Error?error.message:"Workbook could not be read.");setPlan(undefined)}finally{setBusy(false)}}
  function confirm(){if(!plan?.canImport||remote)return;const equipmentWriter={create:(value:Parameters<typeof dependencies.repositories.equipment.create>[0])=>dependencies.repositories.equipment.create(value),delete:(id:string)=>dependencies.repositories.equipment.permanentlyDelete(id)};const result=executeInitialMigration(plan,{Customers:customerRepository,Projects:projectRepository,Operators:operatorRepository,Equipment:equipmentWriter},{canManageMasterData:auth.hasPermission("masterData.manage")});setCompletion(result);migrationAuditRepository.create({timestamp:new Date().toISOString(),actorId:auth.user?.id,filename:plan.fileName,validation:plan.counts,outcome:result.outcome,entities:result.entities})}
  return <div className="space-y-6 p-8"><div><h1 className="text-3xl font-bold">Data Migration</h1><p className="mt-2 text-slate-500">Prepare, validate, and import initial company master data.</p></div>{remote&&<div className="rounded border border-amber-300 bg-amber-50 p-4 text-amber-900">Import is unavailable in remote persistence mode because an atomic multi-entity command is not configured. Template and export downloads remain available.</div>}<div className="grid gap-4 md:grid-cols-3"><Step n="1" title="Download Template" text="Download the standardized onboarding workbook."><Button onClick={()=>void template(false)}>Download Initial Migration Template</Button></Step><Step n="2" title="Export Current Data" text="Download current master data without credentials."><Button variant="secondary" onClick={()=>void template(true)}>Export Current Data</Button></Step><Step n="3" title="Upload and Validate" text="Selecting a file never changes application data."><input aria-label="Import Initial Data" type="file" accept=".xlsx" disabled={busy||remote} onChange={event=>{const file=event.target.files?.[0];if(file)void select(file)}} /></Step></div>{plan&&<section className="space-y-4 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Validation Results</h2><div className="grid grid-cols-3 gap-3"><Count label="Valid rows" value={plan.counts.valid}/><Count label="Warning rows" value={plan.counts.warning}/><Count label="Invalid rows" value={plan.counts.invalid}/></div>{plan.issues.length>0&&<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr>{["Sheet","Row","Field","Value","Severity","Message"].map(value=><th className="p-2 text-left" key={value}>{value}</th>)}</tr></thead><tbody>{plan.issues.map((item,index)=><tr className="border-t" key={`${item.sheet}-${item.row}-${item.field}-${index}`}><td className="p-2">{item.sheet}</td><td className="p-2">{item.row}</td><td className="p-2">{item.field}</td><td className="p-2">{item.value}</td><td className="p-2">{item.severity}</td><td className="p-2">{item.message}{item.suggestion&&<div className="text-slate-500">{item.suggestion}</div>}</td></tr>)}</tbody></table></div>}<div className="flex gap-3">{plan.issues.length>0&&<Button variant="secondary" onClick={()=>void downloadMigrationIssues(plan.issues)}>Download Error Report</Button>}<Button disabled={!plan.canImport||remote} onClick={confirm}>Confirm Import</Button></div></section>}{completion&&<section className="rounded-xl border border-green-300 bg-green-50 p-6"><h2 className="text-xl font-semibold">Import {completion.outcome}</h2><p>Imported: {completion.imported} · Skipped: {completion.skipped} · Failed: {completion.failed} · Rolled back: {completion.rolledBack}</p></section>}</div>}
function Step({n,title,text,children}:{n:string;title:string;text:string;children:ReactNode}){return <section className="space-y-3 rounded-xl border bg-white p-5"><div className="text-sm font-semibold text-blue-700">STEP {n}</div><h2 className="font-semibold">{title}</h2><p className="text-sm text-slate-500">{text}</p>{children}</section>};function Count({label,value}:{label:string;value:number}){return <div className="rounded bg-slate-50 p-3"><div className="text-sm text-slate-500">{label}</div><div className="text-2xl font-bold">{value}</div></div>}
