import { useMemo } from "react";
import Select from "@/components/ui/Select";
import type { CertificationTypeRecord } from "@/features/masters/certification-type/types";
import type { OperatorCertificationAssignment } from "@/features/operators/certifications/repository";

interface Props { options: readonly CertificationTypeRecord[]; selected: readonly string[]; historical?: readonly OperatorCertificationAssignment[]; onChange: (ids: string[]) => void; loading?: boolean; disabled?: boolean }
export default function CertificationMultiSelect({ options, selected, historical = [], onChange, loading, disabled }: Props) {
  const available = useMemo(() => options.filter((item) => item.active && !selected.includes(item.id)), [options, selected]);
  return <fieldset className="space-y-2"><legend className="text-sm font-medium text-slate-700">Certifications</legend><div className="flex flex-wrap gap-2">{selected.map((id) => { const item = options.find((option) => option.id === id); if (!item) return null; return <span key={id} className="inline-flex items-center gap-2 rounded-full bg-amber-50 px-3 py-1 text-sm text-amber-900">{item.name}<button type="button" aria-label={`Remove ${item.name}`} disabled={disabled} className="font-semibold" onClick={() => onChange(selected.filter((value) => value !== id))}>×</button></span>; })}{historical.filter((item) => !item.active && !selected.includes(item.certificationTypeId)).map((item) => <span key={item.certificationTypeId} className="inline-flex items-center rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-500" title="Inactive historical certification">{item.name} · inactive</span>)}</div><Select searchable label="Add certification" value="" options={[{ value: "", label: available.length ? "Search or select certification" : "No active certifications available" }, ...available.map((item) => ({ value: item.id, label: item.name }))]} loading={loading} disabled={disabled} onChange={(event) => { const id = event.target.value; if (id && !selected.includes(id)) onChange([...selected, id]); }} /><p className="text-xs text-slate-500">Select one or more active certifications. Inactive historical assignments remain read-only.</p></fieldset>;
}
