import { act, createElement } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, describe, expect, it, vi } from "vitest";

const state = vi.hoisted(() => { const availability = vi.fn(); return { availability, submitErrors: [] as unknown[], dependencies: { repositories: { equipmentAvailability: { checkEquipmentAvailability: availability } } } }; });
vi.mock("@/app/composition", () => ({ useApplicationDependenciesCompatibility: () => state.dependencies }));
vi.mock("@/components/form/useFormSubmission", () => ({ useFormSubmission: (_: string, handler: (data: unknown) => Promise<void>) => ({ busy: false, feedback: null, fail: vi.fn(), submit: async (data: unknown) => { try { await handler(data); } catch (error) { state.submitErrors.push(error); } } }) }));
vi.mock("@/components/ui/Input", () => ({ default: ({ label, ...props }: any) => createElement("label", {}, label, createElement("input", props)) }));
vi.mock("@/components/ui/Select", () => ({ default: ({ label, options = [], searchable: _searchable, clearable: _clearable, ...props }: any) => createElement("label", {}, label, createElement("select", props, options.map((o: any) => createElement("option", { key: o.value, value: o.value }, o.label)))) }));
vi.mock("@/components/ui/Button", () => ({ default: ({ children, ...props }: any) => createElement("button", props, children) }));
vi.mock("@/features/equipment/context/EquipmentContext", () => ({ useEquipment: () => ({ equipment: [] }) }));
vi.mock("@/features/customer/context/CustomerContext", () => ({ useCustomer: () => ({ customers: [] }) }));
vi.mock("@/features/project/context/ProjectContext", () => ({ useProject: () => ({ projects: [] }) }));
vi.mock("@/features/operators/context/OperatorContext", () => ({ useOperator: () => ({ operators: [] }) }));
vi.mock("@/features/assignment/context/AssignmentContext", () => ({ useAssignment: () => ({ assignments: [] }) }));
vi.mock("@/features/masters/cost-code/context/useCostCodes", () => ({ useCostCodes: () => ({ costCodes: [] }) })); vi.mock("@/features/masters/activity-code", () => ({ useActivityCodes: () => ({ records: [] }) })); vi.mock("@/features/rental/services/selectableRentalEquipment", () => ({ selectableRentalEquipment: () => [] })); vi.mock("@/features/rental/utils/rentalFormOptions", () => ({ getRentalEquipmentLabel: () => "EQ-1", getRentalProjectOptions: () => [] })); vi.mock("@/features/rental/utils/rentalDateValidation", () => ({ localCalendarDate: () => "2031-01-01", validateNewRentalDates: () => undefined })); vi.mock("@/features/rental/deur/shift-window/repository", () => ({ deurShiftWindowRepository: { getAll: () => [] } })); vi.mock("@/features/rental/services/createRentalOperationalMetadataSnapshot", () => ({ createRentalOperationalMetadataSnapshot: () => undefined })); vi.mock("@/features/rental/components/RentalOperationalMetadataCard", () => ({ default: () => null }));
import RentalForm from "@/features/rental/components/RentalForm";
let root: Root | undefined;
const data = { equipment: [{ id: "eq-a", active: true, deleted: false }, { id: "eq-b", active: true, deleted: false }] as never, customers: [] as never, projects: [] as never, operators: [{ id: "op", name: "Operator", status: "Active" }] as never, assignments: [{ id: "a", equipmentId: "eq-a", operatorId: "op", projectId: "p", status: "Active" }, { id: "b", equipmentId: "eq-b", operatorId: "op", projectId: "p", status: "Active" }] as never, costCodes: [], activityCodes: [] };
const set = (e: HTMLInputElement, v: string) => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(e, v); e.dispatchEvent(new Event("input", { bubbles: true })); e.dispatchEvent(new Event("change", { bubbles: true })); };
async function render(onSubmit: any) { const c = document.createElement("div"); root = createRoot(c); state.availability.mockImplementation(async (x: any) => ({ success: true, value: { equipmentId: x.equipmentId, available: true, conflictCount: 0, conflicts: [] } })); await act(async () => root!.render(createElement(RentalForm, { onSubmit, canonicalData: data, initialDateOut: "2031-04-10", initialExpectedReturn: "2031-04-12" }))); await act(async () => { c.querySelectorAll<HTMLInputElement>('input[type=checkbox]')[0].click(); c.querySelectorAll<HTMLInputElement>('input[type=checkbox]')[1].click(); await Promise.resolve(); await Promise.resolve(); }); return c; }
afterEach(async () => { await act(async () => root?.unmount()); state.submitErrors=[]; vi.clearAllMocks(); });
describe("D4-12 executable Rental write-race mapping", () => {
  it("replaces stale Available only on the affected line after canonical write conflict", async () => { const conflict = Object.assign(new Error("blocked"), { code: "EQUIPMENT_INTERVAL_CONFLICT", details: { equipmentId: "eq-b", available: false, conflictCount: 1, conflicts: [{ equipmentId: "eq-b", sourceType: "RENTAL", rentalNumber: "RNT-RACE", commitmentStart: "2031-04-10", commitmentEnd: "2031-04-12", isOpenEnded: false }] } }); const submit=vi.fn(async()=>{throw conflict}); const c=await render(submit); expect(c.textContent).toContain("Available for the selected dates."); await act(async()=>{c.querySelector("form")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await Promise.resolve();}); expect(submit).toHaveBeenCalled(); expect(c.textContent).toContain("Rental RNT-RACE"); expect(c.textContent).toContain("Equipment unavailable for selected dates."); expect(c.textContent).toContain("Available for the selected dates."); expect(state.submitErrors).toHaveLength(1); });
  it("preserves a non-conflict submit failure without converting availability to Conflict", async () => { const submit=vi.fn(async()=>{throw Object.assign(new Error("validation"),{code:"VALIDATION_REJECTED"})}); const c=await render(submit); await act(async()=>{c.querySelector("form")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await Promise.resolve();}); expect(submit).toHaveBeenCalled(); expect(c.textContent).toContain("Available for the selected dates."); expect(c.textContent).not.toContain("Equipment unavailable for selected dates."); });
});
