import { describe,expect,it } from "vitest";
import { BillingRateEngine,type BillingCalculationTerms } from "@/features/rental/billing/engine";
import { createDeurBillingPreview } from "@/features/rental/deur/billing/createDeurBillingPreview";
import { evaluateDeurBillingEligibility } from "@/features/rental/deur/billing/evaluateDeurBillingEligibility";
import { calculateDeurBillingStatementLine } from "@/features/rental/billingstatement/services/calculateDeurBillingStatementLine";
import type { DeurRecord } from "@/features/rental/deur/types";

const snapshot={billingMethod:"Per Cubic Meter" as const,unitRate:420,minimumBillableHours:20,standbyRate:500,overtimeRate:900,mobilizationFee:100,demobilizationFee:50,fuelCharge:25,operatorIncluded:false,operatorRate:75,taxRate:12,withholdingTax:2,currency:"PHP",capturedAt:"2026-02-27T08:15:00.000Z"};
const terms:BillingCalculationTerms={billingMethod:"Per Cubic Meter",unitRate:999,operatorIncluded:true};
function quantityDeur(overrides:Partial<DeurRecord>={}):DeurRecord{return{id:"q",rentalId:"r",equipmentId:"e",operatorId:"o",workDate:"2026-02-27",reportDate:"2026-02-27",status:"Acknowledged",legacy:false,creationSource:"OPERATOR_DIGITAL",evidenceMode:"QUANTITY",billingMethodSnapshot:"Per Cubic Meter",commercialSnapshot:snapshot,commercialSnapshotRequired:true,quantityEvidence:{quantity:18.5,unit:"CUBIC_METER"},operationalMetadata:{costCode:{code:"5031HEAVYEQPT",name:"Heavy Equipment"},activityCode:{code:"LDC",name:"Loading"},workDescription:{name:"MATERIAL HAULING",requiresRemarks:false}},events:[],logs:[],totalOperatingMinutes:999,totalIdleMinutes:999,totalMaintenanceMinutes:999,totalMealBreakMinutes:999,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,createdAt:"",updatedAt:"",...overrides}}

describe("Per Cubic Meter eligibility",()=>{
 it("accepts acknowledged immutable Quantity evidence",()=>expect(evaluateDeurBillingEligibility({deur:quantityDeur(),billingMethod:"Per Cubic Meter",unitRate:420})).toMatchObject({eligible:true,evidence:{quantity:18.5,quantityUnit:"CUBIC_METER"}}));
 it.each([[undefined,"QUANTITY_REQUIRED"],[{quantity:0,unit:"CUBIC_METER"},"QUANTITY_INVALID"],[{quantity:-1,unit:"CUBIC_METER"},"QUANTITY_INVALID"],[{quantity:Number.NaN,unit:"CUBIC_METER"},"QUANTITY_INVALID"],[{quantity:Number.POSITIVE_INFINITY,unit:"CUBIC_METER"},"QUANTITY_INVALID"]] as const)("rejects invalid quantity",(quantityEvidence,code)=>expect(evaluateDeurBillingEligibility({deur:quantityDeur({quantityEvidence:quantityEvidence as DeurRecord["quantityEvidence"]}),billingMethod:"Per Cubic Meter",unitRate:420}).reasonCode).toBe(code));
 it("rejects evidence, DEUR method, and commercial method mismatches",()=>{expect(evaluateDeurBillingEligibility({deur:quantityDeur({evidenceMode:"TIME_TIMELINE"}),billingMethod:"Per Cubic Meter",unitRate:420}).reasonCode).toBe("EVIDENCE_MODE_MISMATCH");expect(evaluateDeurBillingEligibility({deur:quantityDeur({billingMethodSnapshot:"Per Trip"}),billingMethod:"Per Cubic Meter",unitRate:420}).reasonCode).toBe("COMMERCIAL_BILLING_METHOD_MISMATCH");expect(evaluateDeurBillingEligibility({deur:quantityDeur({commercialSnapshot:{...snapshot,billingMethod:"Per Trip"}}),billingMethod:"Per Cubic Meter",unitRate:420}).reasonCode).toBe("COMMERCIAL_TERMS_MISMATCH")});
 it.each([0,-1,Number.NaN,Number.POSITIVE_INFINITY])("rejects invalid rate",unitRate=>expect(evaluateDeurBillingEligibility({deur:quantityDeur(),billingMethod:"Per Cubic Meter",unitRate}).reasonCode).toBe("COMMERCIAL_RATE_INVALID"));
});

describe("Per Cubic Meter calculation",()=>{
 it("calculates 18.5 x 420 using quantity only",()=>{const deur=quantityDeur(),before=structuredClone(deur);const result=BillingRateEngine.calculate(deur,{...terms,unitRate:420});expect(result).toMatchObject({billingQuantity:18.5,billingUnit:"CUBIC_METER",unitRate:420,operatingHours:0,idleHours:0,idleCharge:0,operatingCharge:7770});expect(deur).toEqual(before)});
 it("applies fees, VAT, and withholding once and remains deterministic and serializable",()=>{const evaluatedAt="2026-02-27T12:00:00.000Z";const preview=createDeurBillingPreview({deur:quantityDeur(),terms,evaluatedAt});const repeated=createDeurBillingPreview({deur:quantityDeur(),terms,evaluatedAt});expect(preview).toEqual(repeated);expect(preview).toMatchObject({status:"available",commercialTermsSource:"IMMUTABLE_SNAPSHOT",quantity:{value:18.5,unit:"m³"},rates:{unitRate:420},charges:{operatingCharge:7770,subtotal:8020,vat:962.4,withholdingTax:160.4,grandTotal:8822}});expect(()=>JSON.stringify(preview)).not.toThrow()});
 it("maps semantic statement fields without using hours or putting the date in Description",()=>{const result=calculateDeurBillingStatementLine(quantityDeur(),{...terms,unitRate:420});expect(result).toMatchObject({success:true,line:{description:"MATERIAL HAULING",costCode:"5031HEAVYEQPT",activityCode:"LDC",operatingHours:0,quantity:18.5,unit:"m³",unitRate:420,billingMethod:"Per Cubic Meter",amount:7770}});if(result.success)expect(result.line.description).not.toContain("02/27/2026")});
});
