import{describe,expect,it}from"vitest";
import{canCreateDeurCorrection}from"@/features/rental/deur/services/correction/canCreateDeurCorrection";
import{createDeurCorrectionRevision}from"@/features/rental/deur/services/correction/createDeurCorrectionRevision";
import{resolveEffectiveDeurRevision}from"@/features/rental/deur/services/correction/resolveEffectiveDeurRevision";
import{evaluateDeurBillingEligibility}from"@/features/rental/deur/billing/evaluateDeurBillingEligibility";
import type{DeurRecord}from"@/features/rental/deur/types";

function base(overrides:Partial<DeurRecord>={}):DeurRecord{return{id:"d1",deurNumber:"DEUR-000001",rentalId:"r",equipmentId:"e",operatorId:"o",workDate:"2026-01-01",status:"Acknowledged",legacy:false,creationSource:"OPERATOR_DIGITAL",evidenceMode:"QUANTITY",billingMethodSnapshot:"Per Cubic Meter",quantityEvidence:{quantity:10,unit:"CUBIC_METER"},events:[],logs:[],totalOperatingMinutes:0,totalIdleMinutes:0,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,acknowledgedBy:"Reviewer",acknowledgedAt:"2026-01-01T12:00:00Z",createdAt:"2026-01-01T08:00:00Z",updatedAt:"2026-01-01T12:00:00Z",...overrides}}
const input=(source=base(),chain:DeurRecord[]=[source])=>({source,chain,reasonCode:"INCORRECT_QUANTITY" as const,actor:{id:"a",name:"Admin",role:"Admin"},timestamp:"2026-01-02T08:00:00Z",newId:"d2",newDeurNumber:"DEUR-000002",changes:{quantityEvidence:{quantity:12,unit:"CUBIC_METER" as const}}});

describe("controlled DEUR correction creation",()=>{
 it("uses a pure default-deny Admin policy",()=>{expect(canCreateDeurCorrection({role:"Admin"})).toBe(true);expect(canCreateDeurCorrection({role:"Operator"})).toBe(false);expect(canCreateDeurCorrection({role:"unknown"})).toBe(false)});
 it("creates a detached Draft revision without mutating the acknowledged original",()=>{const source=base(),before=structuredClone(source),result=createDeurCorrectionRevision(input(source));expect(result).toMatchObject({success:true,sourceRevision:{revision:{chainId:"d1",revisionNumber:1,originalDeurId:"d1"}},revision:{id:"d2",status:"Draft",creationSource:"OPERATOR_DIGITAL",quantityEvidence:{quantity:12},revision:{chainId:"d1",revisionNumber:2,originalDeurId:"d1",previousRevisionId:"d1",correctionReasonCode:"INCORRECT_QUANTITY",correctedByName:"Admin"}}});expect(source).toEqual(before);if(result.success){expect(result.revision.acknowledgedAt).toBeUndefined();expect(result.revision.billingLocked).toBe(false);result.revision.quantityEvidence!.quantity=99;expect(source.quantityEvidence!.quantity).toBe(10);expect(()=>JSON.stringify(result)).not.toThrow()}});
 it("preserves Manual, operational, and commercial provenance separately",()=>{const source=base({creationSource:"RENTAL_COMPANY_MANUAL",manualMetadata:{reason:"OTHER",reasonDetails:"paper",encodedByName:"Encoder",encodedAt:"2026-01-01T08:00:00Z",physicalDeurReference:"P-1",operatorConfirmed:false},operationalMetadata:{costCode:{code:"C",name:"Cost"},activityCode:{code:"A",name:"Activity"},workDescription:{name:"WORK",requiresRemarks:false}}});const result=createDeurCorrectionRevision(input(source));expect(result).toMatchObject({success:true,revision:{creationSource:"RENTAL_COMPANY_MANUAL",manualMetadata:{physicalDeurReference:"P-1"},operationalMetadata:{costCode:{code:"C"}},revision:{correctedByName:"Admin"}}})});
 it("creates a new Draft revision after a Customer correction request",()=>{const source=base({status:"Rejected",rejectionReason:"Correct the activity time"});const result=createDeurCorrectionRevision({...input(source),reasonCode:"CUSTOMER_REQUESTED_CORRECTION"});expect(result).toMatchObject({success:true,revision:{status:"Draft",revision:{revisionNumber:2,previousRevisionId:"d1",correctionReasonCode:"CUSTOMER_REQUESTED_CORRECTION"}}});expect(source.status).toBe("Rejected")});
 it("validates reason, OTHER details, authorization, billing, supersession, and pending branches",()=>{expect(createDeurCorrectionRevision({...input(),reasonCode:undefined as never}).success).toBe(false);expect(createDeurCorrectionRevision({...input(),reasonCode:"OTHER",reasonDetails:"  "}).success).toBe(false);expect(createDeurCorrectionRevision({...input(),actor:{name:"Op",role:"Operator"}}).success).toBe(false);expect(createDeurCorrectionRevision(input(base({billingLocked:true}))).success).toBe(false);expect(createDeurCorrectionRevision(input(base({revision:{chainId:"d1",revisionNumber:1,originalDeurId:"d1",supersededByRevisionId:"d2",supersededAt:"2026-01-02T12:00:00Z"}}))).success).toBe(false);const pending=base({id:"d2",status:"Draft",revision:{chainId:"d1",revisionNumber:2,originalDeurId:"d1",previousRevisionId:"d1",correctionReasonCode:"INCORRECT_QUANTITY",correctedByName:"A",correctedAt:"2026-01-02T08:00:00Z"}});expect(createDeurCorrectionRevision(input(base(),[base(),pending])).success).toBe(false)});
});

describe("DEUR revision chain resolver and billing",()=>{
 it("resolves original, pending, rejected, and acknowledged replacement deterministically",()=>{const original=base({revision:{chainId:"d1",revisionNumber:1,originalDeurId:"d1"}});const draft=base({id:"d2",status:"Draft",acknowledgedAt:undefined,revision:{chainId:"d1",revisionNumber:2,originalDeurId:"d1",previousRevisionId:"d1",correctionReasonCode:"INCORRECT_QUANTITY",correctedByName:"A",correctedAt:"2026-01-02T08:00:00Z"}});expect(resolveEffectiveDeurRevision([draft,original])).toMatchObject({valid:true,currentEffective:{id:"d1"},pendingCorrection:{id:"d2"},ordered:[{id:"d1"},{id:"d2"}]});expect(resolveEffectiveDeurRevision([{...draft,status:"Rejected"},original])).toMatchObject({valid:true,currentEffective:{id:"d1"},pendingCorrection:undefined});const effective={...draft,status:"Acknowledged" as const,revision:{...draft.revision!,supersedesRevisionId:"d1"}};const superseded={...original,revision:{...original.revision!,supersededByRevisionId:"d2",supersededAt:"2026-01-03T08:00:00Z"}};expect(resolveEffectiveDeurRevision([effective,superseded])).toMatchObject({valid:true,currentEffective:{id:"d2"},superseded:[{id:"d1"}]})});
 it("rejects duplicate numbers, missing previous links, cycles, forks, and multiple pending corrections",()=>{const original=base({revision:{chainId:"d1",revisionNumber:1,originalDeurId:"d1"}}),r2=base({id:"d2",status:"Draft",revision:{chainId:"d1",revisionNumber:2,originalDeurId:"d1",previousRevisionId:"d1",correctionReasonCode:"OTHER",correctionReasonDetails:"x",correctedByName:"A",correctedAt:"2026-01-02T00:00:00Z"}});expect(resolveEffectiveDeurRevision([original,{...r2,revision:{...r2.revision!,revisionNumber:1}}]).valid).toBe(false);expect(resolveEffectiveDeurRevision([original,{...r2,revision:{...r2.revision!,previousRevisionId:"missing"}}]).valid).toBe(false);expect(resolveEffectiveDeurRevision([original,r2,{...r2,id:"d3",revision:{...r2.revision!,revisionNumber:3,previousRevisionId:"d1"}}]).valid).toBe(false);expect(resolveEffectiveDeurRevision([original,r2,{...r2,id:"d3",revision:{...r2.revision!,revisionNumber:3,previousRevisionId:"d2"}}]).valid).toBe(false)});
 it("blocks billing while pending, after supersession, or after any chain revision is consumed",()=>{const original=base({revision:{chainId:"d1",revisionNumber:1,originalDeurId:"d1"}}),draft=base({id:"d2",status:"Draft",revision:{chainId:"d1",revisionNumber:2,originalDeurId:"d1",previousRevisionId:"d1",correctionReasonCode:"INCORRECT_QUANTITY",correctedByName:"A",correctedAt:"2026-01-02T00:00:00Z"}});expect(evaluateDeurBillingEligibility({deur:original,billingMethod:"Per Cubic Meter",unitRate:10,revisionChain:[original,draft]}).reasonCode).toBe("DEUR_CORRECTION_PENDING");const consumed={...draft,status:"Acknowledged" as const,billingLocked:true};expect(evaluateDeurBillingEligibility({deur:original,billingMethod:"Per Cubic Meter",unitRate:10,revisionChain:[original,consumed]}).reasonCode).toBe("DEUR_REVISION_ALREADY_CONSUMED")});
});
