import { describe,expect,it } from "vitest";
import { resolveDeurEvidenceMode } from "@/features/rental/deur/services/resolveDeurEvidenceMode";
import { buildDeurOdometerTripEvidence } from "@/features/rental/deur/services/buildDeurOdometerTripEvidence";
import { normalizeCompletionEvidence,normalizeQuantityEvidence,summarizeDeurEvidence } from "@/features/rental/deur/services/deurEvidence";
import { beforeEach,vi } from "vitest";
import { storage } from "@/core/storage";
import { createDeur,createManualDeur } from "@/features/rental/deur/services/CreateDeurService";
import { appendDeurOdometerCheckpoint } from "@/features/rental/deur/services/appendDeurOdometerCheckpoint";
import { frozenDeurLine } from "./helpers/deurReleaseFixture";

describe("DEUR evidence mode",()=>{
 it.each([["Per Hour","TIME_TIMELINE"],["Per Day","TIME_TIMELINE"],["Per Week","TIME_TIMELINE"],["Per Month","TIME_TIMELINE"],["Per Kilometer","ODOMETER_TRIP"],["Per Trip","ODOMETER_TRIP"],["Per Cubic Meter","QUANTITY"],["One Lot","COMPLETION"],["Per Lot","COMPLETION"]] as const)("resolves %s",(method,mode)=>expect(resolveDeurEvidenceMode(method)).toEqual({supported:true,mode}));
 it("returns an explicit deterministic unsupported result",()=>{const input={billingMethod:"Unknown"};const first=resolveDeurEvidenceMode(input.billingMethod);expect(first).toEqual({supported:false,billingMethod:"Unknown"});expect(resolveDeurEvidenceMode(input.billingMethod)).toEqual(first);expect(input).toEqual({billingMethod:"Unknown"})});
});

describe("Odometer/trip evidence",()=>{
 const checkpoints=[{id:"a",location:" Plant ",odometerReading:52345,recordedAt:"2026-07-20T08:00:00Z"},{id:"b",location:"Project A",odometerReading:52372,recordedAt:"2026-07-20T09:00:00Z"},{id:"c",location:"Warehouse",odometerReading:52390,recordedAt:"2026-07-20T10:00:00Z"},{id:"d",location:"Plant",odometerReading:52415,recordedAt:"2026-07-20T11:00:00Z"}];
 it("derives detached checkpoints, segments, distance and trip count",()=>{const input=structuredClone(checkpoints);const result=buildDeurOdometerTripEvidence(input);expect(result.success).toBe(true);expect(input).toEqual(checkpoints);if(!result.success)return;expect(result.evidence).toMatchObject({startingOdometer:52345,endingOdometer:52415,totalDistance:70,tripCount:3});expect(result.evidence.checkpoints[0].location).toBe("Plant");expect(result.evidence.segments.map(x=>x.distance)).toEqual([27,18,25]);result.evidence.checkpoints[0].location="Changed";expect(input[0].location).toBe(" Plant ");expect(JSON.parse(JSON.stringify(result.evidence))).toEqual(result.evidence)});
 it.each([[checkpoints.slice(0,1),"At least two"],[ [{...checkpoints[0],location:" "},checkpoints[1]],"location"],[[checkpoints[0],{...checkpoints[1],odometerReading:-1}],"non-negative"],[[checkpoints[0],{...checkpoints[1],odometerReading:52345}],"greater"],[[checkpoints[0],{...checkpoints[1],odometerReading:52300}],"lower"],[[checkpoints[0],{...checkpoints[1],odometerReading:Number.NaN}],"finite"],[[checkpoints[0],{...checkpoints[1],recordedAt:"bad"}],"timestamp"],[[checkpoints[0],{...checkpoints[1],recordedAt:"2026-07-20T07:00:00Z"}],"precede"]])("rejects invalid checkpoints",(input,message)=>{const result=buildDeurOdometerTripEvidence(input as any);expect(result.success).toBe(false);if(!result.success)expect(result.issues.join(" ")).toContain(message)});
});

describe("other evidence models",()=>{
 it("normalizes positive quantity and rejects invalid completed quantity",()=>{expect(normalizeQuantityEvidence({quantity:2.5,unit:"CUBIC_METER",remarks:" load "})).toEqual({quantity:2.5,unit:"CUBIC_METER",remarks:"load"});expect(normalizeQuantityEvidence({quantity:0,unit:"CUBIC_METER"})).toBeUndefined();expect(normalizeQuantityEvidence({quantity:Infinity,unit:"CUBIC_METER"})).toBeUndefined()});
 it("normalizes completion evidence",()=>expect(normalizeCompletionEvidence({status:"COMPLETED",completedAt:"2026-07-20T12:00:00Z",remarks:" done "})).toEqual({status:"COMPLETED",completedAt:"2026-07-20T12:00:00Z",remarks:"done"}));
 it("summarizes each mode without charges",()=>expect(summarizeDeurEvidence({evidenceMode:"ODOMETER_TRIP",odometerTripEvidence:{checkpoints:[],segments:[],totalDistance:70,tripCount:3}} as any)).toEqual({mode:"ODOMETER_TRIP",totalDistance:70,tripCount:3}));
});

describe("evidence creation and persistence",()=>{
 const rental:any={id:"r",equipmentId:"e",customer:"C",project:"P",rentedBy:"A",dateOut:"2026-07-20",statusId:"active",status:"Active",billingMethod:"Per Kilometer",operationalMetadata:{costCode:{code:"5031HEAVYEQPT",name:"Heavy Equipment"},activityCode:{code:"LDC",name:"Company"}}};
 const work:any={id:"w",code:"HAUL",name:"MATERIAL HAULING",active:true,operatorSelectable:true};
 beforeEach(()=>{storage.clear();storage.set("equipment-rental-equipment-lines",{schemaVersion:1,records:[frozenDeurLine({rental,equipmentId:"e",operatorId:"o",work,billingMethod:"Per Kilometer"})]});vi.resetModules()});
 const common:any={rentalId:"r",rentalStatus:"Active",equipmentId:"e",operatorId:"o",rental,selectedWorkDescription:work,workDate:"2026-07-20",billingMethod:"Per Kilometer",openingMeter:100,odometerCheckpoints:[{id:"a",location:"Plant",odometerReading:100,recordedAt:"2026-07-20T08:00:00Z"}]};
 it("snapshots mode/method, saves checkpoints offline, reloads, and protects mode",async()=>{const result=createDeur(common);expect(result.success).toBe(true);if(!result.success)return;expect(result.record).toMatchObject({evidenceMode:"ODOMETER_TRIP",billingMethodSnapshot:"Per Kilometer",odometerTripEvidence:{startingOdometer:100,totalDistance:0,tripCount:0}});const appended=appendDeurOdometerCheckpoint(result.record,{id:"b",location:"Site",odometerReading:127,recordedAt:"2026-07-20T09:00:00Z"});expect(appended.success).toBe(true);if(!appended.success)return;const {deurRepository}=await import("@/features/rental/deur/repository/deurRepository");deurRepository.update(appended.record);const read=deurRepository.getById(result.record.id)!;expect(read.odometerTripEvidence).toMatchObject({totalDistance:27,tripCount:1});read.odometerTripEvidence!.checkpoints[0].location="Changed";expect(deurRepository.getById(result.record.id)?.odometerTripEvidence?.checkpoints[0].location).toBe("Plant");deurRepository.update({...read,evidenceMode:"TIME_TIMELINE"});expect(deurRepository.getById(result.record.id)?.evidenceMode).toBe("ODOMETER_TRIP")});
 it("creates Manual Odometer evidence through the same model",()=>{const result=createManualDeur({...common,source:"RENTAL_COMPANY_MANUAL",actor:{id:"a",name:"Admin",role:"Admin"},odometerCheckpoints:[...common.odometerCheckpoints,{id:"b",location:"Site",odometerReading:130,recordedAt:"2026-07-20T09:00:00Z"}],manualMetadata:{reason:"TECHNICAL_DIFFICULTY",physicalDeurReference:"PAPER-KM-1",operatorConfirmed:true}});expect(result.success).toBe(true);if(result.success)expect(result.record).toMatchObject({creationSource:"RENTAL_COMPANY_MANUAL",evidenceMode:"ODOMETER_TRIP",odometerTripEvidence:{totalDistance:30,tripCount:1},manualMetadata:{physicalDeurReference:"PAPER-KM-1"}})});
 it("creates Quantity and Completion evidence without acknowledgement shortcuts",()=>{const quantityRental={...rental,billingMethod:"Per Cubic Meter"};storage.set("equipment-rental-equipment-lines",{schemaVersion:1,records:[frozenDeurLine({rental:quantityRental,equipmentId:"e",operatorId:"o",work,billingMethod:"Per Cubic Meter"})]});const quantity=createDeur({...common,billingMethod:"Per Cubic Meter",rental:quantityRental,odometerCheckpoints:undefined,quantityEvidence:{quantity:5,unit:"CUBIC_METER"}});expect(quantity.success).toBe(true);if(quantity.success)expect(quantity.record).toMatchObject({evidenceMode:"QUANTITY",status:"Draft",quantityEvidence:{quantity:5}});storage.clear();const completionRental={...rental,billingMethod:"One Lot"};storage.set("equipment-rental-equipment-lines",{schemaVersion:1,records:[frozenDeurLine({rental:completionRental,equipmentId:"e",operatorId:"o",work,billingMethod:"One Lot"})]});const completion=createDeur({...common,billingMethod:"One Lot",rental:completionRental,odometerCheckpoints:undefined,completionEvidence:{status:"IN_PROGRESS"}});expect(completion.success).toBe(true);if(completion.success)expect(completion.record).toMatchObject({evidenceMode:"COMPLETION",status:"Draft",completionEvidence:{status:"IN_PROGRESS"}})});
});
