import { beforeEach, describe, expect, it, vi } from "vitest";
import { storage } from "@/core/storage";
import { canCreateManualDeur } from "@/features/rental/deur/services/manualDeurAuthorization";
import { buildManualDeurTimeline } from "@/features/rental/deur/services/buildManualDeurTimeline";
import { MANUAL_DEUR_REASONS, createManualDeur } from "@/features/rental/deur/services/CreateDeurService";
import { frozenDeurLine } from "./helpers/deurReleaseFixture";

const rental: any = { id:"r",equipmentId:"e",customer:"C",project:"P",rentedBy:"A",dateOut:"2026-07-20",statusId:"active",status:"Active",billingMethod:"Per Hour",operationalMetadata:{costCode:{code:"5031HEAVYEQPT",name:"Heavy Equipment"},activityCode:{code:"LDC",name:"LAUCHANCO DEVELOPMENT CORPORATION"}} };
const work:any={id:"w",code:"MATERIAL_HAULING",name:"MATERIAL HAULING",active:true,operatorSelectable:true,requiresRemarks:false};
const base:any={rentalId:"r",rentalStatus:"Active",equipmentId:"e",operatorId:"o",rental,selectedWorkDescription:work,source:"RENTAL_COMPANY_MANUAL",workDate:"2026-07-20",actor:{id:"admin-1",name:"Maria Santos",role:"Admin"},timeline:[{activityType:"operation",start:"2026-07-20T08:00:00.000Z",end:"2026-07-20T10:00:00.000Z"},{activityType:"idle",start:"2026-07-20T10:00:00.000Z",end:"2026-07-20T11:00:00.000Z"},{activityType:"mealBreak",start:"2026-07-20T11:00:00.000Z",end:"2026-07-20T12:00:00.000Z"},{activityType:"breakdown",start:"2026-07-20T12:00:00.000Z",end:"2026-07-20T14:00:00.000Z"}],manualMetadata:{reason:"SITE_COMPUTER_NOT_AVAILABLE",physicalDeurReference:" PAPER-001 ",sourceDocumentDate:"2026-07-20",operatorConfirmed:true,operatorConfirmedByName:"Juan",remarks:" encoded from paper "}};

describe("Manual DEUR foundation",()=>{
  beforeEach(()=>{storage.clear();storage.set("equipment-rental-equipment-lines",{schemaVersion:1,records:[frozenDeurLine({rental,equipmentId:"e",operatorId:"o",work})]});vi.resetModules()});
  it("authorizes only the temporary Equipment Department Admin role",()=>{expect(canCreateManualDeur({role:"Admin"})).toBe(true);expect(canCreateManualDeur({role:"Operator"})).toBe(false);expect(canCreateManualDeur({role:"unknown"})).toBe(false);expect(canCreateManualDeur({})).toBe(false)});
  it("supports the controlled manual reasons",()=>expect(MANUAL_DEUR_REASONS).toHaveLength(10));
  it("copies the same detached immutable commercial snapshot into a Manual DEUR",()=>{const snapshot={billingMethod:"Per Hour",unitRate:100,minimumBillableHours:0,standbyRate:0,overtimeRate:0,mobilizationFee:0,demobilizationFee:0,fuelCharge:0,operatorIncluded:true,operatorRate:0,taxRate:12,withholdingTax:2,currency:"PHP",capturedAt:"2026-07-20T07:00:00.000Z"} as const;const input:any=structuredClone({...base,rental:{...rental,commercialSnapshot:snapshot,commercialSnapshotRequired:true}});const result=createManualDeur(input);expect(result.success).toBe(true);if(!result.success)return;input.rental.commercialSnapshot.unitRate=999;expect(result.record).toMatchObject({commercialSnapshotRequired:true,commercialSnapshot:{unitRate:100,capturedAt:"2026-07-20T07:00:00.000Z"}})});
  it("creates detached canonical Manual provenance and all timeline states",()=>{const input=structuredClone(base);const result=createManualDeur(input);expect(result.success).toBe(true);if(!result.success)return;expect(result.record).toMatchObject({creationSource:"RENTAL_COMPANY_MANUAL",status:"Draft",manualMetadata:{reason:"SITE_COMPUTER_NOT_AVAILABLE",physicalDeurReference:"PAPER-001",encodedByUserId:"admin-1",encodedByName:"Maria Santos",operatorConfirmed:true,remarks:"encoded from paper"},operationalMetadata:{costCode:{code:"5031HEAVYEQPT"},activityCode:{code:"LDC"},workDescription:{name:"MATERIAL HAULING"}}});expect(new Set(result.record.events?.map((e:any)=>e.activityType))).toEqual(new Set(["shift","operation","idle","mealBreak","breakdown"]));input.manualMetadata.physicalDeurReference="changed";expect(result.record.manualMetadata?.physicalDeurReference).toBe("PAPER-001");expect(JSON.parse(JSON.stringify(result.record))).toEqual(result.record)});
  it.each([[{actor:{name:"",role:"Admin"}},"Encoded-by name is required"],[{actor:{name:"Admin",role:"Operator"}},"not authorized"],[{manualMetadata:{...base.manualMetadata,reason:undefined}},"Manual reason is required"],[{manualMetadata:{...base.manualMetadata,physicalDeurReference:"  "}},"Physical DEUR reference is required"],[{manualMetadata:{...base.manualMetadata,reason:"OTHER",reasonDetails:"  "}},"reason details are required"]])("rejects invalid manual provenance",(override,message)=>{const result=createManualDeur({...base,...override});expect(result.success).toBe(false);if(!result.success)expect(result.message).toContain(message)});
  it("rejects normalized duplicate physical references",()=>{expect(createManualDeur(base).success).toBe(true);const result=createManualDeur({...base,workDate:"2026-07-21",manualMetadata:{...base.manualMetadata,physicalDeurReference:"paper-001"}});expect(result.success).toBe(false);if(!result.success)expect(result.message).toContain("physical DEUR reference")});
  it("repository protects and deep-clones creation provenance",async()=>{const result=createManualDeur(base);expect(result.success).toBe(true);if(!result.success)return;const {deurRepository}=await import("@/features/rental/deur/repository/deurRepository");const returned=deurRepository.getById(result.record.id)!;returned.manualMetadata!.encodedByName="Mutation";expect(deurRepository.getById(result.record.id)?.manualMetadata?.encodedByName).toBe("Maria Santos");deurRepository.update({...result.record,creationSource:"OPERATOR_DIGITAL",manualMetadata:undefined});expect(deurRepository.getById(result.record.id)).toMatchObject({creationSource:"RENTAL_COMPANY_MANUAL",manualMetadata:{encodedByName:"Maria Santos"}})});
  it("uses the existing submit and acknowledgement lifecycle without a billing shortcut",async()=>{const result=createManualDeur(base);expect(result.success).toBe(true);if(!result.success)return;const {deurRepository}=await import("@/features/rental/deur/repository/deurRepository");const submitted=deurRepository.submit(result.record.id,{name:"Maria Santos"});expect(submitted.success).toBe(true);if(!submitted.success)return;expect(submitted.record).toMatchObject({status:"Submitted",creationSource:"RENTAL_COMPANY_MANUAL",billingLocked:false});const acknowledged=deurRepository.acknowledge(result.record.id,{name:"Site Reviewer"});expect(acknowledged.success).toBe(true);if(acknowledged.success)expect(acknowledged.record.manualMetadata?.physicalDeurReference).toBe("PAPER-001")});
});

describe("Manual timeline validation",()=>{
  it("orders entries, maps intervals to canonical events, and leaves inputs unchanged",()=>{const entries=[base.timeline[3],base.timeline[0],base.timeline[2],base.timeline[1]];const before=structuredClone(entries);const result=buildManualDeurTimeline({entries});expect(result.success).toBe(true);expect(entries).toEqual(before);if(result.success){expect(result.events.map(e=>e.activityType)).toContain("breakdown");expect(result.totals).toEqual({shiftMinutes:360,operationMinutes:120,idleMinutes:60,standbyMinutes:0,mealBreakMinutes:60,breakdownMinutes:120})}});
  it.each([[[],"At least one"],[[{activityType:"operation",start:"bad",end:"2026-07-20T09:00:00Z"}],"valid start"],[[{activityType:"operation",start:"2026-07-20T08:00:00Z",end:"2026-07-20T08:00:00Z"}],"positive"],[[base.timeline[0],{activityType:"idle",start:"2026-07-20T09:00:00Z",end:"2026-07-20T11:00:00Z"}],"overlap"]])("rejects invalid timelines",(entries,message)=>{const result=buildManualDeurTimeline({entries:entries as any});expect(result.success).toBe(false);if(!result.success)expect(result.issues.join(" ")).toContain(message)});
});
