import {act,createElement} from "react";
import {createRoot} from "react-dom/client";
import {describe,expect,it,vi} from "vitest";
import {ApplicationDependencyProvider,createLocalApplicationDependencies} from "@/app/composition";
import {EquipmentStatusProvider,useEquipmentStatuses} from "@/features/masters/equipment-status/context/EquipmentStatusContext";
import {repositoryFailure,repositorySuccess} from "@/core/persistence";
import {equipmentStatusRepository} from "@/features/masters/equipment-status/repository";

const record={id:"status-1",status:"Available",description:"Ready",active:true,deleted:false};
function render(repository:any,source:"local"|"supabase"="supabase"){const dependencies=createLocalApplicationDependencies({repositories:{equipmentStatusRead:repository}});dependencies.configuration.equipmentStatusSource=source;const states:string[]=[];function Probe(){const value=useEquipmentStatuses();states.push(value.loadState);return createElement("div",null,createElement("span",null,value.loadState),createElement("output",null,value.records.map(item=>item.id).join(",")),createElement("button",{onClick:value.retry},"retry"));}const container=document.createElement("div"),root=createRoot(container);return{container,root,states,element:createElement(ApplicationDependencyProvider,{dependencies},createElement(EquipmentStatusProvider,null,createElement(Probe)))};}
describe("Equipment Status provider remote state",()=>{
  it("preserves local initialization from the local repository",async()=>{const local={...record,id:"local-status"};const getAll=vi.spyOn(equipmentStatusRepository,"getAll").mockReturnValue([local]);const rendered=render({list:vi.fn().mockResolvedValue(repositorySuccess([local])),getById:vi.fn()},"local");await act(async()=>rendered.root.render(rendered.element));expect(getAll).toHaveBeenCalled();expect(rendered.container.textContent).toContain("local-status");await act(async()=>rendered.root.unmount());getAll.mockRestore();});
  it("loads once and exposes loading then loaded",async()=>{let resolve!:(value:any)=>void;const list=vi.fn(()=>new Promise(result=>{resolve=result;}));const rendered=render({list,getById:vi.fn()});await act(async()=>rendered.root.render(rendered.element));expect(rendered.states).toContain("loading");expect(list).toHaveBeenCalledTimes(1);await act(async()=>resolve(repositorySuccess([record])));expect(rendered.container.textContent).toContain("loaded");await act(async()=>rendered.root.unmount());});
  it("starts empty remotely and retains no local records on failure",async()=>{const getAll=vi.spyOn(equipmentStatusRepository,"getAll").mockReturnValue([{...record,id:"forbidden-local"}]);const list=vi.fn().mockResolvedValueOnce(repositoryFailure("NETWORK","Network failed",{context:{},recoverability:"RETRYABLE",recommendedAction:"Retry"})).mockResolvedValueOnce(repositorySuccess([record]));const rendered=render({list,getById:vi.fn()});await act(async()=>rendered.root.render(rendered.element));expect(getAll).not.toHaveBeenCalled();expect(rendered.container.textContent).toContain("error");expect(rendered.container.textContent).not.toContain("forbidden-local");await act(async()=>rendered.container.querySelector("button")?.click());expect(list).toHaveBeenCalledTimes(2);expect(rendered.container.textContent).toContain("loaded");expect(rendered.container.textContent).toContain(record.id);await act(async()=>rendered.root.unmount());getAll.mockRestore();});
  it("aborts on unmount and ignores stale completion",async()=>{let resolve!:(value:any)=>void;let signal:AbortSignal|undefined;const list=vi.fn((options:any)=>{signal=options.signal;return new Promise(result=>{resolve=result;});});const rendered=render({list,getById:vi.fn()});await act(async()=>rendered.root.render(rendered.element));await act(async()=>rendered.root.unmount());expect(signal?.aborted).toBe(true);await act(async()=>resolve(repositorySuccess([record])));expect(rendered.container.textContent).toBe("");});
});
