import { act, createElement } from "react";
import { createRoot, type Root } from "react-dom/client";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";

const state = vi.hoisted(() => ({ permissions: new Set(["equipment.create"]), localAdd: vi.fn() }));
vi.mock("@/features/auth/AuthContext", () => ({ useAuth: () => ({ hasPermission: (permission: string) => state.permissions.has(permission) }) }));
vi.mock("@/features/equipment/context/EquipmentContext", () => ({ useEquipment: () => ({ equipment: [], addEquipment: state.localAdd }) }));
vi.mock("@/features/equipment/audit/AuditContext", () => ({ useAudit: () => ({ logAction: vi.fn() }) }));

import { ApplicationDependencyProvider, createLocalApplicationDependencies, PersistenceMode, type ApplicationDependencies } from "@/app/composition";
import { subscribeCanonicalEquipmentRefresh } from "@/features/equipment/remote/canonicalEquipmentRefresh";
import NewEquipment from "@/pages/Equipment/New";

const roots: Root[] = [];
function remoteDependencies(input: { enabled?: boolean; repository?: boolean } = {}) {
  const dependencies = createLocalApplicationDependencies();
  const readReferenceData = vi.fn(async () => ({ success: true as const, disposition: "ACCEPTED" as const, serverOccurredAt: "2026-08-23T00:00:00Z", refresh: [], value: { costCodes: [{ id: "cost-1", code: "EQP", name: "Equipment", active: true as const, sortOrder: 1 }] } }));
  const createEquipment = vi.fn(async (_command: unknown) => ({ success: true as const, disposition: "ACCEPTED" as const, serverOccurredAt: "2026-08-23T00:00:00Z", refresh: [], value: { id: "equipment-1", companyId: "tenant", assetNo: "EQ-001", equipmentName: "Excavator", maintenanceType: "Engine Hours" as const, costCodeId: "cost-1", statusId: "available", currentReading: 0, remarks: null, active: true as const, deletedAt: null, createdAt: "2026-08-23T00:00:00Z", updatedAt: "2026-08-23T00:00:00Z", rowVersion: 1 } }));
  return { dependencies: { ...dependencies, commandRepositories: { ...dependencies.commandRepositories, ...(input.repository === false ? {} : { canonicalEquipment: { readReferenceData, createEquipment } }) }, configuration: { ...dependencies.configuration, persistenceMode: PersistenceMode.Remote, remoteOperationalWritesEnabled: input.enabled ?? true } } as ApplicationDependencies, readReferenceData, createEquipment };
}
async function render(dependencies: ApplicationDependencies) { const container = document.createElement("div"); const root = createRoot(container); roots.push(root); const routes = createElement(Routes, null, createElement(Route, { path: "/equipment/new", element: createElement(NewEquipment) }), createElement(Route, { path: "/equipment", element: createElement("div", null, "Canonical Equipment destination") })); await act(async () => { root.render(createElement(ApplicationDependencyProvider, { dependencies }, createElement(MemoryRouter, { initialEntries: ["/equipment/new"] }, routes))); await Promise.resolve(); }); return container; }
function input(container: HTMLElement, label: string) { const node = [...container.querySelectorAll("label")].find((candidate) => candidate.textContent?.trim().startsWith(label)); return container.querySelector(`[id="${node!.htmlFor}"]`) as HTMLInputElement; }
function setInput(node: HTMLInputElement, value: string) { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(node, value); node.dispatchEvent(new Event("input", { bubbles: true })); }
afterEach(async () => { state.permissions = new Set(["equipment.create"]); vi.clearAllMocks(); while (roots.length) await act(async () => roots.pop()?.unmount()); });

describe("canonical Equipment remote create boundary", () => {
  it("fails closed without flag, repository, or permission", async () => { expect((await render(remoteDependencies({ enabled: false }).dependencies)).textContent).toContain("Equipment changes are unavailable"); expect((await render(remoteDependencies({ repository: false }).dependencies)).textContent).toContain("Equipment changes are unavailable"); state.permissions.clear(); expect((await render(remoteDependencies().dependencies)).textContent).toContain("Equipment changes are unavailable"); });
  it("uses Equipment-owned Cost Codes and submits only approved fields", async () => {
    const { dependencies, readReferenceData, createEquipment } = remoteDependencies(); const refreshed = vi.fn(); const unsubscribe = subscribeCanonicalEquipmentRefresh(refreshed); const container = await render(dependencies);
    expect(readReferenceData).toHaveBeenCalledTimes(1); expect(container.textContent).toContain("EQP — Equipment");
    for (const unsupported of ["Status", "Project", "Operator", "Customer", "Category", "Type", "Brand", "Location", "Ownership", "Prefix", "Rate", "PIN", "Password"]) expect([...container.querySelectorAll("label")].some((label) => label.textContent?.trim().startsWith(unsupported))).toBe(false);
    await act(async () => { setInput(input(container, "Asset Number"), " EQ-001 "); setInput(input(container, "Equipment Name"), " Excavator "); const select = container.querySelectorAll("select")[1] as HTMLSelectElement; Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype, "value")!.set!.call(select, "cost-1"); select.dispatchEvent(new Event("change", { bubbles: true })); });
    await act(async () => { (container.querySelector("form") as HTMLFormElement).requestSubmit(); await Promise.resolve(); });
    expect(createEquipment).toHaveBeenCalledWith(expect.objectContaining({ assetNo: "EQ-001", equipmentName: "Excavator", maintenanceType: "Engine Hours", costCodeId: "cost-1" }));
    for (const field of ["companyId", "statusId", "active", "projectId", "operatorId", "createdBy", "rowVersion", "legacyPayload"]) expect(createEquipment.mock.calls[0][0]).not.toHaveProperty(field);
    expect(state.localAdd).not.toHaveBeenCalled(); expect(refreshed).toHaveBeenCalledTimes(1); expect(container.textContent).toContain("Canonical Equipment destination"); unsubscribe();
  });
  it("treats a canonical replay as success", async () => { const { dependencies } = remoteDependencies(); dependencies.commandRepositories.canonicalEquipment!.createEquipment = vi.fn(async () => ({ success: true as const, disposition: "REPLAYED" as const, serverOccurredAt: "2026-08-23T00:00:00Z", refresh: [], value: { id: "equipment-1", companyId: "tenant", assetNo: "EQ-001", equipmentName: "Excavator", maintenanceType: "Engine Hours" as const, costCodeId: "cost-1", statusId: "available", currentReading: 0, remarks: null, active: true as const, deletedAt: null, createdAt: "2026-08-23T00:00:00Z", updatedAt: "2026-08-23T00:00:00Z", rowVersion: 1 } })); const container = await render(dependencies); await act(async () => { setInput(input(container, "Asset Number"), "EQ-001"); setInput(input(container, "Equipment Name"), "Excavator"); const select = container.querySelectorAll("select")[1] as HTMLSelectElement; Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype, "value")!.set!.call(select, "cost-1"); select.dispatchEvent(new Event("change", { bubbles: true })); }); await act(async () => { (container.querySelector("form") as HTMLFormElement).requestSubmit(); await Promise.resolve(); }); expect(container.textContent).toContain("Canonical Equipment destination"); });
  it("shows a controlled duplicate Asset Number response without local fallback", async () => { const { dependencies } = remoteDependencies(); dependencies.commandRepositories.canonicalEquipment!.createEquipment = vi.fn(async () => ({ success: false as const, code: "ASSET_NUMBER_CONFLICT" as const, message: "Asset number already exists.", retryable: false, refreshRequired: true })); const container = await render(dependencies); await act(async () => { setInput(input(container, "Asset Number"), "EQ-001"); setInput(input(container, "Equipment Name"), "Excavator"); const select = container.querySelectorAll("select")[1] as HTMLSelectElement; Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype, "value")!.set!.call(select, "cost-1"); select.dispatchEvent(new Event("change", { bubbles: true })); }); await act(async () => { (container.querySelector("form") as HTMLFormElement).requestSubmit(); await Promise.resolve(); }); expect(container.textContent).toContain("Asset number already exists."); expect(state.localAdd).not.toHaveBeenCalled(); });
  it("keeps a canonical repository error authoritative", async () => { const { dependencies } = remoteDependencies(); dependencies.commandRepositories.canonicalEquipment!.readReferenceData = vi.fn(async () => ({ success: false as const, code: "FORBIDDEN" as const, message: "Reference forbidden.", retryable: false, refreshRequired: false })); const container = await render(dependencies); expect(container.textContent).toContain("Reference forbidden."); expect(state.localAdd).not.toHaveBeenCalled(); });
});
