import{beforeEach,describe,expect,it}from"vitest";import{storage}from"@/core/storage";import{customerReviewSubject,developmentCustomerReviewOutbox,DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY}from"@/features/rental/customer-review/developmentCustomerReviewOutbox";import{updateRentalCustomerContact}from"@/features/rental/services/updateRentalCustomerContact";import{resolveRentalWorkflowStatus}from"@/features/rental/workflow/resolveRentalWorkflowStatus";import type{RentalRecord}from"@/features/rental/types";import type{DeurRecord}from"@/features/rental/deur/types";
const rental=(x:Partial<RentalRecord>={}):RentalRecord=>({id:"r",rentalNumber:"R-1",equipmentId:"e",customer:"Customer",project:"Project",rentedBy:"Admin",dateOut:"2026-07-27",statusId:"",status:"Reserved",...x});
const deur=(x:Partial<DeurRecord>={}):DeurRecord=>({id:"d",deurNumber:"DEUR-1",rentalId:"r",equipmentId:"e",operatorId:"o",workDate:"2026-07-27",events:[],logs:[],totalOperatingMinutes:60,totalIdleMinutes:0,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,status:"Submitted",createdAt:"",updatedAt:"",...x});
const request=()=>({deurId:"d",deurNumber:"DEUR-1",revisionNumber:1,rentalNumber:"R-1",customerName:"<Customer>",representativeName:"Rep",representativeEmail:"rep@test.dev",snapshot:{project:"<Project>",equipment:"Excavator (ME-1)",operator:"Operator",workDate:"2026-07-27",submittedAt:"2026-07-27T01:00:00Z",operationMinutes:60,idleMinutes:0,breakdownMinutes:0,origin:"OPERATOR_DIGITAL",timeline:[{label:"Operation",start:"08:00",end:"09:00"}]}});
describe("final MVP stabilization",()=>{beforeEach(()=>storage.remove(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY));
it("builds a safe immutable subject and preview",()=>{const x=developmentCustomerReviewOutbox.create(request());expect(customerReviewSubject(x)).toBe("DEUR Acknowledgement Required [DEUR-1 R1] [R-1]");expect(x.html).toContain("&lt;Project&gt;");expect(x.html).not.toContain("deurId");const before=x.html;(request().snapshot as any).project="Changed";expect(developmentCustomerReviewOutbox.getById(x.id,x.generatedAt)?.html).toBe(before)});
it("returns the existing duplicate active request and replaces only explicitly",()=>{const first=developmentCustomerReviewOutbox.create(request());expect(developmentCustomerReviewOutbox.create(request()).id).toBe(first.id);const second=developmentCustomerReviewOutbox.replace(first.id,request());expect(second.token).not.toBe(first.token);expect(developmentCustomerReviewOutbox.getByToken(first.token)?.status).toBe("Superseded");expect(developmentCustomerReviewOutbox.getCurrent("d")?.id).toBe(second.id);expect(developmentCustomerReviewOutbox.decide(first.token,"Acknowledged")).toBe(false)});
it("normalizes Admin contact edits without invalidating approval and blocks pending/non-Admin edits",()=>{const approved=rental({approvalStatus:"Approved"}),result=updateRentalCustomerContact(approved,{representativeName:" Rep ","representativeEmail":"REP@TEST.DEV"},{name:"Admin",role:"Admin"},"2026-07-27T01:00:00Z");expect(result).toMatchObject({success:true,rental:{approvalStatus:"Approved",customerContactSnapshot:{representativeName:"Rep",representativeEmail:"rep@test.dev"}}});expect(updateRentalCustomerContact(approved,{representativeName:"Rep",representativeEmail:"bad"},{name:"Admin",role:"Admin"},"",false).success).toBe(false);expect(updateRentalCustomerContact(approved,{representativeName:"Rep",representativeEmail:"r@test.dev"},{name:"Manager",role:"Manager"},"",false).success).toBe(false);expect(updateRentalCustomerContact(approved,{representativeName:"Rep",representativeEmail:"r@test.dev"},{name:"Admin",role:"Admin"},"",true).success).toBe(false)});
it("applies workflow precedence and billing guards",()=>{expect(resolveRentalWorkflowStatus({rental:rental({status:"Closed"}),commercialTermsAvailable:true,billableEvidence:true}).stage).toBe("Closed");expect(resolveRentalWorkflowStatus({rental:rental({approvalStatus:"Pending"}),commercialTermsAvailable:true,billableEvidence:false}).stage).toBe("AwaitingManagerApproval");expect(resolveRentalWorkflowStatus({rental:rental({status:"Active"}),effectiveDeur:deur({status:"Rejected"}),commercialTermsAvailable:true,billableEvidence:true}).stage).toBe("CustomerCorrectionRequested");expect(resolveRentalWorkflowStatus({rental:rental({status:"Active"}),effectiveDeur:deur({status:"Acknowledged"}),commercialTermsAvailable:false,billableEvidence:true})).toMatchObject({stage:"Active",blockingReasons:[expect.stringContaining("Commercial Terms")]});expect(resolveRentalWorkflowStatus({rental:rental({status:"Active"}),effectiveDeur:deur({status:"Acknowledged"}),commercialTermsAvailable:true,billableEvidence:true}).stage).toBe("BillingEligible")})});
