import { describe, expect, it } from "vitest";
import { executeInitialMigration, validateInitialMigration, type MigrationReferences } from "@/features/data-migration/migrationService";
import { buildMigrationWorkbook, MIGRATION_WORKBOOK_HEADERS, parseMigrationWorkbook } from "@/features/data-migration/migrationWorkbook";
import type { MigrationWorkbookRows } from "@/features/data-migration/types";

const emptyRows=():MigrationWorkbookRows=>({Equipment:[],Operators:[],Customers:[],Projects:[]});
const refs=():MigrationReferences=>({equipment:[],operators:[],customers:[],projects:[],prefixes:[{id:"moving",category:"Moving Equipment",code:"ME",description:"Moving",nextNumber:1,digits:6,active:true}],categories:[{id:"cat-moving",name:"Moving Equipment",active:true}],subcategories:[{id:"sub-dump",categoryId:"cat-moving",name:"Dump Truck",active:true}],costCodes:[{id:"cost-1",code:"HEAVY",active:true}]});

describe("initial data migration",()=>{
  it("generates the required professional workbook without credential columns",()=>{const workbook=buildMigrationWorkbook();expect(workbook.worksheets.map(sheet=>sheet.name)).toEqual(expect.arrayContaining(["README","Equipment","Operators","Customers","Projects"]));expect(MIGRATION_WORKBOOK_HEADERS.Operators).not.toEqual(expect.arrayContaining(["Password","PIN","Salt","Verifier"]));expect(workbook.getWorksheet("Equipment")?.views[0]).toMatchObject({state:"frozen",ySplit:1})});
  it("escapes spreadsheet formula injection in current-data exports",()=>{const workbook=buildMigrationWorkbook({customers:[{"Customer Name *":"=HYPERLINK(\"bad\")"}]});expect(workbook.getWorksheet("Customers")?.getCell(2,2).value).toBe("'=HYPERLINK(\"bad\")")});
  it("validates customers and resolves projects by Customer Code",()=>{const rows=emptyRows();rows.Customers=[{"Customer Code":"C-1","Customer Name *":"Customer"}];rows.Projects=[{"Project Code *":"P-1","Project Name *":"Project","Customer Code *":"C-1","Status":"Active"}];const plan=validateInitialMigration(rows,refs(),"input.xlsx");expect(plan.canImport).toBe(true);expect(plan.records.projects[0].customerId).toBe(plan.records.customers[0].id)});
  it("rejects an invalid Project customer without mutation",()=>{const rows=emptyRows();rows.Projects=[{"Project Code *":"P-1","Project Name *":"Project","Customer Code *":"missing"}];const plan=validateInitialMigration(rows,refs(),"input.xlsx");expect(plan.canImport).toBe(false);expect(plan.issues.some(item=>item.field==="Customer Code *")).toBe(true)});
  it("accepts an optional Operator email and rejects duplicate Operator codes",()=>{const rows=emptyRows();rows.Operators=[{"Operator Code / Employee ID *":"OP-1","Operator Name *":"One"},{"Operator Code / Employee ID *":"op-1","Operator Name *":"Two"}];const plan=validateInitialMigration(rows,refs(),"input.xlsx");expect(plan.canImport).toBe(false);expect(plan.issues.filter(item=>item.field==="Operator Code / Employee ID *").length).toBeGreaterThan(0)});
  it("generates category asset numbers and preserves migration status with reconciliation warning",()=>{const rows=emptyRows();rows.Equipment=[{"Equipment Category *":"Moving Equipment","Equipment Sub-category":"Dump Truck","Equipment Code *":"TRUCK-01","Current Status":"Assigned"}];const plan=validateInitialMigration(rows,refs(),"input.xlsx");expect(plan.canImport).toBe(true);expect(plan.records.equipment[0]).toMatchObject({assetNo:"ME-000001",status:"Assigned"});expect(plan.counts.warning).toBe(1)});
  it("rejects duplicate Equipment Codes, unknown categories, wrong sub-category relationships, and invalid dates",()=>{const rows=emptyRows();rows.Equipment=[{"Equipment Category *":"Unknown","Equipment Code *":"EQ-1"},{"Equipment Category *":"Moving Equipment","Equipment Sub-category":"Unknown","Equipment Code *":"eq-1","Acquisition Date":"21/08/2026"}];const plan=validateInitialMigration(rows,refs(),"input.xlsx");expect(plan.canImport).toBe(false);expect(plan.issues.some(item=>item.field==="Equipment Category *")).toBe(true);expect(plan.issues.some(item=>item.field==="Equipment Code *")).toBe(true)});
  it("enforces CREATE NEW ONLY against existing identifiers and repeated imports",()=>{const rows=emptyRows();rows.Customers=[{"Customer Code":"C-1","Customer Name *":"Customer"}];const first=validateInitialMigration(rows,refs(),"input.xlsx");const nextRefs=refs();nextRefs.customers=first.records.customers;const repeated=validateInitialMigration(rows,nextRefs,"input.xlsx");expect(first.canImport).toBe(true);expect(repeated.canImport).toBe(false)});
  it("never mutates during validation and imports only after explicit administrator execution with completion counts",()=>{const rows=emptyRows();rows.Customers=[{"Customer Code":"C-1","Customer Name *":"Customer"}];const written:string[]=[];const plan=validateInitialMigration(rows,refs(),"input.xlsx");expect(written).toEqual([]);const writer={create:(value:{id:string})=>written.push(value.id),delete:(id:string)=>void written.splice(written.indexOf(id),1)};expect(()=>executeInitialMigration(plan,{Customers:writer,Projects:writer,Operators:writer,Equipment:writer},{canManageMasterData:false})).toThrow("permission");expect(written).toEqual([]);const result=executeInitialMigration(plan,{Customers:writer,Projects:writer,Operators:writer,Equipment:writer},{canManageMasterData:true});expect(result).toMatchObject({imported:1,failed:0,outcome:"Completed"});expect(written).toHaveLength(1)});
  it("rolls back staged writes when a later repository fails",()=>{const rows=emptyRows();rows.Customers=[{"Customer Code":"C-1","Customer Name *":"Customer"}];rows.Operators=[{"Operator Code / Employee ID *":"OP-1","Operator Name *":"Operator"}];const plan=validateInitialMigration(rows,refs(),"input.xlsx");const written:string[]=[];const okay={create:(value:{id:string})=>written.push(value.id),delete:(id:string)=>void written.splice(written.indexOf(id),1)};const failing={create:()=>{throw new Error("fail")},delete:()=>{}};const result=executeInitialMigration(plan,{Customers:okay,Projects:okay,Operators:failing,Equipment:okay},{canManageMasterData:true});expect(result.outcome).toBe("RolledBack");expect(written).toEqual([])});
  it("rejects malformed workbooks and unsupported files",async()=>{const file=new File(["not xlsx"],"input.xlsx",{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});await expect(parseMigrationWorkbook(file)).rejects.toThrow()});
});
