import {describe,expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {buildModernReportViewModel,clampUtilization,compactChartMaximum,metricPresentation,reportTheme} from "@/features/reports/services/reportPresentation";
import type {CustomReportSection} from "@/features/reports/services/customReportWorkspace";

const section=(type:CustomReportSection["type"],metrics:CustomReportSection["report"]["metrics"],rows:CustomReportSection["report"]["rows"]=[]):CustomReportSection=>({id:type,fingerprint:type,type,addedAt:"2026-08-15T00:00:00Z",config:{type,groupBy:"none",period:{startDate:"2026-08-01",endDate:"2026-08-15",label:"August"}},report:{title:`${type} report`,period:"August",filters:[],columns:["Reference","Status"],rows,metrics,groupBy:"none"}});
describe("modern custom report presentation",()=>{
 it("uses centralized semantic report colors",()=>{expect(reportTheme).toMatchObject({primary:"#0865d9",success:"#16a34a",danger:"#ef4444",purple:"#7c3aed"});expect(metricPresentation({label:"Active",value:2}).accent).toBe("green");expect(metricPresentation({label:"Outstanding",value:2}).accent).toBe("red");expect(metricPresentation({label:"Completed",value:2}).accent).toBe("purple");expect(metricPresentation({label:"Maintenance",value:2}).accent).toBe("orange")});
 it("builds presentation-only executive metrics from authoritative report values",()=>{const source=[section("rentals",[{label:"Total Rentals",value:12},{label:"Active",value:8}]),section("assignments",[{label:"Assignments",value:5},{label:"Active",value:3}])],view=buildModernReportViewModel(source);expect(view.executiveMetrics.map(x=>[x.metric.label,x.metric.value])).toEqual([["Total Rentals",12],["Active",8],["Assignments",5]]);expect(view.sections[0].metrics[0].metric).toBe(source[0].report.metrics[0])});
 it("uses the canonical utilization metric and clamps only its presentation",()=>{const view=buildModernReportViewModel([section("equipment",[{label:"Utilization",value:"78%",numericValue:78}])]);expect(view.sections[0].utilization).toBe(78);expect(clampUtilization(-2)).toBe(0);expect(clampUtilization(105)).toBe(100)});
 it("keeps zero comparison charts finite and scalable",()=>{expect(compactChartMaximum([metricPresentation({label:"Total",value:0,numericValue:0,previousValue:0})])).toBe(1)});
 it("retains large financial display values without recalculation",()=>{const value="₱125,000,000.00",view=buildModernReportViewModel([section("revenue",[{label:"Billed",value,numericValue:125000000}])]);expect(view.sections[0].metrics[0].metric.value).toBe(value)});
 it("defines sharp vector PDF cards, charts, gauge, continuation header, and dynamic footer",()=>{const pdf=readFileSync("src/features/reports/services/customReportPdfExport.ts","utf8");expect(pdf).toContain('orientation:"landscape"');expect(pdf).toContain("drawMetricCard");expect(pdf).toContain("drawComparisonChart");expect(pdf).toContain("drawGauge");expect(pdf).toContain("continuationHeader");expect(pdf).toContain("Page ${page} of ${total}");expect(pdf).toContain("page===total");expect(pdf).not.toContain("html2canvas")});
 it("aligns preview with the same report view model and print-safe styling",()=>{const preview=readFileSync("src/features/reports/components/ModernReportDocument.tsx","utf8");expect(preview).toContain("buildModernReportViewModel");expect(preview).toContain("MetricCard");expect(preview).toContain("ComparisonChart");expect(preview).toContain("UtilizationGauge");expect(preview).toContain("print-color-adjust:exact");expect(preview).toContain("Primary Structures Corporation logo")});
});
