import { describe, expect, it } from "vitest";
import type { IStorageService } from "@/core/storage/IStorageService";
import type { User } from "@/features/auth/domain/user";
import type { UserRepository } from "@/features/auth/repository/UserRepository";
import { AuthorizationService } from "@/features/auth/services/AuthorizationService";
import { LocalAdministrationRepository } from "@/features/administration/repository/LocalAdministrationRepository";
import { AuthorizationAuditService } from "@/features/administration/services/AuthorizationAuditService";
import { CanonicalRoleAdministrationService } from "@/features/administration/services/CanonicalRoleAdministrationService";
import { ProtectedRoleError, RoleCatalogError } from "@/features/administration/domain/contracts";
import { CONFIGURATION_SECTIONS } from "@/features/administration/services/ConfigurationRegistry";
import { UserManagementService } from "@/features/users/services/UserManagementService";

class MemoryStorage implements IStorageService { values=new Map<string,unknown>();get<T>(k:string){return (this.values.get(k) as T)??null}set<T>(k:string,v:T){this.values.set(k,v)}remove(k:string){this.values.delete(k)}clear(){this.values.clear()} }
class Users implements UserRepository {constructor(public rows:User[]){}getUsers(){return this.rows}getUserById(id:string){return this.rows.find(x=>x.id===id)}getUserByUsername(name:string){return this.rows.find(x=>x.username===name)}createUser(u:User){this.rows.push(u);return u}updateUser(u:User){this.rows=this.rows.map(x=>x.id===u.id?u:x);return u}activateUser(id:string){return this.status(id,"active")}deactivateUser(id:string){return this.status(id,"inactive")}private status(id:string,status:User["status"]){const u=this.getUserById(id)!;return this.updateUser({...u,status})}}
const admin:User={id:"admin",username:"admin",displayName:"Admin",systemRoles:["system-administrator"],status:"active",createdAt:"",updatedAt:""};

describe("P7.8 canonical administration foundation",()=>{
 it("loads nine protected roles and version-aware grouped permissions",()=>{const service=new CanonicalRoleAdministrationService(new LocalAdministrationRepository(new MemoryStorage()));expect(service.catalogVersion).toBe("2.0.0");expect(service.listRoles()).toHaveLength(9);expect(service.listRoles().every(x=>x.systemManaged)).toBe(true);expect(service.getPermissionGroups()).toHaveLength(10)});
 it("resolves Rental Operations union to exactly 47 stable unique permissions",()=>{const service=new CanonicalRoleAdministrationService(new LocalAdministrationRepository(new MemoryStorage()));const forward=service.resolvePermissions(["dispatcher","equipment-coordinator","operations-manager"]),reverse=service.resolvePermissions(["operations-manager","equipment-coordinator","dispatcher"]);expect(forward).toHaveLength(47);expect(forward).toEqual(reverse);expect(new Set(forward).size).toBe(47)});
 it("rejects protected edit, rename, and delete through the service",()=>{const service=new CanonicalRoleAdministrationService(new LocalAdministrationRepository(new MemoryStorage()));expect(()=>service.updateRole(admin,"dispatcher",{name:"Changed"})).toThrow(ProtectedRoleError);expect(()=>service.renameRole(admin,"dispatcher","Changed")).toThrow(ProtectedRoleError);expect(()=>service.deleteRole(admin,"dispatcher")).toThrow(ProtectedRoleError)});
 it("allows only System Administrators to override and reset protected-role permissions with per-permission audit",()=>{const storage=new MemoryStorage(),repo=new LocalAdministrationRepository(storage),service=new CanonicalRoleAdministrationService(repo,undefined,()=>"2026-08-13T00:00:00Z",(()=>{let n=0;return()=>`event-${++n}`})());const before=service.getRole("dispatcher")!.permissions,removed=before[0],added=service.listPermissions().find(x=>x.active&&!x.deprecated&&!before.includes(x.code))!.code;const updated=service.setRolePermissions(admin,"dispatcher",[...before.filter(x=>x!==removed),added]);expect(updated.permissions).toContain(added);expect(updated.permissions).not.toContain(removed);expect(repo.getAuditEvents().map(x=>x.action)).toEqual(["ROLE_PERMISSION_ADDED","ROLE_PERMISSION_REMOVED"]);expect(repo.getAuditEvents().map(x=>x.metadata?.permissionCode)).toEqual([added,removed]);expect(()=>service.setRolePermissions({...admin,systemRoles:["management"]},"dispatcher",before)).toThrow("System Administrator authority");expect(service.resetRolePermissions(admin,"dispatcher").permissions).toEqual(before);expect(repo.getRolePermissionOverride("dispatcher")).toBeUndefined()});
 it("clones without changing source and permits safe custom edits",()=>{const repo=new LocalAdministrationRepository(new MemoryStorage()),service=new CanonicalRoleAdministrationService(repo,undefined,()=>"2026-08-13T00:00:00Z",()=>"event");const before=service.getRole("dispatcher")!;const clone=service.cloneRole(admin,"dispatcher","ed-dispatch-custom","ED Dispatch Custom");expect(clone).toMatchObject({systemManaged:false,sourceRoleCode:"dispatcher"});expect(clone.permissions).toEqual(before.permissions);expect(service.renameRole(admin,clone.code,"Renamed").name).toBe("Renamed");expect(service.getRole("dispatcher")).toEqual(before);expect(()=>service.updateRole(admin,clone.code,{permissions:["unknown.permission"]})).toThrow(RoleCatalogError)});
 it("finds assigned users and compares roles deterministically",()=>{const users=new Users([{...admin,systemRoles:["dispatcher","equipment-coordinator"]}]);const service=new CanonicalRoleAdministrationService(new LocalAdministrationRepository(new MemoryStorage()),users);expect(service.assignedUsers("dispatcher").map(x=>x.id)).toEqual(["admin"]);const delta=service.compare("dispatcher","equipment-coordinator");expect(delta.shared).toEqual([...delta.shared].sort());expect(new Set([...delta.shared,...delta.onlyA,...delta.onlyB]).size).toBe(delta.shared.length+delta.onlyA.length+delta.onlyB.length)});
 it("supports canonical Operator linkage without inferring the role",()=>{const users=new Users([admin,{...admin,id:"u",username:"u",displayName:"U",systemRoles:["operator"]}]),audit={record:()=>undefined};const service=new UserManagementService(users,{create:(u)=>users.createUser(u)},()=>"id",()=>"now",{getById:id=>id==="op"?{id,name:"Op",email:"",licenseNumber:"",certificationType:"None",status:"Active",joinedDate:""}:undefined},new AuthorizationService(),()=>undefined,audit);const linked=service.update(admin,"u",{username:"u",displayName:"U",systemRoles:["operator"],operatorId:"op"});expect(linked.operatorId).toBe("op");const unlinked=service.update(admin,"u",{username:"u",displayName:"U",systemRoles:["operator"]});expect(unlinked.operatorId).toBeUndefined();expect(unlinked.systemRoles).toEqual(["operator"])});
 it("records safe role and access audit evidence without credentials",()=>{const storage=new MemoryStorage(),repo=new LocalAdministrationRepository(storage),audit=new AuthorizationAuditService(repo,()=>"2026-08-13T00:00:00Z",()=>"event-1");audit.record({actor:admin,targetId:"u",action:"USER_ROLE_ASSIGNED",beforeRoles:[],afterRoles:["dispatcher"],metadata:{role:"dispatcher"}});const text=JSON.stringify(audit.forUser("u"));expect(text).toContain("USER_ROLE_ASSIGNED");expect(text).not.toMatch(/password|token|secret|credential/i)});
 it("declares nine secret-safe configuration sections",()=>{expect(CONFIGURATION_SECTIONS.map(x=>x.code)).toEqual(["general","numbering","rental","deur","billing","notifications","scheduler","security","integrations"]);expect(CONFIGURATION_SECTIONS.every(x=>x.secretsPlatformManaged)).toBe(true)});
 it("keeps legacy runtime authorization unchanged and ignores canonical roles",()=>{const legacy=new AuthorizationService();expect(legacy.hasPermission({...admin,systemRoles:["finance"]},"billing.update")).toBe(true);expect(legacy.getEffectivePermissions({...admin,systemRoles:["dispatcher","equipment-coordinator","operations-manager"]}).size).toBe(0)});
});
