import{randomBytes}from"node:crypto";import{createClient,type SupabaseClient}from"@supabase/supabase-js";import{afterAll,beforeAll,describe,expect,it}from"vitest";import{assertSupabaseFixtureMutationAllowed,createSupabasePhaseC2Harness,readSupabasePhaseC2TestConfiguration}from"./support/supabasePhaseC2Harness";import{executePhaseC4bPrivilegedSql}from"./support/phaseC4bPrivilegedSql";import{executeParallelCommandRace}from"./support/parallelCommandRace";
const config=readSupabasePhaseC2TestConfiguration(),enabled=config.enabled&&process.env.RUN_PHASE_C735_LIVE==="true",tenant="TENANT-UAT-C7-NORMALIZE-001",emails=["c735-normalize-a@example.invalid","c735-normalize-b@example.invalid","c735-normalize-denied@example.invalid"];
describe.skipIf(!enabled)("guarded legacy normalization live core",()=>{const harness=enabled?createSupabasePhaseC2Harness(config):undefined,password=`C735-${randomBytes(24).toString("base64url")}`,ids:string[]=[],clients:SupabaseClient[]=[];let a:SupabaseClient,a2:SupabaseClient,b:SupabaseClient,denied:SupabaseClient;const owner=(sql:string)=>executePhaseC4bPrivilegedSql(config,{tenantIds:[tenant],sql}),cleanup=()=>owner(`SELECT erp.cleanup_c7_normalization_fixture('${tenant}','${tenant}','CONFIRM-C7-NORMALIZATION-CLEANUP');`),client=()=>{const c=createClient(config.url!,config.publishableKey!,{auth:{persistSession:false,autoRefreshToken:false,storageKey:randomBytes(8).toString("hex")}});clients.push(c);return c};
 const addRental=(suffix:string,status="Released")=>owner(`
  INSERT INTO erp.operators(id,name,status,company_id)
  VALUES('OPR-UAT-C7-NORMALIZE-${suffix}','Operator ${suffix}','Active','${tenant}');
  INSERT INTO erp.equipment(id,asset_no,equipment_name,maintenance_type,status_id,project_id,operator_id,company_id)
  VALUES('EQP-UAT-C7-NORMALIZE-${suffix}','C735-${suffix}','Equipment ${suffix}','None','REF-UAT-C7-NORMALIZE-RENTED','PRJ-UAT-C7-NORMALIZE-001','OPR-UAT-C7-NORMALIZE-${suffix}','${tenant}');
  INSERT INTO erp.assignments(id,equipment_id,operator_id,project_id,assigned_date,expected_return,status,company_id)
  VALUES('ASN-UAT-C7-NORMALIZE-${suffix}','EQP-UAT-C7-NORMALIZE-${suffix}','OPR-UAT-C7-NORMALIZE-${suffix}','PRJ-UAT-C7-NORMALIZE-001',current_date,current_date+10,'Active','${tenant}');
  INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,rental_type,status,deur_expectation_frequency,deur_expectation_effective_from,legacy_payload,company_id)
  VALUES('RENT-UAT-C7-NORMALIZE-${suffix}','C735-${suffix}','CUST-UAT-C7-NORMALIZE-001','PRJ-UAT-C7-NORMALIZE-001','Customer','Project',current_date,'Operated Rental','${status}','ON_DEMAND',current_date,'{"legacyDeurNormalizationCandidate":true}','${tenant}');
  INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,operational_metadata,commercial_snapshot_required,company_id)
  VALUES('LINE-UAT-C7-NORMALIZE-${suffix}','RENT-UAT-C7-NORMALIZE-${suffix}','EQP-UAT-C7-NORMALIZE-${suffix}','ASN-UAT-C7-NORMALIZE-${suffix}','OPR-UAT-C7-NORMALIZE-${suffix}','${status}','{"costCode":{"code":"C","name":"Cost"},"activityCode":{"code":"A","name":"Activity"},"workDescription":{"id":"W","code":"W","name":"Work","requiresRemarks":false}}',true,'${tenant}');
  INSERT INTO erp.commercial_snapshots(id,rental_id,rental_equipment_line_id,billing_method,unit_rate,operator_included,currency,captured_at)
  VALUES('SNAP-LINE-UAT-C7-NORMALIZE-${suffix}','RENT-UAT-C7-NORMALIZE-${suffix}','LINE-UAT-C7-NORMALIZE-${suffix}','Per Hour',100,true,'PHP',clock_timestamp());`);
 const normalize=(rentalId:string,key:string,expectedVersion=1)=>a.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command:{rentalId,expectedVersion,idempotencyKey:key,reason:"Certification evidence rejection"}});
 const assertRejected=(suffix:string)=>owner(`DO $$ BEGIN
  IF EXISTS(SELECT 1 FROM erp.rental_equipment_lines WHERE rental_id='RENT-UAT-C7-NORMALIZE-${suffix}' AND operational_metadata?'deurExpectationSnapshot') THEN RAISE EXCEPTION 'rejected normalization wrote snapshot'; END IF;
  IF EXISTS(SELECT 1 FROM erp.rentals WHERE id='RENT-UAT-C7-NORMALIZE-${suffix}' AND row_version<>1) OR EXISTS(SELECT 1 FROM erp.rental_equipment_lines WHERE rental_id='RENT-UAT-C7-NORMALIZE-${suffix}' AND row_version<>1) THEN RAISE EXCEPTION 'rejected normalization changed versions'; END IF;
  IF EXISTS(SELECT 1 FROM erp.audit_log WHERE aggregate_id='RENT-UAT-C7-NORMALIZE-${suffix}' AND action='LEGACY_DEUR_EXPECTATIONS_NORMALIZED') THEN RAISE EXCEPTION 'rejected normalization wrote success audit'; END IF;
  IF EXISTS(SELECT 1 FROM erp.operational_command_idempotency WHERE target_aggregate_id='RENT-UAT-C7-NORMALIZE-${suffix}' AND command_type='NORMALIZE_LEGACY_DEUR_EXPECTATIONS' AND command_status='COMPLETED') THEN RAISE EXCEPTION 'rejected normalization completed command'; END IF;
 END $$;`);
 beforeAll(async()=>{assertSupabaseFixtureMutationAllowed(config,[tenant]);expect(process.env.VITE_REMOTE_OPERATIONAL_WRITES_ENABLED).toBe("false");cleanup();const listed=await harness!.admin.auth.admin.listUsers({page:1,perPage:1000});if(listed.error)throw listed.error;for(const u of listed.data.users.filter(u=>emails.includes(u.email??"")))await harness!.admin.auth.admin.deleteUser(u.id);for(const email of emails){const made=await harness!.admin.auth.admin.createUser({email,password,email_confirm:true});if(made.error||!made.data.user)throw made.error;ids.push(made.data.user.id)}
 owner(`BEGIN;
 INSERT INTO erp.companies(id,code,name,environment_class)VALUES('${tenant}','${tenant}','C7 Normalize','test');
 INSERT INTO erp.operators(id,name,status,company_id)VALUES('OPR-UAT-C7-NORMALIZE-A','Operator A','Active','${tenant}'),('OPR-UAT-C7-NORMALIZE-B','Operator B','Active','${tenant}');
 INSERT INTO erp.users(id,username,display_name,status,operator_id,company_id)VALUES('${ids[0]}'::uuid,'c735-a','A','active','OPR-UAT-C7-NORMALIZE-A','${tenant}'),('${ids[1]}'::uuid,'c735-b','B','active','OPR-UAT-C7-NORMALIZE-B','${tenant}'),('${ids[2]}'::uuid,'c735-denied','Denied','active',NULL,'${tenant}');
 INSERT INTO erp.user_roles(user_id,role_id)SELECT actor,r.id FROM(VALUES('${ids[0]}'::uuid),('${ids[1]}'::uuid))x(actor)CROSS JOIN erp.app_roles r WHERE r.code='rental-operations';
 INSERT INTO erp.customers(id,customer_code,name,company_id)VALUES('CUST-UAT-C7-NORMALIZE-001','C735','Customer','${tenant}');
 INSERT INTO erp.projects(id,project_code,name,customer_id,company_id)VALUES('PRJ-UAT-C7-NORMALIZE-001','C735','Project','CUST-UAT-C7-NORMALIZE-001','${tenant}');
 INSERT INTO erp.equipment_statuses(id,code,name,active)VALUES('REF-UAT-C7-NORMALIZE-RENTED','c735-rented','Rented',true);
 INSERT INTO erp.equipment(id,asset_no,equipment_name,maintenance_type,status_id,project_id,operator_id,company_id)VALUES('EQP-UAT-C7-NORMALIZE-A','C735-A','Equipment A','None','REF-UAT-C7-NORMALIZE-RENTED','PRJ-UAT-C7-NORMALIZE-001','OPR-UAT-C7-NORMALIZE-A','${tenant}'),('EQP-UAT-C7-NORMALIZE-B','C735-B','Equipment B','None','REF-UAT-C7-NORMALIZE-RENTED','PRJ-UAT-C7-NORMALIZE-001','OPR-UAT-C7-NORMALIZE-B','${tenant}');
 INSERT INTO erp.assignments(id,equipment_id,operator_id,project_id,assigned_date,expected_return,status,company_id)VALUES('ASN-UAT-C7-NORMALIZE-A','EQP-UAT-C7-NORMALIZE-A','OPR-UAT-C7-NORMALIZE-A','PRJ-UAT-C7-NORMALIZE-001',current_date,current_date+10,'Active','${tenant}'),('ASN-UAT-C7-NORMALIZE-B','EQP-UAT-C7-NORMALIZE-B','OPR-UAT-C7-NORMALIZE-B','PRJ-UAT-C7-NORMALIZE-001',current_date,current_date+10,'Active','${tenant}');
 INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,rental_type,status,deur_expectation_frequency,deur_expectation_effective_from,legacy_payload,company_id)VALUES('RENT-UAT-C7-NORMALIZE-GOOD','C735-GOOD','CUST-UAT-C7-NORMALIZE-001','PRJ-UAT-C7-NORMALIZE-001','Customer','Project',current_date,'Operated Rental','Released','ON_DEMAND',current_date,'{"legacyDeurNormalizationCandidate":true}','${tenant}'),('RENT-UAT-C7-NORMALIZE-BAD','C735-BAD','CUST-UAT-C7-NORMALIZE-001','PRJ-UAT-C7-NORMALIZE-001','Customer','Project',current_date,'Operated Rental','Released','ON_DEMAND',current_date,'{"legacyDeurNormalizationCandidate":true}','${tenant}');
 INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,operational_metadata,commercial_snapshot_required,company_id)VALUES
 ('LINE-UAT-C7-NORMALIZE-A','RENT-UAT-C7-NORMALIZE-GOOD','EQP-UAT-C7-NORMALIZE-A','ASN-UAT-C7-NORMALIZE-A','OPR-UAT-C7-NORMALIZE-A','Released','{"costCode":{"code":"C","name":"Cost"},"activityCode":{"code":"A","name":"Activity"},"workDescription":{"id":"W","code":"W","name":"Work","requiresRemarks":false}}',true,'${tenant}'),
 ('LINE-UAT-C7-NORMALIZE-B','RENT-UAT-C7-NORMALIZE-GOOD','EQP-UAT-C7-NORMALIZE-B','ASN-UAT-C7-NORMALIZE-B','OPR-UAT-C7-NORMALIZE-B','Released','{"costCode":{"code":"C","name":"Cost"},"activityCode":{"code":"A","name":"Activity"},"workDescription":{"id":"W","code":"W","name":"Work","requiresRemarks":false}}',true,'${tenant}'),
 ('LINE-UAT-C7-NORMALIZE-BAD-A','RENT-UAT-C7-NORMALIZE-BAD','EQP-UAT-C7-NORMALIZE-A','ASN-UAT-C7-NORMALIZE-A','OPR-UAT-C7-NORMALIZE-A','Released','{"costCode":{"code":"C"},"activityCode":{"code":"A"},"workDescription":{"name":"Work"}}',true,'${tenant}'),
 ('LINE-UAT-C7-NORMALIZE-BAD-B','RENT-UAT-C7-NORMALIZE-BAD','EQP-UAT-C7-NORMALIZE-B','ASN-UAT-C7-NORMALIZE-B','OPR-UAT-C7-NORMALIZE-B','Released','{}',true,'${tenant}');
 INSERT INTO erp.commercial_snapshots(id,rental_id,rental_equipment_line_id,billing_method,unit_rate,operator_included,currency,captured_at)SELECT 'SNAP-'||id,rental_id,id,'Per Hour',100,true,'PHP',clock_timestamp()FROM erp.rental_equipment_lines WHERE company_id='${tenant}';COMMIT;`);
 a=client();a2=client();b=client();denied=client();for(const [c,email]of[[a,emails[0]],[a2,emails[0]],[b,emails[1]],[denied,emails[2]]]as const){const login=await c.auth.signInWithPassword({email,password});if(login.error)throw login.error}},90_000);
 afterAll(async()=>{await Promise.allSettled(clients.map(c=>c.auth.signOut()));try{cleanup()}catch{}for(const id of ids)await harness!.admin.auth.admin.deleteUser(id);try{cleanup()}catch{}},90_000);
 it("normalizes two lines atomically and enforces replay/mismatch",async()=>{const command={rentalId:"RENT-UAT-C7-NORMALIZE-GOOD",expectedVersion:1,idempotencyKey:"C735-GOOD",reason:"Certified legacy normalization"};const accepted=await a.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command});expect(accepted.error).toBeNull();expect(accepted.data).toMatchObject({success:true,disposition:"ACCEPTED",value:{lineCount:2}});expect((await a.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command})).data).toMatchObject({success:true,disposition:"REPLAYED"});expect((await a.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command:{...command,reason:"changed"}})).data).toMatchObject({success:false,code:"IDEMPOTENCY_MISMATCH"});const ready=await a.schema("erp").rpc("rental_release_readiness",{target_rental_id:command.rentalId});expect(ready.data).toMatchObject({eligible:true});},20_000);
 it("rejects incomplete two-line and unauthorized callers without partial snapshots",async()=>{const command={rentalId:"RENT-UAT-C7-NORMALIZE-BAD",expectedVersion:1,idempotencyKey:"C735-BAD",reason:"test"};expect((await a.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command})).data).toMatchObject({success:false});expect((await denied.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command:{...command,idempotencyKey:"C735-DENIED"}})).data).toMatchObject({success:false,code:"FORBIDDEN"});owner(`DO $$ BEGIN IF EXISTS(SELECT 1 FROM erp.rental_equipment_lines WHERE rental_id='RENT-UAT-C7-NORMALIZE-BAD' AND operational_metadata?'deurExpectationSnapshot')THEN RAISE EXCEPTION 'partial normalization';END IF;END $$;`);},20_000);
 it("starts normalized lines with independent owners and blocks reciprocal cross-owner attempts",async()=>{const start=(c:SupabaseClient,line:string,equipment:string,assignment:string,operator:string,id:string)=>c.schema("erp").rpc("command_start_deur_shift",{command:{commandId:id,idempotencyKey:id,rentalId:"RENT-UAT-C7-NORMALIZE-GOOD",rentalLineId:line,equipmentId:equipment,assignmentId:assignment,operatorId:operator,draft:{id,operationalMetadata:{override:true}}}});expect((await start(a,"LINE-UAT-C7-NORMALIZE-A","EQP-UAT-C7-NORMALIZE-A","ASN-UAT-C7-NORMALIZE-A","OPR-UAT-C7-NORMALIZE-A","DEUR-UAT-C7-NORMALIZE-A")).data).toMatchObject({success:true});expect((await start(b,"LINE-UAT-C7-NORMALIZE-B","EQP-UAT-C7-NORMALIZE-B","ASN-UAT-C7-NORMALIZE-B","OPR-UAT-C7-NORMALIZE-B","DEUR-UAT-C7-NORMALIZE-B")).data).toMatchObject({success:true});expect((await start(a,"LINE-UAT-C7-NORMALIZE-B","EQP-UAT-C7-NORMALIZE-B","ASN-UAT-C7-NORMALIZE-B","OPR-UAT-C7-NORMALIZE-B","DEUR-UAT-C7-NORMALIZE-X")).data).toMatchObject({success:false,code:"OWNERSHIP_MISMATCH"});expect((await start(b,"LINE-UAT-C7-NORMALIZE-A","EQP-UAT-C7-NORMALIZE-A","ASN-UAT-C7-NORMALIZE-A","OPR-UAT-C7-NORMALIZE-A","DEUR-UAT-C7-NORMALIZE-Y")).data).toMatchObject({success:false,code:"OWNERSHIP_MISMATCH"});},20_000);
 it("reports customer-review evidence as the controlling normalization rejection",async()=>{
  owner(`INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,rental_type,status,deur_expectation_frequency,deur_expectation_effective_from,legacy_payload,company_id)
   VALUES('RENT-UAT-C7-NORMALIZE-CUSTOMER','C735-CUSTOMER','CUST-UAT-C7-NORMALIZE-001','PRJ-UAT-C7-NORMALIZE-001','Customer','Project',current_date,'Operated Rental','Released','ON_DEMAND',current_date,'{"legacyDeurNormalizationCandidate":true}','${tenant}');
   INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,operational_metadata,commercial_snapshot_required,company_id)
   VALUES('LINE-UAT-C7-NORMALIZE-CUSTOMER','RENT-UAT-C7-NORMALIZE-CUSTOMER','EQP-UAT-C7-NORMALIZE-A','ASN-UAT-C7-NORMALIZE-A','OPR-UAT-C7-NORMALIZE-A','Released','{"costCode":{"code":"C","name":"Cost"},"activityCode":{"code":"A","name":"Activity"},"workDescription":{"id":"W","code":"W","name":"Work","requiresRemarks":false}}',true,'${tenant}');
   INSERT INTO erp.commercial_snapshots(id,rental_id,rental_equipment_line_id,billing_method,unit_rate,operator_included,currency,captured_at)
   VALUES('SNAP-LINE-UAT-C7-NORMALIZE-CUSTOMER','RENT-UAT-C7-NORMALIZE-CUSTOMER','LINE-UAT-C7-NORMALIZE-CUSTOMER','Per Hour',100,true,'PHP',clock_timestamp());
   INSERT INTO erp.deurs(id,deur_number,rental_id,rental_equipment_line_id,assignment_id,equipment_id,operator_id,project_id,customer_id,commercial_snapshot_id,commercial_snapshot_required,work_date,status,submitted_at,company_id)
   VALUES('DEUR-UAT-C7-NORMALIZE-CUSTOMER','C735-DEUR-CUSTOMER','RENT-UAT-C7-NORMALIZE-CUSTOMER','LINE-UAT-C7-NORMALIZE-CUSTOMER','ASN-UAT-C7-NORMALIZE-A','EQP-UAT-C7-NORMALIZE-A','OPR-UAT-C7-NORMALIZE-A','PRJ-UAT-C7-NORMALIZE-001','CUST-UAT-C7-NORMALIZE-001','SNAP-LINE-UAT-C7-NORMALIZE-CUSTOMER',true,current_date,'Submitted',clock_timestamp(),'${tenant}');
   INSERT INTO erp.customer_review_requests(company_id,rental_id,rental_equipment_line_id,deur_id,revision_id,equipment_id,operator_id,customer_id,token_hash,expires_at,created_by,recipient_name,recipient_destination,revision_version,snapshot)
   VALUES('${tenant}','RENT-UAT-C7-NORMALIZE-CUSTOMER','LINE-UAT-C7-NORMALIZE-CUSTOMER','DEUR-UAT-C7-NORMALIZE-CUSTOMER','DEUR-UAT-C7-NORMALIZE-CUSTOMER','EQP-UAT-C7-NORMALIZE-A','OPR-UAT-C7-NORMALIZE-A','CUST-UAT-C7-NORMALIZE-001','C735-CUSTOMER-HASH',clock_timestamp()+interval '1 hour','${ids[0]}'::uuid,'Controlled Customer','customer@example.invalid',1,'{}');`);
  const result=await a.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command:{rentalId:"RENT-UAT-C7-NORMALIZE-CUSTOMER",expectedVersion:1,idempotencyKey:"C735-CUSTOMER-REJECT",reason:"Certification evidence rejection"}});
  expect(result.error).toBeNull();
  owner(`DO $$ BEGIN
   IF EXISTS(SELECT 1 FROM erp.rental_equipment_lines WHERE rental_id='RENT-UAT-C7-NORMALIZE-CUSTOMER' AND (operational_metadata?'deurExpectationSnapshot' OR operational_metadata?'deurExpectationFingerprint')) THEN RAISE EXCEPTION 'rejected normalization wrote snapshot evidence'; END IF;
   IF EXISTS(SELECT 1 FROM erp.rentals WHERE id='RENT-UAT-C7-NORMALIZE-CUSTOMER' AND row_version<>1) OR EXISTS(SELECT 1 FROM erp.rental_equipment_lines WHERE rental_id='RENT-UAT-C7-NORMALIZE-CUSTOMER' AND row_version<>1) THEN RAISE EXCEPTION 'rejected normalization changed versions'; END IF;
   IF EXISTS(SELECT 1 FROM erp.audit_log WHERE aggregate_id='RENT-UAT-C7-NORMALIZE-CUSTOMER' AND action='LEGACY_DEUR_EXPECTATIONS_NORMALIZED') THEN RAISE EXCEPTION 'rejected normalization wrote success audit'; END IF;
   IF EXISTS(SELECT 1 FROM erp.operational_command_idempotency WHERE target_aggregate_id='RENT-UAT-C7-NORMALIZE-CUSTOMER' AND command_type='NORMALIZE_LEGACY_DEUR_EXPECTATIONS' AND command_status='COMPLETED') THEN RAISE EXCEPTION 'rejected normalization completed command'; END IF;
   IF NOT EXISTS(SELECT 1 FROM erp.customer_review_requests WHERE rental_id='RENT-UAT-C7-NORMALIZE-CUSTOMER' AND token_hash='C735-CUSTOMER-HASH') THEN RAISE EXCEPTION 'protected review evidence changed'; END IF;
  END $$;`);
 expect(result.data).toMatchObject({success:false,code:"CUSTOMER_REVIEW_EXISTS"});
 },20_000);
 it("returns specific Draft and Submitted DEUR evidence reasons",async()=>{
  for(const [suffix,status]of[["DRAFT","Draft"],["SUBMITTED","Submitted"]]as const){
   addRental(suffix);
   owner(`INSERT INTO erp.deurs(id,deur_number,rental_id,rental_equipment_line_id,assignment_id,equipment_id,operator_id,project_id,customer_id,commercial_snapshot_id,commercial_snapshot_required,work_date,status,submitted_at,company_id)
    VALUES('DEUR-UAT-C7-NORMALIZE-${suffix}','C735-DEUR-${suffix}','RENT-UAT-C7-NORMALIZE-${suffix}','LINE-UAT-C7-NORMALIZE-${suffix}','ASN-UAT-C7-NORMALIZE-${suffix}','EQP-UAT-C7-NORMALIZE-${suffix}','OPR-UAT-C7-NORMALIZE-${suffix}','PRJ-UAT-C7-NORMALIZE-001','CUST-UAT-C7-NORMALIZE-001','SNAP-LINE-UAT-C7-NORMALIZE-${suffix}',true,current_date,'${status}',${status==="Draft"?"NULL":"clock_timestamp()"},'${tenant}');`);
   const result=await normalize(`RENT-UAT-C7-NORMALIZE-${suffix}`,`C735-${suffix}-REJECT`);
   expect(result.error).toBeNull();expect(result.data).toMatchObject({success:false,code:status==="Draft"?"DRAFT_DEUR_INCOMPATIBLE":"SUBMITTED_DEUR_EXISTS"});
   assertRejected(suffix);owner(`DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM erp.deurs WHERE id='DEUR-UAT-C7-NORMALIZE-${suffix}' AND status='${status}') THEN RAISE EXCEPTION 'DEUR evidence changed';END IF;END $$;`);
  }
 },30_000);
 it("prioritizes manager outcome over customer and submitted evidence",async()=>{
  owner(`INSERT INTO erp.manager_review_requests(id,company_id,rental_id,rental_equipment_line_id,deur_id,revision_id,recipient_user_id,recipient_name,recipient_destination,token_hash,revision_version,snapshot,expires_at,created_by)
   VALUES('00000000-0000-4000-8000-000000000735'::uuid,'${tenant}','RENT-UAT-C7-NORMALIZE-CUSTOMER','LINE-UAT-C7-NORMALIZE-CUSTOMER','DEUR-UAT-C7-NORMALIZE-CUSTOMER','DEUR-UAT-C7-NORMALIZE-CUSTOMER','${ids[0]}'::uuid,'Manager','manager@example.invalid','C735-MANAGER-HASH',1,'{}',clock_timestamp()+interval '1 hour','${ids[0]}'::uuid);
   INSERT INTO erp.manager_review_outcomes(id,company_id,review_request_id,rental_id,deur_id,revision_id,reviewer_user_id,reviewer_name,action)
   VALUES('00000000-0000-4000-8000-000000000736'::uuid,'${tenant}','00000000-0000-4000-8000-000000000735'::uuid,'RENT-UAT-C7-NORMALIZE-CUSTOMER','DEUR-UAT-C7-NORMALIZE-CUSTOMER','DEUR-UAT-C7-NORMALIZE-CUSTOMER','${ids[0]}'::uuid,'Manager','APPROVE');`);
  const result=await normalize("RENT-UAT-C7-NORMALIZE-CUSTOMER","C735-MANAGER-REJECT");expect(result.error).toBeNull();expect(result.data).toMatchObject({success:false,code:"MANAGER_OUTCOME_EXISTS",eligibility:{reasonCodes:expect.arrayContaining(["MANAGER_OUTCOME_EXISTS","CUSTOMER_REVIEW_EXISTS","SUBMITTED_DEUR_EXISTS"])}});assertRejected("CUSTOMER");owner(`DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM erp.manager_review_outcomes WHERE id='00000000-0000-4000-8000-000000000736'::uuid) THEN RAISE EXCEPTION 'manager evidence changed';END IF;END $$;`);
 },20_000);
 it("returns billing, invoice, and recovery evidence reasons",async()=>{
  for(const [suffix,invoiceStatus,expected]of[["BILLING","Not Invoiced","BILLING_EVIDENCE_EXISTS"],["INVOICE","Invoiced","INVOICE_OR_COLLECTION_EXISTS"]]as const){
   addRental(suffix);owner(`INSERT INTO erp.billing_statements(id,statement_no,rental_id,customer_snapshot,project_snapshot,billing_from,billing_to,subtotal,grand_total,approval_status,invoice_status,created_by,company_id)
    VALUES('BILL-UAT-C7-NORMALIZE-${suffix}','C735-BILL-${suffix}','RENT-UAT-C7-NORMALIZE-${suffix}','Customer','Project',current_date,current_date,0,0,'Draft','${invoiceStatus}','certification','${tenant}');`);
   const result=await normalize(`RENT-UAT-C7-NORMALIZE-${suffix}`,`C735-${suffix}-REJECT`);expect(result.error).toBeNull();expect(result.data).toMatchObject({success:false,code:expected});assertRejected(suffix);owner(`DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM erp.billing_statements WHERE id='BILL-UAT-C7-NORMALIZE-${suffix}' AND invoice_status='${invoiceStatus}') THEN RAISE EXCEPTION 'billing evidence changed';END IF;END $$;`);
  }
  addRental("RECOVERY");owner(`INSERT INTO erp.recovery_compensations(company_id,target_entity_type,target_entity_id,recovery_action,reason,initiated_by,prior_state,resulting_state,prior_version,resulting_version,idempotency_key)
   VALUES('${tenant}','RENTAL','RENT-UAT-C7-NORMALIZE-RECOVERY','CERTIFICATION_BLOCK','Certification recovery evidence','${ids[0]}'::uuid,'{}','{}',1,1,'C735-RECOVERY-EVIDENCE');`);
  const recovery=await normalize("RENT-UAT-C7-NORMALIZE-RECOVERY","C735-RECOVERY-REJECT");expect(recovery.error).toBeNull();expect(recovery.data).toMatchObject({success:false,code:"RECOVERY_EVIDENCE_EXISTS"});assertRejected("RECOVERY");owner(`DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM erp.recovery_compensations WHERE target_entity_id='RENT-UAT-C7-NORMALIZE-RECOVERY') THEN RAISE EXCEPTION 'recovery evidence changed';END IF;END $$;`);
 },30_000);
 it("prioritizes returned and closed lifecycle state",async()=>{
  for(const status of ["Returned","Closed"]as const){const suffix=status.toUpperCase();addRental(suffix,status);const result=await normalize(`RENT-UAT-C7-NORMALIZE-${suffix}`,`C735-${suffix}-REJECT`);expect(result.error).toBeNull();expect(result.data).toMatchObject({success:false,code:"RETURNED_OR_CLOSED_RENTAL"});assertRejected(suffix);owner(`DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM erp.rentals WHERE id='RENT-UAT-C7-NORMALIZE-${suffix}' AND status='${status}') THEN RAISE EXCEPTION 'terminal lifecycle evidence changed';END IF;END $$;`)}
 },20_000);
 it("returns ALREADY_NORMALIZED for a new key and CONFLICT for a stale version",async()=>{
  addRental("VERSION");const accepted=await normalize("RENT-UAT-C7-NORMALIZE-VERSION","C735-VERSION-ACCEPT");expect(accepted.data).toMatchObject({success:true,disposition:"ACCEPTED"});const already=await normalize("RENT-UAT-C7-NORMALIZE-VERSION","C735-VERSION-NEW",2);expect(already.data).toMatchObject({success:false,code:"ALREADY_NORMALIZED"});
  addRental("STALE");const stale=await normalize("RENT-UAT-C7-NORMALIZE-STALE","C735-STALE",0);expect(stale.data).toMatchObject({success:false,code:"CONFLICT",currentVersion:1});const current=await normalize("RENT-UAT-C7-NORMALIZE-STALE","C735-CURRENT",1);expect(current.data).toMatchObject({success:true,disposition:"ACCEPTED"});
 },20_000);
 it("enforces anonymous, same-company permission, payload-authority, and cross-tenant boundaries",async()=>{
  const anonymous=await harness!.anonymous.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command:{rentalId:"RENT-UAT-C7-NORMALIZE-BAD",expectedVersion:1,idempotencyKey:"C735-ANON",reason:"Anonymous probe"}});expect(anonymous.error).not.toBeNull();
  const forbidden=await denied.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command:{rentalId:"RENT-UAT-C7-NORMALIZE-BAD",expectedVersion:1,idempotencyKey:"C735-FORBIDDEN-2",reason:"Permission probe"}});expect(forbidden.data).toMatchObject({success:false,code:"FORBIDDEN"});
  const injected=await a.schema("erp").rpc("command_normalize_legacy_rental_deur_expectations",{command:{rentalId:"RENT-UAT-C7-NORMALIZE-BAD",expectedVersion:1,idempotencyKey:"C735-INJECTED",reason:"Authority probe",companyId:tenant,actorId:ids[0]}});expect(injected.data).toMatchObject({success:false,code:"VALIDATION_REJECTED"});
  executePhaseC4bPrivilegedSql(config,{tenantIds:[tenant,"TENANT-UAT-C7-NORMALIZE-B"],sql:`BEGIN;
   INSERT INTO erp.companies(id,code,name,environment_class)VALUES('TENANT-UAT-C7-NORMALIZE-B','TENANT-UAT-C7-NORMALIZE-B','Cross Tenant','test');
   INSERT INTO erp.rentals(id,customer_snapshot,project_snapshot,date_out,status,legacy_payload,company_id)VALUES('RENT-UAT-C7-NORMALIZE-CROSS','Customer','Project',current_date,'Released','{"legacyDeurNormalizationCandidate":true}','TENANT-UAT-C7-NORMALIZE-B');
   DO $$ DECLARE result jsonb; BEGIN PERFORM set_config('request.jwt.claims',jsonb_build_object('sub','${ids[0]}','role','authenticated')::text,true);result=erp.command_normalize_legacy_rental_deur_expectations('{"rentalId":"RENT-UAT-C7-NORMALIZE-CROSS","expectedVersion":1,"idempotencyKey":"C735-CROSS","reason":"Cross tenant probe"}'::jsonb);IF result->>'code'<>'NOT_FOUND' THEN RAISE EXCEPTION 'cross-tenant concealment failed';END IF;END $$;
   ROLLBACK;`});
 },30_000);
 it("serializes genuine normalization races without duplicates or deadlocks",async()=>{
  const rpc="command_normalize_legacy_rental_deur_expectations";
  addRental("RACE-A");const same={rentalId:"RENT-UAT-C7-NORMALIZE-RACE-A",expectedVersion:1,idempotencyKey:"C735-RACE-A",reason:"Same-key race"};const raceA=await executeParallelCommandRace({clientA:a,clientB:a2,rpcA:rpc,commandA:same,commandB:same,timeoutMs:20_000});expect(raceA.deadlock).toBe(false);expect(raceA.overlapped).toBe(true);expect([raceA.a.data?.disposition,raceA.b.data?.disposition].sort()).toEqual(["ACCEPTED","REPLAYED"]);
  addRental("RACE-B");const baseB={rentalId:"RENT-UAT-C7-NORMALIZE-RACE-B",expectedVersion:1,reason:"Different-key race"};const raceB=await executeParallelCommandRace({clientA:a,clientB:b,rpcA:rpc,commandA:{...baseB,idempotencyKey:"C735-RACE-B-A"},commandB:{...baseB,idempotencyKey:"C735-RACE-B-B"},timeoutMs:20_000});expect(raceB.deadlock).toBe(false);expect(raceB.overlapped).toBe(true);const raceBResults=[raceB.a.data,raceB.b.data];expect(raceBResults.filter(value=>value?.disposition==="ACCEPTED")).toHaveLength(1);expect(raceBResults.filter(value=>value?.code==="CONFLICT"||value?.code==="ALREADY_NORMALIZED")).toHaveLength(1);
  addRental("RACE-C");const baseC={rentalId:"RENT-UAT-C7-NORMALIZE-RACE-C",reason:"Version race"};const raceC=await executeParallelCommandRace({clientA:a,clientB:b,rpcA:rpc,commandA:{...baseC,expectedVersion:1,idempotencyKey:"C735-RACE-C-VALID"},commandB:{...baseC,expectedVersion:0,idempotencyKey:"C735-RACE-C-STALE"},timeoutMs:20_000});expect(raceC.deadlock).toBe(false);expect(raceC.overlapped).toBe(true);expect([raceC.a.data,raceC.b.data].some(value=>value?.disposition==="ACCEPTED")).toBe(true);expect([raceC.a.data,raceC.b.data].some(value=>value?.code==="CONFLICT")).toBe(true);
  console.info("C735_RACE_EVIDENCE",JSON.stringify({A:{skewMs:raceA.releaseSkewMs,overlap:raceA.overlapped,deadlock:raceA.deadlock,results:[raceA.a.data?.disposition,raceA.b.data?.disposition]},B:{skewMs:raceB.releaseSkewMs,overlap:raceB.overlapped,deadlock:raceB.deadlock,results:raceBResults.map(value=>value?.disposition??value?.code)},C:{skewMs:raceC.releaseSkewMs,overlap:raceC.overlapped,deadlock:raceC.deadlock,results:[raceC.a.data?.disposition??raceC.a.data?.code,raceC.b.data?.disposition??raceC.b.data?.code]}}));
  owner(`DO $$ DECLARE target record;BEGIN FOR target IN SELECT unnest(ARRAY['RACE-A','RACE-B','RACE-C']) suffix LOOP IF (SELECT count(*) FROM erp.rental_equipment_lines WHERE rental_id='RENT-UAT-C7-NORMALIZE-'||target.suffix AND operational_metadata?'deurExpectationSnapshot')<>1 THEN RAISE EXCEPTION 'race snapshot count invalid';END IF;IF (SELECT count(*) FROM erp.audit_log WHERE aggregate_id='RENT-UAT-C7-NORMALIZE-'||target.suffix AND action='LEGACY_DEUR_EXPECTATIONS_NORMALIZED')<>1 THEN RAISE EXCEPTION 'race audit count invalid';END IF;IF (SELECT count(*) FROM erp.operational_command_idempotency WHERE target_aggregate_id='RENT-UAT-C7-NORMALIZE-'||target.suffix AND command_type='NORMALIZE_LEGACY_DEUR_EXPECTATIONS' AND command_status='COMPLETED')<>1 THEN RAISE EXCEPTION 'race command count invalid';END IF;END LOOP;END $$;`);
 },60_000);
});
