import {describe,expect,it} from "vitest";
import {buildReport,php} from "@/features/reports/services/reportBuilderService";
import {resolveReportPeriod} from "@/features/reports/services/reportPeriod";
import {presentAuditEvent} from "@/features/administration/services/auditPresentation";
import type {User} from "@/features/auth/domain/user";

const users:User[]=[{id:"admin",username:"administrator",displayName:"Administrator",systemRoles:["system-administrator"],status:"active",createdAt:"2026-01-01",updatedAt:"2026-01-01"},{id:"alan",username:"alanmiscala",displayName:"Alan Miscala Test",systemRoles:["dispatcher"],status:"active",createdAt:"2026-01-01",updatedAt:"2026-01-01"}];
const period=resolveReportPeriod({preset:"THIS_MONTH",now:new Date(2026,7,14)}),empty={rentals:[],assignments:[],equipment:[],maintenance:[],statements:[],collections:[]};
describe("Phase 2E report and audit projections",()=>{
 it("builds filtered rental summaries without mutating source",()=>{const rentals:any[]=[{id:"r1",rentalNumber:"RENT-1",customer:"Acme",project:"P1",dateOut:"2026-08-02",expectedReturn:"2026-08-20",status:"Active",statusId:"active",equipmentId:"e1",rentedBy:"x",billingMethod:"Per Day"},{id:"r2",rentalNumber:"RENT-2",customer:"Other",project:"P2",dateOut:"2026-07-02",status:"Closed",statusId:"closed",equipmentId:"e2",rentedBy:"x"}],before=structuredClone(rentals);const report=buildReport({...empty,rentals},{type:"rentals",period,customer:"Acme",groupBy:"none"});expect(report.rows).toHaveLength(1);expect(report.metrics[0]).toMatchObject({label:"Total Rentals",value:1});expect(rentals).toEqual(before)});
 it("uses PHP presentation and safely omits variance percent for a zero comparison",()=>{expect(php.format(1000)).toContain("₱");const report=buildReport({...empty,collections:[{id:"c",statementId:"s",rentalId:"r",amount:1000,paymentDate:"2026-08-02",referenceNumber:"OR-1",recordedBy:"Admin",recordedAt:"2026-08-02"}]},{type:"collections",period:{...period,comparisonStartDate:"2025-08-01",comparisonEndDate:"2025-08-14"},groupBy:"none"});expect(report.metrics[0]).toMatchObject({numericValue:1000,previousValue:0,variancePercent:undefined});expect(report.rows[0].join(" ")).toContain("₱")});
 it("resolves friendly actor, user target, role target, and technical IDs",()=>{const base:any={id:"1",actorId:"admin",targetType:"USER",targetId:"alan",action:"USER_ACTIVATED",occurredAt:"2026-08-14T00:00:00Z"};const userEvent=presentAuditEvent(base,users,[{code:"billing-staff",name:"Billing Officer"}]);expect(userEvent.actor).toMatchObject({primary:"Administrator",secondary:"administrator",technicalId:"admin"});expect(userEvent.target).toMatchObject({primary:"Alan Miscala Test",secondary:"alanmiscala",technicalId:"alan"});expect(userEvent.details).toEqual(["Account status changed to Active."]);const roleEvent=presentAuditEvent({...base,targetType:"ROLE",targetId:"billing-staff",action:"ROLE_PERMISSION_ADDED",metadata:{permissionCode:"billing.invoice.issue"}},users,[{code:"billing-staff",name:"Billing Officer"}]);expect(roleEvent.target.primary).toBe("Billing Officer");expect(roleEvent.details.join(" ")).toContain("billing.invoice.issue")});
 it("uses historical snapshots then a safe deleted-user fallback and searchable identity",()=>{const snapshot:any={id:"2",actorId:"missing-actor",targetType:"USER",targetId:"deleted-user",action:"USER_DELETED",occurredAt:"2026-08-14",metadata:{targetDisplayName:"Former User",targetUsername:"former"},beforeRoleCodes:["dispatcher"]};const resolved=presentAuditEvent(snapshot,users,[{code:"dispatcher",name:"Dispatcher"}]);expect(resolved.target).toMatchObject({primary:"Former User",secondary:"former",technicalId:"deleted-user"});expect(resolved.searchText).toContain("former");const fallback=presentAuditEvent({...snapshot,metadata:{}},users,[]);expect(fallback.target.primary).toBe("Deleted / unavailable user")});
});
