import {randomBytes,randomUUID} from "node:crypto";
import {createClient} from "@supabase/supabase-js";
import {describe,expect,it} from "vitest";
import {assertSupabaseFixtureMutationAllowed,createSupabasePhaseC2Harness,readSupabasePhaseC2TestConfiguration} from "./support/supabasePhaseC2Harness";
import {executePhaseC4bPrivilegedSql} from "./support/phaseC4bPrivilegedSql";
import {SupabaseTrustedNotificationRepository} from "../server/notifications/SupabaseTrustedNotificationRepository";
import {ResendEmailDeliveryProvider} from "../server/notifications/ResendEmailDeliveryProvider";
import {parseNotificationServerConfiguration} from "../server/notifications/config";
import {renderNotificationTemplate} from "@/features/notifications/templates";
import {TrustedNotificationWorker} from "../server/notifications/TrustedNotificationWorker";
import {FakeEmailDeliveryProvider} from "../server/notifications/FakeEmailDeliveryProvider";
import {generateGroupedReviewCredential} from "../server/notifications/GroupedReviewCredential";
import {encryptGroupedReviewDeliveryEnvelope,parseGroupedReviewDeliveryKey} from "../server/notifications/GroupedReviewDeliveryEnvelope";
import {DailyGroupedCustomerReviewService} from "../server/notifications/DailyGroupedCustomerReviewService";
import {SupabaseDailyGroupedReviewRepository} from "../server/notifications/SupabaseDailyGroupedReviewRepository";

const configuration=readSupabasePhaseC2TestConfiguration();
const retryMode=process.env.RUN_PHASE_C12_GROUPED_RETRY_CERTIFICATION==="true";
const expiryMode=process.env.RUN_PHASE_C12_GROUPED_EXPIRY_CERTIFICATION==="true";const supersessionMode=process.env.RUN_PHASE_C12_GROUPED_SUPERSESSION_CERTIFICATION==="true";
const schedulerPrincipalMode=process.env.RUN_PHASE_C12_SCHEDULER_PRINCIPAL_CERTIFICATION==="true";
const dailySchedulerMode=process.env.RUN_PHASE_C12_DAILY_SCHEDULER_CERTIFICATION==="true";
const deliveryMode=process.env.RUN_PHASE_C12_GROUPED_DELIVERY_CERTIFICATION==="true"||process.env.RUN_PHASE_C12_GROUPED_DELIVERY_PRESEND==="true"||retryMode||expiryMode||supersessionMode||schedulerPrincipalMode||dailySchedulerMode;
const enabled=configuration.enabled&&(process.env.RUN_PHASE_C12_GROUPED_GENERATION_CERTIFICATION==="true"||process.env.RUN_PHASE_C12_GROUPED_PUBLIC_REVIEW_CERTIFICATION==="true"||deliveryMode);
const tenant="TENANT-UAT-C12-GROUPED-CUSTOMER-001";
const quote=(value:string)=>`'${value.replaceAll("'","''")}'`;
const businessDate=(offset:number)=>{const date=new Date(Date.now()+offset*86400000);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);};

describe.skipIf(!enabled)("C12 grouped Customer Review generation live certification",()=>{
 it("creates, replays, reuses next day, suppresses notification, and cleans exactly",async()=>{
  assertSupabaseFixtureMutationAllowed(configuration,[tenant]);
  expect(process.env.VITE_REMOTE_OPERATIONAL_WRITES_ENABLED).toBe("false");
  const harness=createSupabasePhaseC2Harness(configuration);
  const owner=(sql:string)=>executePhaseC4bPrivilegedSql(configuration,{tenantIds:[tenant],sql});
  const value=(sql:string)=>JSON.parse(owner(sql)).rows[0].jsonb_build_object as Record<string,any>;
  const cleanup=()=>Object.values(JSON.parse(owner(`SELECT erp.cleanup_c12_grouped_customer_review_fixture('${tenant}','${tenant}','CONFIRM-C12-GROUPED-CUSTOMER-CLEANUP');`)).rows[0])[0] as Record<string,unknown>;
  const allZero=(row:Record<string,unknown>)=>expect(Object.values(row).every(count=>count===0)).toBe(true);
  allZero(cleanup());allZero(cleanup());
  const password=`C12-${randomBytes(24).toString("base64url")}`;const email=`c12-grouped-${randomUUID()}@example.invalid`;let authId="";let fixture=false;
  try{
   const created=await harness.admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{fixtureTenant:tenant,fixtureKind:"grouped-generation-actor"}});
   if(created.error||!created.data.user)throw created.error??new Error("Auth fixture creation failed");authId=created.data.user.id;
   owner(`BEGIN;
    INSERT INTO erp.companies(id,code,name,active,environment_class) VALUES('${tenant}','${tenant}','Grouped Generation UAT',true,'test');
    INSERT INTO erp.users(id,username,email,display_name,status,company_id) VALUES('${authId}'::uuid,${quote(email)},${quote(email)},'Grouped Review Administrator','active','${tenant}');
    INSERT INTO erp.user_roles(user_id,role_id) VALUES('${authId}'::uuid,${quote(dailySchedulerMode?'ROLE-CANON-SYSTEM-ADMINISTRATOR':'ROLE-CANON-RENTAL-OPERATIONS')});
    INSERT INTO erp.customers(id,customer_code,name,company_id) VALUES('CUSTOMER-UAT-C12-GROUPED-001','GROUPED','Grouped Customer','${tenant}');
    INSERT INTO erp.projects(id,project_code,name,customer_id,company_id) VALUES('PROJECT-UAT-C12-GROUPED-001','GROUPED','Grouped Project','CUSTOMER-UAT-C12-GROUPED-001','${tenant}');
    INSERT INTO erp.operators(id,name,status,company_id) VALUES('OPERATOR-UAT-C12-GROUPED-A','Submitted Operator A','Active','${tenant}'),('OPERATOR-UAT-C12-GROUPED-B','Submitted Operator B','Active','${tenant}'),('OPERATOR-UAT-C12-GROUPED-C','In Progress Operator','Active','${tenant}');
    UPDATE erp.users SET operator_id='OPERATOR-UAT-C12-GROUPED-C' WHERE id='${authId}'::uuid AND company_id='${tenant}';
    INSERT INTO erp.equipment(id,asset_no,equipment_name,maintenance_type,operator_id,project_id,company_id) VALUES
      ('EQUIPMENT-UAT-C12-GROUPED-A','GROUP-A','Submitted Equipment','Hours','OPERATOR-UAT-C12-GROUPED-A','PROJECT-UAT-C12-GROUPED-001','${tenant}'),
      ('EQUIPMENT-UAT-C12-GROUPED-B','GROUP-B','Submitted Equipment B','Hours','OPERATOR-UAT-C12-GROUPED-B','PROJECT-UAT-C12-GROUPED-001','${tenant}'),
      ('EQUIPMENT-UAT-C12-GROUPED-C','GROUP-C','In Progress Equipment','Hours','OPERATOR-UAT-C12-GROUPED-C','PROJECT-UAT-C12-GROUPED-001','${tenant}');
    INSERT INTO erp.assignments(id,equipment_id,operator_id,project_id,assigned_date,expected_return,status,company_id) VALUES
      ('ASSIGN-UAT-C12-GROUPED-A','EQUIPMENT-UAT-C12-GROUPED-A','OPERATOR-UAT-C12-GROUPED-A','PROJECT-UAT-C12-GROUPED-001',current_date,current_date+10,'Active','${tenant}'),
      ('ASSIGN-UAT-C12-GROUPED-B','EQUIPMENT-UAT-C12-GROUPED-B','OPERATOR-UAT-C12-GROUPED-B','PROJECT-UAT-C12-GROUPED-001',current_date,current_date+10,'Active','${tenant}'),
      ('ASSIGN-UAT-C12-GROUPED-C','EQUIPMENT-UAT-C12-GROUPED-C','OPERATOR-UAT-C12-GROUPED-C','PROJECT-UAT-C12-GROUPED-001',current_date,current_date+10,'Active','${tenant}');
    INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,assignment_id,customer_snapshot,project_snapshot,rented_by,date_out,expected_return,status,timezone,customer_review_name_snapshot,customer_review_email_snapshot,company_id)
      VALUES('RENTAL-UAT-C12-GROUPED-001','GROUPED-001','CUSTOMER-UAT-C12-GROUPED-001','PROJECT-UAT-C12-GROUPED-001','ASSIGN-UAT-C12-GROUPED-A','Grouped Customer','Grouped Project','Certification',current_date,current_date+10,'Active','Asia/Manila','Grouped Customer','customer@example.invalid','${tenant}');
    INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,company_id) VALUES
      ('LINE-UAT-C12-GROUPED-A','RENTAL-UAT-C12-GROUPED-001','EQUIPMENT-UAT-C12-GROUPED-A','ASSIGN-UAT-C12-GROUPED-A','OPERATOR-UAT-C12-GROUPED-A','Active','${tenant}'),
      ('LINE-UAT-C12-GROUPED-B','RENTAL-UAT-C12-GROUPED-001','EQUIPMENT-UAT-C12-GROUPED-B','ASSIGN-UAT-C12-GROUPED-B','OPERATOR-UAT-C12-GROUPED-B','Active','${tenant}'),
      ('LINE-UAT-C12-GROUPED-C','RENTAL-UAT-C12-GROUPED-001','EQUIPMENT-UAT-C12-GROUPED-C','ASSIGN-UAT-C12-GROUPED-C','OPERATOR-UAT-C12-GROUPED-C','Active','${tenant}');
    INSERT INTO erp.deurs(id,deur_number,rental_id,rental_equipment_line_id,assignment_id,equipment_id,operator_id,project_id,customer_id,work_date,status,submitted_at,revision_chain_id,revision_number,company_id) VALUES
      ('DEUR-UAT-C12-GROUPED-A','DEUR-GROUP-A','RENTAL-UAT-C12-GROUPED-001','LINE-UAT-C12-GROUPED-A','ASSIGN-UAT-C12-GROUPED-A','EQUIPMENT-UAT-C12-GROUPED-A','OPERATOR-UAT-C12-GROUPED-A','PROJECT-UAT-C12-GROUPED-001','CUSTOMER-UAT-C12-GROUPED-001',current_date,'Submitted',clock_timestamp(),'DEUR-UAT-C12-GROUPED-A',1,'${tenant}'),
      ('DEUR-UAT-C12-GROUPED-B','DEUR-GROUP-B','RENTAL-UAT-C12-GROUPED-001','LINE-UAT-C12-GROUPED-B','ASSIGN-UAT-C12-GROUPED-B','EQUIPMENT-UAT-C12-GROUPED-B','OPERATOR-UAT-C12-GROUPED-B','PROJECT-UAT-C12-GROUPED-001','CUSTOMER-UAT-C12-GROUPED-001',current_date,'Submitted',clock_timestamp(),'DEUR-UAT-C12-GROUPED-B',1,'${tenant}'),
      ('DEUR-UAT-C12-GROUPED-C','DEUR-GROUP-C','RENTAL-UAT-C12-GROUPED-001','LINE-UAT-C12-GROUPED-C','ASSIGN-UAT-C12-GROUPED-C','EQUIPMENT-UAT-C12-GROUPED-C','OPERATOR-UAT-C12-GROUPED-C','PROJECT-UAT-C12-GROUPED-001','CUSTOMER-UAT-C12-GROUPED-001',current_date,'In Progress',NULL,'DEUR-UAT-C12-GROUPED-C',1,'${tenant}');COMMIT;`);fixture=true;
   const client=createClient(configuration.url!,configuration.publishableKey!,{auth:{persistSession:false,autoRefreshToken:false,storageKey:`grouped-${randomUUID()}`}});
   expect((await client.auth.signInWithPassword({email,password})).error).toBeNull();
   if(dailySchedulerMode){
    const configured=JSON.parse(owner(`SELECT erp.configure_c12_grouped_review_scheduler_principal('${tenant}',true,'CONFIRM-C12-GROUPED-SCHEDULER-PRINCIPAL');`)).rows[0];const principalId=Object.values(configured)[0] as string;
    const configure=async(automationEnabled:boolean,key:string)=>client.schema("erp").rpc("command_configure_grouped_review_scheduler",{command:{commandId:randomUUID(),idempotencyKey:key,automationEnabled,localSendTime:"17:30",graceMinutes:60}});
    const enabledConfiguration=await configure(true,"daily-config-enable");expect(enabledConfiguration.error).toBeNull();expect(enabledConfiguration.data).toMatchObject({success:true,value:{automationEnabled:true,schedulerReady:true,localSendTime:"17:30",graceMinutes:60}});
    const scheduler=new DailyGroupedCustomerReviewService(new SupabaseDailyGroupedReviewRepository(harness.admin),parseGroupedReviewDeliveryKey());
    const baseRunAt=new Date(`${businessDate(0)}T09:30:00.000Z`);const run=(commandId:string,offset:number,key:string,minuteOffset=0)=>scheduler.run({commandId,idempotencyKey:key,runAt:new Date(baseRunAt.getTime()+offset*86400000+minuteOffset*60000).toISOString(),batchLimit:1});
    const beforeWindow=await run(randomUUID(),0,"daily-before-window",-1);expect(beforeWindow).toMatchObject({groupsActionable:0,groupsPrepared:0,notificationsPrepared:0,groupsFailed:0});
    const day1Command=randomUUID(),overlapCommand=randomUUID();const overlapping=await Promise.all([run(day1Command,0,"daily-day-1"),run(overlapCommand,0,"daily-day-1-overlap")]);expect(overlapping.reduce((sum,x)=>sum+x.groupsClaimed,0)).toBe(1);expect(overlapping.reduce((sum,x)=>sum+x.groupsPrepared,0)).toBe(1);const winningIndex=overlapping.findIndex(x=>x.groupsClaimed===1);expect(winningIndex).toBeGreaterThanOrEqual(0);const day1=overlapping[winningIndex];expect(day1).toMatchObject({batchLimit:1,groupsClaimed:1,groupsActionable:1,groupsPrepared:1,notificationsPrepared:1,groupsFailed:0});const winningCommand=winningIndex===0?day1Command:overlapCommand,winningKey=winningIndex===0?"daily-day-1":"daily-day-1-overlap";
    const day1State=value(`SELECT jsonb_build_object('batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'items',(SELECT count(*) FROM erp.customer_review_batch_items WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'notifications',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED'),'envelopes',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}'),'schedulerGroups',(SELECT count(*) FROM erp.daily_grouped_review_scheduler_groups WHERE company_id='${tenant}'),'systemAudit',(SELECT count(*) FROM erp.audit_log WHERE company_id='${tenant}' AND actor_id=${quote(principalId)} AND new_values->>'actorType'='SYSTEM'));`);expect(day1State).toEqual({batches:1,items:3,requests:2,notifications:1,envelopes:1,schedulerGroups:1,systemAudit:1});
    const exactReplay=await run(winningCommand,0,winningKey);expect(exactReplay).toMatchObject({groupsActionable:1,groupsPrepared:0,groupsReplayed:1,notificationsPrepared:0});
    const sameDay=await run(randomUUID(),0,"daily-day-1-distinct");expect(sameDay).toMatchObject({groupsActionable:0,groupsPrepared:0,notificationsPrepared:0});
    const notificationRepository=new SupabaseTrustedNotificationRepository(client,harness.admin,undefined,harness.anonymous);
    const day1Intent=value(`SELECT jsonb_build_object('id',(SELECT id FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED' ORDER BY created_at LIMIT 1));`).id as string;
    const day1Path=await notificationRepository.getGroupedReviewPath(day1Intent);const day1Credential=day1Path!.split('/').at(-1)!;
    const notification=parseNotificationServerConfiguration();const firstProvider=new FakeEmailDeliveryProvider("rate-limited");const firstWorker=new TrustedNotificationWorker(notificationRepository,firstProvider,notification.fromAddress,10,notification.publicBaseUrl);expect(await firstWorker.runOnce()).toEqual({claimed:1,providerCalls:1});
    const afterFailure=await run(randomUUID(),0,"daily-after-provider-failure");expect(afterFailure).toMatchObject({groupsActionable:0,groupsPrepared:0,notificationsPrepared:0});
    await new Promise(resolve=>setTimeout(resolve,1100));const secondProvider=new FakeEmailDeliveryProvider("success");const restartedRepository=new SupabaseTrustedNotificationRepository(client,harness.admin,undefined,harness.anonymous);const secondWorker=new TrustedNotificationWorker(restartedRepository,secondProvider,notification.fromAddress,10,notification.publicBaseUrl);expect(await secondWorker.runOnce()).toEqual({claimed:1,providerCalls:1});expect(firstProvider.evidence().redactedCalls[0].idempotencyKey).toBe(secondProvider.evidence().redactedCalls[0].idempotencyKey);expect(await secondWorker.runOnce()).toEqual({claimed:0,providerCalls:0});
    const initial=await harness.anonymous.schema("erp").rpc("get_customer_review_batch",{command:{credential:day1Credential}});expect(initial.data).toMatchObject({success:true,value:{actionableCount:2,inProgressCount:1}});
    const itemA=initial.data.value.items.find((x:any)=>x.assetNumber==="GROUP-A");
    const ack=await harness.anonymous.schema("erp").rpc("acknowledge_customer_review_batch_item",{command:{credential:day1Credential,publicItemId:itemA.publicItemId,commandId:"daily-ack-a",idempotencyKey:"daily-ack-a"}});expect(ack.data).toMatchObject({success:true});
    owner(`DELETE FROM erp.user_roles WHERE user_id='${authId}'::uuid; INSERT INTO erp.user_roles(user_id,role_id) VALUES('${authId}'::uuid,'ROLE-CANON-RENTAL-OPERATIONS');`);
    const cBase={rentalId:"RENTAL-UAT-C12-GROUPED-001",rentalLineId:"LINE-UAT-C12-GROUPED-C",equipmentId:"EQUIPMENT-UAT-C12-GROUPED-C",assignmentId:"ASSIGN-UAT-C12-GROUPED-C",operatorId:"OPERATOR-UAT-C12-GROUPED-C",deurId:"DEUR-UAT-C12-GROUPED-C",deviceId:"C12-DAILY-SCHEDULER"};
    const completed=await client.schema("erp").rpc("command_complete_deur_shift",{command:{...cBase,commandId:randomUUID(),idempotencyKey:"daily-complete-c",expectedVersion:1,meterRequirement:"none"}});expect(completed.data).toMatchObject({success:true,disposition:"ACCEPTED"});
    const submitted=await client.schema("erp").rpc("command_submit_deur",{command:{...cBase,commandId:randomUUID(),idempotencyKey:"daily-submit-c",expectedVersion:completed.data.version}});expect(submitted.data).toMatchObject({success:true,disposition:"ACCEPTED",record:{status:"Submitted"}});
    const lateSameDay=await run(randomUUID(),0,"daily-late-same-day");expect(lateSameDay).toMatchObject({groupsActionable:0,groupsPrepared:0,notificationsPrepared:0});
    owner(`DELETE FROM erp.user_roles WHERE user_id='${authId}'::uuid; INSERT INTO erp.user_roles(user_id,role_id) VALUES('${authId}'::uuid,'ROLE-CANON-SYSTEM-ADMINISTRATOR');`);
    const disabledConfiguration=await configure(false,"daily-config-disable");expect(disabledConfiguration.data).toMatchObject({success:true,value:{automationEnabled:false,schedulerReady:true}});const disabledRun=await run(randomUUID(),1,"daily-disabled");expect(disabledRun).toMatchObject({groupsActionable:0,groupsPrepared:0,notificationsPrepared:0,groupsFailed:0});
    const reenabledConfiguration=await configure(true,"daily-config-reenable");expect(reenabledConfiguration.data).toMatchObject({success:true,value:{automationEnabled:true,schedulerReady:true}});
    const day2=await run(randomUUID(),1,"daily-day-2");expect(day2).toMatchObject({groupsActionable:1,groupsPrepared:1,notificationsPrepared:1,groupsFailed:0});
    const reuse=value(`SELECT jsonb_build_object('batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'notifications',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'bRequestIds',(SELECT count(DISTINCT customer_review_request_id) FROM erp.customer_review_batch_items WHERE company_id='${tenant}' AND rental_equipment_line_id='LINE-UAT-C12-GROUPED-B'),'cRequests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}' AND rental_equipment_line_id='LINE-UAT-C12-GROUPED-C'),'day1Superseded',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}' AND review_date=${quote(businessDate(0))}::date AND superseded_at IS NOT NULL));`);expect(reuse).toEqual({batches:2,notifications:2,requests:3,bRequestIds:1,cRequests:1,day1Superseded:0});
    const day2Intent=value(`SELECT jsonb_build_object('id',(SELECT id FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED' ORDER BY created_at DESC LIMIT 1));`).id as string;
    const day2Path=await notificationRepository.getGroupedReviewPath(day2Intent);const day2Credential=day2Path!.split('/').at(-1)!;const projected=await harness.anonymous.schema("erp").rpc("get_customer_review_batch",{command:{credential:day2Credential}});
    const itemB=projected.data.value.items.find((x:any)=>x.assetNumber==="GROUP-B"),itemC=projected.data.value.items.find((x:any)=>x.assetNumber==="GROUP-C");
    expect((await harness.anonymous.schema("erp").rpc("request_customer_review_batch_item_correction",{command:{credential:day2Credential,publicItemId:itemB.publicItemId,commandId:"daily-correct-b",idempotencyKey:"daily-correct-b",remarks:"Correction required for the daily scheduler certification."}})).data).toMatchObject({success:true});
    expect((await harness.anonymous.schema("erp").rpc("acknowledge_customer_review_batch_item",{command:{credential:day2Credential,publicItemId:itemC.publicItemId,commandId:"daily-ack-c",idempotencyKey:"daily-ack-c"}})).data).toMatchObject({success:true});
    const day3Command=randomUUID();const day3=await run(day3Command,2,"daily-day-3");expect(day3).toMatchObject({groupsActionable:0,groupsPrepared:0,notificationsPrepared:0});const day3Replay=await run(day3Command,2,"daily-day-3");expect(day3Replay).toMatchObject({groupsActionable:0,groupsPrepared:0,notificationsPrepared:0});
    const terminal=value(`SELECT jsonb_build_object('batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'notifications',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED'),'allNotifications',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}'),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'retiredEnvelopes',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}' AND e.retired_at IS NOT NULL AND e.ciphertext IS NULL),'activeEnvelopes',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}' AND e.retired_at IS NULL),'humanPrincipal',(SELECT count(*) FROM erp.users WHERE id=${quote(principalId)}::uuid),'schedulerSecrets',(SELECT count(*) FROM erp.daily_grouped_review_scheduler_groups WHERE company_id='${tenant}' AND coalesce(result_summary::text,'')~*'credential|reviewPath|ciphertext|nonce|authTag|encryption'));`);expect(terminal).toEqual({batches:2,notifications:2,allNotifications:5,attempts:2,retiredEnvelopes:1,activeEnvelopes:1,humanPrincipal:0,schedulerSecrets:0});
    cleanup();fixture=false;const deleted=await harness.admin.auth.admin.deleteUser(authId);if(deleted.error)throw deleted.error;authId="";allZero(cleanup());return;
   }
   if(deliveryMode){
    if(schedulerPrincipalMode){
     const missing=await harness.admin.schema("erp").rpc("resolve_grouped_review_scheduler_principal",{target_company_id:tenant});expect(missing.data).toEqual({success:false,code:"SCHEDULER_PRINCIPAL_NOT_CONFIGURED"});
     const configured=JSON.parse(owner(`SELECT erp.configure_c12_grouped_review_scheduler_principal('${tenant}',true,'CONFIRM-C12-GROUPED-SCHEDULER-PRINCIPAL');`)).rows[0];const principalId=Object.values(configured)[0] as string;
     const resolved=await harness.admin.schema("erp").rpc("resolve_grouped_review_scheduler_principal",{target_company_id:tenant});expect(resolved.data).toMatchObject({success:true,value:{principalId,companyId:tenant,actorType:"SYSTEM",principalType:"GROUPED_REVIEW_SCHEDULER"}});
     const credential=generateGroupedReviewCredential();const notificationId=randomUUID();const envelope=encryptGroupedReviewDeliveryEnvelope(credential.reviewPath,notificationId,parseGroupedReviewDeliveryKey());
     const prepared=await harness.admin.schema("erp").rpc("trusted_prepare_grouped_customer_review_delivery_as_scheduler",{command:{commandId:"scheduler-principal",idempotencyKey:"scheduler-principal",rentalId:"RENTAL-UAT-C12-GROUPED-001",businessDate:businessDate(0),principalId,notificationId,credentialHash:credential.hash,...envelope}});expect(prepared.error).toBeNull();expect(prepared.data).toMatchObject({success:true,disposition:"CREATED"});
     const evidence=value(`SELECT jsonb_build_object('principals',(SELECT count(*) FROM erp.system_principals WHERE company_id='${tenant}' AND principal_type='GROUPED_REVIEW_SCHEDULER' AND active),'permissions',(SELECT count(*) FROM erp.system_principal_permissions p JOIN erp.system_principals s ON s.id=p.principal_id WHERE s.company_id='${tenant}' AND p.permission_code='grouped_review.schedule'),'authProfile',(SELECT count(*) FROM erp.users WHERE id=${quote(principalId)}::uuid),'batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'intents',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}'),'envelopes',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}'),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'systemAudit',(SELECT count(*) FROM erp.audit_log WHERE company_id='${tenant}' AND actor_id=${quote(principalId)} AND new_values->>'actorType'='SYSTEM' AND new_values->>'principalType'='GROUPED_REVIEW_SCHEDULER'));`);expect(evidence).toEqual({principals:1,permissions:1,authProfile:0,batches:1,intents:1,envelopes:1,attempts:0,systemAudit:1});
     cleanup();fixture=false;const deleted=await harness.admin.auth.admin.deleteUser(authId);if(deleted.error)throw deleted.error;authId="";allZero(cleanup());return;
    }
    const notification=parseNotificationServerConfiguration();const recipient=notification.uatRecipientOverride;const readbackKey=process.env.RESEND_READBACK_API_KEY?.trim();
    expect(recipient).toMatch(/^[^@\s]+@[^@\s]+\.[^@\s]+$/);expect(readbackKey).toBeTruthy();
    const repository=new SupabaseTrustedNotificationRepository(client,harness.admin,undefined,harness.anonymous);const command={commandId:"grouped-delivery",idempotencyKey:"grouped-delivery",rentalId:"RENTAL-UAT-C12-GROUPED-001",businessDate:businessDate(0)};
    const issue=await repository.issue("grouped-customer",command);expect(issue).toMatchObject({success:true,disposition:"CREATED"});expect(issue.reviewPath).toMatch(/^\/review\/customer\/grouped\/[0-9a-f]{64}$/);expect(issue.notificationIntentId).toMatch(/^[0-9a-f-]{36}$/i);
    const restartedRepository=new SupabaseTrustedNotificationRepository(client,harness.admin,undefined,harness.anonymous);expect(await restartedRepository.getGroupedReviewPath(issue.notificationIntentId!)).toBe(issue.reviewPath);
    const replay=await repository.issue("grouped-customer",command);expect(replay).toMatchObject({success:true,disposition:"REPLAYED"});expect(replay.reviewPath).toBeUndefined();
    const preSend=value(`SELECT jsonb_build_object('batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'items',(SELECT count(*) FROM erp.customer_review_batch_items WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'groupedIntents',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED'),'individualIntents',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type IN('CUSTOMER_REVIEW_REQUESTED','CUSTOMER_CORRECTED_REVIEW_REQUESTED')),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'current',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}' AND superseded_at IS NULL AND expires_at>clock_timestamp()),'actionable',(SELECT summary_snapshot->>'actionableCount' FROM erp.customer_review_batches WHERE company_id='${tenant}'),'inProgress',(SELECT summary_snapshot->>'inProgressCount' FROM erp.customer_review_batches WHERE company_id='${tenant}'),'recipientValid',(SELECT recipient_destination=lower(${quote('customer@example.invalid')}) FROM erp.notification_outbox WHERE company_id='${tenant}'),'hashOnly',(SELECT credential_hash ~ '^[0-9a-f]{64}$' FROM erp.customer_review_batches WHERE company_id='${tenant}'));`);
    expect(preSend).toEqual({batches:1,items:3,requests:2,groupedIntents:1,individualIntents:0,attempts:0,current:1,actionable:"2",inProgress:"1",recipientValid:true,hashOnly:true});
    const credential=issue.reviewPath!.slice("/review/customer/grouped/".length);const beforeGet=value(`SELECT jsonb_build_object('requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'outcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}'),'corrections',(SELECT count(*) FROM erp.customer_correction_requests WHERE company_id='${tenant}'));`);const lookup=await harness.anonymous.schema("erp").rpc("get_customer_review_batch",{command:{credential}});expect(lookup.error).toBeNull();expect(lookup.data).toMatchObject({success:true,disposition:"AVAILABLE",value:{actionableCount:2,inProgressCount:1,batchStatus:"OPEN"}});const afterGet=value(`SELECT jsonb_build_object('requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'outcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}'),'corrections',(SELECT count(*) FROM erp.customer_correction_requests WHERE company_id='${tenant}'));`);expect(afterGet).toEqual(beforeGet);
    if(expiryMode){
     const batchId=(issue as any).value.batchId;owner(`SELECT erp.certify_c12_grouped_customer_review_batch_expired('${batchId}'::uuid,'${tenant}','CONFIRM-C12-GROUPED-EXPIRY-CERTIFICATION');`);const expired=await harness.anonymous.schema("erp").rpc("get_customer_review_batch",{command:{credential}});expect(expired.data).toEqual({success:false,code:"EXPIRED"});
     const provider=new FakeEmailDeliveryProvider("success");const worker=new TrustedNotificationWorker(new SupabaseTrustedNotificationRepository(client,harness.admin,undefined,harness.anonymous),provider,notification.fromAddress,10,notification.publicBaseUrl);expect(await worker.runOnce()).toEqual({claimed:1,providerCalls:0});expect(provider.evidence().callCount).toBe(0);
     const state=value(`SELECT jsonb_build_object('attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'cancelled',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND status='Cancelled'),'retired',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}' AND e.retired_at IS NOT NULL AND e.ciphertext IS NULL),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'outcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}'),'corrections',(SELECT count(*) FROM erp.customer_correction_requests WHERE company_id='${tenant}'),'batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'));`);expect(state).toEqual({attempts:1,cancelled:1,retired:1,requests:2,outcomes:0,corrections:0,batches:1});cleanup();fixture=false;const deleted=await harness.admin.auth.admin.deleteUser(authId);if(deleted.error)throw deleted.error;authId="";allZero(cleanup());return;
    }
    if(supersessionMode){
     const sourceBatchId=(issue as any).value.batchId;const replaced=await client.schema("erp").rpc("command_supersede_customer_review_batch",{command:{sourceBatchId,commandId:"replace-batch",idempotencyKey:"replace-batch"}});expect(replaced.error).toBeNull();expect(replaced.data).toMatchObject({success:true,disposition:"SUPERSEDED"});const successorCredential=replaced.data.value.credential;expect(successorCredential).toMatch(/^[0-9a-f]{64}$/);
     const oldLookup=await harness.anonymous.schema("erp").rpc("get_customer_review_batch",{command:{credential}});expect(oldLookup.data).toEqual({success:false,code:"SUPERSEDED"});const newLookup=await harness.anonymous.schema("erp").rpc("get_customer_review_batch",{command:{credential:successorCredential}});expect(newLookup.data).toMatchObject({success:true,disposition:"AVAILABLE"});
     const provider=new FakeEmailDeliveryProvider("success");const worker=new TrustedNotificationWorker(new SupabaseTrustedNotificationRepository(client,harness.admin,undefined,harness.anonymous),provider,notification.fromAddress,10,notification.publicBaseUrl);expect(await worker.runOnce()).toEqual({claimed:1,providerCalls:0});
     const state=value(`SELECT jsonb_build_object('batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'items',(SELECT count(*) FROM erp.customer_review_batch_items WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'requestReuse',(SELECT count(DISTINCT customer_review_request_id)=2 FROM erp.customer_review_batch_items WHERE company_id='${tenant}' AND customer_review_request_id IS NOT NULL),'linked',(SELECT superseded_by_batch_id=${quote(replaced.data.value.successorBatchId)}::uuid FROM erp.customer_review_batches WHERE id=${quote(sourceBatchId)}::uuid),'supersededIntent',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND status='Superseded'),'retired',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}' AND e.retired_at IS NOT NULL AND e.ciphertext IS NULL),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'outcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}'),'corrections',(SELECT count(*) FROM erp.customer_correction_requests WHERE company_id='${tenant}'));`);expect(state).toEqual({batches:2,items:6,requests:2,requestReuse:true,linked:true,supersededIntent:1,retired:1,attempts:1,outcomes:0,corrections:0});cleanup();fixture=false;const deleted=await harness.admin.auth.admin.deleteUser(authId);if(deleted.error)throw deleted.error;authId="";allZero(cleanup());return;
    }
    if(retryMode){
     const firstProvider=new FakeEmailDeliveryProvider("rate-limited");const firstWorker=new TrustedNotificationWorker(repository,firstProvider,notification.fromAddress,10,notification.publicBaseUrl);expect(await firstWorker.runOnce()).toEqual({claimed:1,providerCalls:1});
     const afterFirst=value(`SELECT jsonb_build_object('attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'accepted',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}' AND status='ProviderAccepted'),'activeEnvelope',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}' AND e.retired_at IS NULL AND e.ciphertext IS NOT NULL AND e.nonce IS NOT NULL AND e.auth_tag IS NOT NULL),'batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'intents',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'));`);expect(afterFirst).toEqual({attempts:1,accepted:0,activeEnvelope:1,batches:1,intents:1,requests:2});
     await new Promise(resolve=>setTimeout(resolve,1100));const retryRepository=new SupabaseTrustedNotificationRepository(client,harness.admin,undefined,harness.anonymous);const secondProvider=new FakeEmailDeliveryProvider("success");const secondWorker=new TrustedNotificationWorker(retryRepository,secondProvider,notification.fromAddress,10,notification.publicBaseUrl);expect(await secondWorker.runOnce()).toEqual({claimed:1,providerCalls:1});
     expect(firstProvider.evidence().redactedCalls[0].idempotencyKey).toBe(secondProvider.evidence().redactedCalls[0].idempotencyKey);const terminal=value(`SELECT jsonb_build_object('attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'accepted',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}' AND status='ProviderAccepted'),'retired',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}' AND e.retired_at IS NOT NULL AND e.ciphertext IS NULL AND e.nonce IS NULL AND e.auth_tag IS NULL),'batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'intents',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'));`);expect(terminal).toEqual({attempts:2,accepted:1,retired:1,batches:1,intents:1,requests:2});expect(await retryRepository.getGroupedReviewPath(issue.notificationIntentId!)).toBeUndefined();expect(await secondWorker.runOnce()).toEqual({claimed:0,providerCalls:0});
     const removed=cleanup();expect(removed).toMatchObject({notification_delivery_attempts:2,notification_outbox:1,customer_review_batches:1});fixture=false;const deleted=await harness.admin.auth.admin.deleteUser(authId);if(deleted.error)throw deleted.error;authId="";allZero(cleanup());return;
    }
    if(process.env.RUN_PHASE_C12_GROUPED_DELIVERY_PRESEND==="true")return;
    const intent=await repository.getIntent(issue.notificationIntentId!);expect(intent).toMatchObject({type:"CUSTOMER_GROUPED_REVIEW_REQUESTED",sourceAggregateType:"CUSTOMER_REVIEW_BATCH",requiresReviewCredential:true,input:{totalLineCount:3,actionableCount:2,inProgressCount:1}});expect(JSON.stringify(intent.input)).not.toMatch(/credential|tokenHash|credentialHash|tenantId|companyId|batchId/i);
    const workerId=randomUUID();expect(await repository.claim(intent.id,workerId)).toBe(true);const provider=new ResendEmailDeliveryProvider({apiKey:notification.resendApiKey,uatRecipientOverride:recipient,timeoutMs:15_000});const reviewUrl=new URL(issue.reviewPath!,notification.publicBaseUrl).toString();const delivered=await provider.send({from:notification.fromAddress,to:intent.recipient.destination,recipientName:intent.recipient.displayName,email:renderNotificationTemplate(intent.type,{...intent.input,reviewUrl}),idempotencyKey:intent.idempotencyKey});expect(delivered.accepted).toBe(true);if(!delivered.accepted)throw new Error("Grouped provider delivery was not accepted.");await repository.complete({id:intent.id,workerId,status:"ProviderAccepted",providerName:delivered.provider,providerMessageId:delivered.providerMessageId});expect(await repository.claim(intent.id,randomUUID())).toBe(false);
    const response=await fetch(`https://api.resend.com/emails/${encodeURIComponent(delivered.providerMessageId)}`,{headers:{Authorization:`Bearer ${readbackKey}`}});expect(response.status).toBe(200);const message=await response.json() as {id?:string;to?:string[];from?:string;subject?:string;html?:string;text?:string};expect(message.id).toBe(delivered.providerMessageId);expect(message.to).toContain(recipient);expect(message.from).toContain(notification.fromAddress);expect(message.subject).toMatch(/grouped|DEUR|review/i);const content=`${message.html??""}\n${message.text??""}`;expect(content).toContain(reviewUrl);expect(content).toContain("REVIEW");expect(content).not.toMatch(/Acknowledge All|one click acknowledges/i);
    const deliveredState=value(`SELECT jsonb_build_object('groupedIntents',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED'),'individualIntents',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type IN('CUSTOMER_REVIEW_REQUESTED','CUSTOMER_CORRECTED_REVIEW_REQUESTED')),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'accepted',(SELECT count(*) FROM erp.notification_delivery_attempts a JOIN erp.notification_outbox n ON n.id=a.notification_id WHERE n.company_id='${tenant}' AND a.status='ProviderAccepted'),'providerId',(SELECT provider_message_id IS NOT NULL FROM erp.notification_outbox WHERE company_id='${tenant}'),'outcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}'),'corrections',(SELECT count(*) FROM erp.customer_correction_requests WHERE company_id='${tenant}'));`);expect(deliveredState).toEqual({groupedIntents:1,individualIntents:0,attempts:1,accepted:1,providerId:true,outcomes:0,corrections:0});return;
   }
   const call=(commandId:string,idempotencyKey:string,date:string)=>client.schema("erp").rpc("command_generate_customer_review_batch",{command:{commandId,idempotencyKey,rentalId:"RENTAL-UAT-C12-GROUPED-001",businessDate:date}});
   const day1=await call("day-1","day-1",businessDate(0));expect(day1.error).toBeNull();expect(day1.data).toMatchObject({success:true,disposition:"CREATED",value:{totalLineCount:3,actionableCount:2,inProgressCount:1}});expect(day1.data.value.credential).toMatch(/^[0-9a-f]{64}$/);
   const afterDay1=value(`SELECT jsonb_build_object('batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'items',(SELECT count(*) FROM erp.customer_review_batch_items WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'submittedStates',(SELECT count(*) FROM erp.customer_review_batch_items WHERE company_id='${tenant}' AND item_snapshot->>'reviewState'='SUBMITTED_AWAITING_ACKNOWLEDGEMENT'),'inProgressState',(SELECT item_snapshot->>'reviewState' FROM erp.customer_review_batch_items WHERE rental_equipment_line_id='LINE-UAT-C12-GROUPED-C'),'inProgressRequest',(SELECT count(*) FROM erp.customer_review_batch_items WHERE rental_equipment_line_id='LINE-UAT-C12-GROUPED-C' AND customer_review_request_id IS NOT NULL),'notifications',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}'),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'hashMatches',(SELECT credential_hash=encode(digest(${quote(day1.data.value.credential)},'sha256'),'hex') FROM erp.customer_review_batches WHERE company_id='${tenant}'));`);
   expect(afterDay1).toEqual({batches:1,items:3,requests:2,submittedStates:2,inProgressState:"IN_PROGRESS",inProgressRequest:0,notifications:0,attempts:0,hashMatches:true});
   const replay=await call("day-1","day-1",businessDate(0));expect(replay.data).toMatchObject({success:true,disposition:"REPLAYED"});expect(replay.data.value.credential).toBeUndefined();
   const day2=await call("day-2","day-2",businessDate(1));expect(day2.data).toMatchObject({success:true,disposition:"CREATED",value:{totalLineCount:3,actionableCount:2}});expect(day2.data.value.credential).toMatch(/^[0-9a-f]{64}$/);
   const final=value(`SELECT jsonb_build_object('batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'items',(SELECT count(*) FROM erp.customer_review_batch_items WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'requestReuse',(SELECT count(DISTINCT customer_review_request_id)=2 FROM erp.customer_review_batch_items WHERE company_id='${tenant}' AND rental_equipment_line_id IN('LINE-UAT-C12-GROUPED-A','LINE-UAT-C12-GROUPED-B')),'notifications',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}'),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'));`);
   expect(final).toEqual({batches:2,items:6,requests:2,requestReuse:true,notifications:0,attempts:0});await client.auth.signOut();
   if(process.env.RUN_PHASE_C12_GROUPED_PUBLIC_REVIEW_CERTIFICATION==="true"){
    const publicCall=(name:string,command:Record<string,unknown>)=>client.schema("erp").rpc(name,{command});
    const beforeGet=value(`SELECT jsonb_build_object('outcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}'),'corrections',(SELECT count(*) FROM erp.customer_correction_requests WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'));`);
    const initial=await publicCall("get_customer_review_batch",{credential:day1.data.value.credential});expect(initial.error).toBeNull();expect(initial.data).toMatchObject({success:true,disposition:"AVAILABLE",value:{totalLineCount:3,actionableCount:2,inProgressCount:1,acknowledgedCount:0,correctionRequestedCount:0,batchStatus:"OPEN"}});
    const afterGet=value(`SELECT jsonb_build_object('outcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}'),'corrections',(SELECT count(*) FROM erp.customer_correction_requests WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'));`);expect(afterGet).toEqual(beforeGet);
    const itemA=initial.data.value.items.find((item:any)=>item.assetNumber==="GROUP-A");const itemB=initial.data.value.items.find((item:any)=>item.assetNumber==="GROUP-B");const itemC=initial.data.value.items.find((item:any)=>item.assetNumber==="GROUP-C");expect(itemA.availableActions).toEqual(["ACKNOWLEDGE","REQUEST_CORRECTION"]);expect(itemB.availableActions).toEqual(["ACKNOWLEDGE","REQUEST_CORRECTION"]);expect(itemC).toMatchObject({reviewState:"IN_PROGRESS",availableActions:[]});
    const ack={credential:day1.data.value.credential,publicItemId:itemA.publicItemId,commandId:"ack-a",idempotencyKey:"ack-a"};const acked=await publicCall("acknowledge_customer_review_batch_item",ack);expect(acked.data).toMatchObject({success:true,disposition:"ACCEPTED",value:{actionableCount:1,acknowledgedCount:1,batchStatus:"PARTIALLY_REVIEWED"}});const ackReplay=await publicCall("acknowledge_customer_review_batch_item",ack);expect(ackReplay.data).toMatchObject({success:true,disposition:"REPLAYED"});
    const afterAck=await publicCall("get_customer_review_batch",{credential:day1.data.value.credential});expect(afterAck.data.value.items.find((item:any)=>item.assetNumber==="GROUP-A").reviewState).toBe("ACKNOWLEDGED");expect(afterAck.data.value.items.find((item:any)=>item.assetNumber==="GROUP-B").reviewState).toBe("SUBMITTED_AWAITING_ACKNOWLEDGEMENT");expect(afterAck.data.value.items.find((item:any)=>item.assetNumber==="GROUP-C").reviewState).toBe("IN_PROGRESS");
    const day2AfterAck=await publicCall("get_customer_review_batch",{credential:day2.data.value.credential});expect(day2AfterAck.data.value.items.find((item:any)=>item.assetNumber==="GROUP-A").reviewState).toBe("ACKNOWLEDGED");
    const correction={credential:day1.data.value.credential,publicItemId:itemB.publicItemId,commandId:"correct-b",idempotencyKey:"correct-b",remarks:"The operating duration requires customer correction."};const corrected=await publicCall("request_customer_review_batch_item_correction",correction);expect(corrected.data).toMatchObject({success:true,disposition:"ACCEPTED",value:{actionableCount:0,acknowledgedCount:1,correctionRequestedCount:1,inProgressCount:1,batchStatus:"COMPLETED"}});const correctionReplay=await publicCall("request_customer_review_batch_item_correction",correction);expect(correctionReplay.data).toMatchObject({success:true,disposition:"REPLAYED"});
    for(const name of ["acknowledge_customer_review_batch_item","request_customer_review_batch_item_correction"]){const command:any={credential:day1.data.value.credential,publicItemId:itemC.publicItemId,commandId:`reject-${name}`,idempotencyKey:`reject-${name}`};if(name.includes("correction"))command.remarks="This in-progress line must remain read only.";const rejected=await publicCall(name,command);expect(rejected.data).toEqual({success:false,code:"NOT_ACTIONABLE"});}
    const completed=await publicCall("get_customer_review_batch",{credential:day1.data.value.credential});expect(completed.data).toMatchObject({success:true,disposition:"COMPLETED",value:{batchStatus:"COMPLETED"}});const day2Completed=await publicCall("get_customer_review_batch",{credential:day2.data.value.credential});expect(day2Completed.data.value.items.find((item:any)=>item.assetNumber==="GROUP-B").reviewState).toBe("CORRECTION_REQUESTED");
    const evidence=value(`SELECT jsonb_build_object('outcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}'),'acknowledgements',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}' AND action='ACKNOWLEDGE'),'correctionOutcomes',(SELECT count(*) FROM erp.customer_review_outcomes WHERE company_id='${tenant}' AND action='REQUEST_CORRECTION'),'corrections',(SELECT count(*) FROM erp.customer_correction_requests WHERE company_id='${tenant}'),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'));`);expect(evidence).toEqual({outcomes:2,acknowledgements:1,correctionOutcomes:1,corrections:1,attempts:0});
   }
   const passOne=cleanup();expect(passOne).toMatchObject({customer_review_batch_items:6,customer_review_batches:2,customer_review_requests:2,deurs:3,rental_lines:3,rentals:1,companies:1});fixture=false;
   const deleted=await harness.admin.auth.admin.deleteUser(authId);if(deleted.error)throw deleted.error;authId="";allZero(cleanup());
   const residue=value(`SELECT jsonb_build_object('batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'items',(SELECT count(*) FROM erp.customer_review_batch_items WHERE company_id='${tenant}'),'company',(SELECT count(*) FROM erp.companies WHERE id='${tenant}'),'notifications',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}'),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'));`);expect(residue).toEqual({batches:0,items:0,company:0,notifications:0,attempts:0});allZero(cleanup());
  }finally{if(fixture)try{cleanup();}catch{}if(authId)try{await harness.admin.auth.admin.deleteUser(authId);}catch{}try{cleanup();}catch{}}
 },180_000);
});
