import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const path="supabase/migrations/20260803007400_phase_c12_daily_grouped_review_scheduler_configuration.sql";const sql=readFileSync(path,"utf8");
describe("C12.2.7A scheduler configuration foundation",()=>{
 it("stores one tenant configuration and derives readiness",()=>{for(const marker of["grouped_review_scheduler_configurations","company_id text PRIMARY KEY","automation_enabled boolean NOT NULL DEFAULT false","local_send_time time without time zone","grace_minutes BETWEEN 15 AND 180","SCHEDULER_NOT_READY","system_principals","grouped_review.schedule"])expect(sql).toContain(marker);expect(sql).not.toMatch(/scheduler_ready\s+boolean/i);});
 it("uses an audited tenant-derived administration command",()=>{for(const marker of["command_configure_grouped_review_scheduler","current_company_id()","current_user_has_permission('users.manage')","begin_operational_command","finish_operational_command","audit_log","configured_by uuid NOT NULL REFERENCES auth.users(id)"])expect(sql).toContain(marker);expect(sql).not.toMatch(/command->>'companyId'|target_company_id/);});
 it("enforces a bounded same-day local window",()=>{for(const marker of["extract(epoch FROM local_send_time)+grace_minutes*60<86400","INVALID_SEND_WINDOW","AT TIME ZONE r.timezone","::time>=c.local_send_time","::time<c.local_send_time+make_interval"])expect(sql).toContain(marker);});
 it("preserves actionability, anti-flooding, and scheduler authority",()=>{for(const marker of["r.status IN('Released','Active')","d.status='Submitted'","q.status='Pending'","customer_review_batches","system_principal_permissions","service_role"])expect(sql).toContain(marker);expect(sql).not.toMatch(/CUSTOMER_REVIEW_REMINDER|pg_cron|cron\.schedule|cloudflare|resend/i);});
 it("secures storage and extends exact cleanup",()=>{for(const marker of["ENABLE ROW LEVEL SECURITY","FROM PUBLIC,anon,authenticated,service_role","GRANT EXECUTE ON FUNCTION erp.command_configure_grouped_review_scheduler(jsonb) TO authenticated","grouped_review_scheduler_configurations WHERE company_id=target_tenant_id)>1","DELETE FROM grouped_review_scheduler_configurations WHERE company_id=target_tenant_id","TENANT-LOCAL-001"])expect(readFileSync("supabase/migrations/20260803006000_phase_c12_grouped_customer_review_three_line_cleanup.sql","utf8")+sql).toContain(marker);});
});
