import { randomBytes, randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { beforeAll, describe, expect, it } from "vitest";
import { SupabaseAssignmentCommandRepository } from "@/integrations/supabase/SupabaseAssignmentCommandRepository";
import { SupabaseOperationalCommandRepository } from "@/integrations/supabase/SupabaseOperationalCommandRepository";
import { SupabaseRentalPreparationCommandRepository } from "@/integrations/supabase/SupabaseRentalPreparationCommandRepository";
import { SupabaseDeurCommandRepository } from "@/integrations/supabase/SupabaseDeurCommandRepository";
import type { DeurRecord } from "@/features/rental/deur/types";
import { BillingRateEngine } from "@/features/rental/billing/engine";
import { assertSupabaseFixtureMutationAllowed, createSupabasePhaseC2Harness, readSupabasePhaseC2TestConfiguration } from "./support/supabasePhaseC2Harness";

const config=readSupabasePhaseC2TestConfiguration();
const local=config.url ? ["localhost","127.0.0.1"].includes(new URL(config.url).hostname) : false;
const enabled=config.enabled && local && process.env.RUN_P9_2C_LOCAL==="true";
const container=process.env.P9_2C_LOCAL_DB_CONTAINER ?? "";
const tenant="TENANT-UAT-P9-2C";

describe.skipIf(!enabled)("P9.2C prepared shared Rental",()=>{
  const harness=enabled?createSupabasePhaseC2Harness(config):undefined;
  const email=`p9-2c-${randomBytes(8).toString("hex")}@example.invalid`, password=`P9C-${randomBytes(24).toString("base64url")}`;
  let userId="", inactiveUserId="", deniedUserId="", operatorUserId="", wrongOperatorUserId=""; let a:SupabaseClient; let b:SupabaseClient; let missing:SupabaseClient; let inactive:SupabaseClient; let denied:SupabaseClient; let operatorClient:SupabaseClient; let wrongOperatorClient:SupabaseClient;
  const owner=(sql:string)=>{if(!container.startsWith("supabase_db_"))throw new Error("Verified local container required");const r=spawnSync("docker",["exec","-i",container,"psql","-U","postgres","-d","postgres","-X","-v","ON_ERROR_STOP=1"],{input:sql,encoding:"utf8",windowsHide:true});if(r.status!==0)throw new Error(r.stderr)};
  beforeAll(async()=>{
    assertSupabaseFixtureMutationAllowed(config,[tenant]);
    const made=await harness!.admin.auth.admin.createUser({email,password,email_confirm:true}); if(made.error||!made.data.user)throw made.error; userId=made.data.user.id;
    const createIdentity=async(label:string)=>{const result=await harness!.admin.auth.admin.createUser({email:`p9-2c-${label}-${randomBytes(6).toString("hex")}@example.invalid`,password,email_confirm:true});if(result.error||!result.data.user)throw result.error;return result.data.user};
    const missingIdentity=await createIdentity("missing"),inactiveIdentity=await createIdentity("inactive"),deniedIdentity=await createIdentity("denied"),operatorIdentity=await createIdentity("operator"),wrongOperatorIdentity=await createIdentity("wrong-operator"); inactiveUserId=inactiveIdentity.id;deniedUserId=deniedIdentity.id;operatorUserId=operatorIdentity.id;wrongOperatorUserId=wrongOperatorIdentity.id;
    owner(`BEGIN;
      INSERT INTO erp.companies(id,code,name,environment_class)VALUES('${tenant}','P92C','P9.2C','test');
      INSERT INTO erp.companies(id,code,name,environment_class)VALUES('TENANT-UAT-P9-2C-B','P92CB','P9.2C B','test');
      INSERT INTO erp.customers(id,name,active,company_id)VALUES('CUSTOMER-P9-2C','Customer',true,'${tenant}');
      INSERT INTO erp.projects(id,name,customer_id,active,company_id)VALUES('PROJECT-P9-2C','Project','CUSTOMER-P9-2C',true,'${tenant}');
      INSERT INTO erp.operators(id,name,status,company_id)VALUES('OPERATOR-P9-2C','Operator','Active','${tenant}'),('OPERATOR-P9-2C-WRONG','Wrong Operator','Active','${tenant}');
      INSERT INTO erp.cost_codes(id,code,name)VALUES('COST-P9-2C','P92C','P9 Cost');
      INSERT INTO erp.activity_codes(id,code,name)VALUES('ACTIVITY-P9-2C','P92C','P9 Activity');
      INSERT INTO erp.work_descriptions(id,code,name,requires_remarks)VALUES('WORK-P9-2C','P92C-WORK','P9 Work',false);
      INSERT INTO erp.equipment(id,asset_no,equipment_name,status_id,maintenance_type,cost_code_id,company_id) SELECT 'EQUIPMENT-P9-2C','P92C-EQ','Equipment',id,'Engine Hours','COST-P9-2C','${tenant}' FROM erp.equipment_statuses WHERE lower(code)='available' LIMIT 1;
      INSERT INTO erp.users(id,username,display_name,status,company_id)VALUES('${userId}'::uuid,'${email}','Operations','active','${tenant}');
      INSERT INTO erp.users(id,username,display_name,status,company_id)VALUES('${inactiveUserId}'::uuid,'inactive','Inactive','inactive','${tenant}'),('${deniedUserId}'::uuid,'denied','Denied','active','${tenant}');
      INSERT INTO erp.users(id,username,display_name,status,operator_id,company_id)VALUES('${operatorUserId}'::uuid,'operator','Operator','active','OPERATOR-P9-2C','${tenant}'),('${wrongOperatorUserId}'::uuid,'wrong-operator','Wrong Operator','active','OPERATOR-P9-2C-WRONG','${tenant}');
      INSERT INTO erp.app_roles(id,code,name)VALUES('ROLE-P9-2C','p9-2c','P9.2C');
      INSERT INTO erp.role_permissions(role_id,permission_id) SELECT 'ROLE-P9-2C',id FROM erp.app_permissions WHERE code IN('assignment.manage','rental.manage','rental.release','deur.create');
      INSERT INTO erp.user_roles(user_id,role_id)VALUES('${userId}'::uuid,'ROLE-P9-2C'),('${operatorUserId}'::uuid,'ROLE-P9-2C'),('${wrongOperatorUserId}'::uuid,'ROLE-P9-2C'); COMMIT;`);
    const make=(key:string)=>createClient(config.url!,config.publishableKey!,{auth:{persistSession:false,autoRefreshToken:false,storageKey:key}}); a=make(randomUUID());b=make(randomUUID());missing=make(randomUUID());inactive=make(randomUUID());denied=make(randomUUID());operatorClient=make(randomUUID());wrongOperatorClient=make(randomUUID());
    expect((await a.auth.signInWithPassword({email,password})).error).toBeNull();expect((await b.auth.signInWithPassword({email,password})).error).toBeNull();
    expect((await missing.auth.signInWithPassword({email:missingIdentity.email!,password})).error).toBeNull();expect((await inactive.auth.signInWithPassword({email:inactiveIdentity.email!,password})).error).toBeNull();expect((await denied.auth.signInWithPassword({email:deniedIdentity.email!,password})).error).toBeNull();
    expect((await operatorClient.auth.signInWithPassword({email:operatorIdentity.email!,password})).error).toBeNull();expect((await wrongOperatorClient.auth.signInWithPassword({email:wrongOperatorIdentity.email!,password})).error).toBeNull();
  });
  it("creates, prepares, replays and releases one canonical Rental visible to Client B",async()=>{
    const assignment={commandId:randomUUID(),idempotencyKey:randomUUID(),assignmentId:"ASSIGNMENT-P9-2C",equipmentId:"EQUIPMENT-P9-2C",operatorId:"OPERATOR-P9-2C",projectId:"PROJECT-P9-2C",activityCodeId:"ACTIVITY-P9-2C",assignedDate:"2026-08-15",expectedReturn:"2026-08-20"};
    expect(await new SupabaseAssignmentCommandRepository(a).createAssignment(assignment)).toMatchObject({success:true});
    const lifecycle=new SupabaseOperationalCommandRepository(a);
    const created=await lifecycle.createReserved({commandId:randomUUID(),idempotencyKey:randomUUID(),rentalId:"RENTAL-P9-2C",rentalNumber:"P92C-001",customerId:"CUSTOMER-P9-2C",projectId:"PROJECT-P9-2C",dateOut:"2026-08-15",expectedReturn:"2026-08-20",rentalType:"Operated Rental",lines:[{id:"LINE-P9-2C",equipmentId:"EQUIPMENT-P9-2C",assignmentId:"ASSIGNMENT-P9-2C",operatorId:"OPERATOR-P9-2C"}]}); expect(created).toMatchObject({success:true,value:{version:1}});
    expect(await lifecycle.release({commandId:randomUUID(),idempotencyKey:randomUUID(),rentalId:"RENTAL-P9-2C"})).toMatchObject({success:false});
    const command={commandId:randomUUID(),idempotencyKey:randomUUID(),expectedVersion:1,rentalId:"RENTAL-P9-2C",lineId:"LINE-P9-2C",commercialTerms:{billingMethod:"Per Hour" as const,unitRate:100,minimumBillableHours:4,operatorIncluded:true,currency:"PHP"},costCodeId:"COST-P9-2C",activityCodeId:"ACTIVITY-P9-2C",workDescriptionId:"WORK-P9-2C",deurPolicy:{frequency:"ON_DEMAND" as const,effectiveFrom:"2026-08-15"},shiftWindows:[],workDate:"2026-08-15",meterRequirement:"none" as const};
    const preparation=new SupabaseRentalPreparationCommandRepository(a); const prepared=await preparation.prepareReservedRental(command); expect(prepared).toMatchObject({success:true,disposition:"ACCEPTED",value:{releaseReady:true}});
    expect(await preparation.prepareReservedRental({...command,commandId:randomUUID()})).toMatchObject({success:true,disposition:"REPLAYED"});
    expect(await preparation.prepareReservedRental({...command,commandId:randomUUID(),commercialTerms:{...command.commercialTerms,unitRate:200}})).toMatchObject({success:false,code:"IDEMPOTENCY_MISMATCH"});
    expect(await lifecycle.release({commandId:randomUUID(),idempotencyKey:randomUUID(),rentalId:"RENTAL-P9-2C"})).toMatchObject({success:true,value:{status:"Released"}});
    expect((await b.schema("erp").from("rentals").select("id,status").eq("id","RENTAL-P9-2C").single()).data).toEqual({id:"RENTAL-P9-2C",status:"Released"});
    const line=await b.schema("erp").from("rental_equipment_lines").select("id,assignment_id,operational_metadata").eq("id","LINE-P9-2C").single(); expect(line.data?.operational_metadata?.deurExpectationSnapshot?.sourceFingerprint).toBeTruthy();
    expect((await b.schema("erp").from("commercial_snapshots").select("billing_method,unit_rate").eq("rental_equipment_line_id","LINE-P9-2C").single()).data).toMatchObject({billing_method:"Per Hour",unit_rate:100});
    const snapshot=(await b.schema("erp").from("commercial_snapshots").select("billing_method,unit_rate,minimum_billable_hours,operator_included,operator_rate,tax_rate,withholding_tax,contract_amount").eq("rental_equipment_line_id","LINE-P9-2C").single()).data!;
    expect(BillingRateEngine.calculate({totalOperatingMinutes:60,totalIdleMinutes:0,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0} as DeurRecord,{billingMethod:snapshot.billing_method,unitRate:Number(snapshot.unit_rate),minimumBillableHours:Number(snapshot.minimum_billable_hours),operatorIncluded:snapshot.operator_included,operatorRate:Number(snapshot.operator_rate??0)}).operatingCharge).toBe(400);
    const draft={id:"DEUR-P9-2C",rentalId:"RENTAL-P9-2C",rentalEquipmentLineId:"LINE-P9-2C",assignmentId:"ASSIGNMENT-P9-2C",equipmentId:"EQUIPMENT-P9-2C",operatorId:"OPERATOR-P9-2C",projectId:"PROJECT-P9-2C",customerId:"CUSTOMER-P9-2C",workDate:"2026-08-15",shift:"Day",status:"In Progress",evidenceMode:"TIME_TIMELINE",operationalMetadata:line.data!.operational_metadata} as DeurRecord;
    const deurCommand={commandId:randomUUID(),idempotencyKey:randomUUID(),rentalId:"RENTAL-P9-2C",rentalLineId:"LINE-P9-2C",equipmentId:"EQUIPMENT-P9-2C",operatorId:"OPERATOR-P9-2C",assignmentId:"ASSIGNMENT-P9-2C",draft};
    expect(await new SupabaseDeurCommandRepository(operatorClient).startShift(deurCommand)).toMatchObject({success:true,record:{id:"DEUR-P9-2C",rentalId:"RENTAL-P9-2C",rentalEquipmentLineId:"LINE-P9-2C",assignmentId:"ASSIGNMENT-P9-2C",operatorId:"OPERATOR-P9-2C"}});
    expect(await new SupabaseDeurCommandRepository(wrongOperatorClient).startShift({...deurCommand,commandId:randomUUID(),idempotencyKey:randomUUID(),draft:{...draft,id:"DEUR-P9-2C-WRONG"}})).toMatchObject({success:false,code:"OWNERSHIP_MISMATCH"});
  });

  it("rejects the live authority and validation matrix without partial state",async()=>{
    owner(`BEGIN;
      INSERT INTO erp.customers(id,name,active,company_id)VALUES('CUSTOMER-P9-2C-B','Customer B',true,'TENANT-UAT-P9-2C-B');
      INSERT INTO erp.projects(id,name,customer_id,active,company_id)VALUES('PROJECT-P9-2C-B','Project B','CUSTOMER-P9-2C-B',true,'TENANT-UAT-P9-2C-B');
      INSERT INTO erp.operators(id,name,status,company_id)VALUES('OPERATOR-P9-2C-B','Operator B','Active','TENANT-UAT-P9-2C-B');
      INSERT INTO erp.equipment(id,asset_no,equipment_name,status_id,maintenance_type,cost_code_id,company_id) SELECT 'EQUIPMENT-P9-2C-B','P92C-EQB','Equipment B',id,'Engine Hours','COST-P9-2C','TENANT-UAT-P9-2C-B' FROM erp.equipment_statuses WHERE lower(code)='available' LIMIT 1;
      INSERT INTO erp.assignments(id,equipment_id,operator_id,project_id,activity_code_id,assigned_date,expected_return,status,company_id)VALUES('ASSIGNMENT-P9-2C-B','EQUIPMENT-P9-2C-B','OPERATOR-P9-2C-B','PROJECT-P9-2C-B','ACTIVITY-P9-2C','2026-08-15','2026-08-20','Active','TENANT-UAT-P9-2C-B');
      INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,expected_return,rental_type,status,reserved_at,company_id,legacy_payload)VALUES('RENTAL-P9-2C-B','P92C-B','CUSTOMER-P9-2C-B','PROJECT-P9-2C-B','Customer B','Project B','2026-08-15','2026-08-20','Operated Rental','Reserved',clock_timestamp(),'TENANT-UAT-P9-2C-B',jsonb_build_object('approvalStatus','Approved'));
      INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,commercial_snapshot_required,company_id)VALUES('LINE-P9-2C-B','RENTAL-P9-2C-B','EQUIPMENT-P9-2C-B','ASSIGNMENT-P9-2C-B','OPERATOR-P9-2C-B','Reserved',true,'TENANT-UAT-P9-2C-B');
      INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,expected_return,rental_type,status,reserved_at,company_id,legacy_payload)VALUES('RENTAL-P9-2C-NEG','P92C-NEG','CUSTOMER-P9-2C','PROJECT-P9-2C','Customer','Project','2026-08-15','2026-08-20','Operated Rental','Reserved',clock_timestamp(),'${tenant}',jsonb_build_object('approvalStatus','Approved'));
      INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,commercial_snapshot_required,company_id)VALUES('LINE-P9-2C-NEG','RENTAL-P9-2C-NEG','EQUIPMENT-P9-2C','ASSIGNMENT-P9-2C','OPERATOR-P9-2C','Reserved',true,'${tenant}'); COMMIT;`);
    const valid={commandId:randomUUID(),idempotencyKey:randomUUID(),expectedVersion:1,rentalId:"RENTAL-P9-2C-NEG",lineId:"LINE-P9-2C-NEG",commercialTerms:{billingMethod:"Per Hour",unitRate:100,minimumBillableHours:4,operatorIncluded:true,currency:"PHP"},costCodeId:"COST-P9-2C",activityCodeId:"ACTIVITY-P9-2C",workDescriptionId:"WORK-P9-2C",deurPolicy:{frequency:"ON_DEMAND",effectiveFrom:"2026-08-15"},shiftWindows:[],workDate:"2026-08-15",meterRequirement:"none"};
    const invoke=(client:SupabaseClient,command:Record<string,unknown>)=>client.schema("erp").rpc("command_prepare_reserved_rental",{command});
    const state=()=>JSON.parse(spawnSync("docker",["exec",container,"psql","-U","postgres","-d","postgres","-Atc",`SELECT jsonb_build_object('snapshots',(SELECT count(*) FROM erp.commercial_snapshots WHERE rental_id='RENTAL-P9-2C-NEG'),'metadata',(SELECT operational_metadata FROM erp.rental_equipment_lines WHERE id='LINE-P9-2C-NEG'),'rentalVersion',(SELECT row_version FROM erp.rentals WHERE id='RENTAL-P9-2C-NEG'),'lineVersion',(SELECT row_version FROM erp.rental_equipment_lines WHERE id='LINE-P9-2C-NEG'),'audit',(SELECT count(*) FROM erp.audit_log WHERE aggregate_id='RENTAL-P9-2C-NEG' AND action='RENTAL_PREPARED'),'completedIdem',(SELECT count(*) FROM erp.operational_command_idempotency WHERE target_aggregate_id='RENTAL-P9-2C-NEG' AND command_type='PREPARE_RESERVED_RENTAL' AND command_status='COMPLETED'));`],{encoding:"utf8",windowsHide:true}).stdout.trim());
    const baseline=state();
    const rejected=async(client:SupabaseClient,change:Record<string,unknown>)=>{const command={...valid,commandId:randomUUID(),idempotencyKey:randomUUID(),...change};const result=await invoke(client,command);expect(result.data).toMatchObject({success:false});expect(state()).toEqual(baseline)};
    const anonymous=createClient(config.url!,config.publishableKey!,{auth:{persistSession:false}});expect((await invoke(anonymous,valid)).error?.code).toBe("42501");
    await rejected(missing,{}); await rejected(inactive,{}); await rejected(denied,{});
    for(const field of ["company_id","tenant_id","actor","user_id","frozenSnapshot","deurExpectationSnapshot","fingerprint"])await rejected(a,{[field]:field});
    await rejected(a,{rentalId:"RENTAL-P9-2C-B",lineId:"LINE-P9-2C-B"}); await rejected(a,{lineId:"LINE-P9-2C-B"});
    for(const commercialTerms of [
      {...valid.commercialTerms,billingMethod:"Unsupported"},{...valid.commercialTerms,unitRate:-1},{...valid.commercialTerms,minimumBillableHours:-1},{...valid.commercialTerms,overtimeRate:-1},{...valid.commercialTerms,standbyRate:-1},{...valid.commercialTerms,mobilizationFee:-1},{...valid.commercialTerms,demobilizationFee:-1},{...valid.commercialTerms,fuelCharge:-1},{...valid.commercialTerms,operatorRate:-1},{...valid.commercialTerms,taxRate:-1},{...valid.commercialTerms,taxRate:101},{...valid.commercialTerms,withholdingTax:101},{...valid.commercialTerms,currency:"PH"},{...valid.commercialTerms,operatorIncluded:"yes"},{...valid.commercialTerms,contractAmount:-1},
    ])await rejected(a,{commercialTerms});
    await rejected(a,{deurPolicy:{frequency:"INVALID",effectiveFrom:"2026-08-15"}});await rejected(a,{deurPolicy:{frequency:"PER_SHIFT",effectiveFrom:"2026-08-15"}});await rejected(a,{deurPolicy:{frequency:"PER_SHIFT",effectiveFrom:"2026-08-15"},shiftWindows:[{code:"SWING",label:"Swing",startTime:"08:00",endTime:"17:00",timezone:"Asia/Manila"}]});await rejected(a,{deurPolicy:{frequency:"PER_SHIFT",effectiveFrom:"2026-08-15"},shiftWindows:[{code:"DAY",label:"Day",startTime:"invalid",endTime:"17:00",timezone:"Asia/Manila"}]});await rejected(a,{shiftWindows:[{code:"DAY",label:"Day",startTime:"08:00",endTime:"17:00",timezone:"Asia/Manila"}]});await rejected(a,{deurPolicy:{frequency:"ON_DEMAND",effectiveFrom:"2026-08-14"}});await rejected(a,{deurPolicy:{frequency:"ON_DEMAND",effectiveFrom:"2026-08-21"}});await rejected(a,{workDate:"2026-08-16"});await rejected(a,{workDescriptionId:"MISSING"});
    owner("UPDATE erp.equipment SET active=false WHERE id='EQUIPMENT-P9-2C';");await rejected(a,{});owner("UPDATE erp.equipment SET active=true WHERE id='EQUIPMENT-P9-2C';");
    owner("UPDATE erp.equipment SET deleted_at=clock_timestamp() WHERE id='EQUIPMENT-P9-2C';");await rejected(a,{});owner("UPDATE erp.equipment SET deleted_at=NULL WHERE id='EQUIPMENT-P9-2C';");
    owner("UPDATE erp.operators SET status='Suspended' WHERE id='OPERATOR-P9-2C';");await rejected(a,{});owner("UPDATE erp.operators SET status='Active' WHERE id='OPERATOR-P9-2C';");
    owner("UPDATE erp.projects SET active=false WHERE id='PROJECT-P9-2C';");await rejected(a,{});owner("UPDATE erp.projects SET active=true WHERE id='PROJECT-P9-2C';");
    owner("UPDATE erp.activity_codes SET active=false WHERE id='ACTIVITY-P9-2C';");await rejected(a,{});owner("UPDATE erp.activity_codes SET active=true WHERE id='ACTIVITY-P9-2C';");
    owner("UPDATE erp.cost_codes SET active=false WHERE id='COST-P9-2C';");await rejected(a,{});owner("UPDATE erp.cost_codes SET active=true WHERE id='COST-P9-2C';");
    owner("UPDATE erp.work_descriptions SET requires_remarks=true WHERE id='WORK-P9-2C';");await rejected(a,{});owner("UPDATE erp.work_descriptions SET requires_remarks=false WHERE id='WORK-P9-2C';");
    await rejected(a,{meterRequirement:"odometer"});await rejected(a,{meterRequirement:"both"});owner("UPDATE erp.equipment SET maintenance_type='Kilometers' WHERE id='EQUIPMENT-P9-2C';");await rejected(a,{meterRequirement:"hourMeter"});owner("UPDATE erp.equipment SET maintenance_type='Engine Hours' WHERE id='EQUIPMENT-P9-2C';");await rejected(a,{meterRequirement:"invalid"});await rejected(a,{expectedVersion:0});
  },60_000);

  it("commits exactly one canonical result under competing preparations and blocks direct snapshot writes",async()=>{
    owner(`BEGIN;
      INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,expected_return,rental_type,status,reserved_at,company_id,legacy_payload)VALUES('RENTAL-P9-2C-RACE','P92C-RACE','CUSTOMER-P9-2C','PROJECT-P9-2C','Customer','Project','2026-08-15','2026-08-20','Operated Rental','Reserved',clock_timestamp(),'${tenant}',jsonb_build_object('approvalStatus','Approved'));
      INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,commercial_snapshot_required,company_id)VALUES('LINE-P9-2C-RACE','RENTAL-P9-2C-RACE','EQUIPMENT-P9-2C','ASSIGNMENT-P9-2C','OPERATOR-P9-2C','Reserved',true,'${tenant}'); COMMIT;`);
    const base={expectedVersion:1,rentalId:"RENTAL-P9-2C-RACE",lineId:"LINE-P9-2C-RACE",commercialTerms:{billingMethod:"Per Hour",unitRate:100,operatorIncluded:true,currency:"PHP"},costCodeId:"COST-P9-2C",activityCodeId:"ACTIVITY-P9-2C",workDescriptionId:"WORK-P9-2C",deurPolicy:{frequency:"ON_DEMAND",effectiveFrom:"2026-08-15"},shiftWindows:[],workDate:"2026-08-15",meterRequirement:"none"};
    const send=(client:SupabaseClient,key:string)=>client.schema("erp").rpc("command_prepare_reserved_rental",{command:{...base,commandId:randomUUID(),idempotencyKey:key}}).then(result=>result.data as {success:boolean;disposition?:string;code?:string});
    const competing=await Promise.all([send(a,randomUUID()),send(b,randomUUID())]);expect(competing.filter(result=>result.success)).toHaveLength(1);
    const persisted=JSON.parse(spawnSync("docker",["exec",container,"psql","-U","postgres","-d","postgres","-Atc",`SELECT jsonb_build_object('snapshots',(SELECT count(*) FROM erp.commercial_snapshots WHERE rental_id='RENTAL-P9-2C-RACE'),'audit',(SELECT count(*) FROM erp.audit_log WHERE aggregate_id='RENTAL-P9-2C-RACE' AND action='RENTAL_PREPARED'),'fingerprint',(SELECT operational_metadata#>>'{deurExpectationSnapshot,sourceFingerprint}' FROM erp.rental_equipment_lines WHERE id='LINE-P9-2C-RACE'));`],{encoding:"utf8",windowsHide:true}).stdout.trim());expect(persisted).toMatchObject({snapshots:1,audit:1});expect(persisted.fingerprint).toBeTruthy();
    const sameKey=randomUUID();
    owner(`INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,expected_return,rental_type,status,reserved_at,company_id,legacy_payload)VALUES('RENTAL-P9-2C-IDEM','P92C-IDEM','CUSTOMER-P9-2C','PROJECT-P9-2C','Customer','Project','2026-08-15','2026-08-20','Operated Rental','Reserved',clock_timestamp(),'${tenant}',jsonb_build_object('approvalStatus','Approved')); INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,commercial_snapshot_required,company_id)VALUES('LINE-P9-2C-IDEM','RENTAL-P9-2C-IDEM','EQUIPMENT-P9-2C','ASSIGNMENT-P9-2C','OPERATOR-P9-2C','Reserved',true,'${tenant}');`);
    const idemBase={...base,rentalId:"RENTAL-P9-2C-IDEM",lineId:"LINE-P9-2C-IDEM"};const equivalent=await Promise.all([a.schema("erp").rpc("command_prepare_reserved_rental",{command:{...idemBase,commandId:randomUUID(),idempotencyKey:sameKey}}),b.schema("erp").rpc("command_prepare_reserved_rental",{command:{...idemBase,commandId:randomUUID(),idempotencyKey:sameKey}})]);expect(equivalent.map(item=>(item.data as {disposition:string}).disposition).sort()).toEqual(["ACCEPTED","REPLAYED"]);
    const snapshotId=(await b.schema("erp").from("commercial_snapshots").select("id").eq("rental_id","RENTAL-P9-2C-RACE").single()).data!.id;
    expect((await a.schema("erp").from("commercial_snapshots").insert({id:"FORBIDDEN",rental_id:"RENTAL-P9-2C-RACE",billing_method:"Per Hour",unit_rate:1,operator_included:true,currency:"PHP",captured_at:new Date().toISOString()})).error).toBeTruthy();
    expect((await a.schema("erp").from("commercial_snapshots").update({unit_rate:999}).eq("id",snapshotId)).error).toBeTruthy();expect((await a.schema("erp").from("commercial_snapshots").delete().eq("id",snapshotId)).error).toBeTruthy();expect((await a.schema("erp").from("rental_equipment_lines").update({operational_metadata:{deurExpectationSnapshot:{sourceFingerprint:"forged"}}}).eq("id","LINE-P9-2C-RACE")).error).toBeTruthy();
  },30_000);

  it("generates billing-adapter-compatible canonical snapshots for standard methods",async()=>{
    for(const [index,method] of ["Per Hour","Per Day","Per Week","Per Month","One Lot"].entries()){
      const suffix=`M${index}`,rentalId=`RENTAL-P9-2C-${suffix}`,lineId=`LINE-P9-2C-${suffix}`;
      owner(`INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,expected_return,rental_type,status,reserved_at,company_id,legacy_payload)VALUES('${rentalId}','P92C-${suffix}','CUSTOMER-P9-2C','PROJECT-P9-2C','Customer','Project','2026-08-15','2026-08-20','Operated Rental','Reserved',clock_timestamp(),'${tenant}',jsonb_build_object('approvalStatus','Approved')); INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,commercial_snapshot_required,company_id)VALUES('${lineId}','${rentalId}','EQUIPMENT-P9-2C','ASSIGNMENT-P9-2C','OPERATOR-P9-2C','Reserved',true,'${tenant}');`);
      const result=await new SupabaseRentalPreparationCommandRepository(a).prepareReservedRental({commandId:randomUUID(),idempotencyKey:randomUUID(),expectedVersion:1,rentalId,lineId,commercialTerms:{billingMethod:method as "Per Hour",unitRate:100,operatorIncluded:true,operatorRate:25,taxRate:12,withholdingTax:2,contractAmount:1000,currency:"PHP"},costCodeId:"COST-P9-2C",activityCodeId:"ACTIVITY-P9-2C",workDescriptionId:"WORK-P9-2C",deurPolicy:{frequency:"ON_DEMAND",effectiveFrom:"2026-08-15"},shiftWindows:[],workDate:"2026-08-15",meterRequirement:"none"});expect(result).toMatchObject({success:true});
      const generated=(await b.schema("erp").from("commercial_snapshots").select("billing_method,unit_rate,operator_included,operator_rate,tax_rate,withholding_tax,contract_amount,currency").eq("rental_equipment_line_id",lineId).single()).data!;expect(generated).toMatchObject({billing_method:method,operator_included:true,currency:"PHP"});expect([generated.unit_rate,generated.operator_rate,generated.tax_rate,generated.withholding_tax,generated.contract_amount].map(Number)).toEqual([100,25,12,2,1000]);
    }
  },30_000);
});
