import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {describe,expect,it} from "vitest";
const sql=readFileSync(resolve("supabase/migrations/20260803006000_phase_c12_grouped_customer_review_three_line_cleanup.sql"),"utf8");
const pos=(value:string)=>sql.indexOf(value);
describe("C12 grouped Customer Review three-line cleanup expansion",()=>{
 it("replaces only the exact owner cleanup function",()=>{expect(sql).toContain("CREATE OR REPLACE FUNCTION erp.cleanup_c12_grouped_customer_review_fixture");expect(sql).toContain("TENANT-UAT-C12-GROUPED-CUSTOMER-001");expect(sql).toContain("CONFIRM-C12-GROUPED-CUSTOMER-CLEANUP");expect(sql).toContain("session_user<>database_owner OR current_user<>database_owner");expect(sql.match(/CREATE OR REPLACE FUNCTION/g)).toHaveLength(1);});
 it("supports exactly the three-line and two-day shape",()=>{for(const guard of ["operators WHERE company_id=target_tenant_id)>3","equipment WHERE company_id=target_tenant_id)>3","assignments WHERE company_id=target_tenant_id)>3","rental_equipment_lines WHERE company_id=target_tenant_id)>3","deurs WHERE company_id=target_tenant_id)>3","customer_review_requests WHERE company_id=target_tenant_id)>2","customer_review_batches WHERE company_id=target_tenant_id)>2","customer_review_batch_items WHERE company_id=target_tenant_id)>6"])expect(sql).toContain(guard);});
 it("rejects the fourth line/DEUR/equipment and third request structurally",()=>{expect(sql).not.toContain("equipment WHERE company_id=target_tenant_id)>4");expect(sql).not.toContain("rental_equipment_lines WHERE company_id=target_tenant_id)>4");expect(sql).not.toContain("deurs WHERE company_id=target_tenant_id)>4");expect(sql).not.toContain("customer_review_requests WHERE company_id=target_tenant_id)>3");});
 it("preserves child-to-parent deletion order",()=>{const items=pos("DELETE FROM customer_review_batch_items"),batches=pos("DELETE FROM customer_review_batches"),requests=pos("DELETE FROM customer_review_requests"),events=pos("DELETE FROM deur_events"),deurs=pos("DELETE FROM deurs"),lines=pos("DELETE FROM rental_equipment_lines"),rentals=pos("DELETE FROM rentals"),assignments=pos("DELETE FROM assignments"),equipment=pos("DELETE FROM equipment WHERE"),company=pos("DELETE FROM companies WHERE");expect(items).toBeLessThan(batches);expect(batches).toBeLessThan(requests);expect(requests).toBeLessThan(deurs);expect(events).toBeLessThan(deurs);expect(deurs).toBeLessThan(lines);expect(lines).toBeLessThan(rentals);expect(rentals).toBeLessThan(assignments);expect(assignments).toBeLessThan(equipment);expect(equipment).toBeLessThan(company);});
 it("preserves notification, financial, Manager, and maintenance guards",()=>{for(const value of ["notification_outbox WHERE company_id=target_tenant_id)>0","notification_delivery_attempts WHERE company_id=target_tenant_id)>0","billing_statements","billing_statement_lines","collections c","recovery_compensations","manager_review_requests","manager_review_outcomes","maintenance_records","equipment_daily_logs"])expect(sql).toContain(value);});
 it("preserves exact immutable marker and local tenant protection",()=>{expect(sql).toContain("set_config('erp.c12_grouped_review_fixture_cleanup',target_tenant_id,true)");expect(sql.match(/companies WHERE id='TENANT-LOCAL-001' AND code='LOCAL' AND environment_class='compatibility'/g)).toHaveLength(2);});
 it("retains security and avoids broad bypasses or shared catalogs",()=>{expect(sql).toContain("SECURITY DEFINER SET search_path=erp,pg_catalog");expect(sql).toContain("OWNER TO postgres");expect(sql).toContain("FROM PUBLIC,anon,authenticated,service_role");expect(sql).not.toMatch(/target_tenant_id\s+(?:LIKE|~)/i);expect(sql).not.toMatch(/(?:INSERT|UPDATE|DELETE)\s+(?:FROM\s+)?auth\.users/i);expect(sql).not.toMatch(/session_replication_role|DISABLE\s+TRIGGER|DELETE FROM (?:app_roles|app_permissions|role_permissions)/i);});
});
