import { describe, expect, it } from "vitest";
import { filterEquipmentList } from "@/features/equipment/services/equipmentListFilters";
import { filterMaintenanceDue, maintenanceHealth } from "@/features/maintenance/services/maintenanceListFilters";
import { filterMissingDeurItems, missingDeurCounts, type MissingDeurListItem } from "@/features/rental/deur/compliance/missingDeurList";
import { searchGlobalRecords } from "@/components/search/globalSearchService";
import type { EquipmentRecord } from "@/features/equipment/types";

const equipment=(id:string,status:EquipmentRecord["status"],name=id):EquipmentRecord=>({id,prefixId:"ME",assetNo:id,equipmentName:name,category:"Moving Equipment",status,maintenanceType:"Engine Hours",currentReading:0,projectId:"p",operatorId:"o"});
describe("Phase 2D operational list contracts",()=>{
 it("combines equipment status aliases and search without exposing inactive records",()=>{const rows=[equipment("ME-1","Rented","UAT 1"),equipment("ME-2","Assigned"),{...equipment("ME-3","Rented"),active:false}];expect(filterEquipmentList(rows,{status:"Deployed",query:"uat",category:"",ownership:"",location:""}).map(x=>x.id)).toEqual(["ME-1"]);expect(filterEquipmentList(rows,{status:"Assigned",query:"",category:"",ownership:"",location:""}).map(x=>x.id)).toEqual(["ME-2"])});
 it("filters all maintenance health cards deterministically",()=>{const rows=[{due:true,remaining:-1,equipment:{status:"Available"}},{due:false,remaining:20,equipment:{status:"Available"}},{due:false,remaining:100,equipment:{status:"Available"}}];expect(rows.map(maintenanceHealth)).toEqual(["Overdue","Due Soon","Healthy"]);expect(filterMaintenanceDue(rows,"All")).toHaveLength(3);expect(filterMaintenanceDue(rows,"Healthy")).toHaveLength(1)});
 it("filters, counts, and newest-sorts DEUR exceptions while preserving detail data",()=>{const items:MissingDeurListItem[]=[{id:"1",rental:"RENT-1",workDate:"2026-08-10",equipment:"ME-1",operator:"Alan",project:"P1",shift:"Day",status:"Missing",reason:"No DEUR",searchText:"Per Day"},{id:"2",rental:"RENT-2",workDate:"2026-08-12",equipment:"ME-2",operator:"Beth",project:"P2",shift:"Night",status:"Incomplete",reason:"Review pending",searchText:"Per Hour"}];expect(missingDeurCounts(items)).toMatchObject({All:2,Missing:1,Incomplete:1});expect(filterMissingDeurItems(items,{query:"review",status:"All",from:"",to:"",operator:"",equipment:"",rental:"",project:""}).map(x=>x.id)).toEqual(["2"])});
 it("caps global groups and excludes unauthorized entities",()=>{const records=Array.from({length:7},(_,i)=>({type:"Equipment",id:String(i),title:`ME-${i}`,subtitle:"Excavator",searchable:"deployed",href:`/equipment/${i}`,permission:"equipment.read"})).concat([{type:"Rentals",id:"r",title:"RENT-1",subtitle:"Active",searchable:"customer",href:"/rentals/r",permission:"rental.read"}]);expect(searchGlobalRecords(records,"e",()=>true)).toEqual([]);expect(searchGlobalRecords(records,"deployed",()=>true)).toHaveLength(5);expect(searchGlobalRecords(records,"customer",p=>p!=="rental.read")).toEqual([])});
});
