import{randomBytes,randomUUID}from"node:crypto";
import{createClient}from"@supabase/supabase-js";
import{describe,expect,it}from"vitest";
import{assertSupabaseFixtureMutationAllowed,createSupabasePhaseC2Harness,readSupabasePhaseC2TestConfiguration}from"./support/supabasePhaseC2Harness";
import{executePhaseC4bPrivilegedSql}from"./support/phaseC4bPrivilegedSql";
import{loadIgnoredLocalTestEnvironment}from"./support/loadLiveTestEnvironment";
import{parseNotificationServerConfiguration}from"../server/notifications/config";
import{SupabaseTrustedNotificationRepository}from"../server/notifications/SupabaseTrustedNotificationRepository";
import{parseGroupedReviewDeliveryKey}from"../server/notifications/GroupedReviewDeliveryEnvelope";
import{DailyGroupedCustomerReviewService}from"../server/notifications/DailyGroupedCustomerReviewService";
import{SupabaseDailyGroupedReviewRepository}from"../server/notifications/SupabaseDailyGroupedReviewRepository";

loadIgnoredLocalTestEnvironment();
const mode=process.env.C12_CLOUDFLARE_CRON_MODE?.trim().toUpperCase();
const enabled=Boolean(mode);
const tenant="TENANT-UAT-C12-GROUPED-CUSTOMER-001";
const email="c12-cloudflare-cron@example.invalid";
const quote=(value:string)=>`'${value.replaceAll("'","''")}'`;

function nextSchedulerWindow(){const now=Date.now(),next=Math.ceil((now+1000)/900000)*900000;const parts=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(next).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));const hour=Number(parts.hour),minute=Number(parts.minute);if(hour===23&&minute>44)throw new Error("Next scheduler window would cross midnight.");return{next,date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`};}

describe.skipIf(!enabled)("C12.2.7E retained Cloudflare Cron UAT fixture",()=>{
 it("runs exactly one explicit retained-fixture lifecycle mode",async()=>{
  const configuration=readSupabasePhaseC2TestConfiguration();assertSupabaseFixtureMutationAllowed(configuration,[tenant]);expect(configuration.projectRef).toBe("jtkctarqbwmqdcewthkn");expect(process.env.VITE_REMOTE_OPERATIONAL_WRITES_ENABLED).toBe("false");
  const notification=parseNotificationServerConfiguration(process.env),controlled=notification.uatRecipientOverride?.trim().toLowerCase();expect(controlled).toMatch(/^[^\s@]+@[^\s@]+\.[^\s@]+$/);expect(controlled).not.toMatch(/[\r\n]/);
  const harness=createSupabasePhaseC2Harness(configuration),owner=(sql:string)=>executePhaseC4bPrivilegedSql(configuration,{tenantIds:[tenant],sql});
  const value=(sql:string)=>JSON.parse(owner(sql)).rows[0].jsonb_build_object as Record<string,any>;
  const cleanup=()=>Object.values(JSON.parse(owner(`SELECT erp.cleanup_c12_grouped_customer_review_fixture('${tenant}','${tenant}','CONFIRM-C12-GROUPED-CUSTOMER-CLEANUP');`)).rows[0])[0] as Record<string,unknown>;
  const authId=()=>String(value(`SELECT jsonb_build_object('id',(SELECT id FROM auth.users WHERE raw_user_meta_data->>'fixtureTenant'='${tenant}' LIMIT 1));`).id??"");
  const signIn=async()=>{const id=authId();expect(id).toMatch(/^[0-9a-f-]{36}$/i);const password=`C12-${randomBytes(24).toString("base64url")}`;expect((await harness.admin.auth.admin.updateUserById(id,{password})).error).toBeNull();const client=createClient(configuration.url!,configuration.publishableKey!,{auth:{persistSession:false,autoRefreshToken:false,storageKey:`cron-${randomUUID()}`}});expect((await client.auth.signInWithPassword({email,password})).error).toBeNull();return client;};
  if(mode==="PREPARE_RETAINED_FIXTURE"){
   expect(Object.values(cleanup()).every(x=>x===0)).toBe(true);expect(Object.values(cleanup()).every(x=>x===0)).toBe(true);const window=nextSchedulerWindow();
   const password=`C12-${randomBytes(24).toString("base64url")}`;const created=await harness.admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{fixtureTenant:tenant,fixtureKind:"cloudflare-cron-retained"}});if(created.error||!created.data.user)throw created.error??new Error("Auth fixture creation failed");const userId=created.data.user.id;
   owner(`BEGIN;
    INSERT INTO erp.companies(id,code,name,active,environment_class)VALUES('${tenant}','${tenant}','Cloudflare Cron UAT',true,'test');
    INSERT INTO erp.users(id,username,email,display_name,status,company_id)VALUES('${userId}'::uuid,${quote(email)},${quote(email)},'Cron Fixture Administrator','active','${tenant}');
    INSERT INTO erp.user_roles(user_id,role_id)VALUES('${userId}'::uuid,'ROLE-CANON-SYSTEM-ADMINISTRATOR');
    INSERT INTO erp.customers(id,customer_code,name,email,company_id)VALUES('CUSTOMER-UAT-C12-GROUPED-001','GROUPED','Non-authoritative Customer','master@example.invalid','${tenant}');
    INSERT INTO erp.projects(id,project_code,name,customer_id,company_id)VALUES('PROJECT-UAT-C12-GROUPED-001','GROUPED','Cron Project','CUSTOMER-UAT-C12-GROUPED-001','${tenant}');
    INSERT INTO erp.operators(id,name,status,company_id)VALUES('OPERATOR-UAT-C12-GROUPED-A','Cron Operator','Active','${tenant}');
    INSERT INTO erp.equipment(id,asset_no,equipment_name,maintenance_type,operator_id,project_id,company_id)VALUES('EQUIPMENT-UAT-C12-GROUPED-A','CRON-A','Cron Equipment','Hours','OPERATOR-UAT-C12-GROUPED-A','PROJECT-UAT-C12-GROUPED-001','${tenant}');
    INSERT INTO erp.assignments(id,equipment_id,operator_id,project_id,assigned_date,expected_return,status,company_id)VALUES('ASSIGN-UAT-C12-GROUPED-A','EQUIPMENT-UAT-C12-GROUPED-A','OPERATOR-UAT-C12-GROUPED-A','PROJECT-UAT-C12-GROUPED-001',${quote(window.date)}::date,${quote(window.date)}::date+10,'Active','${tenant}');
    INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,assignment_id,customer_snapshot,project_snapshot,rented_by,date_out,expected_return,status,timezone,customer_review_name_snapshot,customer_review_email_snapshot,company_id)VALUES('RENTAL-UAT-C12-GROUPED-001','CRON-001','CUSTOMER-UAT-C12-GROUPED-001','PROJECT-UAT-C12-GROUPED-001','ASSIGN-UAT-C12-GROUPED-A','Frozen Review Customer','Cron Project','Certification',${quote(window.date)}::date,${quote(window.date)}::date+10,'Active','Asia/Manila','Frozen Review Customer',${quote(controlled!)},'${tenant}');
    INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,company_id)VALUES('LINE-UAT-C12-GROUPED-A','RENTAL-UAT-C12-GROUPED-001','EQUIPMENT-UAT-C12-GROUPED-A','ASSIGN-UAT-C12-GROUPED-A','OPERATOR-UAT-C12-GROUPED-A','Active','${tenant}');
    INSERT INTO erp.deurs(id,deur_number,rental_id,rental_equipment_line_id,assignment_id,equipment_id,operator_id,project_id,customer_id,work_date,status,submitted_at,revision_chain_id,revision_number,company_id)VALUES('DEUR-UAT-C12-GROUPED-A','DEUR-CRON-A','RENTAL-UAT-C12-GROUPED-001','LINE-UAT-C12-GROUPED-A','ASSIGN-UAT-C12-GROUPED-A','EQUIPMENT-UAT-C12-GROUPED-A','OPERATOR-UAT-C12-GROUPED-A','PROJECT-UAT-C12-GROUPED-001','CUSTOMER-UAT-C12-GROUPED-001',${quote(window.date)}::date,'Submitted',clock_timestamp(),'DEUR-UAT-C12-GROUPED-A',1,'${tenant}');COMMIT;`);
   owner(`SELECT erp.configure_c12_grouped_review_scheduler_principal('${tenant}',true,'CONFIRM-C12-GROUPED-SCHEDULER-PRINCIPAL');`);const client=createClient(configuration.url!,configuration.publishableKey!,{auth:{persistSession:false,autoRefreshToken:false}});expect((await client.auth.signInWithPassword({email,password})).error).toBeNull();const configured=await client.schema("erp").rpc("command_configure_grouped_review_scheduler",{command:{commandId:randomUUID(),idempotencyKey:"cloudflare-cron-enable",automationEnabled:true,localSendTime:window.time,graceMinutes:15}});expect(configured.error).toBeNull();expect(configured.data).toMatchObject({success:true,value:{automationEnabled:true,schedulerReady:true}});
   const pre=value(`SELECT jsonb_build_object('automation',(SELECT count(*) FROM erp.grouped_review_scheduler_configurations WHERE company_id='${tenant}' AND automation_enabled),'principal',(SELECT count(*) FROM erp.system_principals WHERE company_id='${tenant}' AND active),'actionable',(SELECT count(*) FROM erp.deurs WHERE company_id='${tenant}' AND status='Submitted' AND work_date=${quote(window.date)}::date),'batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'notifications',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}'),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'envelopes',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}'),'snapshot',(SELECT customer_review_email_snapshot=${quote(controlled!)} FROM erp.rentals WHERE company_id='${tenant}'),'masterNotUsed',(SELECT email<>${quote(controlled!)} FROM erp.customers WHERE company_id='${tenant}'));`);expect(pre).toEqual({automation:1,principal:1,actionable:1,batches:0,notifications:0,attempts:0,envelopes:0,snapshot:true,masterNotUsed:true});return;
  }
  if(mode==="VERIFY_PUBLIC_CLIENT_BOUNDARY"){
   const client=await signIn();const repository=new SupabaseTrustedNotificationRepository(client,harness.admin,parseGroupedReviewDeliveryKey(),harness.anonymous);let notificationId=String(value(`SELECT jsonb_build_object('id',(SELECT id FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED' LIMIT 1));`).id??"");
   if(!notificationId){const timing=value(`SELECT jsonb_build_object('date',(SELECT date_out FROM erp.rentals WHERE company_id='${tenant}' LIMIT 1),'time',(SELECT to_char(local_send_time,'HH24:MI') FROM erp.grouped_review_scheduler_configurations WHERE company_id='${tenant}'));`);const scheduler=new DailyGroupedCustomerReviewService(new SupabaseDailyGroupedReviewRepository(harness.admin),parseGroupedReviewDeliveryKey());const prepared=await scheduler.run({commandId:randomUUID(),idempotencyKey:"public-client-authorization-proof",runAt:new Date(`${timing.date}T${timing.time}:00+08:00`).toISOString(),batchLimit:1});expect(prepared).toMatchObject({groupsClaimed:1,groupsPrepared:1,notificationsPrepared:1});notificationId=String(value(`SELECT jsonb_build_object('id',(SELECT id FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED' LIMIT 1));`).id??"");}
   const path=await repository.getGroupedReviewPath(notificationId);expect(path).toMatch(/^\/review\/customer\/grouped\/[0-9a-f]{64}$/);const credential=path!.split("/").at(-1)!;
   const publicLookup=await harness.anonymous.schema("erp").rpc("get_customer_review_batch",{command:{credential}});expect(publicLookup.error).toBeNull();expect(publicLookup.data).toMatchObject({success:true});
   const serviceLookup=await harness.admin.schema("erp").rpc("get_customer_review_batch",{command:{credential}});expect(serviceLookup.error?.code).toBe("42501");
   expect(await repository.resolveGroupedReviewDelivery(notificationId)).toMatchObject({status:"ACTIVE"});
   expect((await harness.anonymous.schema("erp").rpc("claim_notification_delivery",{notification_id:notificationId,worker_id:randomUUID()})).error?.code).toBe("42501");
   expect((await harness.anonymous.schema("erp").rpc("get_grouped_review_delivery_envelope",{notification_id:notificationId})).error?.code).toBe("42501");return;
  }
  if(mode==="VERIFY_SCHEDULER_CRON"||mode==="VERIFY_NOTIFICATION_CRON"||mode==="VERIFY_POST_SEND_REPLAY"||mode==="VERIFY_KILL_SWITCH"){
   const state=value(`SELECT jsonb_build_object('automation',(SELECT count(*) FROM erp.grouped_review_scheduler_configurations WHERE company_id='${tenant}' AND automation_enabled),'batches',(SELECT count(*) FROM erp.customer_review_batches WHERE company_id='${tenant}'),'items',(SELECT count(*) FROM erp.customer_review_batch_items WHERE company_id='${tenant}'),'requests',(SELECT count(*) FROM erp.customer_review_requests WHERE company_id='${tenant}'),'grouped',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type='CUSTOMER_GROUPED_REVIEW_REQUESTED'),'individual',(SELECT count(*) FROM erp.notification_outbox WHERE company_id='${tenant}' AND notification_type IN('CUSTOMER_REVIEW_REQUESTED','CUSTOMER_CORRECTED_REVIEW_REQUESTED')),'attempts',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}'),'accepted',(SELECT count(*) FROM erp.notification_delivery_attempts WHERE company_id='${tenant}' AND status='ProviderAccepted'),'activeEnvelopes',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}' AND e.retired_at IS NULL),'retiredEnvelopes',(SELECT count(*) FROM erp.notification_delivery_envelopes e JOIN erp.notification_outbox n ON n.id=e.notification_id WHERE n.company_id='${tenant}' AND e.retired_at IS NOT NULL AND e.ciphertext IS NULL AND e.nonce IS NULL AND e.auth_tag IS NULL),'systemAudit',(SELECT count(*) FROM erp.audit_log WHERE company_id='${tenant}' AND new_values->>'actorType'='SYSTEM' AND new_values->>'principalType'='GROUPED_REVIEW_SCHEDULER'),'staleClaims',(SELECT count(*) FROM erp.daily_grouped_review_scheduler_groups WHERE company_id='${tenant}' AND status='CLAIMED' AND claim_expires_at<clock_timestamp()));`);
   if(mode==="VERIFY_SCHEDULER_CRON")expect(state).toMatchObject({automation:1,batches:1,items:1,requests:1,grouped:1,individual:0,attempts:0,activeEnvelopes:1,systemAudit:1,staleClaims:0});
   else expect(state).toMatchObject({batches:1,items:1,requests:1,grouped:1,individual:0,attempts:1,accepted:1,activeEnvelopes:0,retiredEnvelopes:1,staleClaims:0});
   if(mode==="VERIFY_NOTIFICATION_CRON"){const messageId=String(value(`SELECT jsonb_build_object('id',(SELECT provider_message_id FROM erp.notification_delivery_attempts WHERE company_id='${tenant}' AND status='ProviderAccepted' LIMIT 1));`).id??"");expect(messageId).toBeTruthy();const response=await fetch(`https://api.resend.com/emails/${encodeURIComponent(messageId)}`,{headers:{Authorization:`Bearer ${process.env.RESEND_READBACK_API_KEY?.trim()}`}});expect(response.status).toBe(200);const message=await response.json() as{id?:string;to?:string[];from?:string;subject?:string;html?:string;text?:string};expect(message.id).toBe(messageId);expect(message.to).toContain(controlled);expect(message.from).toContain(notification.fromAddress);expect(message.subject).toMatch(/grouped|DEUR|review/i);expect(message.html).toBeTruthy();expect(message.text).toBeTruthy();expect(`${message.html}${message.text}`).toMatch(/REVIEW/i);}
   return;
  }
  if(mode==="DISABLE_AUTOMATION"){const client=await signIn();const result=await client.schema("erp").rpc("command_configure_grouped_review_scheduler",{command:{commandId:randomUUID(),idempotencyKey:"cloudflare-cron-disable",automationEnabled:false,localSendTime:"00:00",graceMinutes:15}});expect(result.error).toBeNull();expect(result.data).toMatchObject({success:true,value:{automationEnabled:false,schedulerReady:true}});return;}
  if(mode==="FINAL_CLEANUP"){const first=cleanup(),id=authId();expect(Object.values(first).some(x=>Number(x)>0)||Boolean(id)).toBe(true);if(id)expect((await harness.admin.auth.admin.deleteUser(id)).error).toBeNull();expect(Object.values(cleanup()).every(x=>x===0)).toBe(true);return;}
  throw new Error(`Unsupported C12_CLOUDFLARE_CRON_MODE: ${mode}`);
 });
});
