import { randomBytes,randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { describe,expect,it } from "vitest";
import { assertSupabaseFixtureMutationAllowed,createSupabasePhaseC2Harness,readSupabasePhaseC2TestConfiguration } from "./support/supabasePhaseC2Harness";
import { executePhaseC4bPrivilegedSql } from "./support/phaseC4bPrivilegedSql";
const configuration=readSupabasePhaseC2TestConfiguration();
const enabled=configuration.enabled&&process.env.RUN_PHASE_C12_DEUR_COMPLETION_LIVE==="true";
const tenant="TENANT-UAT-C12-CUSTOMER-EMAIL-001";
const id={operator:"OPR-UAT-C12-CUSTOMER-EMAIL-001",customer:"CUST-UAT-C12-CUSTOMER-EMAIL-001",project:"PRJ-UAT-C12-CUSTOMER-EMAIL-001",equipment:"EQP-UAT-C12-CUSTOMER-EMAIL-001",assignment:"ASN-UAT-C12-CUSTOMER-EMAIL-001",rental:"RENT-UAT-C12-CUSTOMER-EMAIL-001",line:"LINE-UAT-C12-CUSTOMER-EMAIL-001",snapshot:"SNAP-UAT-C12-CUSTOMER-EMAIL-001",deur:"DEUR-UAT-C12-CUSTOMER-EMAIL-001"};
const quote=(value:string)=>`'${value.replaceAll("'","''")}'`;
describe.skipIf(!enabled)("C12 complete-shift live identity diagnosis",()=>{
 it("reproduces incomplete-scope NOT_FOUND and completes with the full canonical identity",async()=>{
  assertSupabaseFixtureMutationAllowed(configuration,[tenant]);expect(process.env.VITE_REMOTE_OPERATIONAL_WRITES_ENABLED).toBe("false");
  const harness=createSupabasePhaseC2Harness(configuration);const owner=(sql:string)=>executePhaseC4bPrivilegedSql(configuration,{tenantIds:[tenant],sql});
  const cleanup=()=>owner(`SELECT erp.cleanup_c12_customer_email_certification_fixture('${tenant}','${tenant}','CONFIRM-C12-CUSTOMER-EMAIL-CLEANUP');`);
  const password=`C12-${randomBytes(24).toString("base64url")}`,email=`c12-complete-${randomUUID()}@example.invalid`;let userId="";
  try{
   const created=await harness.admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{fixtureTenant:tenant}});if(created.error||!created.data.user)throw created.error??new Error("Auth fixture failed");userId=created.data.user.id;
   owner(`BEGIN;
    INSERT INTO erp.companies(id,code,name,environment_class) VALUES('${tenant}','${tenant}','C12 Completion Diagnostic','test');
    INSERT INTO erp.operators(id,name,status,company_id) VALUES('${id.operator}','Diagnostic Operator','Active','${tenant}');
    INSERT INTO erp.users(id,username,display_name,status,operator_id,company_id) VALUES('${userId}'::uuid,${quote(email)},'Diagnostic Operator','active','${id.operator}','${tenant}');
    INSERT INTO erp.user_roles(user_id,role_id) SELECT '${userId}'::uuid,id FROM erp.app_roles WHERE code='rental-operations';
    INSERT INTO erp.customers(id,customer_code,name,company_id) VALUES('${id.customer}','C12-COMPLETE','Diagnostic Customer','${tenant}');
    INSERT INTO erp.projects(id,project_code,name,customer_id,company_id) VALUES('${id.project}','C12-COMPLETE','Diagnostic Project','${id.customer}','${tenant}');
    INSERT INTO erp.equipment(id,asset_no,equipment_name,maintenance_type,company_id) VALUES('${id.equipment}','C12-COMPLETE','Diagnostic Equipment','None','${tenant}');
    INSERT INTO erp.assignments(id,equipment_id,operator_id,project_id,assigned_date,expected_return,status,company_id) VALUES('${id.assignment}','${id.equipment}','${id.operator}','${id.project}',current_date,current_date+1,'Active','${tenant}');
    INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,rental_type,status,company_id) VALUES('${id.rental}','C12-COMPLETE','${id.customer}','${id.project}','Diagnostic Customer','Diagnostic Project',current_date,'Operated Rental','Released','${tenant}');
    INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,operational_metadata,commercial_snapshot_required,company_id) VALUES('${id.line}','${id.rental}','${id.equipment}','${id.assignment}','${id.operator}','Released',jsonb_build_object('costCode',jsonb_build_object('code','C12-COST'),'activityCode',jsonb_build_object('code','C12-ACT'),'deurExpectationSnapshot',jsonb_build_object('rentalEquipmentLineId','${id.line}','rentalId','${id.rental}','equipmentId','${id.equipment}','assignmentId','${id.assignment}','operatorId','${id.operator}','projectId','${id.project}','customerId','${id.customer}','policy',jsonb_build_object('frequency','ON_DEMAND'),'shiftWindows','[]'::jsonb,'workDescription',jsonb_build_object('id','WORK-C12','code','C12-WORK','name','Diagnostic work','requiresRemarks',false),'workDateRule','RENTAL_DATE_OUT','workDate',current_date::text,'meterRequirement','none','fuelEvidenceRequired',false,'billingMethod','Per Hour','operationalMetadata',jsonb_build_object('costCode',jsonb_build_object('code','C12-COST'),'activityCode',jsonb_build_object('code','C12-ACT')),'sourceFingerprint','PENDING')),true,'${tenant}');
    INSERT INTO erp.commercial_snapshots(id,rental_id,rental_equipment_line_id,billing_method,unit_rate,operator_included,currency,captured_at) VALUES('${id.snapshot}','${id.rental}','${id.line}','Per Hour',100,true,'PHP',clock_timestamp());
    UPDATE erp.rental_equipment_lines SET operational_metadata=jsonb_set(operational_metadata,'{deurExpectationSnapshot,sourceFingerprint}',to_jsonb(erp.current_deur_expectation_fingerprint(id)),true) WHERE id='${id.line}';COMMIT;`);
   const actor=createClient(configuration.url!,configuration.publishableKey!,{auth:{persistSession:false,autoRefreshToken:false,storageKey:`c12-complete-${randomUUID()}`}});const login=await actor.auth.signInWithPassword({email,password});if(login.error)throw login.error;
   const base={rentalId:id.rental,rentalLineId:id.line,equipmentId:id.equipment,assignmentId:id.assignment,operatorId:id.operator,deviceId:"C12-COMPLETE"};
   const start=await actor.schema("erp").rpc("command_start_deur_shift",{command:{...base,commandId:randomUUID(),idempotencyKey:randomUUID(),draft:{id:id.deur,shift:"Day"}}});expect(start.error).toBeNull();expect(start.data).toMatchObject({success:true,disposition:"ACCEPTED",version:1});
   const trace=JSON.parse(owner(`SELECT jsonb_build_object('count',(SELECT count(*) FROM erp.deurs WHERE id='${id.deur}'),'company',(SELECT company_id FROM erp.deurs WHERE id='${id.deur}'),'rental',(SELECT rental_id FROM erp.deurs WHERE id='${id.deur}'),'line',(SELECT rental_equipment_line_id FROM erp.deurs WHERE id='${id.deur}'),'assignment',(SELECT assignment_id FROM erp.deurs WHERE id='${id.deur}'),'equipment',(SELECT equipment_id FROM erp.deurs WHERE id='${id.deur}'),'operator',(SELECT operator_id FROM erp.deurs WHERE id='${id.deur}'),'status',(SELECT status FROM erp.deurs WHERE id='${id.deur}'),'version',(SELECT row_version FROM erp.deurs WHERE id='${id.deur}'),'events',(SELECT count(*) FROM erp.deur_events WHERE deur_id='${id.deur}'));`)).rows[0].jsonb_build_object;expect(trace).toMatchObject({count:1,company:tenant,rental:id.rental,line:id.line,assignment:id.assignment,equipment:id.equipment,operator:id.operator,status:"In Progress",version:1,events:2});
   const incomplete=await actor.schema("erp").rpc("command_complete_deur_shift",{command:{commandId:randomUUID(),idempotencyKey:randomUUID(),deurId:id.deur,rentalLineId:id.line,operatorId:id.operator,expectedVersion:1,meterRequirement:"none"}});expect(incomplete.error).toBeNull();expect(incomplete.data).toMatchObject({success:false,code:"NOT_FOUND"});
   const wrongLine=await actor.schema("erp").rpc("command_complete_deur_shift",{command:{...base,rentalLineId:"LINE-NOT-PRESENT",commandId:randomUUID(),idempotencyKey:randomUUID(),deurId:id.deur,expectedVersion:1,meterRequirement:"none"}});expect(wrongLine.data).toMatchObject({success:false,code:"NOT_FOUND"});
   const wrongOperator=await actor.schema("erp").rpc("command_complete_deur_shift",{command:{...base,operatorId:"OPERATOR-NOT-OWNED",commandId:randomUUID(),idempotencyKey:randomUUID(),deurId:id.deur,expectedVersion:1,meterRequirement:"none"}});expect(wrongOperator.data).toMatchObject({success:false,code:"OWNERSHIP_MISMATCH"});
   const stale=await actor.schema("erp").rpc("command_complete_deur_shift",{command:{...base,commandId:randomUUID(),idempotencyKey:randomUUID(),deurId:id.deur,expectedVersion:0,meterRequirement:"none"}});expect(stale.data).toMatchObject({success:false,code:"CONFLICT",currentVersion:1});
   const command={...base,commandId:randomUUID(),idempotencyKey:randomUUID(),deurId:id.deur,expectedVersion:1,meterRequirement:"none"};const complete=await actor.schema("erp").rpc("command_complete_deur_shift",{command});expect(complete.error).toBeNull();expect(complete.data).toMatchObject({success:true,disposition:"ACCEPTED"});const replay=await actor.schema("erp").rpc("command_complete_deur_shift",{command:{...command,commandId:randomUUID()}});expect(replay.data).toMatchObject({success:true,disposition:"REPLAYED"});
   const final=JSON.parse(owner(`SELECT jsonb_build_object('deurs',(SELECT count(*) FROM erp.deurs WHERE company_id='${tenant}'),'shiftEnds',(SELECT count(*) FROM erp.deur_events WHERE deur_id='${id.deur}' AND activity_type='shift' AND action='end'),'sequences',(SELECT jsonb_agg(sequence ORDER BY sequence) FROM erp.deur_events WHERE deur_id='${id.deur}'),'openEvents',(SELECT count(*) FROM erp.deur_events WHERE deur_id='${id.deur}' AND is_open));`)).rows[0].jsonb_build_object;expect(final).toMatchObject({deurs:1,shiftEnds:1,openEvents:0});expect(final.sequences).toEqual([1,2,3,4]);await actor.auth.signOut();
  }finally{try{cleanup();}catch{}if(userId){const removed=await harness.admin.auth.admin.deleteUser(userId);if(removed.error)throw removed.error;}cleanup();}
 },120_000);
});
