import { beforeEach, describe, expect, it } from "vitest";
import { DEUR_FREQUENCY_GUIDANCE, EXPECTED_RETURN_GUIDANCE, RENTAL_TYPE_GUIDANCE } from "@/features/rental/components/RentalForm";
import { configureBulkRentalCommercialTerms, type RentalCommercialTermsInput } from "@/features/rental/services/configureRentalCommercialTerms";
import type { RentalRecord } from "@/features/rental/types";
import type { RentalEquipmentLine } from "@/features/rental/equipment-line";
import { IdleReasonRepository } from "@/features/masters/idle-reason/repository";
import { EquipmentSubcategoryRepository, suggestSubcategoryAssetNumber } from "@/features/masters/equipment-subcategory/repository";
import { LocalEquipmentRepository } from "@/features/equipment/repository/LocalEquipmentRepository";
import { getAssignmentDisplayName } from "@/features/assignment/utils/assignmentDisplay";
import { readFileSync } from "node:fs";
import { billingWorkspaceHref, parseWorkspaceTab } from "@/features/rental/workspace/routing";
import { presentEquipmentStatus } from "@/features/equipment/utils/equipmentStatusPresentation";
import { validateEquipmentAssignment } from "@/features/assignment/utils/assignmentValidation";
import { operatorEditHref } from "@/features/operators/routing";
import { projectActiveRentalEngagements } from "@/features/rental/services/projectActiveRentalEngagements";
import { applyDigitalDeurOperatorAction } from "@/features/rental/deur/operator/applyDigitalDeurOperatorAction";
import { reviewTimelineForDeur } from "@/features/rental/customer-review/buildCustomerReviewSnapshot";
import { buildPublicReviewIntervals } from "@/features/rental/customer-review/buildPublicReviewIntervals";

const now="2026-08-10T00:00:00.000Z";
const rental:RentalRecord={id:"rental",rentalNumber:"R-1",equipmentId:"",customerId:"customer",projectId:"project",customer:"Customer",project:"Project",rentedBy:"",dateOut:"2026-08-10",rentalType:"Operated Rental",statusId:"draft",status:"Draft"};
const line=(id:string,status:RentalEquipmentLine["status"]="Draft"):RentalEquipmentLine=>({id,rentalId:rental.id,equipmentId:`equipment-${id}`,assignmentId:`assignment-${id}`,operatorId:`operator-${id}`,status,commercialSnapshotRequired:true,createdAt:now,updatedAt:now});
const terms:RentalCommercialTermsInput={billingMethod:"Per Hour",currency:"PHP",unitRate:100,minimumBillableHours:8,overtimeRate:125,standbyRate:50,mobilizationFee:500,demobilizationFee:500,fuelCharge:100,operatorIncluded:true,taxRate:12,withholdingTax:2,transactionRelationship:"Non-Affiliate",vatApplicability:"Applicable"};

describe("Phase C13.2 rental creation and commercial authority",()=>{
  it("removes redundant header billing UI and provides persistent canonical guidance",()=>{const source=readFileSync("src/features/rental/components/RentalForm.tsx","utf8");expect(source).not.toContain('label="Billing Method"');expect(source).toContain('label="Expected Return (Optional)"');expect(EXPECTED_RETURN_GUIDANCE).toContain("open-ended rental");expect(RENTAL_TYPE_GUIDANCE["Operated Rental"]).toContain("Digital DEUR");expect(DEUR_FREQUENCY_GUIDANCE.PER_WORKDAY).toContain("each equipment item for each work date");expect(DEUR_FREQUENCY_GUIDANCE.PER_SHIFT).toContain("separate DEUR");expect(DEUR_FREQUENCY_GUIDANCE.ON_DEMAND).toContain("irregular")});
  it("validates every selected line before returning any bulk contracts",()=>{const good=configureBulkRentalCommercialTerms({rental,lines:[line("a"),line("b")],commercialTerms:terms,existingContracts:[],timestamp:now});expect(good.success&&good.contracts.map(c=>c.billingMethod)).toEqual(["Per Hour","Per Hour"]);const frozen:RentalEquipmentLine={...line("b"),commercialSnapshot:{billingMethod:"Per Day",unitRate:1,operatorIncluded:true,currency:"PHP",capturedAt:now}};const blocked=configureBulkRentalCommercialTerms({rental,lines:[line("a"),frozen],commercialTerms:terms,existingContracts:[],timestamp:now});expect(blocked).toMatchObject({success:false,lineId:"b",code:"COMMERCIAL_TERMS_READ_ONLY"})});
  it("continues to support different line billing methods through individual configuration",()=>{const hourly=configureBulkRentalCommercialTerms({rental,lines:[line("a")],commercialTerms:terms,existingContracts:[],timestamp:now});const daily=configureBulkRentalCommercialTerms({rental,lines:[line("b")],commercialTerms:{...terms,billingMethod:"Per Day"},existingContracts:[],timestamp:now});expect(hourly.success&&hourly.contracts[0].billingMethod).toBe("Per Hour");expect(daily.success&&daily.contracts[0].billingMethod).toBe("Per Day")});
});

describe("Phase C13.2 operational masters and equipment classification",()=>{beforeEach(()=>localStorage.clear());
  it("presents persisted statuses and preserves exact Billing navigation identity",()=>{expect(presentEquipmentStatus("Assigned")).toBe("Booked");expect(presentEquipmentStatus("Rented")).toBe("Deployed");expect(validateEquipmentAssignment({status:"Rented"} as never)).toMatchObject({valid:false,message:expect.stringContaining("deployed")});expect(billingWorkspaceHref("rental 1","statement-2")).toBe("/rentals/rental%201/workspace?tab=billing&billingStatementId=statement-2");expect(parseWorkspaceTab("billing")).toBe("billing");expect(parseWorkspaceTab("unknown")).toBe("overview")});
  it.each(["operator-1","operator-2","operator-3","operator-4"])("preserves exact Operator identity for %s",(id)=>expect(operatorEditHref(id)).toBe(`/operators/edit/${id}`));
  it("groups active and financially-open Rentals without collapsing Rental or line identity",()=>{const rentals=[{...rental,id:"r1",customerId:"c1",projectId:"p1",status:"Active" as const},{...rental,id:"r2",customerId:"c1",projectId:"p1",status:"Returned" as const},{...rental,id:"r3",customerId:"c1",projectId:"p2",status:"Reserved" as const},{...rental,id:"r4",customerId:"c1",projectId:"p1",status:"Closed" as const}];const lines=[{...line("l1","Active"),rentalId:"r1"},{...line("l2","Returned"),rentalId:"r2"},{...line("l3","Reserved"),rentalId:"r3"},{...line("l4","Closed"),rentalId:"r4"}];const groups=projectActiveRentalEngagements({rentals,lines});expect(groups).toHaveLength(2);const first=groups.find(item=>item.projectId==="p1")!;expect(first.rentals.map(item=>item.id)).toEqual(["r1","r2"]);expect(first.lines.map(item=>item.id)).toEqual(["l1","l2"]);expect(first.returnedFinanciallyOpenCount).toBe(1);expect(first.rentals.some(item=>item.id==="r4")).toBe(false)});
  it("seeds, searches, creates, edits, and deactivates idle reasons without losing historical identity",()=>{const repo=new IdleReasonRepository();expect(repo.getActive().some(r=>r.name==="Other"&&r.requiresRemarks)).toBe(true);const created=repo.save({id:"idle-custom",code:"SITE",name:"Site delay",active:true,sortOrder:5,createdAt:now,updatedAt:now});expect(created.success).toBe(true);expect(repo.search("site").some(record=>record.id==="idle-custom")).toBe(true);if(!created.success)throw new Error(created.message);expect(repo.save({...created.record,name:"Site access delay",active:false}).success).toBe(true);expect(repo.getById("idle-custom")?.name).toBe("Site access delay");expect(repo.getActive().some(r=>r.id==="idle-custom")).toBe(false)});
  it("requires and freezes provider-neutral Idle Reason evidence",()=>{const deur:any={id:"d",rentalId:"r",rentalEquipmentLineId:"l",assignmentId:"a",equipmentId:"e",operatorId:"o",creationSource:"OPERATOR_DIGITAL",workDate:"2026-08-10",status:"Draft",legacy:false,events:[],logs:[],totalOperatingMinutes:0,totalIdleMinutes:0,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,createdAt:now,updatedAt:now};expect(applyDigitalDeurOperatorAction({deur,action:"START_IDLE",actionTimestamp:"2026-08-10T01:00:00Z",actor:{name:"Operator"}})).toMatchObject({success:false,code:"DEUR_IDLE_REASON_REQUIRED"});const result=applyDigitalDeurOperatorAction({deur,action:"START_IDLE",actionTimestamp:"2026-08-10T01:00:00Z",actor:{name:"Operator"},idleReason:{id:"waiting",labelSnapshot:"Waiting for materials",remarks:"Supplier delayed"}});expect(result.success&&result.record.events?.find((event:any)=>event.activityType==="idle"&&event.action==="start")).toMatchObject({idleReasonId:"waiting",idleReasonLabelSnapshot:"Waiting for materials",idleReasonRemarks:"Supplier delayed"});if(result.success){const next=applyDigitalDeurOperatorAction({deur:result.record,action:"START_OPERATION",actionTimestamp:"2026-08-10T02:00:00Z",actor:{name:"Operator"}});expect(next.success&&next.record.events?.find((event:any)=>event.activityType==="idle"&&event.action==="start")?.idleReasonLabelSnapshot).toBe("Waiting for materials")}});
  it("projects frozen Idle Reason evidence through operator, customer, and manager timeline contracts",()=>{const deur:any={id:"d",rentalId:"r",rentalEquipmentLineId:"line-a",assignmentId:"a",equipmentId:"e",operatorId:"o",creationSource:"OPERATOR_DIGITAL",workDate:"2026-08-10",status:"Draft",legacy:false,events:[{id:"s",activityType:"idle",action:"start",timestamp:"2026-08-10T23:30:00Z",sequence:1,source:"user",idleReasonId:"idle-reason-2",idleReasonLabelSnapshot:"Waiting for materials",idleReasonRemarks:"Delivery truck delayed"},{id:"e",activityType:"idle",action:"end",timestamp:"2026-08-11T00:15:00Z",sequence:2,source:"user"}],logs:[],totalOperatingMinutes:0,totalIdleMinutes:45,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,createdAt:now,updatedAt:now};const timeline=reviewTimelineForDeur(deur);expect(timeline[0]).toMatchObject({activityType:"Idle",idleReasonLabel:"Waiting for materials",remarks:"Delivery truck delayed",durationMinutes:45});const intervals=buildPublicReviewIntervals([{activity:"Idle",action:"start",occurredAt:timeline[0].start,sequence:1,idleReasonLabel:timeline[0].idleReasonLabel,remarks:timeline[0].remarks},{activity:"Idle",action:"end",occurredAt:timeline[0].end,sequence:2}]);expect(intervals[0]).toMatchObject({idleReasonLabel:"Waiting for materials",remarks:"Delivery truck delayed",durationSeconds:2700});for(const page of ["src/pages/OperatorDeur/index.tsx","src/pages/CustomerDeurReview/index.tsx","src/pages/ManagerDeurReview/index.tsx"])expect(readFileSync(page,"utf8")).toContain("idleReasonLabel")});
  it("presents one explicit commercial state and protects frozen lines from bulk selection",()=>{const source=readFileSync("src/pages/Rental/CommercialTerms.tsx","utf8");for(const label of ["Commercial Terms Required","✓ Configured","🔒 Frozen","Billing Method:","Frozen lines are excluded from bulk updates.","Commercial Terms are frozen after reservation preparation."])expect(source).toContain(label);expect(source.match(/<h2 className="font-semibold">Bulk Commercial Terms<\/h2>/g)).toHaveLength(1);expect(source).toContain("disabled={frozen}");expect(source).toContain("checked={!frozen&&bulkLineIds.includes(line.id)}")});
  it("keeps sub-categories under one category and hides inactive values from new selection",()=>{const repo=new EquipmentSubcategoryRepository();const saved=repo.save({id:"dump",categoryId:"moving",name:"Dump Truck",code:"DT",assetPrefix:"dt",active:true,createdAt:now,updatedAt:now});expect(saved.success&&saved.record.assetPrefix).toBe("DT");expect(repo.listByCategory("moving")).toHaveLength(1);if(saved.success)repo.save({...saved.record,active:false});expect(repo.listByCategory("moving")).toHaveLength(0);expect(repo.listByCategory("moving",{includeInactive:true})[0].name).toBe("Dump Truck")});
  it("suggests sub-category numbering, permits user assignment, and rejects case-insensitive duplicates in the repository",()=>{expect(suggestSubcategoryAssetNumber("DT",[{assetNo:"DT-000002"}])).toBe("DT-000003");const repo=new LocalEquipmentRepository();const equipment={id:"e1",prefixId:"",assetNo:"Custom-01",equipmentName:"Truck",category:"Moving Equipment" as const,status:"Available" as const,maintenanceType:"Engine Hours" as const,currentReading:0,projectId:"",operatorId:""};repo.create(equipment);expect(()=>repo.create({...equipment,id:"e2",assetNo:"custom-01"})).toThrow("Asset Number already exists")});
  it("builds a human-readable assignment label without exposing canonical identity as fallback",()=>{const assignment={id:"assignment-1",equipmentId:"e",operatorId:"o",projectId:"p",assignedDate:"2026-08-10",expectedReturn:"",remarks:"",status:"Active" as const};expect(getAssignmentDisplayName({assignment,equipment:{id:"e",prefixId:"",assetNo:"DT-1",equipmentName:"Dump Truck",category:"Moving Equipment",status:"Assigned",maintenanceType:"Engine Hours",currentReading:0,projectId:"p",operatorId:"o"},operator:{id:"o",name:"Operator One",email:"",licenseNumber:"",certificationType:"None",status:"Active",joinedDate:""},project:{id:"p",projectCode:"P",projectName:"Project Alpha",location:"",projectManager:"",status:"Active"}})).toContain("Project Alpha — DT-1 - Dump Truck — Operator One");expect(getAssignmentDisplayName({assignment})).toBe("Assignment details unavailable")});
});
