import{describe,expect,it,vi}from"vitest";
import{SupabaseTrustedNotificationRepository}from"../server/notifications/SupabaseTrustedNotificationRepository";

const client=(responses:Record<string,unknown>)=>{const rpc=vi.fn(async(name:string)=>({data:responses[name],error:null}));return{client:{schema:vi.fn(()=>({rpc}))}as any,rpc};};

describe("C12.2.7E.1 notification public-review client boundary",()=>{
 it("uses only the explicit public client for grouped credential projection",async()=>{const authenticated=client({}),service=client({}),publicReview=client({get_customer_review_batch:{success:true,value:{}}});const repository=new SupabaseTrustedNotificationRepository(authenticated.client,service.client,undefined,publicReview.client);vi.spyOn(repository,"getGroupedReviewPath").mockResolvedValue(`/review/customer/grouped/${"a".repeat(64)}`);expect(await repository.resolveGroupedReviewDelivery("00000000-0000-4000-8000-000000000001")).toMatchObject({status:"ACTIVE"});expect(publicReview.rpc).toHaveBeenCalledWith("get_customer_review_batch",expect.anything());expect(service.rpc).not.toHaveBeenCalled();expect(authenticated.rpc).not.toHaveBeenCalled();});
 it("fails closed instead of falling back to a trusted client",async()=>{const authenticated=client({}),service=client({});const repository=new SupabaseTrustedNotificationRepository(authenticated.client,service.client);vi.spyOn(repository,"getGroupedReviewPath").mockResolvedValue(`/review/customer/grouped/${"b".repeat(64)}`);await expect(repository.resolveGroupedReviewDelivery("00000000-0000-4000-8000-000000000002")).rejects.toThrow(/Public review client/);expect(authenticated.rpc).not.toHaveBeenCalled();expect(service.rpc).not.toHaveBeenCalled();});
 it("keeps trusted notification reads on the service client",async()=>{const authenticated=client({}),service=client({get_notification_delivery_intent:{success:true,value:{id:"notification"}}}),publicReview=client({});const repository=new SupabaseTrustedNotificationRepository(authenticated.client,service.client,undefined,publicReview.client);expect(await repository.getIntent("notification")).toMatchObject({id:"notification"});expect(service.rpc).toHaveBeenCalledWith("get_notification_delivery_intent",expect.anything());expect(publicReview.rpc).not.toHaveBeenCalled();});
});
