import {describe,expect,it} from "vitest";
import {composeCustomReport,loadReportPreview,paginateReportBlocks,saveReportPreview,type ReportBlock} from "@/features/reports/services/reportComposition";
import type {CustomReportSection} from "@/features/reports/services/customReportWorkspace";
import {readFileSync} from "node:fs";

const rows=Array.from({length:40},(_,index)=>[`R-${index+1}`,`ME-${index+1}`,"Active"]);
const section=(id:string,title:string):CustomReportSection=>({id,fingerprint:id,type:"rentals",addedAt:"2026-08-15T00:00:00.000Z",config:{type:"rentals",groupBy:"none",period:{startDate:"2026-08-01",endDate:"2026-08-15",comparisonStartDate:"2026-07-17",comparisonEndDate:"2026-07-31",label:"Aug 1-15"}},report:{title,period:"Aug 1-15, 2026",filters:[],columns:["Rental","Asset","Status"],rows,metrics:[{label:"Active Rentals",value:40,numericValue:40,previousValue:35,variance:5,variancePercent:14.29}],groupBy:"none"}});

describe("Phase 2G shared report composition",()=>{
 it("preserves authoritative section order in both modes",()=>{const sections=[section("a","Rental"),section("b","Revenue")];for(const mode of ["executive","technical"] as const){const report=composeCustomReport("Monthly Review",sections,mode);expect(report.sections.map(x=>x.id)).toEqual(["a","b"]);expect(report.sections[0].report.rows).toBe(sections[0].report.rows)}});
 it("adds an executive summary and minimizes detailed rows",()=>{const report=composeCustomReport("Review",[section("a","Rental")],"executive");expect(report.blocks[0].kind).toBe("executive-summary");expect(report.blocks.find(x=>x.kind==="summary-table")?.rows).toHaveLength(5);expect(report.blocks.some(x=>x.kind==="detail-table")).toBe(false)});
 it("keeps identifiers and every detailed row in technical mode",()=>{const report=composeCustomReport("Review",[section("a","Rental")],"technical"),table=report.blocks.find(x=>x.kind==="detail-table");expect(table?.columns).toEqual(["Rental","Asset","Status"]);expect(table?.rows).toHaveLength(40)});
 it("places compatible small blocks on one page instead of breaking per section",()=>{const blocks:ReportBlock[]=["one","two","three"].map(id=>({id,kind:"kpi-grid",title:id,keepTogether:true,estimatedHeight:120}));expect(paginateReportBlocks(blocks,500)).toHaveLength(1)});
 it("moves a keep-together block to the next page when it cannot fit",()=>{const blocks:ReportBlock[]=[{id:"one",kind:"comparison-chart",title:"one",keepTogether:true,estimatedHeight:350},{id:"two",kind:"comparison-chart",title:"two",keepTogether:true,estimatedHeight:200}];expect(paginateReportBlocks(blocks,500).map(x=>x.blockIds)).toEqual([["one"],["two"]])});
 it("retains an isolated session snapshot when navigating between builder and preview",()=>{const original=[section("a","Rental")];saveReportPreview("Monthly Review",original);original[0].report.title="Changed outside";expect(loadReportPreview()).toMatchObject({name:"Monthly Review",sections:[{report:{title:"Rental"}}]})});
 it("exposes continuous preview controls and PDF export from one composition",()=>{const source=readFileSync("src/features/reports/components/CustomReportPreview.tsx","utf8");expect(source).toContain('useState<ReportViewMode>("continuous")');expect(source).toContain("Fit Width");expect(source).toContain("Executive Review");expect(source).toContain("Technical Review");expect(source).toContain("Export PDF");expect(source).toContain("composeCustomReport")});
 it("uses conditional pagination, repeated table headers, and total page numbers",()=>{const source=readFileSync("src/features/reports/services/customReportPdfExport.ts","utf8");expect(source).not.toMatch(/for\s*\([^)]*sections[^)]*\)\s*\{\s*pdf\.addPage/);expect(source).toContain("header()");expect(source).toContain("Page ${page} of ${total}")});
});
