import{readFileSync}from"node:fs";import{randomBytes}from"node:crypto";import{describe,expect,it,vi}from"vitest";
import worker from"../worker/index";import{parseWorkerConfiguration,selectScheduledJob,type GroupedReviewWorkerEnvironment}from"../worker/configuration";
import{runScheduledJob,type SafeRuntimeLogger,type ScheduledRuntimeDependencies}from"../worker/runtime";
const secretValues={service:"service-secret-synthetic",resend:"resend-secret-synthetic",key:randomBytes(32).toString("base64")};
const env=():GroupedReviewWorkerEnvironment=>({ASSETS:{fetch:vi.fn(async()=>new Response("spa"))},SUPABASE_URL:"https://uat.example.supabase.co",SUPABASE_SERVICE_ROLE_KEY:secretValues.service,SUPABASE_PUBLISHABLE_KEY:"sb_publishable_synthetic_public_key",RESEND_API_KEY:secretValues.resend,EMAIL_UAT_RECIPIENT_OVERRIDE:"controlled@example.test",GROUPED_REVIEW_DELIVERY_ENCRYPTION_KEY_V1:secretValues.key,REVIEW_PUBLIC_BASE_URL:"https://uat.example.test",RESEND_FROM_ADDRESS:"reviews@example.test",SCHEDULER_JOB_CRON:"scheduler-test",NOTIFICATION_JOB_CRON:"notification-test",NOTIFICATION_WORKER_BATCH_LIMIT:"5"});
const dependencies=():ScheduledRuntimeDependencies=>({runScheduler:vi.fn(async command=>({batchLimit:command.batchLimit,groupsClaimed:0,groupsProcessed:0,groupsEvaluated:0,groupsActionable:0,groupsPrepared:0,groupsReplayed:0,groupsNoActionable:0,groupsFailed:0,notificationsPrepared:0,hasMore:false,failureCodes:[]})),runNotificationWorker:vi.fn(async()=>({claimed:0,providerCalls:0}))});
describe("C12.2.7B Cloudflare scheduled runtime",()=>{
 it("preserves assets and exposes no public scheduler endpoint",async()=>{const e=env();expect((await worker.fetch(new Request("https://app.example/review/customer/grouped/test"),e)).status).toBe(200);expect(e.ASSETS.fetch).toHaveBeenCalledOnce();const source=readFileSync("worker/index.ts","utf8");expect(source).not.toMatch(/\/cron|\/run-scheduler|\/internal\/scheduler/);});
 it("selects only explicitly bound future jobs",()=>{const e=env();expect(selectScheduledJob("scheduler-test",e)).toBe("DAILY_GROUPED_REVIEW_SCHEDULER");expect(selectScheduledJob("notification-test",e)).toBe("NOTIFICATION_RETRY_WORKER");expect(()=>selectScheduledJob("unknown",e)).toThrow(/does not match/);});
 it("passes only run identity, runAt and a bound to scheduler",async()=>{const d=dependencies(),e=env();e.SCHEDULER_BATCH_LIMIT="1";await runScheduledJob("DAILY_GROUPED_REVIEW_SCHEDULER",Date.UTC(2026,7,11,9,30),e,d,{log:vi.fn()});expect(d.runScheduler).toHaveBeenCalledTimes(1);expect(d.runScheduler).toHaveBeenCalledWith(expect.objectContaining({commandId:expect.any(String),idempotencyKey:expect.stringMatching(/^cloudflare:/),runAt:"2026-08-11T09:30:00.000Z",batchLimit:1}));expect(JSON.stringify((d.runScheduler as any).mock.calls)).not.toMatch(/tenant|rental|customer|deur|sendTime/i);});
 it("dispatches bounded notification work through injected worker",async()=>{const d=dependencies();const result=await runScheduledJob("NOTIFICATION_RETRY_WORKER",0,env(),d,{log:vi.fn()});expect(d.runNotificationWorker).toHaveBeenCalledWith(expect.any(String));expect(result.result).toEqual({claimed:0,providerCalls:0});});
 it("fails closed for missing job secrets",()=>{const scheduler=env();delete scheduler.SUPABASE_SERVICE_ROLE_KEY;expect(()=>parseWorkerConfiguration(scheduler,"DAILY_GROUPED_REVIEW_SCHEDULER")).toThrow(/SUPABASE_SERVICE_ROLE_KEY/);const notification=env();delete notification.RESEND_API_KEY;expect(()=>parseWorkerConfiguration(notification,"NOTIFICATION_RETRY_WORKER")).toThrow(/RESEND_API_KEY/);delete notification.GROUPED_REVIEW_DELIVERY_ENCRYPTION_KEY_V1;expect(()=>parseWorkerConfiguration(notification,"NOTIFICATION_RETRY_WORKER")).toThrow(/GROUPED_REVIEW_DELIVERY_ENCRYPTION_KEY_V1/);});
 it("requires a valid public-review key for fail-closed Worker composition",()=>{const missing=env();delete missing.SUPABASE_PUBLISHABLE_KEY;expect(()=>parseWorkerConfiguration(missing,"NOTIFICATION_RETRY_WORKER")).toThrow(/SUPABASE_PUBLISHABLE_KEY/);expect(()=>parseWorkerConfiguration(missing,"DAILY_GROUPED_REVIEW_SCHEDULER")).toThrow(/SUPABASE_PUBLISHABLE_KEY/);expect(()=>parseWorkerConfiguration({...env(),SUPABASE_PUBLISHABLE_KEY:"malformed key"},"NOTIFICATION_RETRY_WORKER")).toThrow(/browser-safe/);});
 it("validates the UAT provider-only recipient constraint",()=>{expect(parseWorkerConfiguration(env(),"NOTIFICATION_RETRY_WORKER").uatRecipientOverride).toBe("controlled@example.test");expect(()=>parseWorkerConfiguration({...env(),EMAIL_UAT_RECIPIENT_OVERRIDE:"Injected@Example.test"},"NOTIFICATION_RETRY_WORKER")).toThrow(/normalized header-safe/);expect(()=>parseWorkerConfiguration({...env(),EMAIL_UAT_RECIPIENT_OVERRIDE:"bad\r\nBcc:x@example.test"},"NOTIFICATION_RETRY_WORKER")).toThrow(/normalized header-safe/);});
 it("keeps logs free of secrets, credentials, URLs and envelope fields",async()=>{const events:Record<string,unknown>[]=[];const logger:SafeRuntimeLogger={log:event=>events.push(event)};await runScheduledJob("DAILY_GROUPED_REVIEW_SCHEDULER",0,env(),dependencies(),logger);const output=JSON.stringify(events);for(const forbidden of[...Object.values(secretValues),"/review/customer/grouped/","ciphertext","nonce","authTag","credentialHash"])expect(output).not.toContain(forbidden);});
 it("supports Worker Node crypto and Buffer AES-GCM dependencies",async()=>{const{encryptGroupedReviewDeliveryEnvelope,decryptGroupedReviewDeliveryEnvelope}=await import("../server/notifications/GroupedReviewDeliveryEnvelope");const key=Buffer.from(secretValues.key,"base64"),path=`/review/customer/grouped/${"a".repeat(64)}`;const envelope=encryptGroupedReviewDeliveryEnvelope(path,"00000000-0000-4000-8000-000000000001",key);expect(decryptGroupedReviewDeliveryEnvelope(envelope,"00000000-0000-4000-8000-000000000001",key)).toBe(path);});
 it("isolates fail-closed UAT configuration without moving business authority into the Worker",()=>{const wrangler=JSON.parse(readFileSync("wrangler.jsonc","utf8").replace(/^\uFEFF/,""));const runtime=readFileSync("worker/runtime.ts","utf8");expect(wrangler.env.uat).toMatchObject({name:"psc-ed-uat",workers_dev:true,vars:{SUPABASE_URL:"https://jtkctarqbwmqdcewthkn.supabase.co",REVIEW_PUBLIC_BASE_URL:"https://psc-ed-uat.equipmentdept-psc.workers.dev",SCHEDULER_JOB_CRON:"*/15 * * * *",NOTIFICATION_JOB_CRON:"*/2 * * * *",SCHEDULER_BATCH_LIMIT:"1",NOTIFICATION_WORKER_BATCH_LIMIT:"1"},triggers:{crons:[]}});expect(wrangler.triggers).toBeUndefined();expect(runtime).not.toMatch(/automation_enabled|local_send_time|grace_minutes|companyId|rentalId|timezone/);});
});
