import {describe,expect,it} from "vitest";import {randomUUID} from "node:crypto";
import {DailyGroupedCustomerReviewService,type DailyGroupedReviewRepository} from "../server/notifications/DailyGroupedCustomerReviewService";
const candidate=(rentalId:string,companyId="TENANT-A")=>({groupId:randomUUID(),companyId,customerId:"C",projectId:"P",rentalId,businessDate:"2026-08-11",timezone:"Asia/Manila"});
describe("daily grouped review service",()=>{
 it("resolves system authority and prepares each Rental independently without returning secrets",async()=>{const prepared:any[]=[];let completed:any;const outcomes:string[]=[];const repo:DailyGroupedReviewRepository={discover:async()=>({runId:randomUUID(),candidates:[candidate("R1"),candidate("R2")],groupsClaimed:2,groupsNoActionable:1,hasMore:true,failures:[]}),resolvePrincipal:async()=>({success:true,principalId:randomUUID()}),prepare:async c=>{prepared.push(c);return{success:true,disposition:"CREATED",value:{notificationIntentId:randomUUID()}}},completeGroup:async(_g,_r,o)=>{outcomes.push(o)},complete:async(_id,r)=>{completed=r}};const result=await new DailyGroupedCustomerReviewService(repo,Buffer.alloc(32,7)).run({commandId:randomUUID(),idempotencyKey:"daily-1",runAt:"2026-08-11T01:00:00Z",batchLimit:2});expect(result).toEqual(completed);expect(result).toMatchObject({batchLimit:2,groupsClaimed:2,groupsProcessed:2,groupsPrepared:2,notificationsPrepared:2,groupsNoActionable:1,hasMore:true});expect(outcomes).toEqual(["PREPARED","PREPARED"]);expect(prepared).toHaveLength(2);expect(prepared[0]).not.toHaveProperty("actorId");expect(JSON.stringify(result)).not.toMatch(/credential|ciphertext|reviewPath/i);});
 it("isolates and marks group failures recoverable",async()=>{let n=0;const outcomes:string[]=[];const repo:DailyGroupedReviewRepository={discover:async()=>({runId:randomUUID(),candidates:[candidate("R1","A"),candidate("R2","B")],groupsClaimed:2,groupsNoActionable:0,hasMore:false,failures:[]}),resolvePrincipal:async()=>++n===1?{success:false,code:"SCHEDULER_PRINCIPAL_NOT_CONFIGURED"}:{success:true,principalId:randomUUID()},prepare:async()=>({success:false,code:"FORBIDDEN"}),completeGroup:async(_g,_r,o)=>{outcomes.push(o)},complete:async()=>{}};const result=await new DailyGroupedCustomerReviewService(repo,Buffer.alloc(32,4)).run({commandId:randomUUID(),idempotencyKey:"daily-2",runAt:new Date().toISOString(),batchLimit:2});expect(result.groupsFailed).toBe(2);expect(outcomes).toEqual(["FAILED","FAILED"]);expect(result.failureCodes).toEqual(["SCHEDULER_PRINCIPAL_NOT_CONFIGURED","FORBIDDEN"]);});
 it("processes a large candidate set across periodic bounded invocations without draining",async()=>{const remaining=Array.from({length:8},(_,i)=>candidate(`R${i}`,i%2?"TENANT-B":"TENANT-A"));const claimed:number[]=[];const repo:DailyGroupedReviewRepository={discover:async command=>{const page=remaining.splice(0,command.batchLimit);claimed.push(page.length);return{runId:randomUUID(),candidates:page,groupsClaimed:page.length,groupsNoActionable:0,hasMore:remaining.length>0,failures:[]}},resolvePrincipal:async()=>({success:true,principalId:randomUUID()}),prepare:async()=>({success:true,disposition:"REPLAYED"}),completeGroup:async()=>{},complete:async()=>{}};const service=new DailyGroupedCustomerReviewService(repo,Buffer.alloc(32,5));const run=()=>service.run({commandId:randomUUID(),idempotencyKey:randomUUID(),runAt:new Date().toISOString(),batchLimit:3});expect((await run()).hasMore).toBe(true);expect((await run()).hasMore).toBe(true);expect((await run()).hasMore).toBe(false);expect(claimed).toEqual([3,3,2]);});
 it("retries a failed claim in a later invocation without duplicating preparation",async()=>{const item=candidate("CRASH");let attempt=0,prepared=0;const outcomes:string[]=[];const repo:DailyGroupedReviewRepository={discover:async()=>({runId:randomUUID(),candidates:[item],groupsClaimed:1,groupsNoActionable:0,hasMore:false,failures:[]}),resolvePrincipal:async()=>++attempt===1?Promise.reject(new Error("simulated crash boundary")):Promise.resolve({success:true,principalId:randomUUID()}),prepare:async()=>{prepared++;return{success:true,disposition:"CREATED"}},completeGroup:async(_g,_r,o)=>{outcomes.push(o)},complete:async()=>{}};const service=new DailyGroupedCustomerReviewService(repo,Buffer.alloc(32,6)),run=()=>service.run({commandId:randomUUID(),idempotencyKey:randomUUID(),runAt:new Date().toISOString(),batchLimit:1});expect((await run()).groupsFailed).toBe(1);expect((await run()).groupsPrepared).toBe(1);expect(outcomes).toEqual(["FAILED","PREPARED"]);expect(prepared).toBe(1);});
});
