import {describe,expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {LocalMockExecutiveAnalysisService,UnconfiguredExecutiveAnalysisService,analysisConfigurationHash,buildExecutiveAnalysisInput,isExecutiveAnalysisStale,validateExecutiveAnalysisResult,type ExecutiveAnalysisRecord} from "@/features/reports/services/executiveReportAnalysis";
import {loadReportPreview,savePreviewAnalysis,saveReportPreview,setPreviewAnalysisIncluded} from "@/features/reports/services/reportComposition";
import type {CustomReportSection} from "@/features/reports/services/customReportWorkspace";

const section=(id:string,title:string,type:CustomReportSection["type"]="revenue"):CustomReportSection=>({id,fingerprint:id,type,addedAt:"2026-08-15T00:00:00.000Z",config:{type,groupBy:"none",period:{startDate:"2026-08-01",endDate:"2026-08-15",comparisonStartDate:"2026-07-17",comparisonEndDate:"2026-07-31",label:"August"}},report:{title,period:"August",filters:["Status: Active"],columns:["Invoice","Customer","Amount"],rows:[["INV-1","Authorized Customer","₱1,000"]],metrics:[{label:"Billed",value:"₱1,000",numericValue:1000,previousValue:800,variance:200,variancePercent:25},{label:"Outstanding",value:"₱300",numericValue:300,previousValue:200,variance:100,variancePercent:50}],groupBy:"none"}});

describe("Phase 2H AI executive analysis boundary",()=>{
 it("builds a minimized structured payload without raw or secret fields",()=>{const input=buildExecutiveAnalysisInput("Review","executive",[section("finance","Revenue")]),serialized=JSON.stringify(input);expect(input.sections[0]).toMatchObject({reportType:"revenue",recordCount:1,columns:["Invoice","Customer","Amount"]});expect(serialized).not.toContain("INV-1");expect(serialized).not.toContain("Authorized Customer");expect(serialized).not.toMatch(/password|token|secret|credential|api.?key/i)});
 it("includes comparison metrics and multiple authorized section summaries",()=>{const input=buildExecutiveAnalysisInput("Review","executive",[section("finance","Revenue"),section("ops","Rental","rentals")]);expect(input.comparisonPeriod).toBe("2026-07-17 to 2026-07-31");expect(input.sections).toHaveLength(2);expect(input.sections[0].metrics[0]).toMatchObject({previousValue:800,variance:200,variancePercent:25})});
 it("creates deterministic hashes and detects stale analysis",()=>{const input=buildExecutiveAnalysisInput("Review","executive",[section("finance","Revenue")]),record={configurationHash:analysisConfigurationHash(input)} as ExecutiveAnalysisRecord;expect(isExecutiveAnalysisStale(record,input)).toBe(false);expect(isExecutiveAnalysisStale(record,{...input,reportTitle:"Changed"})).toBe(true)});
 it("returns a validated deterministic schema with facts, recommendations, evidence, and limitations",async()=>{const service=new LocalMockExecutiveAnalysisService(),result=await service.analyze(buildExecutiveAnalysisInput("Review","executive",[section("finance","Revenue")])) ;expect(validateExecutiveAnalysisResult(result)).toBe(true);expect(result.keyFindings.every(x=>x.kind==="FACT")).toBe(true);expect(result.recommendations).toEqual(expect.arrayContaining([expect.objectContaining({kind:"RECOMMENDATION",responsibleFunction:"Finance",supportingMetric:"Outstanding"})]));expect(result.confidenceNotes.join(" ")).toMatch(/no external AI provider|decision support/i)});
 it("rejects malformed provider output instead of rendering untrusted schema",()=>{expect(validateExecutiveAnalysisResult({executiveSummary:"Bad",keyFindings:[{kind:"CLAIM",priority:"Extreme",text:"Unsupported"}],risks:[],recommendations:[],positiveTrends:[],validationItems:[],confidenceNotes:[]})).toBe(false)});
 it("produces safe observational cross-section guidance without causal claims",async()=>{const result=await new LocalMockExecutiveAnalysisService().analyze(buildExecutiveAnalysisInput("Review","executive",[section("finance","Revenue"),section("ops","Rental","rentals")]));expect(result.recommendations.some(x=>/without assuming.*caused/i.test(x.text))).toBe(true);expect(result.executiveSummary).toContain("do not establish causation")});
 it("supports include, exclude, regeneration replacement, and snapshot isolation",async()=>{const sections=[section("finance","Revenue")],input=buildExecutiveAnalysisInput("Review","executive",sections),result=await new LocalMockExecutiveAnalysisService().analyze(input);saveReportPreview("Review",sections);savePreviewAnalysis({configurationHash:analysisConfigurationHash(input),generatedAt:"2026-08-15T00:00:00Z",providerId:"mock",included:false,result});setPreviewAnalysisIncluded(true);expect(loadReportPreview()?.analysis?.included).toBe(true);setPreviewAnalysisIncluded(false);expect(loadReportPreview()?.analysis?.included).toBe(false);savePreviewAnalysis({configurationHash:analysisConfigurationHash(input),generatedAt:"2026-08-15T01:00:00Z",providerId:"mock",included:false,result});expect(loadReportPreview()?.analysis?.generatedAt).toBe("2026-08-15T01:00:00Z")});
 it("fails safely when no provider is configured",async()=>{await expect(new UnconfiguredExecutiveAnalysisService().analyze()).rejects.toThrow("not configured")});
 it("keeps provider abstraction React-free and never references frontend secrets",()=>{const source=readFileSync("src/features/reports/services/executiveReportAnalysis.ts","utf8");expect(source).not.toMatch(/from ["']react|VITE_.*KEY|OPENAI_API_KEY|fetch\(/);expect(source).toContain("interface ExecutiveReportAnalysisService")});
 it("offers explicit preview controls and optional PDF placement",()=>{const preview=readFileSync("src/features/reports/components/CustomReportPreview.tsx","utf8"),pdf=readFileSync("src/features/reports/services/customReportPdfExport.ts","utf8");expect(preview).toContain("Generate AI Analysis");expect(preview).toContain("Regenerate");expect(preview).toContain("Include in Report");expect(preview).toContain("Exclude");expect(preview).toContain("Out of date");expect(pdf).toContain("if(input.analysis?.included)");expect(pdf.indexOf("drawAiAnalysis")).toBeLessThan(pdf.indexOf("for(const section"))});
});
