import { beforeEach, describe, expect, it } from "vitest";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { getCompletedDeursForBillingPeriod } from "@/features/rental/workspace/billing/BillingPreviewBuilder";
import { developmentCustomerReviewOutbox, DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY } from "@/features/rental/customer-review/developmentCustomerReviewOutbox";
import { billingStatementRepository } from "@/features/rental/billingstatement/repository";
import { collectionRepository, COLLECTION_STORAGE_KEY } from "@/features/rental/collections/repository";
import { recordCollection, reconcileStatementCollections } from "@/features/rental/collections/collectionService";
import { buildBillingStatementEmail } from "@/features/rental/billing-email/buildBillingStatementEmail";
import { calculateBusinessDashboardSummary } from "@/features/dashboard/services/businessDashboardSummary";
import { buildInvoiceDocument } from "@/features/rental/workspace/invoice/InvoiceDocumentBuilder";
import InvoiceDocumentView from "@/features/rental/workspace/invoice/InvoiceDocumentView";
import { storage } from "@/core/storage";
import type { BillingStatement } from "@/features/rental/billingstatement/types";
import type { DeurRecord } from "@/features/rental/deur/types";

const events:DeurRecord["events"]=[{id:"s",activityType:"shift",action:"start",timestamp:"2026-07-27T00:00:00Z",sequence:1,source:"user"},{id:"o1",activityType:"operation",action:"start",timestamp:"2026-07-27T00:00:00Z",sequence:2,source:"user"},{id:"o2",activityType:"operation",action:"end",timestamp:"2026-07-27T02:00:00Z",sequence:3,source:"user"},{id:"e",activityType:"shift",action:"end",timestamp:"2026-07-27T02:00:00Z",sequence:4,source:"user"}];
const deur=(overrides:Partial<DeurRecord>={}):DeurRecord=>({id:"8d86a588-2e24-4af0-991d-ef10d8cf99e1",deurNumber:"DEUR-000001",rentalId:"r",rentalEquipmentLineId:"line",equipmentId:"equipment-uuid",operatorId:"operator-uuid",workDate:"2026-07-27",status:"Acknowledged",events,totals:{shiftMinutes:120,operationMinutes:120,idleMinutes:0,mealBreakMinutes:0,breakdownMinutes:0},logs:[],totalOperatingMinutes:120,totalIdleMinutes:0,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,legacy:false,createdAt:"",updatedAt:"",...overrides});
const statement=(overrides:Partial<BillingStatement>={}):BillingStatement=>({id:"statement-1",statementNo:"BS-1",version:1,rentalId:"r",rentalNumber:"RENT-1",equipmentId:"equipment-uuid",operatorId:"operator-uuid",customer:"Customer",customerRepresentativeName:"Rep",customerRepresentativeEmail:"rep@test.dev",project:"Project",billingFrom:"2026-07-27",billingTo:"2026-07-27",subtotal:1000,grandTotal:1000,approvalStatus:"Approved",invoiceStatus:"Invoiced",lines:[{id:"l",deurId:deur().id,deurReference:"DEUR-000001 R1",equipmentId:"equipment-uuid",equipmentLabel:"UAT 1 (ME-000001)",operatorId:"operator-uuid",operatorLabel:"UAT operator 1",workDate:"2026-07-27",description:"Rental",costCode:"",hours:2,hourlyRate:500,amount:1000,grandTotal:1000}],createdBy:"Admin",createdAt:"2026-07-27T00:00:00Z",...overrides});
const request=()=>({deurId:deur().id,deurNumber:"DEUR-000001",revisionNumber:1,rentalNumber:"RENT-1",customerName:"Customer",representativeName:"Rep",representativeEmail:"rep@test.dev",snapshot:{project:"Project",equipment:"UAT 1 (ME-000001)",operator:"UAT operator 1",workDate:"2026-07-27",operationMinutes:120,idleMinutes:0,breakdownMinutes:0,origin:"OPERATOR_DIGITAL"}});

describe("post-DEUR Billing and Collections stabilization",()=>{
 beforeEach(()=>{localStorage.clear();storage.remove(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY);storage.remove(COLLECTION_STORAGE_KEY)});
 it("discovers the acknowledged effective Operator DEUR without Complete Day",()=>{expect(getCompletedDeursForBillingPeriod([deur({endOfDay:undefined})],"2026-07-27","2026-07-27")).toEqual([expect.objectContaining({deurNumber:"DEUR-000001"})]);expect(getCompletedDeursForBillingPeriod([deur()],"2026-07-28","2026-07-28")).toEqual([])});
 it("returns one pending acknowledgement request for a double action",()=>{const first=developmentCustomerReviewOutbox.create(request()),second=developmentCustomerReviewOutbox.create(request());expect(second.id).toBe(first.id);expect(developmentCustomerReviewOutbox.getAll()).toHaveLength(1)});
 it("records multiple partial Collections then collects only the remainder",()=>{billingStatementRepository.create(statement());const first=recordCollection({statementId:"statement-1",mode:"partial",amount:300,paymentDate:"2026-07-27",referenceNumber:"PAY-1",actor:{name:"Admin"}});expect(first).toMatchObject({success:true,totals:{totalCollected:300,outstandingBalance:700}});const second=recordCollection({statementId:"statement-1",mode:"partial",amount:200,paymentDate:"2026-07-28",referenceNumber:"PAY-2",actor:{name:"Admin"}});expect(second).toMatchObject({success:true,totals:{totalCollected:500,outstandingBalance:500}});const final=recordCollection({statementId:"statement-1",mode:"full",paymentDate:"2026-07-29",referenceNumber:"PAY-3",actor:{name:"Admin"}});expect(final).toMatchObject({success:true,transaction:{amount:500},totals:{totalCollected:1000,outstandingBalance:0},statement:{invoiceStatus:"Fully Collected"}});expect(collectionRepository.getByStatementId("statement-1")).toHaveLength(3)});
 it("rejects zero, overpayment, missing reference, and duplicate reference",()=>{billingStatementRepository.create(statement());expect(recordCollection({statementId:"statement-1",mode:"partial",amount:0,paymentDate:"2026-07-27",referenceNumber:"P",actor:{name:"Admin"}}).success).toBe(false);expect(recordCollection({statementId:"statement-1",mode:"partial",amount:1000,paymentDate:"2026-07-27",referenceNumber:"P",actor:{name:"Admin"}}).success).toBe(false);expect(recordCollection({statementId:"statement-1",mode:"partial",amount:100,paymentDate:"2026-07-27",referenceNumber:"",actor:{name:"Admin"}}).success).toBe(false)});
 it("renders immutable labels and DEUR number without UUIDs or inapplicable taxes",()=>{const document=buildInvoiceDocument(statement());const html=renderToStaticMarkup(createElement(InvoiceDocumentView,{document}));expect(html).toContain("UAT 1 (ME-000001)");expect(html).toContain("UAT operator 1");expect(html).toContain("DEUR-000001 R1");expect(html).not.toContain("equipment-uuid");expect(html).not.toContain("operator-uuid");expect(html).not.toContain(">VAT<");expect(html).not.toContain(">WHT<")});
 it("builds a safe local email and finance summary from persisted transactions",()=>{const email=buildBillingStatementEmail({statementNumber:"BS-1",rentalNumber:"RENT-1",customer:"Customer",representativeName:"Rep",recipient:"rep@test.dev",project:"Project",billingFrom:"2026-07-01",billingTo:"2026-07-31",amountDue:700,currency:"PHP"});expect(email).toMatchObject({recipient:"rep@test.dev",subject:"Billing Statement BS-1 — Rental RENT-1"});const s=statement(),transactions=[{id:"c",statementId:s.id,rentalId:s.rentalId,amount:300,paymentDate:"2026-07-27",referenceNumber:"P",recordedBy:"Admin",recordedAt:"2026-07-27T00:00:00Z"}];expect(reconcileStatementCollections(s,transactions)).toEqual({invoiceTotal:1000,totalCollected:300,outstandingBalance:700});expect(calculateBusinessDashboardSummary({statements:[s],collections:transactions,rentals:[],deurs:[]})).toMatchObject({revenue:{billed:1000,collected:300,outstanding:700},collectionPerformance:{collectionRate:30}})});
});
