import{readFileSync}from"node:fs";import{afterEach,describe,expect,it,vi}from"vitest";
import type{Session,SupabaseClient}from"@supabase/supabase-js";
import{repositorySuccess}from"@/core/persistence";import type{User}from"@/features/auth/domain/user";
import{SupabaseAuthenticationProvider}from"@/integrations/supabase/SupabaseAuthenticationProvider";
import worker from"../worker/index";import{TrustedUsernameAuthentication,type UsernameLoginLimiters}from"../worker/usernameAuthentication";

const migration=readFileSync("supabase/migrations/20260822000200_trusted_username_authentication.sql","utf8"),workerSource=readFileSync("worker/usernameAuthentication.ts","utf8"),loginSource=readFileSync("src/pages/Login.tsx","utf8"),wrangler=JSON.parse(readFileSync("wrangler.jsonc","utf8").replace(/^\uFEFF/,""));
const user:User={id:"22000000-0000-4000-8000-000000000201",username:"uat.finance.test",displayName:"UAT Finance",email:"finance@example.test",companyId:"tenant",systemRoles:["finance"],status:"active",createdAt:"",updatedAt:""};
const session={access_token:"access-token",refresh_token:"refresh-token",expires_at:1785200000,user:{id:user.id,last_sign_in_at:"2026-08-22T00:00:00Z"}}as Session;
const allow=()=>({limit:vi.fn(async()=>({success:true}))});
const limiters=():UsernameLoginLimiters=>({networkBurst:allow(),networkSustained:allow(),identifierBurst:allow(),identifierSustained:allow()});
const request=(identifier="uat.finance.test",password="Secret123!")=>new Request("https://uat.example/api/auth/username-login",{method:"POST",headers:{"content-type":"application/json","cf-connecting-ip":"192.0.2.10"},body:JSON.stringify({identifier,password})});
afterEach(()=>vi.restoreAllMocks());

describe("trusted remote username authentication",()=>{
 it("defines a service-role-only, active, unique resolver without widening identity reads",()=>{for(const evidence of["SECURITY DEFINER","SET search_path = erp, auth, pg_catalog","lower(application_user.username) = normalized_identifier","application_user.status = 'active'","company.active","match_count <> 1","JOIN auth.users auth_user"])expect(migration).toContain(evidence);expect(migration).toMatch(/REVOKE ALL ON FUNCTION[\s\S]*FROM PUBLIC, anon, authenticated/);expect(migration).toMatch(/GRANT EXECUTE ON FUNCTION[\s\S]*TO service_role/);expect(migration).not.toMatch(/GRANT SELECT[\s\S]*(?:username|email)/i);expect(migration).not.toContain("user_provisioning_commands");});
 it("keeps email direct, installs username sessions, and resolves the same user and permissions",async()=>{const permissions={data:[{permission_code:"billing.read"}],error:null};const query={select:()=>query,eq:()=>query,then:(resolve:(x:typeof permissions)=>unknown)=>Promise.resolve(permissions).then(resolve)};const signInWithPassword=vi.fn(async()=>({data:{session},error:null})),setSession=vi.fn(async()=>({data:{session},error:null}));const client={auth:{signInWithPassword,setSession,getSession:vi.fn(async()=>({data:{session},error:null})),refreshSession:vi.fn(),signOut:vi.fn(async()=>({error:null}))},schema:()=>({from:()=>query})}as unknown as SupabaseClient;const users={getById:vi.fn(async()=>repositorySuccess(user)),list:vi.fn(),search:vi.fn()};const provider=new SupabaseAuthenticationProvider(client,users);const email=await provider.login({username:"finance@example.test",password:"Secret123!"});expect(email).toMatchObject({success:true,value:{user:{id:user.id},permissions:["billing.read"]}});expect(signInWithPassword).toHaveBeenCalledWith({email:"finance@example.test",password:"Secret123!"});vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({success:true,session:{accessToken:"access-token",refreshToken:"refresh-token"}}),{status:200,headers:{"content-type":"application/json"}}));const username=await provider.login({username:"UAT.FINANCE.TEST",password:"Secret123!"});expect(username).toMatchObject({success:true,value:{user:{id:user.id},permissions:["billing.read"]}});expect(setSession).toHaveBeenCalledWith({access_token:"access-token",refresh_token:"refresh-token"});await expect(provider.restoreSession()).resolves.toMatchObject({success:true,value:{user:{id:user.id}}});});
 it("returns only session tokens after case-insensitive resolver success",async()=>{const rpc=vi.fn(async()=>({data:{success:true,email:"finance@example.test"},error:null})),signInWithPassword=vi.fn(async()=>({data:{session},error:null}));const limits=limiters(),service=new TrustedUsernameAuthentication({schema:()=>({rpc})},{auth:{signInWithPassword}},limits);const result=await service.handle(request("UAT.FINANCE.TEST"));expect(result).toMatchObject({status:200,body:{success:true,session:{accessToken:"access-token",refreshToken:"refresh-token"}}});expect(JSON.stringify(result.body)).not.toContain("finance@example.test");expect(rpc).toHaveBeenCalledWith("resolve_active_application_user_login",{identifier:"UAT.FINANCE.TEST"});for(const binding of Object.values(limits))expect(binding.limit.mock.calls[0][0].key).toMatch(/^[a-f0-9]{64}$/);});
 it.each([{name:"unknown username",resolved:{success:false},authError:{message:"invalid"}},{name:"inactive ERP user",resolved:{success:false},authError:{message:"invalid"}},{name:"inactive company",resolved:{success:false},authError:{message:"invalid"}},{name:"ambiguous username",resolved:{success:false},authError:{message:"invalid"}},{name:"missing Auth identity",resolved:{success:false},authError:{message:"invalid"}},{name:"wrong password",resolved:{success:true,email:"finance@example.test"},authError:{message:"wrong"}}])("returns the same generic failure for $name",async({resolved,authError})=>{const signInWithPassword=vi.fn(async()=>({data:{session:null},error:authError}));const service=new TrustedUsernameAuthentication({schema:()=>({rpc:async()=>({data:resolved,error:null})})},{auth:{signInWithPassword}},limiters());const result=await service.handle(request());expect(result).toEqual({status:401,body:{success:false,message:"Invalid username/email or password."}});expect(JSON.stringify(result)).not.toMatch(/finance@example|wrong|invalid-login/);});
 it("hides raw resolver and Supabase errors",async()=>{const service=new TrustedUsernameAuthentication({schema:()=>({rpc:async()=>({data:null,error:{message:"raw database error"}})})},{auth:{signInWithPassword:async()=>({data:{session:null},error:{message:"raw auth error"}})}},limiters());const result=await service.handle(request());expect(result).toEqual({status:401,body:{success:false,message:"Invalid username/email or password."}});expect(JSON.stringify(result)).not.toMatch(/raw database|raw auth/);});
 it("normalizes direct email failures without exposing Supabase details",async()=>{const client={auth:{signInWithPassword:async()=>({data:{session:null},error:{message:"Email not confirmed",status:400}})}}as unknown as SupabaseClient;const users={getById:vi.fn(),list:vi.fn(),search:vi.fn()};const result=await new SupabaseAuthenticationProvider(client,users).login({username:"unknown@example.test",password:"wrong"});expect(result).toMatchObject({success:false,error:{code:"REMOTE_AUTHORIZATION_DENIED",message:"Invalid username/email or password."}});expect(JSON.stringify(result)).not.toContain("Email not confirmed");});
 it("uses a dummy Supabase attempt for unavailable canonical identities",async()=>{const signInWithPassword=vi.fn(async()=>({data:{session:null},error:{}}));const service=new TrustedUsernameAuthentication({schema:()=>({rpc:async()=>({data:{success:false},error:null})})},{auth:{signInWithPassword}},limiters());await service.handle(request());expect(signInWithPassword).toHaveBeenCalledWith({email:"invalid-login@invalid.example",password:"Secret123!"});});
 it("fails closed with generic 429 when either limiter rejects",async()=>{const limits=limiters();limits.networkBurst.limit=vi.fn(async()=>({success:false}));const rpc=vi.fn();const result=await new TrustedUsernameAuthentication({schema:()=>({rpc})},{auth:{signInWithPassword:vi.fn()}},limits).handle(request());expect(result).toEqual({status:429,body:{success:false,message:"Invalid username/email or password."}});expect(rpc).not.toHaveBeenCalled();});
 it("exposes a POST-only no-store route and four native UAT limiter bindings",async()=>{const environment={ASSETS:{fetch:vi.fn()}};const result=await worker.fetch(new Request("https://uat.example/api/auth/username-login",{method:"GET"}),environment);expect(result.status).toBe(405);expect(result.headers.get("cache-control")).toBe("no-store");expect(wrangler.env.uat.ratelimits).toHaveLength(4);expect(new Set(wrangler.env.uat.ratelimits.map((x:{name:string})=>x.name))).toEqual(new Set(["USERNAME_LOGIN_NETWORK_BURST","USERNAME_LOGIN_NETWORK_SUSTAINED","USERNAME_LOGIN_IDENTIFIER_BURST","USERNAME_LOGIN_IDENTIFIER_SUSTAINED"]));});
 it("uses deterministic email-shaped classification and updates only the remote label",()=>{expect(workerSource).not.toMatch(/console\.|audit_log|new_values/i);expect(loginSource).toContain('remote ? "Email or Username" : "Username"');});
});
