import {act,createElement} from "react";
import {createRoot,type Root} from "react-dom/client";
import {MemoryRouter,Route,Routes} from "react-router-dom";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import type {RentalContractRecord} from "@/features/rental/types/RentalContract";
import type {RentalEquipmentLine} from "@/features/rental/equipment-line";

const state=vi.hoisted(()=>({contracts:new Map<string,RentalContractRecord>(),saveResult:{success:true,message:undefined as string|undefined},removeResult:{success:true,message:undefined as string|undefined},saveCalls:0,removeCalls:0,toasts:[] as Array<[string,string|undefined]>}));
const lines:RentalEquipmentLine[]=["line-1","line-2"].map((id,index)=>({id,rentalId:"rental-1",equipmentId:`equipment-${index+1}`,operatorId:`operator-${index+1}`,status:"Reserved",commercialSnapshotRequired:true,createdAt:"2026-07-20",updatedAt:"2026-07-20"}));
const rental={id:"rental-1",rentalNumber:"R-1",equipmentId:"",customerId:"customer",projectId:"project",customer:"Customer",project:"Project",rentedBy:"Admin",dateOut:"2026-07-20",rentalType:"Operated Rental" as const,statusId:"reserved",status:"Reserved" as const};

vi.mock("@/components/ui/toast/ToastContext",()=>({useToast:()=>({showToast:(message:string,type?:string)=>state.toasts.push([message,type])})}));
vi.mock("@/features/equipment/context/EquipmentContext",()=>({useEquipment:()=>({equipment:lines.map((line,index)=>({id:line.equipmentId,assetNo:`EQ-${index+1}`,equipmentName:`Machine ${index+1}`}))})}));
vi.mock("@/features/operators/context/OperatorContext",()=>({useOperator:()=>({operators:lines.map((line,index)=>({id:line.operatorId,name:`Operator ${index+1}`}))})}));
vi.mock("@/features/assignment/context/AssignmentContext",()=>({useAssignment:()=>({assignments:[]})}));
vi.mock("@/features/rental/context/RentalContext",async()=>{const React=await import("react");return{useRental:()=>{const [visibleLines,setVisibleLines]=React.useState(lines);const [,refresh]=React.useState(0);return{getRental:()=>rental,rentalEquipmentLines:visibleLines,getContractForRentalEquipmentLine:(id:string)=>state.contracts.get(id),saveCommercialTermsForRentalEquipmentLine:(_rentalId:string,lineId:string,input:any)=>{state.saveCalls++;if(!state.saveResult.success)return state.saveResult;const now=`2026-07-20T00:00:0${state.saveCalls}.000Z`;state.contracts.set(lineId,{id:`contract-${lineId}`,rentalId:"rental-1",rentalEquipmentLineId:lineId,contractNo:"C",customerId:"customer",equipmentId:lines.find(item=>item.id===lineId)!.equipmentId,projectId:"project",rentalType:"Operated Rental",billingMethod:input.billingMethod,currency:input.currency,unitRate:input.unitRate,operatorIncluded:input.operatorIncluded,startDate:"2026-07-20",expectedEndDate:"2026-07-21",status:"Active",createdAt:now,updatedAt:now});refresh(value=>value+1);return{success:true};},addRentalEquipmentLine:()=>({success:false}),removeRentalEquipmentLine:(_rentalId:string,lineId:string)=>{state.removeCalls++;if(!state.removeResult.success)return state.removeResult;setVisibleLines(current=>current.filter(line=>line.id!==lineId));state.contracts.delete(lineId);return{success:true};}};}}});

let root:Root,container:HTMLDivElement;
async function render(){container=document.createElement("div");document.body.append(container);root=createRoot(container);const Page=(await import("@/pages/Rental/CommercialTerms")).default;const tree=createElement(MemoryRouter,{initialEntries:["/rentals/rental-1/commercial-terms"]},createElement(Routes,null,createElement(Route,{path:"/rentals/:rentalId/commercial-terms",element:createElement(Page)})));await act(async()=>root.render(tree));}
function click(text:string){const button=[...container.querySelectorAll("button")].find(item=>item.textContent?.includes(text));if(!button)throw new Error(`Button '${text}' not found`);button.dispatchEvent(new MouseEvent("click",{bubbles:true}));}
function enter(input:HTMLInputElement,value:string){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));}
beforeEach(()=>{state.contracts.clear();state.saveResult={success:true,message:undefined};state.removeResult={success:true,message:undefined};state.saveCalls=0;state.removeCalls=0;state.toasts=[];});
afterEach(async()=>{if(root)await act(async()=>root.unmount());container?.remove();});

describe("Commercial Terms UAT workflow",()=>{
  it("selects the next incomplete line after save and shows completion actions after the final save",async()=>{await render();await act(async()=>click("Save This Line"));expect(state.saveCalls).toBe(1);expect(container.textContent).toContain("EQ-2");expect(state.toasts.at(-1)?.[0]).toContain("next incomplete");await act(async()=>click("Save This Line"));expect(state.saveCalls).toBe(2);expect(container.textContent).toContain("Commercial terms complete");expect(container.textContent).toContain("Review Commercial Terms");expect(container.textContent).toContain("Continue to Rental Workspace");});
  it("prevents duplicate save submission while pending and preserves entered data on failure",async()=>{state.saveResult={success:false,message:"Persistence failed"};await render();const rate=container.querySelector('input[type="number"]') as HTMLInputElement;await act(async()=>enter(rate,"725"));await act(async()=>{click("Save This Line");click("Save This Line");});expect(state.saveCalls).toBe(1);expect(rate.value).toBe("725");expect(container.textContent).toContain("Persistence failed");expect(container.textContent).toContain("Save This Line");});
  it("shows no success when removal fails and removes only the selected visible configuration when it succeeds",async()=>{state.removeResult={success:false,message:"Removal failed"};await render();await act(async()=>click("Remove selected line"));expect(container.textContent).toContain("EQ-1");expect(state.toasts.at(-1)).toEqual(["Removal failed","error"]);state.removeResult={success:true,message:undefined};await act(async()=>click("Remove selected line"));expect(container.textContent).not.toContain("EQ-1 - Machine 1");expect(container.textContent).toContain("EQ-2 - Machine 2");expect(state.toasts.at(-1)).toEqual(["Equipment line removed.","success"]);});
});
