import { beforeEach, describe, expect, it } from "vitest";
import { storage } from "@/core/storage";
import { createRentalCommercialSnapshot } from "@/features/rental/services/createRentalCommercialSnapshot";
import { LocalRentalRepository } from "@/features/rental/repository/LocalRentalRepository";
import type { RentalCommercialSnapshot, RentalRecord } from "@/features/rental/types";
import type { RentalContractRecord } from "@/features/rental/types/RentalContract";
import { createDeurBillingPreview } from "@/features/rental/deur/billing/createDeurBillingPreview";
import type { DeurRecord } from "@/features/rental/deur/types";

const contract: RentalContractRecord = { id:"r",contractNo:"C",customerId:"c",equipmentId:"e",projectId:"p",rentalType:"Operated Rental",billingMethod:"Per Kilometer",currency:"php",unitRate:35,minimumBillableHours:0,overtimeRate:0,standbyRate:0,mobilizationFee:0,demobilizationFee:0,fuelCharge:0,operatorIncluded:false,operatorRate:0,taxRate:12,withholdingTax:2,contractAmount:0,startDate:"2026-01-01",expectedEndDate:"2026-12-31",status:"Active",createdAt:"",updatedAt:"" };
const rental=(snapshot?:RentalCommercialSnapshot):RentalRecord=>({id:"r",equipmentId:"e",customer:"C",project:"P",rentedBy:"",dateOut:"2026-01-01",statusId:"",status:"Reserved",billingMethod:"Per Kilometer",commercialSnapshotRequired:true,...(snapshot?{commercialSnapshot:snapshot}:{})});

describe("Rental commercial snapshot",()=>{
 beforeEach(()=>storage.clear());
 it.each(["Per Hour","Per Day","Per Week","Per Month","Per Kilometer","Per Trip","Per Cubic Meter","One Lot"] as const)("creates detached deterministic %s terms",billingMethod=>{const input={...contract,billingMethod};const before=structuredClone(input);const result=createRentalCommercialSnapshot(input,"2026-02-27T08:15:00.000Z");expect(result).toMatchObject({success:true,snapshot:{billingMethod,unitRate:35,currency:"PHP",minimumBillableHours:0,standbyRate:0,overtimeRate:0,mobilizationFee:0,operatorIncluded:false,taxRate:12,withholdingTax:2,capturedAt:"2026-02-27T08:15:00.000Z"}});expect(input).toEqual(before);if(result.success){result.snapshot.unitRate=999;expect(input.unitRate).toBe(35);expect(()=>JSON.stringify(result.snapshot)).not.toThrow()}});
 it.each([Number.NaN,Number.POSITIVE_INFINITY])("rejects invalid numeric values",value=>expect(createRentalCommercialSnapshot({...contract,unitRate:value},"2026-02-27T08:15:00.000Z")).toMatchObject({success:false}));
 it("rejects invalid method and timestamp",()=>{expect(createRentalCommercialSnapshot({...contract,billingMethod:"Other" as never},"2026-02-27T08:15:00.000Z")).toMatchObject({success:false});expect(createRentalCommercialSnapshot(contract,"bad")).toMatchObject({success:false})});
 it("preserves an existing repository snapshot against replacement, removal, and nested mutation",()=>{const made=createRentalCommercialSnapshot(contract,"2026-02-27T08:15:00.000Z");if(!made.success)throw Error();const repo=new LocalRentalRepository();repo.create(rental(made.snapshot));const changed={...rental({...made.snapshot,unitRate:42}),commercialSnapshot:undefined};repo.update(changed);expect(repo.getById("r")?.commercialSnapshot?.unitRate).toBe(35);const read=repo.getById("r")!;read.commercialSnapshot!.unitRate=88;expect(repo.getById("r")?.commercialSnapshot?.unitRate).toBe(35)});
 it("keeps legacy records without a snapshot loadable",()=>{storage.set("equipment-rental-records",[{...rental(),commercialSnapshotRequired:undefined}]);expect(new LocalRentalRepository().getById("r")?.commercialSnapshot).toBeUndefined()});
});

describe("historical commercial calculation",()=>{
 it("uses the DEUR rate 35 after the live kilometer rate changes to 42",()=>{const made=createRentalCommercialSnapshot(contract,"2026-02-27T08:15:00.000Z");if(!made.success)throw Error();const deur:DeurRecord={id:"d",rentalId:"r",equipmentId:"e",operatorId:"o",workDate:"2026-02-27",status:"Acknowledged",legacy:false,creationSource:"OPERATOR_DIGITAL",evidenceMode:"ODOMETER_TRIP",billingMethodSnapshot:"Per Kilometer",commercialSnapshot:made.snapshot,commercialSnapshotRequired:true,odometerTripEvidence:{checkpoints:[{id:"a",location:"A",odometerReading:100},{id:"b",location:"B",odometerReading:170}],segments:[{id:"segment-a-b",startCheckpointId:"a",endCheckpointId:"b",startLocation:"A",endLocation:"B",startOdometer:100,endOdometer:170,distance:70}],startingOdometer:100,endingOdometer:170,totalDistance:70,tripCount:1},events:[],logs:[],totalOperatingMinutes:0,totalIdleMinutes:0,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,createdAt:"",updatedAt:""};const preview=createDeurBillingPreview({deur,terms:{billingMethod:"Per Kilometer",unitRate:42,operatorIncluded:true}});expect(preview).toMatchObject({status:"available",commercialTermsSource:"IMMUTABLE_SNAPSHOT",rates:{unitRate:35},charges:{operatingCharge:2450,unitRate:35}})});
 it("marks snapshot-required records without terms ineligible while legacy records use an explicit fallback",()=>{const base:DeurRecord={id:"d",rentalId:"r",equipmentId:"e",operatorId:"o",workDate:"2026-01-01",status:"Acknowledged",legacy:false,evidenceMode:"TIME_TIMELINE",billingMethodSnapshot:"Per Hour",events:[{id:"s",activityType:"shift",action:"start",timestamp:"2026-01-01T08:00:00Z",sequence:1,source:"user"},{id:"o1",activityType:"operation",action:"start",timestamp:"2026-01-01T08:00:00Z",sequence:2,source:"user"},{id:"o2",activityType:"operation",action:"end",timestamp:"2026-01-01T09:00:00Z",sequence:3,source:"user"},{id:"e",activityType:"shift",action:"end",timestamp:"2026-01-01T09:00:00Z",sequence:4,source:"user"}],logs:[],totalOperatingMinutes:60,totalIdleMinutes:0,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,createdAt:"",updatedAt:""};const terms={billingMethod:"Per Hour" as const,unitRate:100,operatorIncluded:true};expect(createDeurBillingPreview({deur:{...base,commercialSnapshotRequired:true},terms})).toMatchObject({status:"ineligible",eligibility:{reasonCodes:["COMMERCIAL_SNAPSHOT_NOT_CAPTURED"]}});expect(createDeurBillingPreview({deur:base,terms})).toMatchObject({status:"available",commercialTermsSource:"LEGACY_RENTAL_FALLBACK"})});
});
