import{beforeEach,describe,expect,it}from"vitest";
import{resolveAuthenticatedOperator}from"@/features/rental/deur/operator/resolveAuthenticatedOperator";
import{operatorUserLinkRepository}from"@/features/operators/operatorUserLink";
import{localUatUserId}from"@/features/auth/user";
import{applyDigitalDeurOperatorAction}from"@/features/rental/deur/operator/applyDigitalDeurOperatorAction";
import{deriveDeurEventState}from"@/features/rental/deur/services/deriveDeurEventState";
import{resolveRentalLinePresentation}from"@/features/rental/deur/presentation/resolveDeurPresentation";
import{developmentCustomerReviewOutbox,DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY}from"@/features/rental/customer-review/developmentCustomerReviewOutbox";
import{storage}from"@/core/storage";
import type{DeurRecord}from"@/features/rental/deur/types";

const operator={id:"operator-master",name:"UAT Operator",email:"o@test.dev",licenseNumber:"L",certificationType:"Heavy Machinery" as const,status:"Active" as const,joinedDate:"2026-01-01"};
const record:DeurRecord={id:"deur",rentalId:"rental",rentalEquipmentLineId:"line",equipmentId:"equipment",operatorId:operator.id,creationSource:"OPERATOR_DIGITAL",workDate:"2026-07-26",events:[],logs:[],totalOperatingMinutes:0,totalIdleMinutes:0,totalMaintenanceMinutes:0,totalMealBreakMinutes:0,totalMobilizationMinutes:0,totalDemobilizationMinutes:0,status:"Draft",createdAt:"2026-07-26T00:00:00Z",updatedAt:"2026-07-26T00:00:00Z"};
describe("verified UAT workflow defects",()=>{
 beforeEach(()=>storage.remove(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY));
 it("maps a persisted UAT login identity to one Operator master record",()=>{operatorUserLinkRepository.link("UAT Operator",operator.id,"2026-07-27T00:00:00Z");expect(resolveAuthenticatedOperator({id:localUatUserId("UAT Operator","Operator"),name:"UAT Operator",role:"Operator"},[operator])).toMatchObject({status:"RESOLVED",operator:{id:"operator-master"}});expect(resolveAuthenticatedOperator({id:"x",name:"Unknown",role:"Operator"},[operator])).toMatchObject({status:"NOT_LINKED",message:"This login has no Operator mapping."})});
 it("ends the canonical current activity without ending the shift and prevents duplicates",()=>{const actor={id:operator.id,name:operator.name,role:"Operator"};const started=applyDigitalDeurOperatorAction({deur:record,action:"START_OPERATION",actionTimestamp:"2026-07-26T01:00:00Z",actor});if(!started.success)throw Error(started.message);const ended=applyDigitalDeurOperatorAction({deur:started.record,action:"END_ACTIVITY",actionTimestamp:"2026-07-26T02:00:00Z",actor});if(!ended.success)throw Error(ended.message);expect(deriveDeurEventState(ended.record)).toMatchObject({shiftOpen:true,openPrimaryActivity:undefined});expect(ended.record.totals?.operationMinutes).toBe(60);expect(applyDigitalDeurOperatorAction({deur:ended.record,action:"END_ACTIVITY",actionTimestamp:"2026-07-26T02:01:00Z",actor})).toMatchObject({success:false,code:"DEUR_NO_ACTIVITY"})});
 it("uses readable compliance identity and never a UUID",()=>{const line={id:"550e8400-e29b-41d4-a716-446655440000",rentalId:"rental",equipmentId:"equipment",operatorId:operator.id,status:"Released" as const,createdAt:"",updatedAt:""};const value=resolveRentalLinePresentation(line,[line],[{id:"equipment",prefixId:"NME",assetNo:"NME-000001",equipmentName:"UAT 1",category:"Moving Equipment",status:"Rented",maintenanceType:"Engine Hours",currentReading:0,projectId:"",operatorId:""}]);expect(value.label).toBe("Rental Line 1 — UAT 1 (NME-000001)");expect(value.label).not.toContain(line.id)});
 it("creates immutable escaped Customer review requests and consumes one token",()=>{const entry=developmentCustomerReviewOutbox.create({deurId:"deur",deurNumber:"DEUR-1",revisionNumber:1,rentalNumber:"R-1",customerName:"Customer",representativeName:"Rep",representativeEmail:"rep@test.dev",snapshot:{project:"<Project>",equipment:"UAT 1",operator:"Operator",workDate:"2026-07-26",operationMinutes:60,idleMinutes:0,breakdownMinutes:0,origin:"Digital"}});expect(entry.html).toContain("&lt;Project&gt;");expect(developmentCustomerReviewOutbox.decide(entry.token,"Acknowledged")).toBe(true);expect(developmentCustomerReviewOutbox.decide(entry.token,"Acknowledged")).toBe(false)});
});
