import{describe,expect,it,vi}from"vitest";
import{readFileSync}from"node:fs";
import{TrustedNotificationWorker,type ClaimedNotification,type TrustedNotificationWorkerRepository}from"../server/notifications/TrustedNotificationWorker";

const intent:ClaimedNotification={id:"10000000-0000-4000-8000-000000000001",companyId:"TENANT-LOCAL-001",type:"CUSTOMER_GROUPED_REVIEW_REQUESTED",recipient:{destination:"controlled@example.test",displayName:"Customer"},sourceAggregateType:"CUSTOMER_REVIEW_BATCH",sourceAggregateId:"batch",templateVersion:1,idempotencyKey:"stable",input:{recipientName:"Customer",companyName:"Company",customerName:"Customer",projectName:"Project",rentalReference:"R-1",totalLineCount:1,actionableCount:1,inProgressCount:0},requiresReviewCredential:false,attempt:1};
describe("isolated UAT existing-notification dispatch",()=>{
 it("claims and delivers only the specified existing notification",async()=>{const claim=vi.fn(async()=>true),getIntent=vi.fn(async()=>intent),complete=vi.fn();const repository:TrustedNotificationWorkerRepository={claimBatch:async()=>[],claim,getIntent,complete};const provider={name:"resend",send:vi.fn(async()=>({accepted:true as const,provider:"resend",providerMessageId:"safe"}))};const worker=new TrustedNotificationWorker(repository,provider,"sender@example.test");await expect(worker.runExistingNotification(intent.id,"00000000-0000-4000-8000-000000000001")).resolves.toEqual({claimed:1,providerCalls:1});expect(claim).toHaveBeenCalledWith(intent.id,expect.any(String));expect(getIntent).toHaveBeenCalledWith(intent.id);expect(provider.send).toHaveBeenCalledOnce();expect(complete).toHaveBeenCalledWith(expect.objectContaining({id:intent.id,status:"ProviderAccepted"}));});
 it("fails closed when canonical claim rejects a duplicate or active lease",async()=>{const repository:TrustedNotificationWorkerRepository={claimBatch:async()=>[],claim:async()=>false,complete:async()=>undefined};const worker=new TrustedNotificationWorker(repository,{send:vi.fn()} as any,"sender@example.test");await expect(worker.runExistingNotification(intent.id)).resolves.toEqual({claimed:0,providerCalls:0});});
 it("requires the canonical active System Administrator role in addition to settings.update",()=>{const source=readFileSync("worker/uatNotificationDispatch.ts","utf8");expect(source).toContain('app_roles.code","system-administrator"');expect(source).toContain('app_roles.active",true');expect(source).toContain('app_roles.deprecated_at",null');expect(source).toContain('permission_code","settings.update');});
 it("keeps the dispatch route input-only, UAT-scoped, and outside review generation",()=>{const source=readFileSync("worker/uatNotificationDispatch.ts","utf8"),index=readFileSync("worker/index.ts","utf8");expect(source).toContain("Object.keys(body??{}).length!==1");expect(source).toContain("TENANT-LOCAL-001");expect(source).toContain("CUSTOMER_GROUPED_REVIEW_REQUESTED");expect(source).toContain("dispatchExistingNotification");expect(source).not.toMatch(/recipient|sender|reviewPath|credentialHash|runScheduler/);expect(index).toContain("/api/admin/uat/dispatch-existing-notification");});
});
