import { describe, expect, it } from "vitest";
import type { User } from "@/features/auth/domain/user";
import type { UserRepository } from "@/features/auth/repository/UserRepository";
import { AuthorizationError } from "@/features/auth/services/AuthorizationError";
import { UserManagementService } from "@/features/users/services/UserManagementService";
import type { Operator } from "@/features/operators/types";

const admin: User = { id:"a",username:"admin",displayName:"Admin",systemRoles:["system-administrator"],status:"active",createdAt:"",updatedAt:"" };
const manager: User = { id:"m",username:"manager",displayName:"Manager",systemRoles:["management"],status:"active",createdAt:"",updatedAt:"" };
const operator=(id:string,status:Operator["status"]="Active"):Operator=>({id,name:id,email:"",licenseNumber:"",certificationType:"None",status,joinedDate:""});

class MemoryUsers implements UserRepository {
  constructor(public records: User[] = [admin, manager]) {}
  getUsers(){return this.records.map(user=>({...user,systemRoles:[...user.systemRoles]}));}
  getUserById(id:string){return this.getUsers().find(user=>user.id===id);}
  getUserByUsername(username:string){return this.getUsers().find(user=>user.username.toLowerCase()===username.trim().toLowerCase());}
  createUser(user:User){if(this.getUserByUsername(user.username))throw Error("Username already exists");this.records.push(user);return user;}
  updateUser(user:User){if(this.records.some(item=>item.id!==user.id&&item.username.toLowerCase()===user.username.toLowerCase()))throw Error("Username already exists");this.records=this.records.map(item=>item.id===user.id?user:item);return user;}
  activateUser(id:string){return this.status(id,"active");}
  deactivateUser(id:string){return this.status(id,"inactive");}
  deleteUser(id:string){this.records=this.records.filter(user=>user.id!==id);}
  private status(id:string,status:User["status"]){const user=this.getUserById(id);if(!user)throw Error("missing");return this.updateUser({...user,status});}
}

function setup(records?:User[],operators?:Operator[],audit?:{record(event:{actor:User;targetId:string;action:string;beforeRoles?:readonly string[];afterRoles?:readonly string[];metadata?:Record<string,string>}):void}){
  const operatorRecords=operators??[operator("operator-1"),operator("operator-2"),operator("inactive-operator","Suspended")];
  const repo=new MemoryUsers(records);
  const provisioned:{user:User;password:string}[]=[];
  const service=new UserManagementService(repo,{create:(user,password)=>{provisioned.push({user,password});return repo.createUser(user);}},()=>"new-user",()=>"2026-07-28T00:00:00Z",{getById:(id)=>operatorRecords.find(item=>item.id===id)},undefined,undefined,audit);
  return{repo,service,provisioned};
}

describe("UserManagementService",()=>{
  it("lists and searches without exposing credentials",()=>{const{service}=setup();expect(service.list(admin)).toHaveLength(2);expect(service.search(admin,"MANAG")).toEqual([manager]);expect("password" in service.list(admin)[0]).toBe(false);});
  it("rejects unauthorized administration without mutation",()=>{const{repo,service}=setup();const before=repo.getUsers();expect(()=>service.create(manager,{username:"x",displayName:"X",systemRoles:["finance"],initialPassword:"secret"})).toThrow(AuthorizationError);expect(repo.getUsers()).toEqual(before);});
  it("creates a linked local user through the credential boundary",()=>{const{service,provisioned}=setup();const created=service.create(admin,{username:" operator.two ",displayName:" Operator Two ",systemRoles:["rental-operations","rental-operations"],initialPassword:"secret",operatorId:"operator-1"});expect(created).toMatchObject({id:"new-user",username:"operator.two",displayName:"Operator Two",systemRoles:["rental-operations"],operatorId:"operator-1"});expect(provisioned).toEqual([{user:created,password:"secret"}]);});
  it("preserves case-insensitive duplicate protection",()=>{const{service}=setup();expect(()=>service.create(admin,{username:"MANAGER",displayName:"Duplicate",systemRoles:["management"],initialPassword:"secret"})).toThrow("Username already exists");});
  it("enforces normalized tenant email identity without partial creation or misleading audit",()=>{const existing:User={...manager,email:"abc.pco@lightstrong.com.ph"};const events:string[]=[];const{repo,service,provisioned}=setup([admin,existing],undefined,{record:event=>events.push(event.action)});for(const email of ["abc.pco@lightstrong.com.ph","ABC.PCO@LIGHTSTRONG.COM.PH"," abc.pco@lightstrong.com.ph "]){expect(()=>service.create(admin,{username:`unique-${email.length}`,displayName:"Duplicate",email,systemRoles:["auditor"],initialPassword:"secret"})).toThrow("Email already exists. This email is assigned to Manager (manager). Edit the existing user and assign additional roles instead.")}expect(repo.getUsers()).toHaveLength(2);expect(provisioned).toHaveLength(0);expect(events).not.toContain("USER_CREATED")});
  it("allows unique identities, multiple roles, and multiple missing legacy emails",()=>{const legacyTwo:User={...manager,id:"m2",username:"manager2"};const{service}=setup([admin,manager,legacyTwo]);const created=service.create(admin,{username:" unique.person ",displayName:"Unique Person",email:" Person@Example.COM ",systemRoles:["dispatcher","auditor","dispatcher"],initialPassword:"secret"});expect(created).toMatchObject({username:"unique.person",email:"person@example.com",systemRoles:["dispatcher","auditor"]})});
  it("allows retaining normalized own email but rejects another user's email on edit",()=>{const first:User={...manager,email:"first@example.com"},second:User={...manager,id:"m2",username:"second",displayName:"Second",email:"second@example.com"};const{service}=setup([admin,first,second]);expect(service.update(admin,"m",{username:"manager",displayName:"Manager",email:" FIRST@EXAMPLE.COM ",systemRoles:["management"]}).email).toBe("first@example.com");expect(()=>service.update(admin,"m",{username:"manager",displayName:"Manager",email:" SECOND@example.com ",systemRoles:["management"]})).toThrow("Email already exists. This email is assigned to Second (second)")});
  it("rejects changing a username to another tenant user's normalized username",()=>{const second:User={...manager,id:"m2",username:"second"};const{service}=setup([admin,manager,second]);expect(()=>service.update(admin,"m",{username:" SECOND ",displayName:"Manager",systemRoles:["management"]})).toThrow("Username already exists.")});
  it("edits identity, roles, and operator linkage",()=>{const{service}=setup();expect(service.update(admin,"m",{username:"leader",displayName:"Leader",systemRoles:["rental-operations"],operatorId:"operator-1"})).toMatchObject({username:"leader",systemRoles:["rental-operations"],operatorId:"operator-1"});});
  it("rejects missing, inactive, role-incompatible, and duplicate active links",()=>{const linked:User={...manager,id:"linked",username:"linked",systemRoles:["rental-operations"],operatorId:"operator-1"};const{service}=setup([admin,manager,linked]);expect(()=>service.update(admin,"m",{username:"manager",displayName:"Manager",systemRoles:["rental-operations"],operatorId:"missing"})).toThrow("active canonical Operator");expect(()=>service.update(admin,"m",{username:"manager",displayName:"Manager",systemRoles:["rental-operations"],operatorId:"inactive-operator"})).toThrow("active canonical Operator");expect(()=>service.update(admin,"m",{username:"manager",displayName:"Manager",systemRoles:["management"],operatorId:"operator-2"})).toThrow("Only a Rental Operations");expect(()=>service.update(admin,"m",{username:"manager",displayName:"Manager",systemRoles:["rental-operations"],operatorId:"operator-1"})).toThrow("already linked");});
  it("prevents self-deactivation",()=>{const{service}=setup();expect(()=>service.deactivate(admin,"a")).toThrow("own active account");});
  it("does not revalidate duplicate legacy email for deactivate, reactivate, or reset access",()=>{const duplicate={...manager,id:"m2",username:"manager2",email:" same@example.com "},first={...manager,email:"SAME@EXAMPLE.COM"};const events:string[]=[];const repo=new MemoryUsers([admin,first,duplicate]);const service=new UserManagementService(repo,{create:user=>repo.createUser(user),replacePassword:id=>repo.getUserById(id)!},()=>"id",()=>"now",undefined,undefined,undefined,{record:event=>events.push(event.action)});expect(service.deactivate(admin,"m2").status).toBe("inactive");expect(service.activate(admin,"m2").status).toBe("active");expect(service.resetLocalPassword(admin,"m2",{newPassword:"Replacement2!",confirmNewPassword:"Replacement2!"}).id).toBe("m2");expect(events).toEqual(["USER_DEACTIVATED","USER_ACTIVATED","USER_ACCESS_RESET"])});
  it("deletes only clean non-self users, preserves operator master, and emits safe audit",()=>{const linked={...manager,id:"test",username:"test",operatorId:"operator-1"},events:{action:string;metadata?:Record<string,string>}[]=[];const{repo,service}=setup([admin,manager,linked],undefined,{record:event=>events.push({action:event.action,metadata:event.metadata})});service.delete(admin,"test");expect(repo.getUserById("test")).toBeUndefined();expect(events).toEqual([{action:"USER_DELETED",metadata:{username:"test"}}]);expect(()=>service.delete(admin,"a")).toThrow("own signed-in account")});
  it("blocks deletion when business or meaningful audit history exists",()=>{const target={...manager,id:"history",username:"history"},repo=new MemoryUsers([admin,target]),service=new UserManagementService(repo,{create:user=>repo.createUser(user)},()=>"id",()=>"now",undefined,undefined,undefined,undefined,{hasBusinessReferences:user=>user.id==="history",hasBlockingAuditHistory:()=>false});expect(()=>service.delete(admin,"history")).toThrow("business or audit history exists");expect(repo.getUserById("history")).toBeDefined()});
  it("blocks deletion of the final active System Administrator",()=>{const external={...admin,id:"external",username:"external"},repo=new MemoryUsers([admin,manager]),service=new UserManagementService(repo,{create:user=>repo.createUser(user)});expect(()=>service.delete(external,"a")).toThrow("retain at least one active System Administrator");expect(repo.getUserById("a")).toBeDefined()});
  it("retains at least one active System Administrator",()=>{const second={...admin,id:"b",username:"admin2"};const{service}=setup([admin,second,manager]);expect(service.deactivate(admin,"b").status).toBe("inactive");expect(()=>service.update(admin,"a",{username:"admin",displayName:"Admin",systemRoles:["management"]})).toThrow("final active System Administrator");});
});
