import ResponsiveTable from "@/components/ui/ResponsiveTable";
import type { InvoiceDocument } from "./InvoiceDocumentBuilder";

const money = (value: number, currency: string) => new Intl.NumberFormat("en-PH", { style: "currency", currency }).format(value);
export default function InvoiceDocumentView({ document }: { document: InvoiceDocument }) {
  return <article className="invoice-document rounded-xl border bg-white p-4 sm:p-6">
    <div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-bold">Billing Statement / Invoice {document.statementNo}</h2><p className="text-sm text-slate-600">Rental {document.rentalId} · {document.customer} · {document.project}</p><p className="text-sm text-slate-600">{document.billingFrom} – {document.billingTo} · Statement date {document.statementDate.slice(0, 10)}</p></div><div className="text-right"><div className="font-semibold">{document.status}</div><button type="button" className="print:hidden mt-2 rounded border px-3 py-1 text-sm" onClick={() => window.print()}>Print</button></div></div>
    {document.warnings.length > 0 && <div className="mt-4 rounded border border-amber-300 bg-amber-50 p-3 text-sm"><div className="font-semibold">Reconciliation / historical warnings</div><ul className="mt-1 list-disc pl-5">{document.warnings.map((warning, index) => <li key={`${warning.code}-${warning.lineId ?? index}`}>{warning.message}</li>)}</ul></div>}
    <ResponsiveTable><table className="mt-5 min-w-max text-xs"><thead className="bg-slate-100"><tr>{["Equipment", "Operator", "DEUR", "Date / Shift", "Description", "Method", "Qty / Hours", "Rate", "Operating", "Optional charges", "Subtotal", "VAT", "WHT", "Grand total"].map((heading) => <th key={heading} className="px-2 py-2 text-left">{heading}</th>)}</tr></thead><tbody>{document.lines.map((line) => <tr key={line.id ?? line.deurId} className="border-t align-top"><td className="px-2 py-2"><div className="font-medium">{line.equipmentLabel}</div><div>{line.equipmentDescription}</div></td><td className="px-2 py-2">{line.operatorLabel}</td><td className="px-2 py-2">{line.deurId}</td><td className="px-2 py-2">{line.workDate}{line.shift ? ` / ${line.shift}` : ""}</td><td className="px-2 py-2">{line.description}</td><td className="px-2 py-2">{line.billingMethod ?? "—"}</td><td className="px-2 py-2 text-right">{line.quantity !== undefined ? `${line.quantity} ${line.unit ?? ""}` : `${line.hours} h`}</td><td className="px-2 py-2 text-right">{money(line.unitRate ?? line.hourlyRate, document.currency)}</td><td className="px-2 py-2 text-right">{money(line.operatingCharge ?? line.amount, document.currency)}</td><td className="px-2 py-2">{line.optionalCharges.length ? line.optionalCharges.map((charge) => <div key={charge.label}>{charge.label}: {money(charge.amount, document.currency)}</div>) : "—"}</td><td className="px-2 py-2 text-right">{money(line.amount, document.currency)}</td><td className="px-2 py-2 text-right">{money(line.vat ?? 0, document.currency)}</td><td className="px-2 py-2 text-right">{money(line.withholdingTax ?? 0, document.currency)}</td><td className="px-2 py-2 text-right font-semibold">{money(line.grandTotal ?? line.amount, document.currency)}</td></tr>)}</tbody></table></ResponsiveTable>
    <dl className="ml-auto mt-5 grid max-w-sm grid-cols-2 gap-x-6 gap-y-2 text-sm"><dt>Subtotal</dt><dd className="text-right">{money(document.subtotal, document.currency)}</dd><dt>VAT</dt><dd className="text-right">{money(document.vat, document.currency)}</dd><dt>Withholding tax</dt><dd className="text-right">{money(document.withholdingTax, document.currency)}</dd><dt className="font-bold">Grand total</dt><dd className="text-right font-bold">{money(document.grandTotal, document.currency)}</dd>{document.amountCollected !== undefined && <><dt>Amount collected</dt><dd className="text-right">{money(document.amountCollected, document.currency)}</dd></>}{document.outstandingBalance !== undefined && <><dt>Outstanding balance</dt><dd className="text-right">{money(document.outstandingBalance, document.currency)}</dd></>}</dl>
  </article>;
}
