import type { BillingStatement, BillingStatementLine } from "@/features/rental/billingstatement/types";
import type { EquipmentRecord } from "@/features/equipment/types";
import type { Operator } from "@/features/operators/types";

export interface InvoiceDocumentWarning { code: "LEGACY_HEADER_ONLY" | "LINE_IDENTITY_INCOMPLETE" | "AMBIGUOUS_HISTORICAL_EQUIPMENT" | "SUBTOTAL_MISMATCH" | "VAT_MISMATCH" | "WITHHOLDING_MISMATCH" | "GRAND_TOTAL_MISMATCH"; message: string; lineId?: string }
export interface InvoiceDocumentLine extends BillingStatementLine { equipmentLabel: string; equipmentDescription?: string; operatorLabel: string; optionalCharges: Array<{ label: string; amount: number }> }
export interface InvoiceDocument { billingStatementId: string; statementNo: string; rentalId: string; rentalNumber: string; customer: string; customerRepresentativeName?: string; customerRepresentativeEmail?: string; project: string; billingFrom: string; billingTo: string; statementDate: string; status: BillingStatement["invoiceStatus"]; currency: string; lines: InvoiceDocumentLine[]; optionalChargeTotals: Array<{label:string;amount:number}>; subtotal: number; vatApplicable: boolean; vat?: number; withholdingTaxApplicable: boolean; withholdingTax?: number; grandTotal: number; amountCollected?: number; outstandingBalance?: number; warnings: InvoiceDocumentWarning[] }

const sum = (lines: BillingStatementLine[], field: "amount" | "vat" | "withholdingTax" | "grandTotal") => lines.reduce((total, line) => total + (line[field] ?? (field === "grandTotal" ? line.amount : 0)), 0);

/** Builds a read-only accounting document exclusively from persisted statement values. */
export function buildInvoiceDocument(statement: BillingStatement, equipment: EquipmentRecord[] = [], operators: Operator[] = [], currency = "PHP", collection?: { amountCollected: number; outstandingBalance: number }): InvoiceDocument {
  const warnings: InvoiceDocumentWarning[] = [];
  if (!Array.isArray(statement.lines) || statement.lines.length === 0) warnings.push({ code: "LEGACY_HEADER_ONLY", message: "This historical document has header totals only; detailed rows were not fabricated." });
  const distinctLineEquipment = new Set((statement.lines ?? []).map((line) => line.equipmentId).filter(Boolean));
  const lines = (statement.lines ?? []).map((line) => {
    if (!line.rentalEquipmentLineId || !line.equipmentId || !line.deurId) warnings.push({ code: "LINE_IDENTITY_INCOMPLETE", lineId: line.id ?? line.deurId, message: "Historical statement line does not contain complete Rental Equipment Line identity." });
    const equipmentId = line.equipmentId || (distinctLineEquipment.size === 0 ? statement.equipmentId : "");
    if (!equipmentId && distinctLineEquipment.size > 1) warnings.push({ code: "AMBIGUOUS_HISTORICAL_EQUIPMENT", lineId: line.id ?? line.deurId, message: "Historical equipment identity is ambiguous and was not inferred." });
    const machine = equipment.find((item) => item.id === equipmentId); const operator = operators.find((item) => item.id === line.operatorId);
    const optionalCharges = [["Idle", line.idleCharge], ["Standby", line.standbyCharge], ["Mobilization", line.mobilizationCharge], ["Demobilization", line.demobilizationCharge], ["Operator", line.operatorCharge], ["Fuel", line.fuelCharge]].filter((item): item is [string, number] => typeof item[1] === "number" && item[1] > 0).map(([label, amount]) => ({ label, amount }));
    return { ...structuredClone(line), equipmentLabel: line.equipmentLabel ?? (machine ? `${machine.equipmentName} (${machine.assetNo})` : "Equipment record unavailable"), equipmentDescription: machine?.equipmentName, operatorLabel: line.operatorLabel ?? operator?.name ?? "Operator not assigned", deurReference: line.deurReference ?? "DEUR reference unavailable", optionalCharges };
  });
  const checks = [{ code: "SUBTOTAL_MISMATCH" as const, actual: sum(statement.lines ?? [], "amount"), expected: statement.subtotal, label: "subtotal" }, { code: "VAT_MISMATCH" as const, actual: sum(statement.lines ?? [], "vat"), expected: statement.vat ?? 0, label: "VAT" }, { code: "WITHHOLDING_MISMATCH" as const, actual: sum(statement.lines ?? [], "withholdingTax"), expected: statement.withholdingTax ?? 0, label: "withholding tax" }, { code: "GRAND_TOTAL_MISMATCH" as const, actual: sum(statement.lines ?? [], "grandTotal"), expected: statement.grandTotal ?? statement.subtotal, label: "grand total" }];
  for (const check of checks) if (check.actual !== check.expected) warnings.push({ code: check.code, message: `Persisted line ${check.label} (${check.actual}) does not reconcile to the statement ${check.label} (${check.expected}).` });
  const vatApplicable = statement.vatApplicable ?? statement.vat !== undefined;
  const withholdingTaxApplicable = statement.withholdingTaxApplicable ?? statement.withholdingTax !== undefined;
  const optionalChargeTotals = [...lines.flatMap(line=>line.optionalCharges).reduce((totals,charge)=>totals.set(charge.label,(totals.get(charge.label)??0)+charge.amount),new Map<string,number>())].map(([label,amount])=>({label,amount}));
  return { billingStatementId: statement.id, statementNo: statement.statementNo, rentalId: statement.rentalId, rentalNumber: statement.rentalNumber ?? "Rental number unavailable", customer: statement.customer, customerRepresentativeName: statement.customerRepresentativeName, customerRepresentativeEmail: statement.customerRepresentativeEmail, project: statement.project, billingFrom: statement.billingFrom, billingTo: statement.billingTo, statementDate: statement.createdAt, status: statement.invoiceStatus, currency, lines, optionalChargeTotals, subtotal: statement.subtotal, vatApplicable, ...(vatApplicable && statement.vat !== undefined ? { vat: statement.vat } : {}), withholdingTaxApplicable, ...(withholdingTaxApplicable && statement.withholdingTax !== undefined ? { withholdingTax: statement.withholdingTax } : {}), grandTotal: statement.grandTotal ?? statement.subtotal, amountCollected: collection?.amountCollected, outstandingBalance: collection?.outstandingBalance, warnings };
}
