import { useMemo, useState } from "react";
import { AuthorizationAuditService } from "../services/AuthorizationAuditService";

const labels:Record<string,string>={ROLE_PERMISSION_ADDED:"Permission Added to Role",ROLE_PERMISSION_REMOVED:"Permission Removed from Role",ROLE_PERMISSIONS_RESET:"Role Permissions Reset",USER_CREATED:"User Created",USER_UPDATED:"User Updated",USER_ACTIVATED:"User Activated",USER_DEACTIVATED:"User Deactivated",USER_ROLE_ASSIGNED:"Role Assigned to User",USER_ROLE_REMOVED:"Role Removed from User",USER_OPERATOR_LINKED:"Operator Linked to User",USER_OPERATOR_UNLINKED:"Operator Unlinked from User",USER_ACCESS_RESET:"User Access Reset",USER_DELETED:"User Deleted",ROLE_CLONED:"Role Cloned",CUSTOM_ROLE_CREATED:"Custom Role Created",CUSTOM_ROLE_UPDATED:"Custom Role Updated",CUSTOM_ROLE_DEACTIVATED:"Custom Role Deactivated"};
const localTime=(iso:string)=>new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(iso));
export default function AuditTrailPage(){
 const service=useMemo(()=>new AuthorizationAuditService(),[]),events=service.all();
 const [search,setSearch]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[action,setAction]=useState("all"),[actor,setActor]=useState("all"),[target,setTarget]=useState(""),[pageSize,setPageSize]=useState(25),[page,setPage]=useState(1);
 const resetPage=()=>setPage(1),actions=[...new Set(events.map(x=>x.action))].sort(),actors=[...new Set(events.map(x=>x.actorId))].sort();
 const filtered=events.filter(event=>{const text=`${event.actorId} ${event.targetType} ${event.targetId} ${event.action} ${labels[event.action]??""} ${Object.values(event.metadata??{}).join(" ")}`.toLowerCase(),day=event.occurredAt.slice(0,10);return(!search||text.includes(search.toLowerCase()))&&(!from||day>=from)&&(!to||day<=to)&&(action==="all"||event.action===action)&&(actor==="all"||event.actorId===actor)&&(!target||`${event.targetType} ${event.targetId}`.toLowerCase().includes(target.toLowerCase()))}).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)||b.id.localeCompare(a.id));
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,pages),start=(safePage-1)*pageSize,shown=filtered.slice(start,start+pageSize);
 const clear=()=>{setSearch("");setFrom("");setTo("");setAction("all");setActor("all");setTarget("");setPage(1)};
 const details=(event:typeof events[number])=>{const permission=event.metadata?.permissionCode,roleChange=event.beforeRoleCodes||event.afterRoleCodes;return <>{permission&&<span className="block">Permission: <code>{String(permission)}</code></span>}{event.targetType==="ROLE"&&<span className="block">Role: {event.targetId}</span>}{roleChange&&<span className="block">{event.beforeRoleCodes?.join(", ")||"—"} → {event.afterRoleCodes?.join(", ")||"—"}</span>}{!permission&&!roleChange&&event.targetType!=="ROLE"&&<span>—</span>}</>};
 return <main className="space-y-6"><header><h1 className="text-2xl font-bold">Authorization Audit Trail</h1><p>Find and review safe evidence of user and role administration changes. Audit events are never deleted by this screen.</p></header>
 <section aria-label="Audit filters" className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-3 xl:grid-cols-6"><label htmlFor="audit-search">Search<input id="audit-search" className="mt-1 block w-full rounded border p-2" value={search} onChange={e=>{setSearch(e.target.value);resetPage()}}/></label><label htmlFor="audit-from">Date From<input id="audit-from" type="date" className="mt-1 block w-full rounded border p-2" value={from} onChange={e=>{setFrom(e.target.value);resetPage()}}/></label><label htmlFor="audit-to">Date To<input id="audit-to" type="date" className="mt-1 block w-full rounded border p-2" value={to} onChange={e=>{setTo(e.target.value);resetPage()}}/></label><label htmlFor="audit-action">Action<select id="audit-action" className="mt-1 block w-full rounded border p-2" value={action} onChange={e=>{setAction(e.target.value);resetPage()}}><option value="all">All Actions</option>{actions.map(x=><option key={x}>{x}</option>)}</select></label><label htmlFor="audit-actor">Actor<select id="audit-actor" className="mt-1 block w-full rounded border p-2" value={actor} onChange={e=>{setActor(e.target.value);resetPage()}}><option value="all">All Actors</option>{actors.map(x=><option key={x}>{x}</option>)}</select></label><label htmlFor="audit-target">Target<input id="audit-target" className="mt-1 block w-full rounded border p-2" value={target} onChange={e=>{setTarget(e.target.value);resetPage()}}/></label><button className="rounded border px-3 py-2 md:self-end" onClick={clear}>Clear Filters</button></section>
 <div className="flex flex-wrap items-center justify-between gap-3"><p>Showing {filtered.length?start+1:0}–{Math.min(start+pageSize,filtered.length)} of {filtered.length} events</p><label htmlFor="audit-page-size">Rows per page<select id="audit-page-size" className="ml-2 rounded border p-2" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[25,50,100].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3" scope="col">Date &amp; Time</th><th className="p-3" scope="col">Action</th><th className="p-3" scope="col">Actor</th><th className="p-3" scope="col">Target</th><th className="p-3" scope="col">Change / Details</th></tr></thead><tbody>{shown.map(event=><tr className="border-t align-top" key={event.id}><td className="p-3" title={event.occurredAt}>{localTime(event.occurredAt)}</td><td className="p-3"><b>{labels[event.action]??event.action}</b><code className="block text-xs text-slate-500">{event.action}</code></td><td className="p-3">{event.actorId}</td><td className="p-3">{event.targetType} {event.targetId}</td><td className="p-3">{details(event)}</td></tr>)}</tbody></table>{!shown.length&&<p className="p-6 text-center text-slate-500">No audit events match the selected filters.</p>}</div>
 <nav aria-label="Audit pagination" className="flex items-center justify-center gap-3"><button className="rounded border px-3 py-2" aria-label="Previous audit page" disabled={safePage<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>Previous</button><span>Page {safePage} of {pages}</span><button className="rounded border px-3 py-2" aria-label="Next audit page" disabled={safePage>=pages} onClick={()=>setPage(x=>Math.min(pages,x+1))}>Next</button></nav></main>
}
