import { useMemo,useState } from "react";
import Button from "@/components/ui/Button";
import ResponsiveTable from "@/components/ui/ResponsiveTable";
import { LocalUserRepository } from "@/features/auth/repository/LocalUserRepository";
import { AuthorizationAuditService } from "../services/AuthorizationAuditService";
import { CanonicalRoleAdministrationService } from "../services/CanonicalRoleAdministrationService";
import { presentAuditEvent } from "../services/auditPresentation";

const localTime=(iso:string)=>new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(iso));
export default function AuditTrailPage(){
 const model=useMemo(()=>{const userRepository=new LocalUserRepository(),users=userRepository.getUsers(),roles=new CanonicalRoleAdministrationService(undefined,userRepository).listRoles(),events=new AuthorizationAuditService().all();return events.map(event=>({event,presentation:presentAuditEvent(event,users,roles)}))},[]);
 const [search,setSearch]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[action,setAction]=useState("all"),[actor,setActor]=useState("all"),[target,setTarget]=useState(""),[pageSize,setPageSize]=useState(20),[page,setPage]=useState(1);const resetPage=()=>setPage(1),actions=[...new Set(model.map(x=>x.event.action))].sort(),actors=[...new Map(model.map(x=>[x.event.actorId,x.presentation.actor])).entries()].sort((a,b)=>a[1].primary.localeCompare(b[1].primary));
 const filtered=model.filter(({event,presentation})=>{const day=event.occurredAt.slice(0,10);return(!search||presentation.searchText.includes(search.trim().toLowerCase()))&&(!from||day>=from)&&(!to||day<=to)&&(action==="all"||event.action===action)&&(actor==="all"||event.actorId===actor)&&(!target||`${presentation.target.primary} ${presentation.target.secondary} ${presentation.target.technicalId}`.toLowerCase().includes(target.toLowerCase()))}).sort((a,b)=>b.event.occurredAt.localeCompare(a.event.occurredAt)||b.event.id.localeCompare(a.event.id));
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,pages),start=(safePage-1)*pageSize,shown=filtered.slice(start,start+pageSize);const clear=()=>{setSearch("");setFrom("");setTo("");setAction("all");setActor("all");setTarget("");setPage(1)};
 return <main className="app-page"><header><h1 className="text-2xl font-bold">Authorization Audit Trail</h1><p className="text-slate-500">Who changed what, to whom, and when. Immutable IDs remain available as secondary evidence.</p></header>
 <section aria-label="Audit filters" className="app-card grid gap-3 p-4 md:grid-cols-3 xl:grid-cols-6"><label htmlFor="audit-search">Search<input id="audit-search" aria-label="Search audit identities and events" className="app-control mt-1 block w-full" value={search} onChange={e=>{setSearch(e.target.value);resetPage()}}/></label><label htmlFor="audit-from">Date From<input id="audit-from" type="date" className="app-control mt-1 block w-full" value={from} onChange={e=>{setFrom(e.target.value);resetPage()}}/></label><label htmlFor="audit-to">Date To<input id="audit-to" type="date" className="app-control mt-1 block w-full" value={to} onChange={e=>{setTo(e.target.value);resetPage()}}/></label><label htmlFor="audit-action">Action<select id="audit-action" className="app-control mt-1 block w-full" value={action} onChange={e=>{setAction(e.target.value);resetPage()}}><option value="all">All Actions</option>{actions.map(x=><option value={x} key={x}>{model.find(item=>item.event.action===x)?.presentation.actionLabel??x}</option>)}</select></label><label htmlFor="audit-actor">Actor<select id="audit-actor" className="app-control mt-1 block w-full" value={actor} onChange={e=>{setActor(e.target.value);resetPage()}}><option value="all">All Actors</option>{actors.map(([id,identity])=><option value={id} key={id}>{identity.primary} ({identity.secondary})</option>)}</select></label><label htmlFor="audit-target">Target<input id="audit-target" className="app-control mt-1 block w-full" value={target} onChange={e=>{setTarget(e.target.value);resetPage()}}/></label><Button variant="secondary" className="md:self-end" onClick={clear}>Clear Filters</Button></section>
 <div className="flex flex-wrap items-center justify-between gap-3"><p>Showing {filtered.length?start+1:0}–{Math.min(start+pageSize,filtered.length)} of {filtered.length} events</p><label htmlFor="audit-page-size">Rows per page<select id="audit-page-size" className="app-control ml-2" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[20,50,100].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <ResponsiveTable><div className="app-card min-w-[900px] overflow-hidden"><table className="app-table w-full text-left text-sm"><thead><tr><th className="p-3" scope="col">Date &amp; Time</th><th className="p-3" scope="col">Action</th><th className="p-3" scope="col">Actor</th><th className="p-3" scope="col">Target</th><th className="p-3" scope="col">Details</th></tr></thead><tbody>{shown.map(({event,presentation})=><tr className="align-top" key={event.id}><td className="p-3" title={event.occurredAt}>{localTime(event.occurredAt)}</td><td className="p-3"><b>{presentation.actionLabel}</b><code className="block text-xs text-slate-500">{event.action}</code></td><td className="p-3"><b className="block">{presentation.actor.primary}</b><span className="block">{presentation.actor.secondary}</span><code className="block text-xs text-slate-500">{presentation.actor.technicalId}</code></td><td className="p-3"><b className="block">{presentation.target.primary}</b><span className="block">{presentation.target.secondary}</span><code className="block text-xs text-slate-500">ID: {presentation.target.technicalId}</code></td><td className="p-3">{presentation.details.map((detail,index)=><span className="block" key={index}>{detail}</span>)}</td></tr>)}</tbody></table>{!shown.length&&<p className="p-6 text-center text-slate-500">No audit events match the selected filters.</p>}</div></ResponsiveTable>
 <nav aria-label="Audit pagination" className="flex items-center justify-center gap-3"><Button variant="secondary" aria-label="Previous audit page" disabled={safePage<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>Previous</Button><span>Page {safePage} of {pages}</span><Button variant="secondary" aria-label="Next audit page" disabled={safePage>=pages} onClick={()=>setPage(x=>Math.min(pages,x+1))}>Next</Button></nav></main>;
}
