import { useMemo, useState } from "react";
import { CanonicalRoleAdministrationService } from "../services/CanonicalRoleAdministrationService";

const title=(code:string)=>code.replace(/([a-z])([A-Z])/g,"$1 $2").split(/[. -]/).map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(" ");
const actionNames:Record<string,string>={read:"View",create:"Create",update:"Update",delete:"Delete",approve:"Approve",close:"Close",export:"Export"};
const permissionName=(permission:{code:string;resource:string;action:string;description:string})=>permission.code.split(".").length===2?`${actionNames[permission.action]??title(permission.action)} ${title(permission.resource)}`:permission.description||title(permission.code);
export default function PermissionsPage(){
 const service=useMemo(()=>new CanonicalRoleAdministrationService(),[]),permissions=service.listPermissions(),roles=service.listRoles(),groups=service.getPermissionGroups();
 const [search,setSearch]=useState(""),[module,setModule]=useState("all"),[action,setAction]=useState("all"),[risk,setRisk]=useState("all"),[state,setState]=useState("all"),[assignedRole,setAssignedRole]=useState("all");
 const actions=[...new Set(permissions.map(p=>p.action))].sort(),risks=[...new Set(permissions.map(p=>p.riskClass))].sort();
 const filtered=permissions.filter(p=>{const group=groups.find(g=>g.resources.includes(p.resource));const assigned=roles.filter(r=>r.permissions.includes(p.code));return (!search||`${p.description} ${p.code}`.toLowerCase().includes(search.toLowerCase()))&&(module==="all"||group?.code===module)&&(action==="all"||p.action===action)&&(risk==="all"||p.riskClass===risk)&&(state==="all"||(state==="active"?!p.deprecated&&p.active:p.deprecated))&&(assignedRole==="all"||assigned.some(r=>r.code===assignedRole))});
 return <main className="space-y-6"><header><h1 className="text-2xl font-bold">Permissions</h1><p>Permissions define individual system capabilities. Permissions are assigned to roles, not directly to users.</p><p className="text-sm text-slate-600">Read-only catalog {service.catalogVersion}</p></header>
 <section aria-label="Permission filters" className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-3"><label htmlFor="permission-search">Search permissions<input id="permission-search" type="search" className="mt-1 block w-full rounded border p-2" value={search} onChange={e=>setSearch(e.target.value)}/></label><label htmlFor="permission-module">Module<select id="permission-module" className="mt-1 block w-full rounded border p-2" value={module} onChange={e=>setModule(e.target.value)}><option value="all">All Modules</option>{groups.map(g=><option value={g.code} key={g.code}>{g.label}</option>)}</select></label><label htmlFor="permission-action">Action<select id="permission-action" className="mt-1 block w-full rounded border p-2" value={action} onChange={e=>setAction(e.target.value)}><option value="all">All Actions</option>{actions.map(x=><option key={x}>{x}</option>)}</select></label><label htmlFor="permission-risk">Risk<select id="permission-risk" className="mt-1 block w-full rounded border p-2" value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">All Risk Levels</option>{risks.map(x=><option key={x}>{x}</option>)}</select></label><label htmlFor="permission-state">State<select id="permission-state" className="mt-1 block w-full rounded border p-2" value={state} onChange={e=>setState(e.target.value)}><option value="all">All</option><option value="active">Active</option><option value="deprecated">Deprecated</option></select></label><label htmlFor="permission-role">Assigned Role<select id="permission-role" className="mt-1 block w-full rounded border p-2" value={assignedRole} onChange={e=>setAssignedRole(e.target.value)}><option value="all">All Roles</option>{roles.map(r=><option value={r.code} key={r.code}>{r.name}</option>)}</select></label></section>
 <p aria-live="polite">{filtered.length} permissions match the current filters.</p>{groups.map(group=>{const items=filtered.filter(p=>group.resources.includes(p.resource));if(!items.length)return null;return <details open key={group.code} className="rounded-xl border bg-white"><summary className="cursor-pointer p-4 text-lg font-semibold">{group.label} ({items.length})</summary><div className="overflow-x-auto border-t"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3" scope="col">Permission</th><th className="p-3" scope="col">Action</th><th className="p-3" scope="col">Risk</th><th className="p-3" scope="col">Status</th><th className="p-3" scope="col">Assigned Roles</th></tr></thead><tbody>{items.map(p=>{const assigned=roles.filter(r=>r.permissions.includes(p.code));return <tr className="border-t align-top" key={p.code}><td className="p-3"><span className="font-medium">{permissionName(p)}</span><span className="mt-1 block text-xs text-slate-600">{p.description}</span><code className="mt-1 block text-xs text-slate-500">{p.code}</code></td><td className="p-3 uppercase">{p.action}</td><td className="p-3"><span className="rounded-full border px-2 py-1 font-medium uppercase">{p.riskClass}</span></td><td className="p-3"><span className="font-medium">{p.deprecated?"Deprecated":p.active?"Active":"Inactive"}</span>{p.deprecated&&<span className="mt-1 block text-xs"><b>Replacement:</b> {p.replacementPermissions.length?p.replacementPermissions.join(", "):"None"}</span>}</td><td className="p-3"><div className="flex flex-wrap gap-1">{assigned.slice(0,3).map(r=><span className="rounded-full border bg-slate-100 px-2 py-0.5" key={r.code}>{r.name}</span>)}{assigned.length>3&&<span className="rounded-full border px-2 py-0.5">+{assigned.length-3} more</span>}{!assigned.length&&"None"}</div></td></tr>})}</tbody></table></div></details>})}{!filtered.length&&<p className="rounded-xl border bg-white p-6 text-center text-slate-500">No permissions match the selected filters.</p>}</main>
}
