import { useEffect, useMemo, useState } from "react";
import type { RemoteUserAdministration } from "@/features/users/services/RemoteUserAdministration";
import type { User } from "@/features/auth/domain/user";

export function RemoteRolesPage({administration}:{administration:RemoteUserAdministration}){
  const [roles,setRoles]=useState<Awaited<ReturnType<RemoteUserAdministration["listRoles"]>>>([]);
  const [users,setUsers]=useState<readonly User[]>([]);
  const [selected,setSelected]=useState("");
  const [error,setError]=useState("");
  useEffect(()=>{let active=true;void Promise.all([administration.listRoles(),administration.listUsers()]).then(([nextRoles,nextUsers])=>{if(!active)return;setRoles(nextRoles);setUsers(nextUsers);setSelected(current=>current&&nextRoles.some(role=>role.code===current)?current:(nextRoles.find(role=>role.code==="system-administrator")?.code??nextRoles[0]?.code??""))}).catch(value=>{if(active)setError(value instanceof Error?value.message:"Unable to load runtime roles.")});return()=>{active=false}},[administration]);
  const role=roles.find(item=>item.code===selected),assigned=useMemo(()=>users.filter(user=>user.systemRoles.includes(selected)),[selected,users]);
  return <main className="space-y-6"><header><h1 className="text-2xl font-bold">Roles</h1><p>Runtime roles and effective permission mappings from the canonical database.</p></header>{error&&<p role="alert" className="text-red-700">{error}</p>}<label className="block max-w-xl" htmlFor="runtime-role-selector"><span className="font-semibold">Role</span><select id="runtime-role-selector" className="mt-1 block w-full rounded border bg-white p-3" value={selected} onChange={event=>setSelected(event.target.value)}>{roles.map(item=><option key={item.code} value={item.code}>{item.name}{item.deprecatedAt?" — Deprecated compatibility":""}</option>)}</select></label>{role&&<section aria-label="Selected runtime role details" className="space-y-4 rounded-xl border bg-white p-5"><div><h2 className="text-xl font-semibold">{role.name}</h2><code>{role.code}</code><p className="mt-2 text-sm text-slate-600">{role.permissions.length} effective permissions · {assigned.length} assigned {assigned.length===1?"user":"users"} · Catalog {role.catalogVersion??"runtime"}</p><p className="mt-1 text-sm">Status: {role.active?"Active":"Inactive"}{role.deprecatedAt?" · Deprecated compatibility role":""}</p></div><div><h3 className="font-semibold">Effective Runtime Permissions</h3><ul className="mt-2 grid gap-2 sm:grid-cols-2">{role.permissions.map(permission=><li className="rounded border p-2" key={permission}><code>{permission}</code></li>)}</ul>{!role.permissions.length&&<p className="text-slate-500">No active permissions are assigned.</p>}</div><div><h3 className="font-semibold">Assigned Users</h3>{assigned.length?<ul>{assigned.map(user=><li key={user.id}>{user.displayName} ({user.username})</li>)}</ul>:<p className="text-slate-500">No users assigned.</p>}</div><p className="rounded border bg-slate-50 p-3 text-sm">Remote role administration is read-only in the browser. Changes require the approved canonical administrative command boundary.</p></section>}</main>;
}
