import { useMemo, useState } from "react";
import { useAuth } from "@/features/auth/AuthContext";
import { useApplicationDependenciesCompatibility } from "@/app/composition";
import { CanonicalRoleAdministrationService } from "../services/CanonicalRoleAdministrationService";

type DetailTab="overview"|"assigned"|"edit"|"impact";
const words=(value:string)=>value.replace(/([a-z])([A-Z])/g,"$1 $2").split(/[. _-]/).filter(Boolean).map(x=>x[0].toUpperCase()+x.slice(1)).join(" ");
const actions:Record<string,string>={read:"View",create:"Create",update:"Update",delete:"Delete",approve:"Approve",close:"Close",export:"Export",activate:"Activate",release:"Release",submit:"Submit"};
const friendly=(permission:{code:string;resource:string;action:string;description:string})=>permission.code.split(".").length===2?`${actions[permission.action]??words(permission.action)} ${words(permission.resource)}`:permission.description||words(permission.code);

export default function RolesPage(){
 const {user}=useAuth(),deps=useApplicationDependenciesCompatibility();
 const service=useMemo(()=>new CanonicalRoleAdministrationService(undefined,deps.authentication.userRepository),[deps.authentication.userRepository]);
 const [version,setVersion]=useState(0),[selected,setSelected]=useState("system-administrator"),[compare,setCompare]=useState("operations-manager"),[tab,setTab]=useState<DetailTab>("overview"),[code,setCode]=useState(""),[name,setName]=useState(""),[message,setMessage]=useState("");
 const [draft,setDraft]=useState<readonly string[]>([]),[search,setSearch]=useState(""),[module,setModule]=useState("all"),[action,setAction]=useState("all"),[risk,setRisk]=useState("all"),[pendingRole,setPendingRole]=useState<string>();
 const roles=[...service.listRoles()].sort((a,b)=>a.name.localeCompare(b.name)),role=service.getRole(selected),allPermissions=service.listPermissions().filter(x=>x.active&&!x.deprecated),groups=service.getPermissionGroups(),delta=service.compare(selected,compare);void version;
 const assignedUsers=role?service.assignedUsers(role.code):[],defaults=role?service.getDefaultPermissions(role.code):[],defaultSet=new Set(defaults),currentSet=new Set(role?.permissions??[]);
 const customAdditions=(role?.permissions??[]).filter(x=>!defaultSet.has(x)),customRemovals=defaults.filter(x=>!currentSet.has(x));
 const added=draft.filter(x=>!currentSet.has(x)),removed=(role?.permissions??[]).filter(x=>!draft.includes(x));
 const actionsList=[...new Set(allPermissions.map(x=>x.action))].sort(),risks=[...new Set(allPermissions.map(x=>x.riskClass))].sort();
 const matches=(permission:typeof allPermissions[number])=>{const group=groups.find(x=>x.resources.includes(permission.resource));return (!search||`${friendly(permission)} ${permission.description} ${permission.code}`.toLowerCase().includes(search.toLowerCase()))&&(module==="all"||group?.code===module)&&(action==="all"||permission.action===action)&&(risk==="all"||permission.riskClass===risk)};
 function applyRole(next:string){setSelected(next);setDraft(tab==="edit"?service.getRole(next)?.permissions??[]:[]);setSearch("");setModule("all");setAction("all");setRisk("all")}
 function selectRole(next:string){if(tab==="edit"&&(added.length||removed.length)){setPendingRole(next);return}applyRole(next)}
 function beginEdit(){if(!role)return;setDraft(role.permissions);setTab("edit")}
 function clone(){if(!user)return;try{const created=service.cloneRole(user,selected,code,name);setVersion(x=>x+1);selectRole(created.code);setCode("");setName("");setMessage("Custom role cloned.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to clone role.")}}
 function rename(){if(!user||!role||role.systemManaged)return;const next=window.prompt("Custom role name",role.name);if(!next)return;try{service.renameRole(user,role.code,next);setVersion(x=>x+1);setMessage("Custom role updated.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to update role.")}}
 function deactivate(){if(!user||!role||role.systemManaged)return;try{service.updateRole(user,role.code,{active:false});setVersion(x=>x+1);setMessage("Custom role deactivated.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to deactivate role.")}}
 function save(){if(!user||!role)return;try{service.setRolePermissions(user,role.code,draft);setVersion(x=>x+1);setTab("assigned");setMessage("Role permissions saved and audited.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to save role permissions.")}}
 function reset(){if(!user||!role)return;try{service.resetRolePermissions(user,role.code);setVersion(x=>x+1);setTab("assigned");setMessage("Role permissions reset to default and audited.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to reset role permissions.")}}
 const permissionItem=(permission:typeof allPermissions[number],control?:"add"|"remove")=><div className="flex items-start justify-between gap-2 rounded border p-3" key={permission.code}><div><p className="font-medium">{friendly(permission)}</p><p className="text-sm text-slate-600">{permission.description}</p><code className="text-xs text-slate-500">{permission.code}</code><div className="mt-1"><span className="rounded-full border px-2 py-0.5 text-xs uppercase">{permission.riskClass}</span></div></div>{control&&<button className="shrink-0 rounded border px-2 py-1" aria-label={`${control==="add"?"Add":"Remove"} ${permission.code}`} onClick={()=>setDraft(current=>control==="add"?[...new Set([...current,permission.code])].sort():current.filter(x=>x!==permission.code))}>{control==="add"?"Add":"Remove"}</button>}</div>;
 return <main className="space-y-6"><header><h1 className="text-2xl font-bold">Roles</h1><p>Choose a role and manage what it can do.</p></header>{message&&<p role="status">{message}</p>}{pendingRole&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div role="dialog" aria-modal="true" aria-labelledby="unsaved-role-title" className="w-full max-w-md rounded-xl bg-white p-5"><h2 id="unsaved-role-title" className="text-xl font-bold">Unsaved Permission Changes</h2><p className="my-4">You have unsaved changes for {role?.name}.</p><div className="flex justify-end gap-2"><button className="rounded border px-3 py-2" onClick={()=>setPendingRole(undefined)}>Stay</button><button className="rounded bg-red-700 px-3 py-2 text-white" onClick={()=>{applyRole(pendingRole);setPendingRole(undefined)}}>Discard and Switch</button></div></div></div>}
 <label className="block max-w-xl" htmlFor="role-selector"><span className="font-semibold">Role</span><select id="role-selector" className="mt-1 block w-full rounded border bg-white p-3" value={selected} onChange={e=>selectRole(e.target.value)}>{roles.map(x=><option key={x.code} value={x.code}>{x.name}{!x.systemManaged?" — Custom":""}</option>)}</select></label>
 <div>{role&&<section aria-label="Selected role details" className="space-y-4 rounded-xl border bg-white p-5"><div><h2 className="text-xl font-semibold">{role.name}</h2><p>{role.description}</p><p className="mt-2 text-sm text-slate-600">{role.permissions.length} current permissions · {assignedUsers.length} assigned {assignedUsers.length===1?"user":"users"} · Catalog {role.catalogVersion}</p>{role.systemManaged?<p className="mt-1 text-sm text-slate-500">System role. Name and code are protected.</p>:!role.active?<p className="mt-1 text-sm font-medium">Status: Inactive</p>:<p className="mt-1 text-sm text-slate-500">Custom role</p>}</div>
 <p className="rounded border bg-slate-50 p-3 text-sm"><b>Default</b> {defaults.length} &nbsp;|&nbsp; <b>Current</b> {role.permissions.length} &nbsp;|&nbsp; <b>Added</b> +{customAdditions.length} &nbsp;|&nbsp; <b>Removed</b> {customRemovals.length} &nbsp;|&nbsp; <b>Users</b> {assignedUsers.length}</p>
 <div className="flex flex-wrap gap-2"><button className="rounded bg-blue-700 px-3 py-2 text-white" onClick={beginEdit}>Edit Permissions</button><button className="rounded border border-amber-600 px-3 py-2 text-amber-800" onClick={reset}>Reset to Default</button>{!role.systemManaged&&<><button className="rounded border px-3 py-2" onClick={rename}>Edit Role Details</button><button className="rounded border px-3 py-2" onClick={deactivate} disabled={!role.active}>Deactivate</button></>}</div>
 <div className="flex flex-wrap gap-1 border-b" role="tablist" aria-label="Role details">{(["overview","assigned","edit","impact"] as DetailTab[]).map(value=><button role="tab" aria-selected={tab===value} className={`px-3 py-2 ${tab===value?"border-b-2 border-blue-700 font-semibold":""}`} key={value} onClick={()=>value==="edit"?beginEdit():setTab(value)}>{value==="assigned"?"Assigned Permissions":value==="edit"?"Edit Permissions":value==="impact"?"Impact Analysis":"Overview"}</button>)}</div>
 {tab==="overview"&&<div className="space-y-4"><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Role code</dt><dd><code>{role.code}</code></dd></div><div><dt className="text-sm text-slate-500">Catalog version</dt><dd>{role.catalogVersion}</dd></div><div><dt className="text-sm text-slate-500">Permission count</dt><dd>{role.permissions.length}</dd></div><div><dt className="text-sm text-slate-500">Assigned users</dt><dd>{assignedUsers.length}</dd></div></dl><div className="grid gap-3 sm:grid-cols-2"><div><h3 className="font-semibold">Custom Additions</h3>{customAdditions.length?<ul>{customAdditions.map(x=><li key={x} className="text-green-800">+ {x}</li>)}</ul>:<p className="text-slate-500">None</p>}</div><div><h3 className="font-semibold">Custom Removals</h3>{customRemovals.length?<ul>{customRemovals.map(x=><li key={x} className="text-red-800">− {x}</li>)}</ul>:<p className="text-slate-500">None</p>}</div></div><div className="flex flex-wrap gap-2"><button className="rounded bg-blue-700 px-3 py-2 text-white" onClick={beginEdit}>Edit Permissions</button><button className="rounded border px-3 py-2" onClick={()=>document.getElementById("clone-role")?.scrollIntoView()}>Clone Role</button>{!role.systemManaged&&<><button className="rounded border px-3 py-2" onClick={rename}>Rename</button><button className="rounded border px-3 py-2" onClick={deactivate} disabled={!role.active}>Deactivate</button></>}</div></div>}
 {tab==="assigned"&&<div className="space-y-3"><div className="flex justify-between"><p><b>{role.permissions.length}</b> permissions currently assigned</p><button className="rounded bg-blue-700 px-3 py-2 text-white" onClick={beginEdit}>Edit Permissions</button></div>{groups.map(group=>{const items=allPermissions.filter(p=>role.permissions.includes(p.code)&&group.resources.includes(p.resource));return items.length?<details open className="rounded border p-3" key={group.code}><summary className="cursor-pointer font-semibold">{group.label} ({items.length})</summary><div className="mt-2 grid gap-2 sm:grid-cols-2">{items.map(p=>permissionItem(p))}</div></details>:null})}</div>}
 {tab==="edit"&&<div className="space-y-4"><div className="rounded border border-amber-300 bg-amber-50 p-3"><b>Impact warning:</b> This role is assigned to {assignedUsers.length} {assignedUsers.length===1?"user":"users"}. Saved changes will affect their canonical access projection.</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label htmlFor="role-permission-search">Search permission<input id="role-permission-search" className="mt-1 block w-full rounded border p-2" value={search} onChange={e=>setSearch(e.target.value)}/></label><label htmlFor="role-permission-module">Module<select id="role-permission-module" className="mt-1 block w-full rounded border p-2" value={module} onChange={e=>setModule(e.target.value)}><option value="all">All Modules</option>{groups.map(x=><option value={x.code} key={x.code}>{x.label}</option>)}</select></label><label htmlFor="role-permission-action">Action<select id="role-permission-action" className="mt-1 block w-full rounded border p-2" value={action} onChange={e=>setAction(e.target.value)}><option value="all">All Actions</option>{actionsList.map(x=><option key={x}>{x}</option>)}</select></label><label htmlFor="role-permission-risk">Risk<select id="role-permission-risk" className="mt-1 block w-full rounded border p-2" value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">All Risk Levels</option>{risks.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="grid gap-3 sm:grid-cols-3"><p><b>Assigned:</b> {draft.length}</p><p><b>Added:</b> {added.length}</p><p><b>Removed:</b> {removed.length}</p></div><div className="grid gap-4 lg:grid-cols-2"><section><h3 className="mb-2 text-lg font-semibold">Assigned Permissions ({draft.filter(code=>{const p=allPermissions.find(x=>x.code===code);return p&&matches(p)}).length})</h3><div className="space-y-2">{allPermissions.filter(p=>draft.includes(p.code)&&matches(p)).map(p=>permissionItem(p,"remove"))}</div></section><section><h3 className="mb-2 text-lg font-semibold">Available Permissions ({allPermissions.filter(p=>!draft.includes(p.code)&&matches(p)).length})</h3><div className="space-y-2">{allPermissions.filter(p=>!draft.includes(p.code)&&matches(p)).map(p=>permissionItem(p,"add"))}</div></section></div><div className="sticky bottom-0 flex flex-wrap gap-2 border-t bg-white py-3"><button className="rounded bg-blue-700 px-3 py-2 text-white" onClick={save}>Save Changes</button><button className="rounded border px-3 py-2" onClick={()=>{setDraft(role.permissions);setTab("assigned")}}>Cancel</button><button className="rounded border border-amber-600 px-3 py-2 text-amber-800" onClick={reset}>Reset To Default</button></div></div>}
 {tab==="impact"&&<div className="space-y-3"><div className="rounded border border-amber-300 bg-amber-50 p-3"><b>Impact Analysis:</b> Changes to this role will affect {assignedUsers.length} {assignedUsers.length===1?"user":"users"}.</div><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th scope="col">User</th><th scope="col">Status</th><th scope="col">Other Roles</th><th scope="col">Operator Link</th></tr></thead><tbody>{assignedUsers.map(x=><tr className="border-t" key={x.id}><td className="py-2"><b>{x.displayName}</b><span className="block text-sm">{x.username}</span></td><td>{x.status}</td><td>{x.systemRoles.filter(r=>r!==role.code).map(r=>service.getRoleDisplayName(r)).join(", ")||"None"}</td><td>{x.operatorId??"None"}</td></tr>)}</tbody></table>{!assignedUsers.length&&<p className="py-5 text-slate-500">No users will be affected because this role is not assigned.</p>}</div></div>}
 </section>}</div>
 <details className="rounded-xl border bg-white"><summary className="cursor-pointer p-4 font-semibold">More role actions</summary><div className="grid gap-4 border-t p-4 lg:grid-cols-2"><section id="clone-role"><h2 className="text-lg font-semibold">Clone as Custom Role</h2><div className="mt-3 grid gap-3"><label htmlFor="custom-role-code">Custom role code<input id="custom-role-code" className="mt-1 block w-full rounded border p-2" value={code} onChange={e=>setCode(e.target.value)}/></label><label htmlFor="custom-role-name">Custom role name<input id="custom-role-name" className="mt-1 block w-full rounded border p-2" value={name} onChange={e=>setName(e.target.value)}/></label></div><button className="mt-3 rounded border px-3 py-2" onClick={clone}>Clone Role</button></section><section id="role-comparison"><h2 className="text-lg font-semibold">Compare Role</h2><label htmlFor="comparison-role">Compare with<select id="comparison-role" className="ml-2 rounded border p-2" value={compare} onChange={e=>setCompare(e.target.value)}>{roles.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label><p className="mt-3">{delta.shared.length} shared · {delta.onlyA.length} only in {role?.name} · {delta.onlyB.length} only in {service.getRoleDisplayName(compare)}</p></section></div></details></main>
}
