import type { ManagerApprovalEmailSnapshot } from "./types";

const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character]!);
const yesNo = (value: boolean) => value ? "YES" : "NO";
const money = (value: number | undefined, currency: string) => value === undefined ? "Not configured" : `${escapeHtml(currency)} ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function managerApprovalEmailSubject(snapshot: ManagerApprovalEmailSnapshot) {
  return `Rental Approval Required [${snapshot.rentalNumber}] ${snapshot.customer}`;
}

export function renderManagerApprovalEmail(snapshot: ManagerApprovalEmailSnapshot, approvalUrl: string): string {
  const field = (label: string, value: unknown) => `<tr><th align="left">${escapeHtml(label)}</th><td>${escapeHtml(value)}</td></tr>`;
  const equipmentRows = snapshot.equipment.map((item) => `<tr><td>${escapeHtml(item.equipmentCode)}</td><td>${escapeHtml(item.equipmentName)}</td><td>${escapeHtml(item.assetNumber)}</td><td>${escapeHtml(item.assignedOperator)}</td><td>${item.quantity}</td></tr>`).join("");
  const commercialRows = snapshot.commercial.map((item) => `<tr><td>${escapeHtml(item.equipmentCode)}</td><td>${escapeHtml(item.billingMethod)}</td><td>${money(item.unitRate, item.currency)}</td><td>${money(item.contractAmount, item.currency)}</td><td>${yesNo(item.vatIncluded)}</td><td>${yesNo(item.fuelIncluded)}</td><td>${yesNo(item.operatorIncluded)}</td><td>${yesNo(item.commercialTermsConfigured)}</td><td>${yesNo(item.commercialSnapshotLocked)}</td></tr>`).join("");
  const warnings = snapshot.warnings.length ? `<section><h2>Warnings</h2><ul>${snapshot.warnings.map((warning) => `<li>${escapeHtml(warning)}</li>`).join("")}</ul></section>` : "";
  return `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#172033"><h1>Rental Approval Request</h1><p>A Rental is awaiting your approval before equipment can be released.</p><table>${field("Rental Number", snapshot.rentalNumber)}${field("Customer", snapshot.customer)}${field("Project", snapshot.project)}</table><h2>Rental</h2><table>${field("Rental Number", snapshot.rentalNumber)}${field("Customer", snapshot.customer)}${field("Project", snapshot.project)}${field("Rental Type", snapshot.rentalType)}${field("Rental Period", snapshot.rentalPeriod)}${field("Requested By", snapshot.requestedBy)}${field("Requested Date", snapshot.requestedDate)}${field("Current Status", snapshot.currentStatus)}${field("Approval Status", snapshot.approvalStatus)}</table><h2>Equipment</h2><table border="1" cellpadding="6"><tr><th>Equipment Code</th><th>Equipment Name</th><th>Asset Number</th><th>Assigned Operator</th><th>Quantity</th></tr>${equipmentRows}</table><h2>Commercial Summary</h2><table border="1" cellpadding="6"><tr><th>Equipment</th><th>Billing Method</th><th>Unit Rate</th><th>Contract Amount</th><th>VAT Included</th><th>Fuel Included</th><th>Operator Included</th><th>Terms Configured</th><th>Snapshot Locked</th></tr>${commercialRows}</table><h2>Operational Readiness</h2><table>${field("Assignment Complete", yesNo(snapshot.readiness.assignmentComplete))}${field("Commercial Terms Complete", yesNo(snapshot.readiness.commercialTermsComplete))}${field("Equipment Available", yesNo(snapshot.readiness.equipmentAvailable))}${field("Operator Assigned", yesNo(snapshot.readiness.operatorAssigned))}${field("Conflicts Detected", yesNo(snapshot.readiness.conflictsDetected))}${field("Expected Release Date", snapshot.readiness.expectedReleaseDate)}</table>${warnings}<p><a href="${escapeHtml(approvalUrl)}" style="display:inline-block;padding:12px 18px;background:#166534;color:white;text-decoration:none">Approve Rental</a> <a href="${escapeHtml(approvalUrl)}" style="display:inline-block;padding:12px 18px;background:#991b1b;color:white;text-decoration:none">Reject Rental</a></p><hr><p>This approval authorizes release eligibility only.</p><p>Equipment will still require release by the authorized release actor. Approval does NOT release equipment.</p></body></html>`;
}
