import { storage } from "@/core/storage";
import { formatCustomerReviewDateTime } from "./customerReviewDateTime";
export const DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY="equipment-rental-development-customer-review-outbox";
const CHANGE_EVENT="customer-review-outbox-change";
const notify=()=>{if(typeof window!=="undefined")window.dispatchEvent(new Event(CHANGE_EVENT))};
export function subscribeCustomerReviewOutbox(listener:()=>void){if(typeof window==="undefined")return()=>{};const local=()=>listener(),cross=(event:StorageEvent)=>{if(event.key===DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY)listener()};window.addEventListener(CHANGE_EVENT,local);window.addEventListener("storage",cross);return()=>{window.removeEventListener(CHANGE_EVENT,local);window.removeEventListener("storage",cross)}}
export type CustomerReviewStatus="Pending"|"Acknowledged"|"CorrectionRequested"|"Expired"|"Superseded"|"Consumed";
export interface CustomerReviewTimelineSnapshot{sequence?:number;activityType?:string;label?:string;start:string;end?:string;durationMinutes?:number;durationSeconds?:number;workDescription?:string;remarks?:string;openingMeter?:number;closingMeter?:number}
export interface CustomerReviewSnapshot{project:string;equipment:string;operator:string;workDate:string;shift?:string;workDescription?:string;remarks?:string;startedAt?:string;completedAt?:string;submittedAt?:string;openingMeter?:number;closingMeter?:number;operationMinutes:number;idleMinutes:number;standbyMinutes?:number;breakdownMinutes:number;origin:string;timeline?:CustomerReviewTimelineSnapshot[]}
export interface CustomerReviewOutboxEntry{id:string;deurId:string;deurNumber:string;revisionNumber:number;rentalNumber:string;customerName:string;representativeName:string;representativeEmail:string;generatedAt:string;expiresAt:string;token:string;status:CustomerReviewStatus;subject:string;snapshot:CustomerReviewSnapshot;html:string;supersededById?:string}
const clone=<T>(v:T):T=>structuredClone(v);const esc=(v:string|undefined)=>((v?.trim()||"Not provided").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!)));
export const customerReviewSubject=(x:Pick<CustomerReviewOutboxEntry,"deurNumber"|"revisionNumber"|"rentalNumber">)=>`DEUR Acknowledgement Required [${x.deurNumber} R${x.revisionNumber}] [${x.rentalNumber}]`;
export function renderCustomerReviewEmailHtml(input:Omit<CustomerReviewOutboxEntry,"id"|"token"|"generatedAt"|"expiresAt"|"status"|"subject"|"html">,token:string){const s=input.snapshot;const timeline=(s.timeline??[]).map(x=>`<li><b>${x.sequence??""}. ${esc(x.activityType??x.label)}</b><br>Start: ${esc(formatCustomerReviewDateTime(x.start))}<br>End: ${esc(formatCustomerReviewDateTime(x.end))}<br>Duration: ${x.durationSeconds??((x.durationMinutes??0)*60)} seconds${x.workDescription?`<br>Work: ${esc(x.workDescription)}`:""}${x.remarks?`<br>Remarks: ${esc(x.remarks)}`:""}${x.openingMeter!==undefined?`<br>Opening meter: ${x.openingMeter}`:""}${x.closingMeter!==undefined?`<br>Closing meter: ${x.closingMeter}`:""}</li>`).join("")||"<p>Detailed activity timestamps were not recorded for this legacy DEUR.</p>";return`<article style="font-family:Arial,sans-serif;max-width:680px;margin:auto"><h1>Daily Equipment Utilization Report for Review</h1><p>A DEUR is awaiting your acknowledgement or correction request.</p><h2>Rental summary</h2><p>Rental: ${esc(input.rentalNumber)}<br>Customer: ${esc(input.customerName)}<br>Project: ${esc(s.project)}</p><h2>Equipment summary</h2><p>Equipment: ${esc(s.equipment)}<br>Operator: ${esc(s.operator)}</p><h2>DEUR summary</h2><p>DEUR: ${esc(input.deurNumber)} R${input.revisionNumber}<br>Work Date: ${esc(s.workDate)}<br>Shift: ${esc(s.shift)}<br>Work Description: ${esc(s.workDescription)}<br>Started: ${esc(formatCustomerReviewDateTime(s.startedAt))}<br>Completed: ${esc(formatCustomerReviewDateTime(s.completedAt))}<br>Submitted: ${esc(formatCustomerReviewDateTime(s.submittedAt))}<br>Opening meter: ${s.openingMeter??"Not applicable"}<br>Closing meter: ${s.closingMeter??"Not applicable"}<br>Remarks: ${esc(s.remarks)}</p><h2>Activity Timeline</h2><ol>${timeline}</ol><h2>Activity Summary</h2><p>Operation: ${s.operationMinutes} min<br>Idle: ${s.idleMinutes} min<br>Standby: ${s.standbyMinutes??0} min<br>Breakdown: ${s.breakdownMinutes} min<br>Total: ${s.operationMinutes+s.idleMinutes+(s.standbyMinutes??0)+s.breakdownMinutes} min</p><p><a href="/customer-deur-review/${encodeURIComponent(token)}">Acknowledge DEUR or Request Correction</a></p><footer>Acknowledgement confirms the recorded daily equipment activity. It does not confirm invoice payment.</footer></article>`}
class Outbox{
 getAll(now=new Date().toISOString()){const all=clone(storage.get<CustomerReviewOutboxEntry[]>(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY)??[]);let changed=false;const next=all.map(x=>{if(x.status==="Pending"&&Date.parse(x.expiresAt)<=Date.parse(now)){changed=true;return{...x,status:"Expired" as const}}return x});if(changed){storage.set(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY,next);notify()}return next}
 getById(id:string,now?:string){return this.getAll(now).find(x=>x.id===id)}
 getByToken(token:string,now?:string){return this.getAll(now).find(x=>x.token===token)}
 getCurrent(deurId:string,now?:string){return this.getAll(now).filter(x=>x.deurId===deurId).at(-1)}
 hasPendingForRental(rentalNumber:string){return this.getAll().some(x=>x.rentalNumber===rentalNumber&&x.status==="Pending")}
 create(input:Omit<CustomerReviewOutboxEntry,"id"|"token"|"generatedAt"|"expiresAt"|"status"|"subject"|"html">){const existing=this.getAll().find(x=>x.deurId===input.deurId&&x.revisionNumber===input.revisionNumber&&x.status==="Pending");if(existing)return clone(existing);const generatedAt=new Date().toISOString(),token=crypto.randomUUID(),base={...clone(input),id:crypto.randomUUID(),token,generatedAt,expiresAt:new Date(Date.parse(generatedAt)+7*86400000).toISOString(),status:"Pending" as const};const entry={...base,subject:customerReviewSubject(base),html:renderCustomerReviewEmailHtml(input,token)};storage.set(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY,[...this.getAll(generatedAt),entry]);notify();return clone(entry)}
 replace(id:string,input:Omit<CustomerReviewOutboxEntry,"id"|"token"|"generatedAt"|"expiresAt"|"status"|"subject"|"html">){const old=this.getById(id);if(!old||!["Pending","Expired"].includes(old.status))throw Error("Only a Pending or Expired request can be replaced.");const all=this.getAll().map(x=>x.id===id?{...x,status:"Superseded" as const}:x);storage.set(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY,all);const next=this.create(input);storage.set(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY,this.getAll().map(x=>x.id===id?{...x,supersededById:next.id}:x));return next}
 decide(token:string,status:"Acknowledged"|"CorrectionRequested"){const entry=this.getByToken(token);if(!entry||entry.status!=="Pending")return false;storage.set(DEVELOPMENT_CUSTOMER_REVIEW_OUTBOX_KEY,this.getAll().map(x=>x.token===token?{...x,status}:x));notify();return true}
}
export const developmentCustomerReviewOutbox=new Outbox();
