import { useCallback, useEffect, useState } from "react";
import { useApplicationDependenciesCompatibility, PersistenceMode } from "@/app/composition";
import { useAuth } from "@/features/auth/AuthContext";
import { MasterDrawer, MasterFormActions, MasterPageLayout, MasterStatusBadge } from "@/components/master-data";
import { LoadingState, ErrorState, EmptyDataState } from "@/components/ui/AsyncState";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";
import type { CertificationTypeRecord } from "../types";

export default function CertificationTypesPage() {
  const deps = useApplicationDependenciesCompatibility(); const { hasPermission } = useAuth();
  const [items, setItems] = useState<CertificationTypeRecord[]>([]); const [state, setState] = useState<"loading"|"ready"|"error">("loading"); const [error, setError] = useState(""); const [editing, setEditing] = useState<CertificationTypeRecord | null>(null); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [, setBusy] = useState(false); const [message, setMessage] = useState("");
  const refresh = useCallback(async () => { setState("loading"); setError(""); const result = await deps.readRepositories.certificationTypes.list(); if (!result.success) { setState("error"); setError(result.error.message); return; } setItems(result.value.items); setState("ready"); }, [deps]);
  useEffect(() => { void refresh(); }, [refresh]);
  const close = () => { setOpen(false); setEditing(null); setName(""); };
  async function save() { if (!deps.commandRepositories.certificationTypes || !name.trim()) return; setBusy(true); setMessage(""); const commandId = crypto.randomUUID(); const result = editing ? await deps.commandRepositories.certificationTypes.update({ commandId, idempotencyKey: commandId, certificationTypeId: editing.id, name: name.trim(), expectedRowVersion: editing.rowVersion }) : await deps.commandRepositories.certificationTypes.create({ commandId, idempotencyKey: commandId, certificationTypeId: crypto.randomUUID(), name: name.trim() }); setBusy(false); if (!result.success) { setMessage(result.code === "CERTIFICATION_TYPE_CONFLICT" ? "A certification with this name already exists." : result.code === "CONFLICT" ? "This certification was changed by another user. Refresh and try again." : "The certification could not be saved. Refresh and try again."); return; } close(); await refresh(); }
  async function setActive(item: CertificationTypeRecord, active: boolean) { if (!deps.commandRepositories.certificationTypes) return; if (!active && !window.confirm("This certification will no longer be available for new Operator assignments. Existing assignments will remain visible.")) return; const commandId = crypto.randomUUID(); const result = await deps.commandRepositories.certificationTypes.setActive({ commandId, idempotencyKey: commandId, certificationTypeId: item.id, expectedRowVersion: item.rowVersion }, active); if (!result.success) setMessage(result.code === "CONFLICT" ? "This certification was changed by another user. Refresh and try again." : "The certification status could not be changed. Refresh and try again."); else await refresh(); }
  const remote = deps.configuration.persistenceMode === PersistenceMode.Remote;
  return <div className="p-4 sm:p-8"><MasterPageLayout title="Certification Types" toolbar={<div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">Manage approved Operator certifications.</p>{hasPermission("masterData.create") && <Button onClick={() => { setEditing(null); setName(""); setOpen(true); }}>Add Certification</Button>}</div>} table={state === "loading" ? <LoadingState label="Loading certification types…" /> : state === "error" ? <ErrorState message={error} onRetry={() => void refresh()} /> : !items.length ? <EmptyDataState title="No certification types" description="Add a certification type to make it available for Operator assignments." /> : <div className="overflow-x-auto rounded-xl border bg-white dark:bg-slate-900"><table className="min-w-full text-sm"><thead className="bg-slate-100 dark:bg-slate-800"><tr><th className="p-3 text-left">Certification Name</th><th className="p-3 text-left">Status</th><th className="p-3 text-right">Usage Count</th><th className="p-3 text-left">Updated</th>{hasPermission("masterData.update") && <th className="p-3 text-right">Actions</th>}</tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-t dark:border-slate-700"><td className="p-3 font-medium">{item.name}</td><td className="p-3"><MasterStatusBadge active={item.active} /></td><td className="p-3 text-right">{item.usageCount}</td><td className="p-3">{new Date(item.updatedAt).toLocaleDateString()}</td>{hasPermission("masterData.update") && <td className="p-3 text-right"><Button size="sm" variant="secondary" onClick={() => { setEditing(item); setName(item.name); setOpen(true); }}>Edit</Button> <Button size="sm" variant="secondary" onClick={() => void setActive(item, !item.active)}>{item.active ? "Deactivate" : "Activate"}</Button></td>}</tr>)}</tbody></table></div>} />{message && <p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}{!remote && <p className="mt-3 text-sm text-slate-500">Certification administration requires canonical remote mode.</p>}<MasterDrawer open={open} title={editing ? "Edit Certification" : "Add Certification"} onClose={close}><div className="space-y-5"><Input label="Certification Name" required value={name} onChange={event => setName(event.target.value)} /><MasterFormActions isEditing={!!editing} onSave={() => void save()} onCancel={close} /></div></MasterDrawer></div>;
}
