import pg from'pg';const{Client}=pg;const c=new Client({host:'127.0.0.1',port:55435,database:process.env.CERT_DB,user:'postgres',password:'postgres'});const local='11111111-1111-1111-1111-111111111111',foreign='44444444-4444-4444-4444-444444444444';async function rpc(a,n,x){await c.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);return(await c.query(`select erp.${n}($1::jsonb) value`,[JSON.stringify(x)])).rows[0].value;}await c.connect();try{
 await c.query("insert into erp.customers(id,customer_code,name,company_id) values('TENANT-B-CUSTOMER','TENANT-B-CUSTOMER','Tenant B Customer','TENANT-FOREIGN-001') on conflict(id) do nothing;insert into erp.projects(id,project_code,name,customer_id,company_id) values('TENANT-B-PROJECT','TENANT-B-PROJECT','Tenant B Project','TENANT-B-CUSTOMER','TENANT-FOREIGN-001') on conflict(id) do nothing;insert into erp.operators(id,name,status,company_id) values('TENANT-B-OP','Tenant B Operator','Active','TENANT-FOREIGN-001') on conflict(id) do nothing;insert into erp.equipment(id,asset_no,equipment_name,maintenance_type,current_reading,status_id,company_id) values('TENANT-B-EQ','TENANT-B-EQ','Tenant B Equipment','Engine Hours',0,'equipment-status-available','TENANT-FOREIGN-001') on conflict(id) do nothing;insert into erp.assignments(id,equipment_id,operator_id,project_id,assigned_date,expected_return,status,company_id) values('TENANT-B-ASG','TENANT-B-EQ','TENANT-B-OP','TENANT-B-PROJECT','2026-08-22','2026-08-23','Active','TENANT-FOREIGN-001') on conflict(id) do nothing");
 await c.query("insert into erp.operators(id,name,status,company_id) values('TENANT-A-OP','Tenant A Operator','Active','TENANT-LOCAL-001') on conflict(id) do nothing;insert into erp.equipment(id,asset_no,equipment_name,maintenance_type,current_reading,status_id,company_id) values('TENANT-A-EQ','TENANT-A-EQ','Tenant A Equipment','Engine Hours',0,'equipment-status-available','TENANT-LOCAL-001') on conflict(id) do nothing;insert into erp.assignments(id,equipment_id,operator_id,project_id,assigned_date,expected_return,status,company_id) values('TENANT-A-ASG','TENANT-A-EQ','TENANT-A-OP','CERT-PROJECT','2026-08-22','2026-08-23','Active','TENANT-LOCAL-001') on conflict(id) do nothing");
 const draft=(id,key,customerId,projectId,assignmentId)=>({commandId:id,idempotencyKey:key,customerId,projectId,dateOut:'2026-08-22',expectedReturn:'2026-08-23',rentalType:'Operated Rental',lines:[{assignmentId}]});
 const fc=await rpc(local,'command_create_draft_rental',draft('TENANT-FC','TENANT-FC','TENANT-B-CUSTOMER','CERT-PROJECT','TENANT-A-ASG')),fp=await rpc(local,'command_create_draft_rental',draft('TENANT-FP','TENANT-FP','CERT-CUSTOMER','TENANT-B-PROJECT','TENANT-A-ASG')),fa=await rpc(local,'command_create_draft_rental',draft('TENANT-FA','TENANT-FA','CERT-CUSTOMER','CERT-PROJECT','TENANT-B-ASG'));
 const foreignRental='EXTENDED-RENTAL-MULTI-5',base={commandId:'TENANT-X',idempotencyKey:'TENANT-X',rentalId:foreignRental,expectedVersion:6};const terms=await rpc(foreign,'command_update_draft_rental_terms',{...base,lines:[{}]}),submit=await rpc(foreign,'command_submit_rental_approval',base),decision=await rpc(foreign,'command_decide_rental_approval',{...base,decision:'Approved'}),reserve=await rpc(foreign,'command_reserve_rental',base),release=await rpc(foreign,'command_release_rental',base);
 const localCompleted=await rpc(local,'command_create_draft_rental',draft('TENANT-A-IDEM','TENANT-SHARED-IDEM','CERT-CUSTOMER','CERT-PROJECT','TENANT-A-ASG'));const foreignSameKey=await rpc(foreign,'command_create_draft_rental',draft('TENANT-B-IDEM','TENANT-SHARED-IDEM','TENANT-B-CUSTOMER','TENANT-B-PROJECT','TENANT-B-ASG'));
 const a={foreignCustomer:fc.code,foreignProject:fp.code,foreignAssignment:fa.code,terms:terms.code,submit:submit.code,decision:decision.code,reserve:reserve.code,release:release.code,companyA:localCompleted.disposition,companyB:foreignSameKey.disposition,companyBId:foreignSameKey.value?.rentalId,foreignRaw:foreignSameKey};if(fc.code!=='NOT_FOUND'||fp.code!=='NOT_FOUND'||fa.code!=='MISSING_RELATIONSHIP'||[terms,submit,decision,reserve,release].some(v=>v.code!=='NOT_FOUND')||!['ACCEPTED','REPLAYED'].includes(localCompleted.disposition)||foreignSameKey.disposition!=='ACCEPTED'||foreignSameKey.value.rentalId!=='TENANT-B-IDEM')throw Error(JSON.stringify(a));console.log(JSON.stringify({...a,tenantIsolation:'PASS'}));
}finally{await c.end();}
