import pg from "pg"; const {Client}=pg; const client=new Client({host:'127.0.0.1',port:55435,database:process.env.CERT_DB,user:'postgres',password:'postgres'}); const requester='11111111-1111-1111-1111-111111111111';
async function rpc(actor,name,command){await client.query("select set_config('request.jwt.claim.sub',$1,false)",[actor]);return(await client.query(`select erp.${name}($1::jsonb) value`,[JSON.stringify(command)])).rows[0].value;}
await client.connect();try{
 const lineId=(await client.query("select id from erp.rental_equipment_lines where rental_id='TERMS-NEG-RENTAL'")).rows[0].id;
 const terms=await rpc(requester,'command_update_draft_rental_terms',{commandId:'SUB-TERMS',idempotencyKey:'SUB-TERMS',rentalId:'TERMS-NEG-RENTAL',expectedVersion:1,lines:[{lineId,commercialTerms:{billingMethod:'Per Hour',currency:'PHP',unitRate:100,operatorIncluded:true,transactionRelationship:'Non-Affiliate',vatApplicability:'Applicable'},costCodeId:'CERT-COST',activityCodeId:'CERT-ACT',workDescriptionId:'CERT-WORK',deurPolicy:{frequency:'PER_WORKDAY',effectiveFrom:'2026-08-22'},shiftWindows:[],workDate:'2026-08-22',meterRequirement:'hourMeter'}]});
 const base={commandId:'SUB-NEG',idempotencyKey:'SUB-NEG',rentalId:'TERMS-NEG-RENTAL',expectedVersion:terms.value.version};
 const unauthorized=await rpc('33333333-3333-3333-3333-333333333333','command_submit_rental_approval',base); const inactive=await rpc('55555555-5555-5555-5555-555555555555','command_submit_rental_approval',base); const cross=await rpc('44444444-4444-4444-4444-444444444444','command_submit_rental_approval',base);
 const malformed=await rpc(requester,'command_submit_rental_approval',{...base,idempotencyKey:'SUB-MALFORMED',expectedVersion:'bad'}); const stale=await rpc(requester,'command_submit_rental_approval',{...base,idempotencyKey:'SUB-STALE',expectedVersion:999}); const wrongLifecycle=await rpc(requester,'command_submit_rental_approval',{...base,idempotencyKey:'SUB-LIFECYCLE',rentalId:'EXTENDED-RENTAL-MULTI-5',expectedVersion:6});
 const actual={unauthorized:unauthorized.code,inactive:inactive.code,cross:cross.code,malformed:malformed.code,stale:stale.code,wrongLifecycle:wrongLifecycle.code}; const expected={unauthorized:'FORBIDDEN',inactive:'FORBIDDEN',cross:'NOT_FOUND',malformed:'VALIDATION_REJECTED',stale:'CONFLICT',wrongLifecycle:'INVALID_TRANSITION'}; if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(`Submission matrix failed ${JSON.stringify(actual)}`);
 const accepted=await rpc(requester,'command_submit_rental_approval',{...base,commandId:'SUB-ACCEPT',idempotencyKey:'SUB-ACCEPT'}); if(accepted.value.approvalStatus!=='Pending')throw new Error(`submission setup failed ${JSON.stringify(accepted)}`); console.log(JSON.stringify({...actual,submissionNegativeMatrix:'PASS',accepted:'Pending'}));
}finally{await client.end();}
