SET search_path TO erp, public;

-- Each query returns actionable exception rows; an empty result is success.
SELECT 'rental_without_line' issue_code,r.id record_id,jsonb_build_object('status',r.status) context FROM rentals r LEFT JOIN rental_equipment_lines l ON l.rental_id=r.id AND l.deleted_at IS NULL WHERE l.id IS NULL AND r.status<>'Cancelled';
SELECT 'duplicate_rental_equipment' issue_code,rental_id record_id,jsonb_build_object('equipment_id',equipment_id,'count',count(*)) context FROM rental_equipment_lines WHERE deleted_at IS NULL GROUP BY rental_id,equipment_id HAVING count(*)>1;
SELECT 'released_line_without_snapshot' issue_code,l.id record_id,jsonb_build_object('rental_id',l.rental_id,'equipment_id',l.equipment_id) context FROM rental_equipment_lines l LEFT JOIN commercial_snapshots s ON s.rental_equipment_line_id=l.id WHERE l.status IN ('Released','Active','Returned','Closed') AND s.id IS NULL;
SELECT 'deur_without_line' issue_code,d.id record_id,jsonb_build_object('rental_id',d.rental_id,'equipment_id',d.equipment_id) context FROM deurs d WHERE d.rental_equipment_line_id IS NULL AND d.legacy=false;
SELECT 'deur_identity_mismatch' issue_code,d.id record_id,jsonb_build_object('deur_rental',d.rental_id,'line_rental',l.rental_id,'deur_equipment',d.equipment_id,'line_equipment',l.equipment_id) context FROM deurs d JOIN rental_equipment_lines l ON l.id=d.rental_equipment_line_id WHERE d.rental_id<>l.rental_id OR d.equipment_id<>l.equipment_id;
SELECT 'duplicate_deur_line_date_shift' issue_code,min(id) record_id,jsonb_build_object('line_id',rental_equipment_line_id,'work_date',work_date,'shift',shift,'count',count(*)) context FROM deurs WHERE superseded_at IS NULL GROUP BY rental_equipment_line_id,work_date,shift HAVING rental_equipment_line_id IS NOT NULL AND count(*)>1;
SELECT 'acknowledged_deur_without_evidence' issue_code,id record_id,jsonb_build_object('evidence_mode',evidence_mode) context FROM deurs d WHERE status IN ('Acknowledged','Billed') AND NOT EXISTS(SELECT 1 FROM deur_events e WHERE e.deur_id=d.id) AND NOT EXISTS(SELECT 1 FROM deur_activity_logs l WHERE l.deur_id=d.id) AND odometer_trip_evidence IS NULL AND quantity_evidence IS NULL AND completion_evidence IS NULL;
SELECT 'statement_total_mismatch' issue_code,s.id record_id,jsonb_build_object('stored_subtotal',s.subtotal,'line_subtotal',coalesce(sum(l.amount),0),'stored_vat',s.vat,'line_vat',coalesce(sum(l.vat),0),'stored_withholding',s.withholding_tax,'line_withholding',coalesce(sum(l.withholding_tax),0),'stored_grand_total',s.grand_total,'line_grand_total',coalesce(sum(l.grand_total),0)) context FROM billing_statements s LEFT JOIN billing_statement_lines l ON l.billing_statement_id=s.id GROUP BY s.id HAVING s.subtotal<>coalesce(sum(l.amount),0) OR s.vat<>coalesce(sum(l.vat),0) OR s.withholding_tax<>coalesce(sum(l.withholding_tax),0) OR s.grand_total<>coalesce(sum(l.grand_total),0);
SELECT 'duplicate_deur_consumption' issue_code,deur_id record_id,jsonb_build_object('count',count(*),'line_ids',jsonb_agg(id)) context FROM billing_statement_lines GROUP BY deur_id HAVING count(*)>1;
SELECT 'snapshot_hash_missing' issue_code,id record_id,jsonb_build_object('line_id',rental_equipment_line_id) context FROM commercial_snapshots WHERE snapshot_hash IS NULL OR snapshot_hash='';
SELECT 'invoice_state_inconsistent' issue_code,id record_id,jsonb_build_object('approval_status',approval_status,'invoice_status',invoice_status) context FROM billing_statements WHERE invoice_status IN ('Invoiced','Partially Collected','Fully Collected') AND approval_status<>'Approved';
SELECT 'collections_exceed_statement' issue_code,s.id record_id,jsonb_build_object('grand_total',s.grand_total,'collected',sum(c.amount)) context FROM billing_statements s JOIN collections c ON c.billing_statement_id=s.id GROUP BY s.id HAVING sum(c.amount)>s.grand_total;
SELECT 'audit_actor_missing' issue_code,id record_id,jsonb_build_object('aggregate_type',aggregate_type,'aggregate_id',aggregate_id,'action',action) context FROM audit_log WHERE actor_id IS NULL AND actor_name IS NULL;
SELECT 'unresolved_staging_record' issue_code,id::text record_id,jsonb_build_object('repository',source_repository,'validation_status',validation_status,'transformation_status',transformation_status,'error_code',import_error_code) context FROM migration_staging_records WHERE validation_status<>'Valid' OR transformation_status NOT IN ('Ready','Imported');
SELECT 'completed_maintenance_without_date' issue_code,id record_id,jsonb_build_object('equipment_id',equipment_id,'status',status) context FROM maintenance_records WHERE status='Completed' AND completed_date IS NULL;
SELECT 'daily_log_reading_regression' issue_code,id record_id,jsonb_build_object('equipment_id',equipment_id,'start_reading',start_reading,'end_reading',end_reading) context FROM equipment_daily_logs WHERE end_reading<start_reading;
