import { useState } from "react";
import Button from "@/components/ui/Button";
import { useToast } from "@/components/ui/toast/ToastContext";
import { useAuth } from "@/features/auth/AuthContext";
import { useWorkDescriptions } from "@/features/masters/work-description/context/WorkDescriptionContext";
import { getSelectableWorkDescriptions } from "@/features/masters/work-description/services/getSelectableWorkDescriptions";
import { createManualDeur, MANUAL_DEUR_REASONS } from "@/features/rental/deur/services/CreateDeurService";
import { deurRepository } from "@/features/rental/deur/repository/deurRepository";
import type { ManualDeurReason } from "@/features/rental/deur/types";
import { useRentalWorkspaceAggregate } from "..";
import { resolveDeurEvidenceMode } from "@/features/rental/deur/services/resolveDeurEvidenceMode";

const labels:Record<ManualDeurReason,string>={POWER_NOT_AVAILABLE:"Power Not Available",SITE_COMPUTER_NOT_AVAILABLE:"Site Computer Not Available",TECHNICAL_DIFFICULTY:"Technical Difficulty",DEVICE_MALFUNCTION:"Device Malfunction",OPERATOR_DEVICE_NOT_ISSUED:"Operator Device Not Issued",APPLICATION_UNAVAILABLE:"Application Unavailable",INTERNET_UNAVAILABLE:"Internet Unavailable",DELAYED_DIGITAL_DEPLOYMENT:"Delayed Digital Deployment",PHYSICAL_DEUR_USED_AS_BACKUP:"Physical DEUR Used as Backup",OTHER:"Other"};
const states=[{value:"operation",label:"Operation"},{value:"idle",label:"Standby"},{value:"mealBreak",label:"Meal Break"},{value:"breakdown",label:"Breakdown"}] as const;
type Row={activityType:"operation"|"idle"|"mealBreak"|"breakdown";start:string;end:string};
export default function ManualDeurAction(){
 const {user}=useAuth(),aggregate=useRentalWorkspaceAggregate(),{showToast}=useToast(),{records}=useWorkDescriptions();
 const options=getSelectableWorkDescriptions({workDescriptions:records,equipmentCategoryId:aggregate.equipment?.categoryId});
 const [open,setOpen]=useState(false),[workId,setWorkId]=useState(""),[workDate,setWorkDate]=useState(new Date().toISOString().slice(0,10)),[shift,setShift]=useState<"Day"|"Night"|"">(""),[operationalRemarks,setOperationalRemarks]=useState(""),[reason,setReason]=useState<ManualDeurReason>("POWER_NOT_AVAILABLE"),[reasonDetails,setReasonDetails]=useState(""),[reference,setReference]=useState(""),[manualRemarks,setManualRemarks]=useState(""),[confirmed,setConfirmed]=useState(false),[confirmationName,setConfirmationName]=useState(""),[rows,setRows]=useState<Row[]>([{activityType:"operation",start:"",end:""}]);
 const manualMode=resolveDeurEvidenceMode(aggregate.rental.commercialSnapshot?.billingMethod??aggregate.rental.billingMethod??aggregate.contract?.billingMethod);
 if(user?.role!=="Admin"||!manualMode.supported||manualMode.mode!=="TIME_TIMELINE")return null;
 const adminUser=user;
 const selected=options.find(x=>x.id===workId);const context=aggregate.rental.operationalMetadata;
 const update=(index:number,patch:Partial<Row>)=>setRows(current=>current.map((row,i)=>i===index?{...row,...patch}:row));
 function save(submit=false){let timeline;try{timeline=rows.map(row=>({...row,start:new Date(row.start).toISOString(),end:new Date(row.end).toISOString()}))}catch{showToast("Timeline dates are invalid.","error");return}const result=createManualDeur({source:"RENTAL_COMPANY_MANUAL",rentalId:aggregate.rental.id,rentalStatus:aggregate.rental.status,equipmentId:aggregate.equipment?.id??aggregate.rental.equipmentId,operatorId:aggregate.operator?.id??aggregate.rental.operatorId??"",assignmentId:aggregate.assignment?.id,projectId:aggregate.project?.id??aggregate.rental.projectId,customerId:aggregate.rental.customerId,rental:aggregate.rental,selectedWorkDescription:selected,remarks:operationalRemarks,workDate,shift:shift||undefined,actor:{id:adminUser.id,name:adminUser.name,role:adminUser.role},timeline,manualMetadata:{reason,reasonDetails,physicalDeurReference:reference,sourceDocumentDate:workDate,operatorConfirmed:confirmed,operatorConfirmedByName:confirmationName,remarks:manualRemarks}});if(!result.success){showToast(result.message,"error");return}if(submit){const submitted=deurRepository.submit(result.record.id,{id:adminUser.id,name:adminUser.name});if(!submitted.success){showToast(submitted.message,"error");return}showToast("Manual DEUR submitted for acknowledgement.","success")}else showToast("Manual DEUR draft created.","success");setOpen(false)}
 if(!open)return <Button type="button" onClick={()=>setOpen(true)}>CREATE MANUAL DEUR</Button>;
 return <section className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h3 className="font-semibold">Create Manual DEUR</h3><p className="text-xs text-slate-500">Admin is currently the Equipment Department Admin role.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 text-sm"><div>Rental<p>{aggregate.rental.rentalNumber??aggregate.rental.id}</p></div><div>Equipment<p>{aggregate.equipment?.assetNo??aggregate.rental.equipmentId}</p></div><div>Operator<p>{aggregate.operator?.name??aggregate.rental.operatorId}</p></div><div>Project<p>{aggregate.project?.projectName??aggregate.rental.project}</p></div><div>Cost Code<p>{context?.costCode?`${context.costCode.code} — ${context.costCode.name}`:"Not captured"}</p></div><div>Activity Code<p>{context?.activityCode?`${context.activityCode.code} — ${context.activityCode.name}`:"Not captured"}</p></div>
 <label>DEUR Date<input className="block w-full rounded border p-2" type="date" value={workDate} onChange={e=>setWorkDate(e.target.value)}/></label><label>Work Description<select className="block w-full rounded border p-2" value={workId} onChange={e=>setWorkId(e.target.value)}><option value="">Select</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{aggregate.rental.deurExpectationPolicy?.frequency==="PER_SHIFT"&&<label>Shift<select className="block w-full rounded border p-2" value={shift} onChange={e=>setShift(e.target.value as typeof shift)}><option value="">Select</option>{aggregate.rental.deurExpectationPolicy.expectedShiftCodes?.map(code=><option key={code} value={code==="DAY"?"Day":"Night"}>{code==="DAY"?"Day":"Night"}</option>)}</select></label>}{selected?.requiresRemarks&&<label className="sm:col-span-2">Operational Remarks<textarea className="block w-full rounded border p-2" value={operationalRemarks} onChange={e=>setOperationalRemarks(e.target.value)}/></label>}
 <div className="sm:col-span-2"><p className="font-medium">Paper Timeline</p>{rows.map((row,index)=><div className="mt-2 grid grid-cols-3 gap-2" key={index}><select value={row.activityType} onChange={e=>update(index,{activityType:e.target.value as Row["activityType"]})}>{states.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><input type="datetime-local" value={row.start} onChange={e=>update(index,{start:e.target.value})}/><input type="datetime-local" value={row.end} onChange={e=>update(index,{end:e.target.value})}/></div>)}<button type="button" className="mt-2 text-blue-700" onClick={()=>setRows(x=>[...x,{activityType:"operation",start:"",end:""}])}>Add timeline entry</button></div>
 <label>Manual Reason<select className="block w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value as ManualDeurReason)}>{MANUAL_DEUR_REASONS.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></label>{reason==="OTHER"&&<label>Other Reason Details<input className="block w-full rounded border p-2" value={reasonDetails} onChange={e=>setReasonDetails(e.target.value)}/></label>}<label>Physical DEUR Reference<input className="block w-full rounded border p-2" value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Operator Confirmation Name<input className="block w-full rounded border p-2" value={confirmationName} onChange={e=>setConfirmationName(e.target.value)}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Operator Confirmed</label><label className="sm:col-span-2">Manual Remarks<textarea className="block w-full rounded border p-2" value={manualRemarks} onChange={e=>setManualRemarks(e.target.value)}/></label></div><div className="mt-4 flex gap-2"><Button type="button" onClick={()=>save(false)}>Save Draft</Button><Button type="button" variant="success" onClick={()=>save(true)}>Submit for Acknowledgement</Button><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button></div></section>;
}
