import { useState } from "react";
import Button from "@/components/ui/Button";
import { useToast } from "@/components/ui/toast/ToastContext";
import { useAuth } from "@/features/auth/AuthContext";
import { useEquipment } from "@/features/equipment/context/EquipmentContext";
import { useWorkDescriptions } from "@/features/masters/work-description/context/WorkDescriptionContext";
import { getSelectableWorkDescriptions } from "@/features/masters/work-description/services/getSelectableWorkDescriptions";
import { createManualDeur } from "@/features/rental/deur/services/CreateDeurService";
import { resolveDeurEvidenceMode } from "@/features/rental/deur/services/resolveDeurEvidenceMode";
import { useRentalWorkspaceAggregate } from "..";

export default function ManualOdometerDeurAction() {
  const { user } = useAuth(); const aggregate = useRentalWorkspaceAggregate(); const { showToast } = useToast(); const { records } = useWorkDescriptions(); const { equipment } = useEquipment();
  const [lineId, setLineId] = useState(() => aggregate.rentalEquipmentLines.length === 1 ? aggregate.rentalEquipmentLines[0].id : ""); const line = aggregate.rentalEquipmentLines.find((item) => item.id === lineId); const machine = equipment.find((item) => item.id === line?.equipmentId);
  const billingMethod = line?.commercialSnapshot?.billingMethod ?? aggregate.rental.billingMethod ?? aggregate.contract?.billingMethod; const resolved = resolveDeurEvidenceMode(billingMethod); const options = getSelectableWorkDescriptions({ workDescriptions: records, equipmentCategoryId: machine?.categoryId });
  const [open, setOpen] = useState(false), [workId, setWorkId] = useState(""), [workDate, setWorkDate] = useState(new Date().toISOString().slice(0, 10)), [shift, setShift] = useState<"Day" | "Night" | "">(""), [startLocation, setStartLocation] = useState(""), [startOdometer, setStartOdometer] = useState(""), [endLocation, setEndLocation] = useState(""), [endOdometer, setEndOdometer] = useState(""), [reference, setReference] = useState(""), [reasonDetails, setReasonDetails] = useState("");
  if (user?.role !== "Admin" || !resolved.supported || resolved.mode !== "ODOMETER_TRIP") return null;
  if (!open) return <Button type="button" onClick={() => setOpen(true)}>CREATE MANUAL ODOMETER DEUR</Button>;
  function save() {
    if (!line) return showToast("Select an Equipment Line.", "error");
    const result = createManualDeur({ source: "RENTAL_COMPANY_MANUAL", rentalId: aggregate.rental.id, rentalEquipmentLineId: line.id, rentalStatus: aggregate.rental.status, equipmentId: line.equipmentId, operatorId: line.operatorId, assignmentId: line.assignmentId, rental: aggregate.rental, billingMethod, selectedWorkDescription: options.find((item) => item.id === workId), workDate, shift: shift || undefined, actor: { id: user!.id, name: user!.name, role: user!.role }, odometerCheckpoints: [{ id: crypto.randomUUID(), location: startLocation, odometerReading: Number(startOdometer) }, { id: crypto.randomUUID(), location: endLocation, odometerReading: Number(endOdometer) }], manualMetadata: { reason: "OTHER", reasonDetails, physicalDeurReference: reference, operatorConfirmed: false } });
    if (!result.success) return showToast(result.message, "error"); showToast("Manual Odometer DEUR created.", "success"); setOpen(false);
  }
  return <section className="rounded-xl border bg-blue-50 p-5"><h3 className="font-semibold">Manual Odometer / Trip DEUR</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{aggregate.rentalEquipmentLines.length > 1 && <select value={lineId} onChange={(event) => setLineId(event.target.value)}><option value="">Equipment Line</option>{aggregate.rentalEquipmentLines.map((item) => <option key={item.id} value={item.id}>{equipment.find((record) => record.id === item.equipmentId)?.assetNo ?? item.equipmentId}</option>)}</select>}<input type="date" value={workDate} onChange={(event) => setWorkDate(event.target.value)} />{aggregate.rental.deurExpectationPolicy?.frequency === "PER_SHIFT" && <select value={shift} onChange={(event) => setShift(event.target.value as typeof shift)}><option value="">Shift</option>{aggregate.rental.deurExpectationPolicy.expectedShiftCodes?.map((code) => <option key={code} value={code === "DAY" ? "Day" : "Night"}>{code === "DAY" ? "Day" : "Night"}</option>)}</select>}<select value={workId} onChange={(event) => setWorkId(event.target.value)}><option value="">Work Description</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input placeholder="Physical DEUR Reference" value={reference} onChange={(event) => setReference(event.target.value)} /><input placeholder="Starting Location" value={startLocation} onChange={(event) => setStartLocation(event.target.value)} /><input type="number" placeholder="Starting Odometer" value={startOdometer} onChange={(event) => setStartOdometer(event.target.value)} /><input placeholder="Ending Location" value={endLocation} onChange={(event) => setEndLocation(event.target.value)} /><input type="number" placeholder="Ending Odometer" value={endOdometer} onChange={(event) => setEndOdometer(event.target.value)} /><input className="sm:col-span-2" placeholder="Manual reason details" value={reasonDetails} onChange={(event) => setReasonDetails(event.target.value)} /></div><div className="mt-3 flex gap-2"><Button type="button" onClick={save}>Save Manual Odometer DEUR</Button><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancel</Button></div></section>;
}
