import { useState } from "react";
import Button from "@/components/ui/Button";
import { useToast } from "@/components/ui/toast/ToastContext";
import { useApplicationDependenciesCompatibility } from "@/app/composition";
import type { ManualDeurCommandRepository } from "@/features/rental/deur/commands/contracts";
import type { DeurRecord } from "@/features/rental/deur/types";

export default function RemoteManualDeurWorkspace({deur}:{deur:DeurRecord}) {
  const {showToast}=useToast(); const {commandRepositories}=useApplicationDependenciesCompatibility(); const repo=commandRepositories.deurCommands as unknown as ManualDeurCommandRepository;
  const [action,setAction]=useState<"START_OPERATION"|"START_IDLE"|"START_MEAL_BREAK"|"START_BREAKDOWN"|"END_ACTIVITY">("START_OPERATION"),[odometer,setOdometer]=useState(""),[liters,setLiters]=useState(""),[location,setLocation]=useState(""),[occurrence,setOccurrence]=useState("");
  const base={commandId:crypto.randomUUID(),idempotencyKey:crypto.randomUUID(),deurId:deur.id,expectedVersion:Number((deur as unknown as {rowVersion?:number;version?:number}).rowVersion ?? (deur as unknown as {version?:number}).version ?? 0)}; const occurred=occurrence?new Date(occurrence).toISOString():undefined;
  async function run(operation:()=>Promise<any>){const result=await operation(); if(!result.success){showToast(result.message,"error");return} showToast("manual DEUR saved.","success"); window.location.reload();}
  if(import.meta.env.VITE_REMOTE_MANUAL_DEUR_RECORD_ENABLED!=="true") return null;
  return <section className="rounded-xl border border-indigo-200 bg-indigo-50 p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Manual DEUR Transcription Workspace</h3><span className="rounded bg-indigo-100 px-2 py-1 text-xs text-indigo-800">MANUAL_WEB</span></div><p className="mt-1 text-xs text-slate-600">server identity, tenant, assignment, operator and frozen meter policy are read-only.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label>Activity<select className="block w-full rounded border p-2" value={action} onChange={e=>setAction(e.target.value as typeof action)}><option value="START_OPERATION">Start operation</option><option value="START_IDLE">Start idle</option><option value="START_MEAL_BREAK">Start meal break</option><option value="START_BREAKDOWN">Start breakdown</option><option value="END_ACTIVITY">End activity</option></select></label><label>Occurrence time<input className="block w-full rounded border p-2" type="datetime-local" value={occurrence} onChange={e=>setOccurrence(e.target.value)}/></label><label>Travel odometer<input className="block w-full rounded border p-2" type="number" min="0" value={odometer} onChange={e=>setOdometer(e.target.value)}/></label><label>Location<input className="block w-full rounded border p-2" value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Refuel liters<input className="block w-full rounded border p-2" type="number" min="0" value={liters} onChange={e=>setLiters(e.target.value)}/></label></div><div className="mt-4 flex flex-wrap gap-2"><Button type="button" onClick={()=>run(()=>repo.recordManualActivity({...base,action,clientOccurredAt:occurred}))}>Record Activity</Button><Button type="button" onClick={()=>run(()=>repo.recordManualTravel({...base,odometer:Number(odometer),locationName:location||undefined,clientOccurredAt:occurred}))}>Record Travel</Button><Button type="button" onClick={()=>run(()=>repo.recordManualRefuel({...base,odometer:Number(odometer),liters:Number(liters),locationName:location||undefined,clientOccurredAt:occurred}))}>Record Refuel</Button><Button type="button" variant="success" onClick={()=>run(()=>repo.completeManualShift({...base,closingOdometer:Number(odometer),clientOccurredAt:occurred}))}>End Shift</Button><Button type="button" variant="secondary" onClick={()=>run(()=>repo.submitManualDeur(base))}>Submit</Button></div></section>;
}
