import { useState } from "react";
import Button from "@/components/ui/Button";
import { useToast } from "@/components/ui/toast/ToastContext";
import { useAuth } from "@/features/auth/AuthContext";
import { useRentalWorkspaceAggregate } from "..";
import { useApplicationDependenciesCompatibility } from "@/app/composition";
import type { ManualDeurCommandRepository } from "@/features/rental/deur/commands/contracts";

const reasons = ["DEVICE_LOST","DEVICE_DAMAGED","APP_UNAVAILABLE","CONNECTIVITY_OR_TECHNICAL_ISSUE","OPERATOR_DEVICE_UNAVAILABLE","OTHER"] as const;
export default function RemoteManualDeurAction() {
  const aggregate=useRentalWorkspaceAggregate(); const {hasPermission}=useAuth(); const {showToast}=useToast();
  const {commandRepositories}=useApplicationDependenciesCompatibility();
  const [open,setOpen]=useState(false), [lineId,setLineId]=useState(aggregate.rentalEquipmentLines.length===1?aggregate.rentalEquipmentLines[0].id:""), [reason,setReason]=useState<string>(reasons[0]), [notes,setNotes]=useState(""), [reference,setReference]=useState(""), [openingOdometer,setOpeningOdometer]=useState("");
  const repository=commandRepositories.deurCommands as unknown as ManualDeurCommandRepository;
  const line=aggregate.rentalEquipmentLines.find(item=>item.id===lineId); const remote=import.meta.env.VITE_REMOTE_MANUAL_DEUR_CREATE_ENABLED === "true";
  if(!remote || !hasPermission("deur.create") || !line) return null;
  async function create(){ if(reason==="OTHER"&&!notes.trim()){showToast("Notes are required for Other.","error");return} const value=Number(openingOdometer); if(!Number.isFinite(value)||value<0){showToast("Enter a non-negative opening odometer.","error");return} const result=await repository.createManualDeur({commandId:crypto.randomUUID(),idempotencyKey:crypto.randomUUID(),rentalLineId:lineId,reason,notes:notes||undefined,physicalDeurReference:reference||undefined,openingOdometer:value}); if(!result.success){showToast(result.message,"error");return} showToast("Manual DEUR created in the canonical workspace.","success"); setOpen(false); window.location.reload(); }
  if(!open) return <Button type="button" onClick={()=>setOpen(true)}>CREATE MANUAL DEUR</Button>;
  return <section className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h3 className="font-semibold">Create Manual DEUR <span className="ml-2 rounded bg-indigo-100 px-2 py-1 text-xs text-indigo-800">MANUAL_WEB</span></h3><p className="text-xs text-slate-600">Canonical identity and meter policy are resolved from the selected active line. Only transcription reason and physical evidence are entered here.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 text-sm">{aggregate.rentalEquipmentLines.length>1&&<label className="sm:col-span-2">Equipment Line<select className="block w-full rounded border p-2" value={lineId} onChange={e=>setLineId(e.target.value)}><option value="">Select</option>{aggregate.rentalEquipmentLines.filter(x=>["Released","Active"].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.equipmentId}</option>)}</select></label>}<div>Rental<p>{aggregate.rental.rentalNumber??aggregate.rental.id}</p></div><div>Assignment<p>{line.assignmentId}</p></div><div>Equipment<p>{line.equipmentId}</p></div><div>Operator<p>{line.operatorId}</p></div><label>Reason<select className="block w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Opening Odometer<input className="block w-full rounded border p-2" type="number" min="0" value={openingOdometer} onChange={e=>setOpeningOdometer(e.target.value)}/></label><label>Physical DEUR Reference<input className="block w-full rounded border p-2" value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="sm:col-span-2">Notes<textarea className="block w-full rounded border p-2" value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="mt-4 flex gap-2"><Button type="button" onClick={create}>Create canonical DEUR</Button><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button></div></section>;
}
