import { useEffect, useMemo, useRef, useState } from "react";
import { Search, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useApplicationDependenciesCompatibility } from "@/app/composition";
import { PersistenceMode } from "@/app/composition/ApplicationDependencies";
import { useAssignment } from "@/features/assignment/context/AssignmentContext";
import { useAuth } from "@/features/auth/AuthContext";
import type { Permission } from "@/features/auth/domain/permission";
import { useCustomer } from "@/features/customer/context/CustomerContext";
import { useEquipment } from "@/features/equipment/context/EquipmentContext";
import { useOperator } from "@/features/operators/context/OperatorContext";
import { useProject } from "@/features/project/context/ProjectContext";
import { useRental } from "@/features/rental/context/RentalContext";
import { buildGlobalSearchRecords, createLatestSearchGuard, loadRemoteGlobalSearchData, searchGlobalRecords, type GlobalSearchData } from "./globalSearchService";

export default function GlobalSearch() {
  const [query,setQuery]=useState(""),[debounced,setDebounced]=useState(""),[active,setActive]=useState(-1),[mobileOpen,setMobileOpen]=useState(false),[remoteData,setRemoteData]=useState<GlobalSearchData>(),[loading,setLoading]=useState(false),[searchError,setSearchError]=useState(false);
  const inputRef=useRef<HTMLInputElement>(null),guard=useRef(createLatestSearchGuard());
  const navigate=useNavigate(),{hasPermission}=useAuth(),dependencies=useApplicationDependenciesCompatibility(),remote=dependencies.configuration.persistenceMode===PersistenceMode.Remote;
  const {equipment}=useEquipment(),{operators}=useOperator(),{customers}=useCustomer(),{projects}=useProject(),{rentals}=useRental(),{assignments}=useAssignment();
  const localData=useMemo<GlobalSearchData>(()=>({equipment,operators,customers,projects,rentals,assignments,deurs:dependencies.repositories.deur.getAll(),billing:dependencies.repositories.billingStatement.getAll()}),[assignments,customers,dependencies,equipment,operators,projects,rentals]);
  useEffect(()=>{const timer=setTimeout(()=>setDebounced(query),180);return()=>clearTimeout(timer)},[query]);
  useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null,isEditable=target?.tagName==="INPUT"||target?.tagName==="TEXTAREA"||target?.isContentEditable;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"||event.key==="/"&&!isEditable){event.preventDefault();inputRef.current?.focus()}};window.addEventListener("keydown",shortcut);return()=>window.removeEventListener("keydown",shortcut)},[]);
  useEffect(()=>{if(!remote||debounced.trim().length<2){guard.current.cancel();setRemoteData(undefined);setLoading(false);setSearchError(false);return}const controller=new AbortController(),isCurrent=guard.current.begin();setLoading(true);setSearchError(false);void loadRemoteGlobalSearchData(dependencies.readRepositories,debounced,p=>hasPermission(p as Permission),controller.signal).then(result=>{if(isCurrent()){setRemoteData(result.data);setSearchError(result.hasError)}}).catch(()=>{if(isCurrent()&&!controller.signal.aborted)setSearchError(true)}).finally(()=>{if(isCurrent())setLoading(false)});return()=>controller.abort()},[debounced,dependencies.readRepositories,hasPermission,remote]);
  const records=useMemo(()=>buildGlobalSearchRecords(remote?(remoteData??{equipment:[],operators:[],customers:[],projects:[],assignments:[],rentals:[],deurs:[],billing:[]}):localData),[localData,remote,remoteData]);
  const results=useMemo(()=>searchGlobalRecords(records,debounced,p=>hasPermission(p as Permission)),[debounced,hasPermission,records]);
  const groups=Object.entries(results.reduce<Record<string,typeof results>>((all,result)=>{(all[result.type]??=[]).push(result);return all},{}));
  const close=()=>{setQuery("");setDebounced("");setActive(-1);setMobileOpen(false)};const choose=(href:string)=>{navigate(href);close()};
  const input=<div className="relative"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-2.5 text-slate-400" size={16}/><input ref={inputRef} autoFocus={mobileOpen} aria-label="Global search" aria-controls="global-search-results" aria-expanded={query.trim().length>=2} className="app-control w-full py-2 pl-9 pr-9 text-xs" placeholder="Search equipment, rentals, DEUR, billing..." value={query} onChange={e=>{setQuery(e.target.value);setActive(-1)}} onKeyDown={e=>{if(e.key==="Escape")close();else if(e.key==="ArrowDown"){e.preventDefault();setActive(v=>Math.min(v+1,results.length-1))}else if(e.key==="ArrowUp"){e.preventDefault();setActive(v=>Math.max(v-1,0))}else if(e.key==="Enter"&&active>=0){e.preventDefault();choose(results[active].href)}}}/>{query&&<button type="button" aria-label="Clear global search" className="absolute right-2 top-2 rounded p-1 text-slate-500" onClick={close}><X size={16}/></button>}{query.trim().length>=2&&<div id="global-search-results" role="listbox" className="absolute right-0 z-50 mt-1 max-h-[70vh] w-full min-w-[340px] overflow-auto rounded-lg border border-slate-200 bg-white p-2 shadow-xl dark:border-slate-700 dark:bg-slate-900">{loading?<p className="p-3 text-sm text-slate-500">Searching…</p>:results.length===0?<p className="p-3 text-sm text-slate-500">No results found.</p>:groups.map(([type,items])=><section key={type} aria-label={`${type} results`}><h3 className="px-2 py-1 text-xs font-semibold uppercase text-slate-500">{type}</h3>{items.map(item=>{const index=results.indexOf(item);return <button role="option" aria-selected={active===index} type="button" key={`${item.type}:${item.id}`} onMouseEnter={()=>setActive(index)} onClick={()=>choose(item.href)} className={`block w-full rounded-md p-2 text-left ${active===index?"bg-blue-50 text-blue-950 dark:bg-blue-950 dark:text-blue-50":"hover:bg-slate-100 dark:hover:bg-slate-800"}`}><strong className="block text-sm">{item.title}</strong><span className="block text-xs text-slate-500 dark:text-slate-400">{item.subtitle}</span></button>})}</section>)}{searchError&&<p role="status" className="border-t p-2 text-xs text-amber-700">Some search sources are temporarily unavailable.</p>}</div>}</div>;
  return <><div className="hidden sm:block">{input}</div><button type="button" aria-label="Open global search" className="rounded-md p-2 sm:hidden" onClick={()=>setMobileOpen(true)}><Search size={19}/></button>{mobileOpen&&<div role="dialog" aria-modal="true" aria-label="Global search" className="fixed inset-0 z-[70] bg-white p-4 dark:bg-slate-950 sm:hidden"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Global Search</h2><button aria-label="Close global search" onClick={close}><X/></button></div>{input}</div>}</>;
}
