import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Eye, EyeOff, X } from "lucide-react";
import { PersistenceMode, useApplicationDependenciesCompatibility } from "@/app/composition";
import { useAuth } from "@/features/auth/AuthContext";
import type { User } from "@/features/auth/domain/user";
import { useOperator } from "@/features/operators/context/OperatorContext";
import { CanonicalRoleAdministrationService } from "@/features/administration/services/CanonicalRoleAdministrationService";
import { AuthorizationAuditService } from "@/features/administration/services/AuthorizationAuditService";
import type { RemoteAssignableRole } from "../services/RemoteUserAdministration";

const emptyForm={username:"",displayName:"",email:"",initialPassword:"",roleCodes:[] as string[],operatorId:""};
type UserForm=typeof emptyForm;
type FieldErrors={username?:string;email?:string};
function Dialog({title,onClose,children,returnFocus}:{title:string;onClose:()=>void;children:ReactNode;returnFocus?:HTMLElement|null}){const titleId=`dialog-${title.toLowerCase().replace(/\W+/g,"-")}`,panel=useRef<HTMLDivElement>(null),closeRef=useRef(onClose);closeRef.current=onClose;useEffect(()=>{panel.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")closeRef.current()};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);returnFocus?.focus()}},[returnFocus]);return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 id={titleId} className="text-xl font-bold">{title}</h2><button aria-label={`Close ${title}`} className="rounded p-2" onClick={onClose}><X aria-hidden="true"/></button></div>{children}</div></div>}

export default function UsersPage(){
 const {user:actor,hasPermission}=useAuth(),{operators:localOperators}=useOperator(),deps=useApplicationDependenciesCompatibility(),service=deps.authentication.userManagementService,remote=deps.configuration.persistenceMode===PersistenceMode.Remote,remoteAdmin=deps.authentication.remoteUserAdministration;
 const catalog=useMemo(()=>new CanonicalRoleAdministrationService(undefined,deps.authentication.userRepository),[deps.authentication.userRepository]),audit=useMemo(()=>new AuthorizationAuditService(),[]),localRoles=catalog.listRoles().filter(x=>x.active);
 const [version,setVersion]=useState(0),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[form,setForm]=useState<UserForm>(emptyForm),[passwordVisible,setPasswordVisible]=useState(false),[fieldErrors,setFieldErrors]=useState<FieldErrors>({});
 const [remoteUsers,setRemoteUsers]=useState<readonly User[]>([]),[remoteRoles,setRemoteRoles]=useState<readonly RemoteAssignableRole[]>([]),[remoteOperators,setRemoteOperators]=useState(localOperators),[remoteLoading,setRemoteLoading]=useState(false);
 const [editUser,setEditUser]=useState<User>(),[editForm,setEditForm]=useState<UserForm>(emptyForm),[viewUser,setViewUser]=useState<User>(),[resetUser,setResetUser]=useState<User>(),[statusUser,setStatusUser]=useState<User>(),[deleteUser,setDeleteUser]=useState<User>(),[trigger,setTrigger]=useState<HTMLElement|null>(null),[busy,setBusy]=useState(false),[newPassword,setNewPassword]=useState(""),[confirmNewPassword,setConfirmNewPassword]=useState(""),[resetVisible,setResetVisible]=useState(false);
 const creating=useRef(false),resetCommand=useRef<string|undefined>(undefined);
 const refreshRemote=async()=>{if(!remoteAdmin)return;setRemoteLoading(true);try{const[nextUsers,nextRoles,nextOperators]=await Promise.all([remoteAdmin.listUsers(),remoteAdmin.listRoles(),remoteAdmin.listOperators()]);setRemoteUsers(nextUsers);setRemoteRoles(nextRoles);setRemoteOperators([...nextOperators]);}catch(value){setError(value instanceof Error?value.message:"Unable to load remote user administration data.");}finally{setRemoteLoading(false)}};
 const handleCreateDetailsToggle=(event:React.SyntheticEvent<HTMLDetailsElement>)=>{if(event.currentTarget.open&&remote&&!remoteLoading)void refreshRemote()};
 useEffect(()=>{if(remote)void refreshRemote()},[remote,remoteAdmin,version]);
 const runtimeRoles=remote?remoteRoles:localRoles,roles=runtimeRoles.filter(role=>role.active&&!('deprecatedAt' in role&&role.deprecatedAt)),operators=remote?remoteOperators:localOperators,activeOperators=useMemo(()=>operators.filter(x=>x.status==="Active"),[operators]),users=useMemo(()=>{const all=remote?remoteUsers:(actor?service.search(actor,query):[]),term=query.trim().toLocaleLowerCase();return term?all.filter(user=>`${user.username} ${user.displayName} ${user.email??""} ${user.systemRoles.join(" ")}`.toLocaleLowerCase().includes(term)):all},[actor,query,remote,remoteUsers,service,version]),canResetPassword=runtimeRoles.some(role=>actor?.systemRoles.includes(role.code)&&role.permissions.includes("users.password.reset")),localOperatorPin=!remote&&!!resetUser?.operatorId;
 const close=()=>{setEditUser(undefined);setViewUser(undefined);setResetUser(undefined);setStatusUser(undefined);setDeleteUser(undefined);resetCommand.current=undefined;setNewPassword("");setConfirmNewPassword("");setResetVisible(false);setError("");setBusy(false)};
 const roleToggle=(target:"create"|"edit",code:string)=>{const update=(current:UserForm)=>({...current,roleCodes:current.roleCodes.includes(code)?current.roleCodes.filter(x=>x!==code):[...new Set([...current.roleCodes,code])].sort()});target==="create"?setForm(update):setEditForm(update)};
 const mapError=(value:unknown)=>{const text=value instanceof Error?value.message:"Unable to save user.";setError(text);if(text.startsWith("Username already exists"))setFieldErrors({username:text});else if(text.startsWith("Email already exists"))setFieldErrors({email:text});return text};
 async function create(event:React.FormEvent){event.preventDefault();if(!actor||creating.current)return;creating.current=true;setBusy(true);setError("");setFieldErrors({});try{const input={username:form.username,displayName:form.displayName,email:form.email||undefined,initialPassword:form.initialPassword,systemRoles:form.roleCodes,operatorId:form.operatorId||undefined};if(remote){if(!remoteAdmin)throw new Error("Remote user administration is unavailable.");const commandId=crypto.randomUUID();await remoteAdmin.create({...input,commandId,idempotencyKey:commandId});}else service.create(actor,input);setForm(emptyForm);setPasswordVisible(false);setVersion(x=>x+1);setMessage("User successfully created.")}catch(value){mapError(value)}finally{creating.current=false;setBusy(false)}}
 function openEdit(user:User,event:React.MouseEvent<HTMLButtonElement>){setTrigger(event.currentTarget);setFieldErrors({});setError("");setEditUser(user);setEditForm({username:user.username,displayName:user.displayName,email:user.email??"",initialPassword:"",roleCodes:[...new Set(user.systemRoles)].sort(),operatorId:user.operatorId??""})}
 function saveEdit(event:React.FormEvent){event.preventDefault();if(!actor||!editUser)return;setBusy(true);setFieldErrors({});try{service.update(actor,editUser.id,{username:editForm.username,displayName:editForm.displayName,email:editForm.email||undefined,systemRoles:editForm.roleCodes,operatorId:editForm.operatorId||undefined});setVersion(x=>x+1);setMessage("User updated successfully. Sign out and sign back in for the repaired link to take effect.");close()}catch(value){mapError(value);setBusy(false)}}
 async function confirmStatus(){if(!actor||!statusUser)return;setBusy(true);try{const activating=statusUser.status==="inactive";if(remote){if(activating)throw new Error("Remote user activation is not available in this milestone.");if(!remoteAdmin)throw new Error("Remote user administration is unavailable.");const commandId=crypto.randomUUID();await remoteAdmin.deactivate(statusUser.id,commandId,commandId)}else activating?service.activate(actor,statusUser.id):service.deactivate(actor,statusUser.id);setVersion(x=>x+1);setMessage(`${statusUser.displayName} was ${activating?"activated":"deactivated"}.`);close()}catch(value){setError(value instanceof Error?value.message:"Unable to update user status.");setBusy(false)}}
 async function reset(event:React.FormEvent){event.preventDefault();if(!actor||!resetUser)return;setBusy(true);setError("");try{if(newPassword!==confirmNewPassword)throw new Error("New Password and Confirm New Password do not match.");if(remote){if(!remoteAdmin)throw new Error("Remote password reset is unavailable.");const commandId=resetCommand.current??crypto.randomUUID();resetCommand.current=commandId;await remoteAdmin.resetPassword(resetUser.id,newPassword,commandId,commandId)}else if(resetUser.operatorId)await deps.authentication.operatorPinCredentialService?.setPin(resetUser.id,newPassword,confirmNewPassword);else service.resetLocalPassword(actor,resetUser.id,{newPassword,confirmNewPassword});setVersion(x=>x+1);setMessage(remote||!resetUser.operatorId?`Access reset successfully for ${resetUser.displayName}.`:`PIN reset successfully for ${resetUser.displayName}.`);close()}catch(value){setError(value instanceof Error?value.message:"Unable to reset access.");setBusy(false)}finally{setNewPassword("");setConfirmNewPassword("");setResetVisible(false)}}
 function confirmDelete(){if(!actor||!deleteUser)return;setBusy(true);try{service.delete(actor,deleteUser.id);setVersion(x=>x+1);setMessage(`${deleteUser.displayName} was deleted.`);close()}catch(value){setError(value instanceof Error?value.message:"Unable to delete user. Deactivate this user instead.");setBusy(false)}}
 const fields=(value:UserForm,setValue:(next:UserForm)=>void,editing=false)=><><div className="grid gap-3 md:grid-cols-2"><label htmlFor={editing?"edit-full-name":"user-full-name"}>Full Name *<input id={editing?"edit-full-name":"user-full-name"} className="mt-1 block w-full rounded border p-2" required value={value.displayName} onChange={e=>setValue({...value,displayName:e.target.value})}/></label><label htmlFor={editing?"edit-username":"user-username"}>Username *<input id={editing?"edit-username":"user-username"} aria-invalid={!!fieldErrors.username} className="mt-1 block w-full rounded border p-2" required value={value.username} onChange={e=>setValue({...value,username:e.target.value})}/>{fieldErrors.username&&<span role="alert" className="text-sm text-red-700">{fieldErrors.username}</span>}</label><label htmlFor={editing?"edit-email":"user-email"}>Email {!editing&&"*"}<input id={editing?"edit-email":"user-email"} type="email" aria-invalid={!!fieldErrors.email} className="mt-1 block w-full rounded border p-2" required={!editing} value={value.email} onChange={e=>setValue({...value,email:e.target.value})}/>{fieldErrors.email&&<span role="alert" className="text-sm text-red-700">{fieldErrors.email}</span>}</label>{!editing&&<label htmlFor="user-password">Password *<span className="relative mt-1 block"><input id="user-password" type={passwordVisible?"text":"password"} className="w-full rounded border p-2 pr-10" required value={value.initialPassword} onChange={e=>setValue({...value,initialPassword:e.target.value})}/><button type="button" aria-label={passwordVisible?"Hide password":"Show password"} className="absolute inset-y-0 right-0 px-3" onClick={()=>setPasswordVisible(x=>!x)}>{passwordVisible?<EyeOff aria-hidden="true" size={18}/>:<Eye aria-hidden="true" size={18}/>}</button></span></label>}</div><fieldset className="mt-3"><legend className="font-semibold">Assigned Roles</legend><div className="grid gap-2 md:grid-cols-3">{roles.map(role=><label className="rounded border p-2" key={role.code}><input type="checkbox" checked={value.roleCodes.includes(role.code)} onChange={()=>roleToggle(editing?"edit":"create",role.code)}/> {role.name}</label>)}</div></fieldset><label className="mt-3 block" htmlFor={editing?"edit-linked-operator":"linked-operator"}>Linked Operator<select id={editing?"edit-linked-operator":"linked-operator"} aria-label="Linked operator" className="ml-2 rounded border p-2" value={value.operatorId} onChange={e=>setValue({...value,operatorId:e.target.value})}><option value="">None</option>{activeOperators.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></>;
 const effective=viewUser?(remote?[...new Set(runtimeRoles.filter(role=>viewUser.systemRoles.includes(role.code)).flatMap(role=>role.permissions))].sort():catalog.resolvePermissions(viewUser.systemRoles)):[],history=viewUser?audit.forUser(viewUser.id):[];
 return <main className="space-y-6"><header className="flex flex-wrap items-end justify-between"><div><h1 className="text-2xl font-bold">Users</h1><p>Manage employee identities, roles, Operator links, and account status.</p></div></header>{message&&<p role="status" className="rounded border border-green-300 bg-green-50 p-3">{message}</p>}{deleteUser&&<Dialog title="Delete User" onClose={close} returnFocus={trigger}><div className="mt-4 space-y-4"><p>You are about to permanently delete:</p><p><b>{deleteUser.displayName} ({deleteUser.username})</b></p><p>This action may remove the application user account and local administration records. This action cannot be undone. Business and audit history will never be cascade-deleted.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button className="rounded border px-3 py-2" onClick={close}>Cancel</button><button disabled={busy} className="rounded bg-red-700 px-3 py-2 text-white" onClick={confirmDelete}>{busy?"Deleting…":"Delete User"}</button></div></div></Dialog>}
 <details className="rounded-xl border bg-white" onToggle={handleCreateDetailsToggle}><summary className="cursor-pointer p-4 text-lg font-semibold">+ Create User</summary><form className="space-y-3 border-t p-5" onSubmit={create}>{error&&<p tabIndex={-1} role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-700">{error}</p>}{fields(form,setForm)}<button disabled={busy||remoteLoading} className="rounded bg-blue-700 p-2 text-white disabled:opacity-60">{busy?"Creating…":"Create User"}</button></form></details>
 <label htmlFor="user-search">Search Users and System Records<input id="user-search" type="search" className="mt-1 block w-full rounded border p-3" placeholder="Search by name, username, email, or role" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3" scope="col">Full Name</th><th className="p-3" scope="col">Username</th><th className="p-3" scope="col">Email</th><th className="p-3" scope="col">Roles</th><th className="p-3" scope="col">Linked Operator</th><th className="p-3" scope="col">Status</th><th className="p-3" scope="col">Actions</th></tr></thead><tbody>{users.map(user=><tr className="border-t align-top" key={user.id}><td className="p-3 font-medium">{user.displayName}</td><td className="p-3">{user.username}</td><td className="p-3">{user.email||"—"}</td><td className="p-3"><div className="flex flex-wrap gap-1">{user.systemRoles.map(code=><span className="rounded-full border px-2" key={code}>{roles.find(role=>role.code===code)?.name??catalog.getRoleDisplayName(code)}</span>)}</div></td><td className="p-3">{operators.find(x=>x.id===user.operatorId)?.name??"None"}</td><td className="p-3"><span className="rounded-full border px-2">{user.status==="active"?"Active":"Inactive"}</span></td><td className="p-3"><div className="flex flex-wrap gap-2"><button disabled={remote} title={remote?"Remote editing is not available in this milestone.":undefined} className="rounded border px-2 py-1 disabled:opacity-50" onClick={event=>openEdit(user,event)}>Edit</button><button className="rounded border px-2 py-1" onClick={event=>{setTrigger(event.currentTarget);setViewUser(user)}}>View Access</button>{(!remote||canResetPassword)&&<button className="rounded border px-2 py-1" onClick={event=>{setTrigger(event.currentTarget);setResetUser(user);setError("");setNewPassword("");setConfirmNewPassword("")}}>{!remote&&user.operatorId?"Reset PIN":"Reset Password"}</button>}{!user.systemRoles.includes("system-administrator")&&((user.status==="active"&&(!remote||hasPermission("users.deactivate")))||(user.status==="inactive"&&!remote))&&<button disabled={user.id===actor?.id} title={user.id===actor?.id?"You cannot deactivate your own active account.":undefined} className={`rounded border px-2 py-1 disabled:opacity-50 ${user.status==="active"?"border-red-500 text-red-700":""}`} onClick={event=>{setTrigger(event.currentTarget);setStatusUser(user);setError("")}}>{user.status==="active"?"Deactivate":"Activate"}</button>}<button disabled={remote} title={remote?"Remote deletion is not available in this milestone.":undefined} className="rounded border border-red-700 px-2 py-1 text-red-800 disabled:opacity-50" onClick={event=>{setTrigger(event.currentTarget);setDeleteUser(user);setError("")}}>Delete</button></div></td></tr>)}</tbody></table>{!users.length&&<p className="p-6 text-center">{remoteLoading?"Loading canonical Users…":"No users found."}</p>}</div>
 {editUser&&<Dialog title="Edit User" onClose={close} returnFocus={trigger}><form className="mt-4" onSubmit={saveEdit}>{error&&<p role="alert" className="mb-3 text-red-700">{error}</p>}{fields(editForm,setEditForm,true)}<div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded border px-3 py-2" onClick={close}>Cancel</button><button disabled={busy} className="rounded bg-blue-700 px-3 py-2 text-white">{busy?"Saving…":"Save Changes"}</button></div></form></Dialog>}
 {viewUser&&<Dialog title="User Access" onClose={close} returnFocus={trigger}><div className="mt-3"><h3 className="text-lg font-semibold">{viewUser.displayName}</h3><p>{viewUser.username}</p><h4 className="mt-4 font-semibold">Assigned Roles</h4><div className="flex flex-wrap gap-1">{viewUser.systemRoles.map(x=><span className="rounded-full border px-2" key={x}>{runtimeRoles.find(role=>role.code===x)?.name??catalog.getRoleDisplayName(x)}</span>)}</div><p className="mt-4"><b>Effective Canonical Access:</b> {effective.length} permissions · Catalog {remote?(runtimeRoles.find(role=>role.catalogVersion)?.catalogVersion??"runtime"):catalog.catalogVersion}</p>{!remote&&<p className="text-sm text-amber-800">Canonical access is an administration projection. Legacy authorization remains runtime authority.</p>}{catalog.getPermissionGroups().map(group=>{const items=effective.filter(code=>group.resources.some(resource=>code===resource||code.startsWith(`${resource}.`)));return items.length?<details className="mt-2 rounded border p-2" key={group.code}><summary>{group.label} ({items.length})</summary><ul>{items.map(code=><li key={code}><span>{words(code)}</span><code className="ml-2 text-xs text-slate-500">{code}</code></li>)}</ul></details>:null})}<h4 className="mt-4 font-semibold">Authorization History</h4>{history.length?<ul>{history.map(x=><li key={x.id}>{x.occurredAt} — {x.action}</li>)}</ul>:<p>No authorization events recorded.</p>}</div></Dialog>}
 {resetUser&&<Dialog title={localOperatorPin?"Reset PIN":"Reset Password"} onClose={close} returnFocus={trigger}><form className="mt-4 space-y-3" onSubmit={reset}><p><b>User:</b> {resetUser.displayName}<span className="block">{resetUser.username}</span></p><p>{localOperatorPin?"This replaces the Operator’s field PIN. The PIN is stored only as a salted verifier and is never written to audit evidence.":"This replaces the user’s existing password. The password is never written to audit evidence."}</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<label htmlFor="reset-new-password">{localOperatorPin?"New PIN":"New Password"}<span className="relative mt-1 block"><input id="reset-new-password" type={resetVisible?"text":"password"} inputMode={localOperatorPin?"numeric":undefined} minLength={localOperatorPin?4:8} maxLength={localOperatorPin?4:undefined} pattern={localOperatorPin?"[0-9]{4}":undefined} className="w-full rounded border p-2 pr-10" required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><button type="button" className="absolute inset-y-0 right-0 px-3" aria-label={resetVisible?"Hide credential":"Show credential"} onClick={()=>setResetVisible(x=>!x)}>{resetVisible?<EyeOff aria-hidden="true" size={18}/>:<Eye aria-hidden="true" size={18}/>}</button></span></label><label htmlFor="reset-confirm-password">{localOperatorPin?"Confirm PIN":"Confirm Password"}<input id="reset-confirm-password" type="password" inputMode={localOperatorPin?"numeric":undefined} minLength={localOperatorPin?4:8} maxLength={localOperatorPin?4:undefined} pattern={localOperatorPin?"[0-9]{4}":undefined} className="mt-1 block w-full rounded border p-2" required value={confirmNewPassword} onChange={e=>setConfirmNewPassword(e.target.value)}/></label><div className="flex justify-end gap-2"><button type="button" className="rounded border px-3 py-2" onClick={close}>Cancel</button><button disabled={busy} className="rounded bg-amber-700 px-3 py-2 text-white">{busy?"Resetting…":localOperatorPin?"Reset PIN":"Reset Password"}</button></div></form></Dialog>}
 {statusUser&&<Dialog title={statusUser.status==="active"?"Deactivate User":"Activate User"} onClose={close} returnFocus={trigger}><div className="mt-4 space-y-4"><p>{statusUser.status==="active"?`Deactivate ${statusUser.displayName} (${statusUser.username})? This user will no longer be able to sign in until reactivated.`:`Activate ${statusUser.displayName} (${statusUser.username})? This user will be able to sign in again.`}</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button className="rounded border px-3 py-2" onClick={close}>Cancel</button><button disabled={busy} className={`rounded px-3 py-2 text-white ${statusUser.status==="active"?"bg-red-700":"bg-blue-700"}`} onClick={confirmStatus}>{busy?"Updating…":statusUser.status==="active"?"Deactivate User":"Activate User"}</button></div></div></Dialog>}</main>
}

function words(value:string){return value.replace(/([a-z])([A-Z])/g,"$1 $2").split(/[._-]/).map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(" ")}
