import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Eye, EyeOff, X } from "lucide-react";
import { useApplicationDependenciesCompatibility } from "@/app/composition";
import { useAuth } from "@/features/auth/AuthContext";
import type { User } from "@/features/auth/domain/user";
import { useOperator } from "@/features/operators/context/OperatorContext";
import { CanonicalRoleAdministrationService } from "@/features/administration/services/CanonicalRoleAdministrationService";
import { AuthorizationAuditService } from "@/features/administration/services/AuthorizationAuditService";

const emptyForm={username:"",displayName:"",email:"",initialPassword:"",roleCodes:[] as string[],operatorId:""};
type UserForm=typeof emptyForm;
type FieldErrors={username?:string;email?:string};
function Dialog({title,onClose,children,returnFocus}:{title:string;onClose:()=>void;children:ReactNode;returnFocus?:HTMLElement|null}){const titleId=`dialog-${title.toLowerCase().replace(/\W+/g,"-")}`,panel=useRef<HTMLDivElement>(null),closeRef=useRef(onClose);closeRef.current=onClose;useEffect(()=>{panel.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")closeRef.current()};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);returnFocus?.focus()}},[returnFocus]);return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 id={titleId} className="text-xl font-bold">{title}</h2><button aria-label={`Close ${title}`} className="rounded p-2" onClick={onClose}><X aria-hidden="true"/></button></div>{children}</div></div>}

export default function UsersPage(){
 const {user:actor}=useAuth(),{operators}=useOperator(),deps=useApplicationDependenciesCompatibility(),service=deps.authentication.userManagementService;
 const catalog=useMemo(()=>new CanonicalRoleAdministrationService(undefined,deps.authentication.userRepository),[deps.authentication.userRepository]),audit=useMemo(()=>new AuthorizationAuditService(),[]),roles=catalog.listRoles().filter(x=>x.active);
 const [version,setVersion]=useState(0),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[form,setForm]=useState<UserForm>(emptyForm),[passwordVisible,setPasswordVisible]=useState(false),[fieldErrors,setFieldErrors]=useState<FieldErrors>({});
 const [editUser,setEditUser]=useState<User>(),[editForm,setEditForm]=useState<UserForm>(emptyForm),[viewUser,setViewUser]=useState<User>(),[resetUser,setResetUser]=useState<User>(),[statusUser,setStatusUser]=useState<User>(),[deleteUser,setDeleteUser]=useState<User>(),[trigger,setTrigger]=useState<HTMLElement|null>(null),[busy,setBusy]=useState(false),[newPassword,setNewPassword]=useState(""),[confirmNewPassword,setConfirmNewPassword]=useState(""),[resetVisible,setResetVisible]=useState(false);
 const activeOperators=useMemo(()=>operators.filter(x=>x.status==="Active"),[operators]),users=useMemo(()=>actor?service.search(actor,query):[],[actor,query,service,version]);
 const close=()=>{setEditUser(undefined);setViewUser(undefined);setResetUser(undefined);setStatusUser(undefined);setDeleteUser(undefined);setError("");setBusy(false)};
 const roleToggle=(target:"create"|"edit",code:string)=>{const update=(current:UserForm)=>({...current,roleCodes:current.roleCodes.includes(code)?current.roleCodes.filter(x=>x!==code):[...new Set([...current.roleCodes,code])].sort()});target==="create"?setForm(update):setEditForm(update)};
 const mapError=(value:unknown)=>{const text=value instanceof Error?value.message:"Unable to save user.";setError(text);if(text.startsWith("Username already exists"))setFieldErrors({username:text});else if(text.startsWith("Email already exists"))setFieldErrors({email:text});return text};
 function create(event:React.FormEvent){event.preventDefault();if(!actor)return;setError("");setFieldErrors({});try{service.create(actor,{username:form.username,displayName:form.displayName,email:form.email||undefined,initialPassword:form.initialPassword,systemRoles:form.roleCodes,operatorId:form.operatorId||undefined});setForm(emptyForm);setPasswordVisible(false);setVersion(x=>x+1);setMessage("User created successfully.")}catch(value){mapError(value)}}
 function openEdit(user:User,event:React.MouseEvent<HTMLButtonElement>){setTrigger(event.currentTarget);setFieldErrors({});setError("");setEditUser(user);setEditForm({username:user.username,displayName:user.displayName,email:user.email??"",initialPassword:"",roleCodes:[...new Set(user.systemRoles)].sort(),operatorId:user.operatorId??""})}
 function saveEdit(event:React.FormEvent){event.preventDefault();if(!actor||!editUser)return;setBusy(true);setFieldErrors({});try{service.update(actor,editUser.id,{username:editForm.username,displayName:editForm.displayName,email:editForm.email||undefined,systemRoles:editForm.roleCodes,operatorId:editForm.operatorId||undefined});setVersion(x=>x+1);setMessage("User updated successfully. Sign out and sign back in for the repaired link to take effect.");close()}catch(value){mapError(value);setBusy(false)}}
 function confirmStatus(){if(!actor||!statusUser)return;setBusy(true);try{const activating=statusUser.status==="inactive";activating?service.activate(actor,statusUser.id):service.deactivate(actor,statusUser.id);setVersion(x=>x+1);setMessage(`${statusUser.displayName} was ${activating?"activated":"deactivated"}.`);close()}catch(value){setError(value instanceof Error?value.message:"Unable to update user status.");setBusy(false)}}
async function reset(event:React.FormEvent){event.preventDefault();if(!actor||!resetUser)return;setBusy(true);setError("");try{if(resetUser.operatorId)await deps.authentication.operatorPinCredentialService?.setPin(resetUser.id,newPassword,confirmNewPassword);else service.resetLocalPassword(actor,resetUser.id,{newPassword,confirmNewPassword});setVersion(x=>x+1);setMessage(resetUser.operatorId?`PIN reset successfully for ${resetUser.displayName}.`:`Access reset successfully for ${resetUser.displayName}.`);setNewPassword("");setConfirmNewPassword("");setResetVisible(false);close()}catch(value){setError(value instanceof Error?value.message:"Unable to reset access.");setBusy(false)}}
 function confirmDelete(){if(!actor||!deleteUser)return;setBusy(true);try{service.delete(actor,deleteUser.id);setVersion(x=>x+1);setMessage(`${deleteUser.displayName} was deleted.`);close()}catch(value){setError(value instanceof Error?value.message:"Unable to delete user. Deactivate this user instead.");setBusy(false)}}
 const fields=(value:UserForm,setValue:(next:UserForm)=>void,editing=false)=><><div className="grid gap-3 md:grid-cols-2"><label htmlFor={editing?"edit-full-name":"user-full-name"}>Full Name *<input id={editing?"edit-full-name":"user-full-name"} className="mt-1 block w-full rounded border p-2" required value={value.displayName} onChange={e=>setValue({...value,displayName:e.target.value})}/></label><label htmlFor={editing?"edit-username":"user-username"}>Username *<input id={editing?"edit-username":"user-username"} aria-invalid={!!fieldErrors.username} className="mt-1 block w-full rounded border p-2" required value={value.username} onChange={e=>setValue({...value,username:e.target.value})}/>{fieldErrors.username&&<span role="alert" className="text-sm text-red-700">{fieldErrors.username}</span>}</label><label htmlFor={editing?"edit-email":"user-email"}>Email {!editing&&"*"}<input id={editing?"edit-email":"user-email"} type="email" aria-invalid={!!fieldErrors.email} className="mt-1 block w-full rounded border p-2" required={!editing} value={value.email} onChange={e=>setValue({...value,email:e.target.value})}/>{fieldErrors.email&&<span role="alert" className="text-sm text-red-700">{fieldErrors.email}</span>}</label>{!editing&&<label htmlFor="user-password">Password *<span className="relative mt-1 block"><input id="user-password" type={passwordVisible?"text":"password"} className="w-full rounded border p-2 pr-10" required value={value.initialPassword} onChange={e=>setValue({...value,initialPassword:e.target.value})}/><button type="button" aria-label={passwordVisible?"Hide password":"Show password"} className="absolute inset-y-0 right-0 px-3" onClick={()=>setPasswordVisible(x=>!x)}>{passwordVisible?<EyeOff aria-hidden="true" size={18}/>:<Eye aria-hidden="true" size={18}/>}</button></span></label>}</div><fieldset className="mt-3"><legend className="font-semibold">Assigned Roles</legend><div className="grid gap-2 md:grid-cols-3">{roles.map(role=><label className="rounded border p-2" key={role.code}><input type="checkbox" checked={value.roleCodes.includes(role.code)} onChange={()=>roleToggle(editing?"edit":"create",role.code)}/> {role.name}</label>)}</div></fieldset><label className="mt-3 block" htmlFor={editing?"edit-linked-operator":"linked-operator"}>Linked Operator<select id={editing?"edit-linked-operator":"linked-operator"} aria-label="Linked operator" className="ml-2 rounded border p-2" value={value.operatorId} onChange={e=>setValue({...value,operatorId:e.target.value})}><option value="">None</option>{activeOperators.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></>;
 const effective=viewUser?catalog.resolvePermissions(viewUser.systemRoles):[],history=viewUser?audit.forUser(viewUser.id):[];
 return <main className="space-y-6"><header className="flex flex-wrap items-end justify-between"><div><h1 className="text-2xl font-bold">Users</h1><p>Manage employee identities, roles, Operator links, and account status.</p></div></header>{message&&<p role="status" className="rounded border border-green-300 bg-green-50 p-3">{message}</p>}{deleteUser&&<Dialog title="Delete User" onClose={close} returnFocus={trigger}><div className="mt-4 space-y-4"><p>You are about to permanently delete:</p><p><b>{deleteUser.displayName} ({deleteUser.username})</b></p><p>This action may remove the application user account and local administration records. This action cannot be undone. Business and audit history will never be cascade-deleted.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button className="rounded border px-3 py-2" onClick={close}>Cancel</button><button disabled={busy} className="rounded bg-red-700 px-3 py-2 text-white" onClick={confirmDelete}>{busy?"Deleting…":"Delete User"}</button></div></div></Dialog>}
 <details className="rounded-xl border bg-white"><summary className="cursor-pointer p-4 text-lg font-semibold">+ Create User</summary><form className="space-y-3 border-t p-5" onSubmit={create}>{fields(form,setForm)}<button className="rounded bg-blue-700 p-2 text-white">Create User</button></form></details>
 <label htmlFor="user-search">Search Users and System Records<input id="user-search" type="search" className="mt-1 block w-full rounded border p-3" placeholder="Search by name, username, email, or role" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3" scope="col">Full Name</th><th className="p-3" scope="col">Username</th><th className="p-3" scope="col">Email</th><th className="p-3" scope="col">Roles</th><th className="p-3" scope="col">Linked Operator</th><th className="p-3" scope="col">Status</th><th className="p-3" scope="col">Actions</th></tr></thead><tbody>{users.map(user=><tr className="border-t align-top" key={user.id}><td className="p-3 font-medium">{user.displayName}</td><td className="p-3">{user.username}</td><td className="p-3">{user.email||"—"}</td><td className="p-3"><div className="flex flex-wrap gap-1">{user.systemRoles.map(code=><span className="rounded-full border px-2" key={code}>{catalog.getRoleDisplayName(code)}</span>)}</div></td><td className="p-3">{operators.find(x=>x.id===user.operatorId)?.name??"None"}</td><td className="p-3"><span className="rounded-full border px-2">{user.status==="active"?"Active":"Inactive"}</span></td><td className="p-3"><div className="flex flex-wrap gap-2"><button className="rounded border px-2 py-1" onClick={event=>openEdit(user,event)}>Edit</button><button className="rounded border px-2 py-1" onClick={event=>{setTrigger(event.currentTarget);setViewUser(user)}}>View Access</button><button className="rounded border px-2 py-1" onClick={event=>{setTrigger(event.currentTarget);setResetUser(user);setError("");setNewPassword("");setConfirmNewPassword("")}}>{user.operatorId?"Reset PIN":"Reset Password"}</button>{!user.systemRoles.includes("system-administrator")&&<button className={`rounded border px-2 py-1 ${user.status==="active"?"border-red-500 text-red-700":""}`} onClick={event=>{setTrigger(event.currentTarget);setStatusUser(user);setError("")}}>{user.status==="active"?"Deactivate":"Activate"}</button>}<button className="rounded border border-red-700 px-2 py-1 text-red-800" onClick={event=>{setTrigger(event.currentTarget);setDeleteUser(user);setError("")}}>Delete</button></div></td></tr>)}</tbody></table>{!users.length&&<p className="p-6 text-center">No users found.</p>}</div>
 {editUser&&<Dialog title="Edit User" onClose={close} returnFocus={trigger}><form className="mt-4" onSubmit={saveEdit}>{error&&<p role="alert" className="mb-3 text-red-700">{error}</p>}{fields(editForm,setEditForm,true)}<div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded border px-3 py-2" onClick={close}>Cancel</button><button disabled={busy} className="rounded bg-blue-700 px-3 py-2 text-white">{busy?"Saving…":"Save Changes"}</button></div></form></Dialog>}
 {viewUser&&<Dialog title="User Access" onClose={close} returnFocus={trigger}><div className="mt-3"><h3 className="text-lg font-semibold">{viewUser.displayName}</h3><p>{viewUser.username}</p><h4 className="mt-4 font-semibold">Assigned Roles</h4><div className="flex flex-wrap gap-1">{viewUser.systemRoles.map(x=><span className="rounded-full border px-2" key={x}>{catalog.getRoleDisplayName(x)}</span>)}</div><p className="mt-4"><b>Effective Canonical Access:</b> {effective.length} permissions · Catalog {catalog.catalogVersion}</p><p className="text-sm text-amber-800">Canonical access is an administration projection. Legacy authorization remains runtime authority.</p>{catalog.getPermissionGroups().map(group=>{const items=service?effective.filter(code=>group.resources.some(resource=>code===resource||code.startsWith(`${resource}.`))):[];return items.length?<details className="mt-2 rounded border p-2" key={group.code}><summary>{group.label} ({items.length})</summary><ul>{items.map(code=><li key={code}><span>{words(code)}</span><code className="ml-2 text-xs text-slate-500">{code}</code></li>)}</ul></details>:null})}<h4 className="mt-4 font-semibold">Authorization History</h4>{history.length?<ul>{history.map(x=><li key={x.id}>{x.occurredAt} — {x.action}</li>)}</ul>:<p>No authorization events recorded.</p>}</div></Dialog>}
 {resetUser&&<Dialog title={resetUser.operatorId?"Reset PIN":"Reset Password"} onClose={close} returnFocus={trigger}><form className="mt-4 space-y-3" onSubmit={reset}><p><b>User:</b> {resetUser.displayName}<span className="block">{resetUser.username}</span></p><p>{resetUser.operatorId?"This replaces the Operator’s field PIN. The PIN is stored only as a salted verifier and is never written to audit evidence.":"This replaces the user’s existing local password. The password is never written to audit evidence."}</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<label htmlFor="reset-new-password">{resetUser.operatorId?"New PIN":"New temporary password"}<span className="relative mt-1 block"><input id="reset-new-password" type={resetVisible?"text":"password"} inputMode={resetUser.operatorId?"numeric":undefined} minLength={resetUser.operatorId?4:undefined} maxLength={resetUser.operatorId?6:undefined} className="w-full rounded border p-2 pr-10" required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><button type="button" className="absolute inset-y-0 right-0 px-3" aria-label={resetVisible?"Hide credential":"Show credential"} onClick={()=>setResetVisible(x=>!x)}>{resetVisible?<EyeOff aria-hidden="true" size={18}/>:<Eye aria-hidden="true" size={18}/>}</button></span></label><label htmlFor="reset-confirm-password">{resetUser.operatorId?"Confirm PIN":"Confirm temporary password"}<input id="reset-confirm-password" type="password" inputMode={resetUser.operatorId?"numeric":undefined} minLength={resetUser.operatorId?4:undefined} maxLength={resetUser.operatorId?6:undefined} className="mt-1 block w-full rounded border p-2" required value={confirmNewPassword} onChange={e=>setConfirmNewPassword(e.target.value)}/></label><div className="flex justify-end gap-2"><button type="button" className="rounded border px-3 py-2" onClick={close}>Cancel</button><button disabled={busy} className="rounded bg-amber-700 px-3 py-2 text-white">{busy?"Resetting…":resetUser.operatorId?"Reset PIN":"Reset Password"}</button></div></form></Dialog>}
 {statusUser&&<Dialog title={statusUser.status==="active"?"Deactivate User":"Activate User"} onClose={close} returnFocus={trigger}><div className="mt-4 space-y-4"><p>{statusUser.status==="active"?`Deactivate ${statusUser.displayName} (${statusUser.username})? This user will no longer be able to sign in until reactivated.`:`Activate ${statusUser.displayName} (${statusUser.username})? This user will be able to sign in again.`}</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button className="rounded border px-3 py-2" onClick={close}>Cancel</button><button disabled={busy} className={`rounded px-3 py-2 text-white ${statusUser.status==="active"?"bg-red-700":"bg-blue-700"}`} onClick={confirmStatus}>{busy?"Updating…":statusUser.status==="active"?"Deactivate User":"Activate User"}</button></div></div></Dialog>}</main>
}

function words(value:string){return value.replace(/([a-z])([A-Z])/g,"$1 $2").split(/[._-]/).map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(" ")}
