import type { DeurActivityTypeCanonical, DeurEventAction, DeurRecord } from "../types";
import { calculateDeurTotals } from "./calculateDeurTotals";
import { deriveDeurEventState } from "./deriveDeurEventState";
export function applyDeurAction(record: DeurRecord, request: { activityType: DeurActivityTypeCanonical; action: DeurEventAction; timestamp: string; idFactory?: () => string; idleReason?: { id: string; labelSnapshot: string; remarks?: string } }) {
  const state = deriveDeurEventState(record); if (record.legacy || ["Submitted", "Acknowledged", "Rejected"].includes(record.status)) return { success: false as const, message: "DEUR is not editable." }; if (!Number.isFinite(Date.parse(request.timestamp)) || state.structuralIssues.length) return { success: false as const, message: "DEUR event history is invalid." };
  const id = request.idFactory ?? (() => crypto.randomUUID()); const group = id(); const events = [...(record.events ?? [])]; const add = (activityType: DeurActivityTypeCanonical, action: DeurEventAction, source: "user" | "automatic") => events.push({ id: id(), activityType, action, timestamp: request.timestamp, sequence: events.length + 1, source, logicalActionId: group, ...(activityType === "idle" && action === "start" && request.idleReason ? { idleReasonId: request.idleReason.id, idleReasonLabelSnapshot: request.idleReason.labelSnapshot, idleReasonRemarks: request.idleReason.remarks } : {}) });
  if (request.activityType === "shift") { if (request.action === "start") { if (!state.shiftNotStarted) return { success:false as const,message:"Shift has already started."}; add("shift","start","user"); } else { if (!state.shiftOpen) return {success:false as const,message:"Shift is not open."}; if(state.openPrimaryActivity) add(state.openPrimaryActivity,"end","automatic"); add("shift","end","user"); } }
  else { if (!state.shiftOpen) return {success:false as const,message:"Start Shift before recording activities."}; if(request.action === "end") { if(state.openPrimaryActivity !== request.activityType) return {success:false as const,message:"Selected activity is not open."}; add(request.activityType,"end","user"); } else { if(state.openPrimaryActivity === request.activityType) return {success:false as const,message:"Selected activity is already open."}; if(state.openPrimaryActivity) add(state.openPrimaryActivity,"end","automatic"); add(request.activityType,"start","user"); } }
  const calculated = calculateDeurTotals(events); return { success:true as const, record:{...record, events, totals:calculated.totals, status:"In Progress" as const, updatedAt:request.timestamp}, createdEvents:events.slice((record.events ?? []).length), logicalActionId:group };
}
