import type { DeurRecord, DeurReviewHistoryEntry } from "../types";
import { formatDeurSubmissionIssues, validateDeurSubmission } from "./validateDeurSubmission";
type Actor={name:string;id?:string;email?:string}; const append=(record:DeurRecord,entry:DeurReviewHistoryEntry)=>[...(record.reviewHistory??[]),entry];
export function submitDeur(record:DeurRecord, actor:Actor, timestamp=new Date().toISOString()){
 const validation=validateDeurSubmission(record);if(!validation.eligible)return{success:false as const,message:formatDeurSubmissionIssues(validation.issues),issues:validation.issues};
 return{success:true as const,record:{...record,status:"Submitted" as const,...(validation.totals?{totals:validation.totals}:{}),submittedAt:timestamp,submittedBy:actor.name,updatedAt:timestamp,reviewHistory:append(record,{action:"submitted",actorName:actor.name,actorId:actor.id,timestamp})}}
}
export function acknowledgeDeur(record:DeurRecord,actor:Actor,timestamp=new Date().toISOString(),remarks=""){if(record.status!=="Submitted"||!actor.name)return{success:false as const,message:"Only submitted DEUR records can be acknowledged."};return{success:true as const,record:{...record,status:"Acknowledged" as const,acknowledgedAt:timestamp,acknowledgedBy:actor.name,acknowledgedByUserId:actor.id,acknowledgementRemarks:remarks.trim()||undefined,updatedAt:timestamp,reviewHistory:append(record,{action:"acknowledged",actorName:actor.name,actorId:actor.id,actorEmail:actor.email,timestamp,reason:remarks.trim()||undefined})}}}
export function rejectDeur(record:DeurRecord,actor:Actor,reason:string,timestamp=new Date().toISOString()){if(record.status!=="Submitted"||!actor.name)return{success:false as const,message:"Only submitted DEUR records can be rejected."};if(!reason.trim())return{success:false as const,message:"A rejection reason is required."};return{success:true as const,record:{...record,status:"Rejected" as const,rejectedAt:timestamp,rejectedBy:actor.name,rejectedByUserId:actor.id,rejectionReason:reason.trim(),updatedAt:timestamp,reviewHistory:append(record,{action:"rejected",actorName:actor.name,actorId:actor.id,actorEmail:actor.email,timestamp,reason:reason.trim()})}}}
export function reopenDeur(record:DeurRecord,actor:Actor,timestamp=new Date().toISOString()){if(record.status!=="Rejected"||!actor.name)return{success:false as const,message:"Only rejected DEUR records can be reopened."};return{success:true as const,record:{...record,status:(record.events?.length?"In Progress":"Draft") as DeurRecord["status"],updatedAt:timestamp,reviewHistory:append(record,{action:"reopened",actorName:actor.name,actorId:actor.id,timestamp})}}}
