import { createClient } from '@supabase/supabase-js';
import type { GroupedReviewWorkerEnvironment } from './configuration';
type Json=Record<string,unknown>;const KEY='DEUR-OFFLINE-RUNTIME-CERT-2026-08-31',PROFILE='UAT_DEUR_OFFLINE_RUNTIME_V1',DATE='2026-08-31';const out=(status:number,body:Json)=>({status,body});
const fixed=(body:unknown)=>Boolean(body&&typeof body==='object'&&!Array.isArray(body)&&Object.keys(body as Json).length===2&&(body as Json).scenarioKey===KEY&&(body as Json).profileVersion===PROFILE);
async function canonical(client:any,name:string,command:Json){const r=await client.schema('erp').rpc(name,{command});if(r.error||(r.data as Json)?.success!==true)throw new Error(String((r.data as Json)?.code??'CANONICAL_COMMAND_FAILED'));}
export async function provisionUatDeurOfflineDomain(request:Request,env:GroupedReviewWorkerEnvironment){
 if(env.ENABLE_UAT_SYNTHETIC_PROVISIONER!=='true'||!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY||!env.SUPABASE_PUBLISHABLE_KEY)return out(503,{success:false,code:'UAT_PROVISIONER_DISABLED'});const token=request.headers.get('authorization')?.match(/^Bearer (.+)$/i)?.[1];if(!token||!fixed(await request.json().catch(()=>null)))return out(400,{success:false,code:'VALIDATION_REJECTED'});
 const service=createClient(env.SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const identity=await service.auth.getUser(token);if(identity.error||!identity.data.user)return out(401,{success:false,code:'UNAUTHENTICATED'});const actor=await service.schema('erp').from('users').select('company_id,status').eq('id',identity.data.user.id).eq('status','active').maybeSingle();const permission=await service.schema('erp').from('effective_user_permissions').select('permission_code').eq('user_id',identity.data.user.id).eq('permission_code','settings.update').maybeSingle();if(actor.error||!actor.data||permission.error||!permission.data)return out(403,{success:false,code:'FORBIDDEN'});const tenant=String(actor.data.company_id);
 const [cost,activity,work]=await Promise.all([service.schema('erp').from('cost_codes').select('id').eq('active',true).is('deleted_at',null).order('code').limit(1).maybeSingle(),service.schema('erp').from('activity_codes').select('id').eq('active',true).is('deleted_at',null).order('code').limit(1).maybeSingle(),service.schema('erp').from('work_descriptions').select('id').eq('active',true).is('deleted_at',null).order('code').limit(1).maybeSingle()]);if(cost.error||activity.error||work.error||!cost.data||!activity.data||!work.data)return out(409,{success:false,code:'UAT_REFERENCE_UNAVAILABLE'});
 const claim=await service.schema('erp').rpc('claim_uat_deur_offline_runtime_scenario',{command:{companyId:tenant,scenarioKey:KEY,profileVersion:PROFILE,references:{costCodeId:cost.data.id,activityCodeId:activity.data.id,workDescriptionId:work.data.id}}});if(claim.error||(claim.data as Json)?.success!==true)return out(409,{success:false,code:(claim.data as Json)?.code as string??'SCENARIO_CLAIM_FAILED'});const s=(claim.data as Json).scenario as Json;if((claim.data as Json).state==='DOMAIN_READY')return inspect(service,tenant);
 const client=createClient(env.SUPABASE_URL,env.SUPABASE_PUBLISHABLE_KEY,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const id=(key:string)=>({commandId:`UAT-OFFLINE-${key}-${s[key+'Id']}`,idempotencyKey:`uat-offline:${key}:${s[key+'Id']}`});
 try{await canonical(client,'command_create_customer',{...id('customer'),customerId:s.customerId,customerCode:'UAT-OFFLINE-CUSTOMER-001',name:'Synthetic UAT Offline Customer 001'});await canonical(client,'command_create_project',{...id('project'),projectId:s.projectId,projectCode:'UAT-OFFLINE-SITE-001',name:'Synthetic UAT Offline Certification Site 001',customerId:s.customerId,location:'Isolated UAT'});await canonical(client,'command_create_operator',{...id('operator'),operatorId:s.operatorId,name:'Synthetic UAT Offline Operator 001',certificationType:'Heavy Machinery',joinedDate:DATE});await canonical(client,'command_create_equipment',{...id('equipment'),equipmentId:s.equipmentId,assetNo:'UAT-OFFLINE-EQ-001',equipmentName:'Synthetic UAT Offline Equipment 001',maintenanceType:'Engine Hours',costCodeId:cost.data.id,currentReading:0,remarks:'Synthetic isolated-UAT offline certification equipment.'});await canonical(client,'command_create_assignment',{...id('assignment'),assignmentId:s.assignmentId,equipmentId:s.equipmentId,operatorId:s.operatorId,projectId:s.projectId,activityCodeId:activity.data.id,assignedDate:DATE,expectedReturn:DATE,remarks:'Synthetic offline certification assignment.'});await canonical(client,'command_create_reserved_rental',{...id('rental'),rentalId:s.rentalId,rentalNumber:'UAT-OFFLINE-20260831',customerId:s.customerId,projectId:s.projectId,dateOut:DATE,expectedReturn:DATE,rentalType:'Operated Rental',lines:[{id:s.lineId,equipmentId:s.equipmentId,assignmentId:s.assignmentId,operatorId:s.operatorId}]});await canonical(client,'command_prepare_reserved_rental_aggregate',{...id('rental'),expectedRentalVersion:1,rentalId:s.rentalId,lines:[{lineId:s.lineId,commercialTerms:{billingMethod:'Per Hour',unitRate:1000,minimumBillableHours:0,overtimeRate:0,standbyRate:0,mobilizationFee:0,demobilizationFee:0,fuelCharge:0,operatorIncluded:true,operatorRate:0,taxRate:0,withholdingTax:0,contractAmount:0,currency:'PHP'},costCodeId:cost.data.id,activityCodeId:activity.data.id,workDescriptionId:work.data.id,operationalRemarks:'Synthetic isolated-UAT offline synchronization runtime certification.',deurPolicy:{frequency:'PER_WORKDAY',effectiveFrom:DATE},shiftWindows:[],workDate:DATE,meterRequirement:'hourMeter'}]});await canonical(client,'command_release_rental',{...id('rental'),rentalId:s.rentalId,expectedVersion:2});await canonical(client,'command_activate_rental',{...id('rental'),rentalId:s.rentalId,expectedVersion:3});await service.schema('erp').rpc('complete_uat_deur_offline_runtime_scenario',{command:{companyId:tenant,scenarioKey:KEY}});return inspect(service,tenant);}catch(error){return out(409,{success:false,code:'UAT_OFFLINE_SCENARIO_FAILED',stage:error instanceof Error?error.message:'UNKNOWN'});}
}
async function inspect(service:any,tenant:string){const r=await service.schema('erp').rpc('inspect_uat_deur_offline_runtime_scenario',{command:{companyId:tenant,scenarioKey:KEY,profileVersion:PROFILE}});return out(r.error?503:200,r.error?{success:false,code:'READ_FAILED'}:r.data as Json);}
export async function inspectUatDeurOfflineDomain(request:Request,env:GroupedReviewWorkerEnvironment){if(!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY||!fixed(await request.json().catch(()=>null)))return out(400,{success:false,code:'VALIDATION_REJECTED'});const token=request.headers.get('authorization')?.match(/^Bearer (.+)$/i)?.[1];if(!token)return out(401,{success:false,code:'UNAUTHENTICATED'});const service=createClient(env.SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const i=await service.auth.getUser(token);if(i.error||!i.data.user)return out(401,{success:false,code:'UNAUTHENTICATED'});const actor=await service.schema('erp').from('users').select('company_id,status').eq('id',i.data.user.id).eq('status','active').maybeSingle();if(actor.error||!actor.data)return out(403,{success:false,code:'FORBIDDEN'});return inspect(service,String(actor.data.company_id));}
