import{createClient}from"@supabase/supabase-js";
import type{GroupedReviewWorkerEnvironment}from"./configuration";
type SafeResult={status:number;body:Record<string,unknown>};const safe=(status:number,body:Record<string,unknown>):SafeResult=>({status,body});
const scenarioKey="MULTI-EQUIPMENT-RUNTIME-CERT-2026-08-29";
export async function inspectUatMultiEquipmentProvisioning(request:Request,environment:GroupedReviewWorkerEnvironment):Promise<SafeResult>{
 if(environment.ENABLE_UAT_SYNTHETIC_PROVISIONER!=="true"||!environment.SUPABASE_URL||!environment.SUPABASE_SERVICE_ROLE_KEY)return safe(503,{success:false,code:"UAT_PROVISIONER_DISABLED"});
 const token=request.headers.get("authorization")?.match(/^Bearer (.+)$/i)?.[1];if(!token)return safe(401,{success:false,code:"UNAUTHENTICATED"});
 const service=createClient(environment.SUPABASE_URL,environment.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const identity=await service.auth.getUser(token);if(identity.error||!identity.data.user)return safe(401,{success:false,code:"UNAUTHENTICATED"});const actorId=identity.data.user.id;
 const [permission,admin,user]=await Promise.all([service.schema("erp").from("effective_user_permissions").select("permission_code").eq("user_id",actorId).eq("permission_code","settings.update").maybeSingle(),service.schema("erp").from("user_roles").select("role_id,app_roles!inner(code,active,deprecated_at)").eq("user_id",actorId).eq("app_roles.code","system-administrator").eq("app_roles.active",true).is("app_roles.deprecated_at",null).maybeSingle(),service.schema("erp").from("users").select("company_id").eq("id",actorId).eq("status","active").maybeSingle()]);
 if(permission.error||!permission.data||admin.error||!admin.data||user.error||!user.data)return safe(403,{success:false,code:"FORBIDDEN"});const companyId=user.data.company_id;
 const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body||Object.keys(body).length!==1||body.scenarioKey!==scenarioKey)return safe(400,{success:false,code:"VALIDATION_REJECTED"});const tenantMeta=await service.schema("erp").rpc("get_isolated_uat_tenant_metadata",{target_tenant:companyId});if(tenantMeta.error||!tenantMeta.data?.length)return safe(403,{success:false,code:"UAT_TENANT_REQUIRED"});
 const inspected=await service.schema("erp").rpc("inspect_isolated_uat_multi_equipment_scenario",{target_tenant:companyId,target_scenario:scenarioKey});if(inspected.error)return safe(409,{success:false,code:"INSPECTION_UNAVAILABLE"});
 const execution=await service.schema("erp").rpc("inspect_isolated_uat_execution",{command:{companyId,scenarioKey}});
 const value=inspected.data as Record<string,unknown>; const counts=(value.counts??{}) as Record<string,unknown>;
 const attempts=Array.isArray((value as any).executionAttempts)?(value as any).executionAttempts.length:0;
 const guard={advisoryLockHeld:"UNPROVEN",actorAuthorized:"YES",executionAttempts:attempts,activeExecution:execution.data?.activeExecution??"UNKNOWN_LEGACY",residueCount:counts.residue??0,residueState:(value.scenario as any)?.residueState??"UNKNOWN",rentals:counts.rentals??0,lines:counts.lines??0,deurs:counts.deurs??0,reviewArtifacts:"UNPROVEN",notificationArtifacts:"UNPROVEN",deliveryAttempts:"UNPROVEN",billingStatements:counts.billingStatements??0,invoices:"UNPROVEN",returnTransitions:counts.returns??0,referencesStillEmpty:((value.scenario as any)?.ids?.costCodeId??"")===""&&((value.scenario as any)?.ids?.activityCodeId??"")==="",overallRecoveryEligibility:"UNPROVEN"};
 return safe(200,{...value,actorPresent:true,actorApplicationUserActive:true,actorTenantMatch:true,actorSystemRoles:["system-administrator"],actorAuthorizedForLegacyRecovery:true,executionAttempts:attempts,activeExecution:execution.data?.activeExecution??"UNKNOWN_LEGACY",legacyRecoveryGuard:guard});
}
