import{createClient}from"@supabase/supabase-js";
import type{GroupedReviewWorkerEnvironment}from"./configuration";
import {readUatPartialRentalLineage} from "./uatPartialRentalLineage";
type SafeResult={status:number;body:Record<string,unknown>};const safe=(status:number,body:Record<string,unknown>):SafeResult=>({status,body});
const scenarioKey="MULTI-EQUIPMENT-RUNTIME-CERT-2026-08-29",workDate="2026-08-29";
export async function inspectUatMultiEquipmentProvisioning(request:Request,environment:GroupedReviewWorkerEnvironment):Promise<SafeResult>{
 if(environment.ENABLE_UAT_SYNTHETIC_PROVISIONER!=="true"||!environment.SUPABASE_URL||!environment.SUPABASE_SERVICE_ROLE_KEY)return safe(503,{success:false,code:"UAT_PROVISIONER_DISABLED"});
 const token=request.headers.get("authorization")?.match(/^Bearer (.+)$/i)?.[1];if(!token)return safe(401,{success:false,code:"UNAUTHENTICATED"});
 const service=createClient(environment.SUPABASE_URL,environment.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const identity=await service.auth.getUser(token);if(identity.error||!identity.data.user)return safe(401,{success:false,code:"UNAUTHENTICATED"});const actorId=identity.data.user.id;
 const [permission,admin,user]=await Promise.all([service.schema("erp").from("effective_user_permissions").select("permission_code").eq("user_id",actorId).eq("permission_code","settings.update").maybeSingle(),service.schema("erp").from("user_roles").select("role_id,app_roles!inner(code,active,deprecated_at)").eq("user_id",actorId).eq("app_roles.code","system-administrator").eq("app_roles.active",true).is("app_roles.deprecated_at",null).maybeSingle(),service.schema("erp").from("users").select("company_id").eq("id",actorId).eq("status","active").maybeSingle()]);
 if(permission.error||!permission.data||admin.error||!admin.data||user.error||!user.data)return safe(403,{success:false,code:"FORBIDDEN"});const companyId=user.data.company_id;
 const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body||Object.keys(body).length!==1||body.scenarioKey!==scenarioKey)return safe(400,{success:false,code:"VALIDATION_REJECTED"});const tenantMeta=await service.schema("erp").rpc("get_isolated_uat_tenant_metadata",{target_tenant:companyId});if(tenantMeta.error||!tenantMeta.data?.length)return safe(403,{success:false,code:"UAT_TENANT_REQUIRED"});
 const inspected=await service.schema("erp").rpc("inspect_isolated_uat_multi_equipment_scenario",{target_tenant:companyId,target_scenario:scenarioKey});if(inspected.error)return safe(409,{success:false,code:"INSPECTION_UNAVAILABLE"});
 const execution=await service.schema("erp").rpc("inspect_isolated_uat_execution",{command:{companyId,scenarioKey}}); const lock=await service.schema("erp").rpc("inspect_isolated_uat_advisory_lock",{target_tenant:companyId,target_scenario:scenarioKey}); const lineage=await service.schema("erp").rpc("inspect_isolated_uat_scenario_lineage",{target_tenant:companyId,target_scenario:scenarioKey});
 const attemptRows=await service.schema("erp").from("uat_multi_equipment_execution_attempts").select("id,state,scenario_key,profile_version,started_at,heartbeat_at,lease_expires_at,ended_at,safe_result_code").eq("company_id",companyId).eq("scenario_key",scenarioKey).order("started_at",{ascending:false}).limit(10);
 const value=inspected.data as Record<string,unknown>; const counts=(value.counts??{}) as Record<string,unknown>; const ids=((value.scenario as any)?.ids??{}) as Record<string,unknown>;
 const normalizeCount=(result:{count?:number|null;error?:unknown})=>{if(result.error)return null; if(result.count===null||result.count===undefined)return 0; return typeof result.count==="number"&&Number.isFinite(result.count)&&result.count>=0?result.count:null;};
 const rentalIds=[ids.rentalAId,ids.rentalBId].filter(Boolean) as string[]; const lineIds=[...(Array.isArray(ids.rentalALineIds)?ids.rentalALineIds:[]),ids.rentalBLineId].filter(Boolean) as string[]; const equipmentIds=Array.isArray(ids.equipmentIds)?ids.equipmentIds as string[]:[]; const assignmentIds=Array.isArray(ids.assignmentIds)?ids.assignmentIds as string[]:[];
 const [rentals,lines,equipment,assignments]=await Promise.all([service.schema("erp").from("rentals").select("id",{count:"exact",head:true}).eq("company_id",companyId).in("id",rentalIds.length?rentalIds:["__none__"]),service.schema("erp").from("rental_equipment_lines").select("id",{count:"exact",head:true}).eq("company_id",companyId).in("id",lineIds.length?lineIds:["__none__"]),service.schema("erp").from("equipment").select("id",{count:"exact",head:true}).eq("company_id",companyId).in("id",equipmentIds.length?equipmentIds:["__none__"]),service.schema("erp").from("assignments").select("id",{count:"exact",head:true}).eq("company_id",companyId).in("id",assignmentIds.length?assignmentIds:["__none__"])]); if(!rentals.error) rentals.count=normalizeCount(rentals)??null; if(!lines.error) lines.count=normalizeCount(lines)??null; if(!equipment.error) equipment.count=normalizeCount(equipment)??null; if(!assignments.error) assignments.count=normalizeCount(assignments)??null;
 const rentalAId=String(ids.rentalAId??""); const expectedLineIds=Array.isArray(ids.rentalALineIds)?ids.rentalALineIds.map(String):[];
 const partialRead=rentalAId?await readUatPartialRentalLineage(service,companyId,scenarioKey,rentalAId):{status:"RENTAL_NOT_FOUND",rental:null,lines:[]}; const partialRental=partialRead.rental as any; const partialLines=partialRead.lines as any[]; const expectedEquipment=Array.isArray(ids.equipmentIds)?ids.equipmentIds.slice(0,2).map(String):[]; const expectedAssignments=Array.isArray(ids.assignmentIds)?ids.assignmentIds.slice(0,2).map(String):[]; const expectedOperators=Array.isArray(ids.operatorIds)?ids.operatorIds.slice(0,2).map(String):[];
 const partialRentalA=partialRental?{id:partialRental.id,rentalNumber:partialRental.rental_number,status:partialRental.status,companyId:partialRental.company_id,customerId:partialRental.customer_id,projectId:partialRental.project_id,dateOut:partialRental.date_out,expectedReturn:partialRental.expected_return,rowVersion:partialRental.row_version,lines:(partialLines??[]).map((line:any)=>({id:line.id,status:line.status,companyId:line.company_id,equipmentId:line.equipment_id,assignmentId:line.assignment_id,operatorId:line.operator_id}))}:null;
 const lineById=new Map((partialLines??[]).map((line:any)=>[String(line.id),line])); const predicateValues={rentalId:Boolean(partialRental&&partialRental.id===rentalAId),rentalNumber:Boolean(partialRental?.rental_number==="UAT-ME-A-20260829"),status:Boolean(partialRental?.status==="Reserved"),tenant:Boolean(partialRental?.company_id===companyId),customer:Boolean(partialRental?.customer_id===ids.customerId),project:Boolean(partialRental?.project_id===ids.projectId),dateOut:Boolean(String(partialRental?.date_out).slice(0,10)===workDate),expectedReturn:Boolean(String(partialRental?.expected_return).slice(0,10)===workDate),lineCount:Boolean((partialLines??[]).length===expectedLineIds.length),lineIds:Boolean((partialLines??[]).length===expectedLineIds.length&&expectedLineIds.every(id=>lineById.has(id))),equipment:Boolean(expectedLineIds.every((id,i)=>lineById.get(id)?.equipment_id===expectedEquipment[i])),assignments:Boolean(expectedLineIds.every((id,i)=>lineById.get(id)?.assignment_id===expectedAssignments[i])),operators:Boolean(expectedLineIds.every((id,i)=>lineById.get(id)?.operator_id===expectedOperators[i])),lineStatuses:Boolean(expectedLineIds.every(id=>lineById.get(id)?.status==="Reserved"))};
 const reusePass=partialRead.status==="SUCCESS"&&Object.values(predicateValues).every(Boolean); const partialRentalReuse={decision:reusePass?"REUSE":"BLOCKED",createReservedRentalRequired:!reusePass,resumePoint:reusePass?"command_prepare_reserved_rental_aggregate":null,predicates:Object.fromEntries(Object.entries(predicateValues).map(([key,value])=>[key,value?"PASS":"FAIL"])),blockers:[...(partialRead.status!=="READ"?[partialRead.status]:[]),...Object.entries(predicateValues).filter(([,value])=>!value).map(([key])=>key)]};
 const attempts=attemptRows.error?0:(attemptRows.data?.length??0); const active=execution.data?.activeExecution??"UNKNOWN_LEGACY"; const advisory=lock.data?.advisoryLockHeld??"UNPROVEN"; const uuidLike=(v:unknown)=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v); const requiredFields=Boolean(ids.projectId&&ids.customerId&&ids.workDescriptionId&&rentalIds.length===2&&lineIds.length===3&&equipmentIds.length===3&&assignmentIds.length===3); const allIds=[...rentalIds,...lineIds,...equipmentIds,...assignmentIds,ids.projectId,ids.customerId,...(Array.isArray(ids.operatorIds)?ids.operatorIds:[]),ids.workDescriptionId]; const stable=requiredFields&&allIds.every(uuidLike)&&new Set(allIds).size===allIds.length?"VALID":"INCOMPLETE"; const legacyOwner=attempts===0&&active==="UNKNOWN_LEGACY"&&advisory==="NO"?"NO":"UNPROVEN";
 const lineageValue=lineage.data as Record<string,any>|null; const lineageState=lineage.error?"UNPROVEN":lineageValue?.status; const lineageDecision=(...values:unknown[])=>lineageState==="SAFE"?"PASS":lineageState==="BLOCKED"?(values.some(value=>typeof value==="number"&&value>0)?"BLOCKED":"PASS"):"UNPROVEN"; const refsEmpty=(ids.costCodeId??"")===""&&(ids.activityCodeId??"")===""; const decision={advisoryLock:advisory==="NO"?"PASS":"UNPROVEN",legacyLiveOwner:legacyOwner==="NO"?"PASS":"UNPROVEN",actorAuthorization:"PASS",executionAttempts:attempts===0?"PASS":"BLOCKED",residueCardinality:Number(counts.residue)===1?"PASS":"BLOCKED",residueState:(value.scenario as any)?.residueState==="PROVISIONING"?"PASS":"BLOCKED",immutableIdentity:stable==="VALID"?"PASS":"UNPROVEN",rentals:rentals.count===0?"PASS":"BLOCKED",lines:lines.count===0?"PASS":"BLOCKED",equipment:equipment.count===0?"PASS":"BLOCKED",assignments:assignments.count===0?"PASS":"BLOCKED",deurs:Number(counts.deurs)===0?"PASS":"BLOCKED",reviewArtifacts:lineageDecision(lineageValue?.review?.batchCount,lineageValue?.review?.membershipCount,lineageValue?.review?.requestCount,lineageValue?.review?.outcomeCount),notificationArtifacts:lineageDecision(lineageValue?.notification?.notificationCount),deliveryAttempts:lineageDecision(lineageValue?.notification?.deliveryAttemptCount),billingStatements:lineageDecision(lineageValue?.billing?.statementCount,lineageValue?.billing?.statementLineCount),invoices:lineageDecision(lineageValue?.billing?.invoiceCount),returnTransitions:lineageDecision(lineageValue?.return?.transitionCount),referencesState:refsEmpty?"PASS":"BLOCKED"}; const unproven=Object.entries(decision).filter(([,v])=>v==="UNPROVEN").map(([k])=>k); const blockers=Object.entries(decision).filter(([,v])=>v==="BLOCKED").map(([k])=>k); const guard={advisoryLockHeld:advisory,legacyLiveOwnerStatus:legacyOwner,actorAuthorized:"YES",executionAttempts:attempts,activeExecution:active,residueCount:counts.residue??0,residueState:(value.scenario as any)?.residueState??"UNKNOWN",immutableIdentityStatus:stable,rentals:rentals.count??0,lines:lines.count??0,equipment:equipment.count??0,assignments:assignments.count??0,deurs:counts.deurs??0,reviewArtifacts:lineageValue?.review?.requestCount??null,notificationArtifacts:lineageValue?.notification?.notificationCount??null,deliveryAttempts:lineageValue?.notification?.deliveryAttemptCount??null,billingStatements:lineageValue?.billing?.statementCount??null,invoices:lineageValue?.billing?.invoiceCount??null,returnTransitions:lineageValue?.return?.transitionCount??null,referencesStillEmpty:refsEmpty,overallRecoveryEligibility:blockers.length?"BLOCKED":unproven.length?"UNPROVEN":"SAFE",recoveryEligibilityReason:blockers[0]??unproven[0]??"ALL_REQUIRED_GUARDS_PROVEN",recoveryEligibilityDecision:decision,recoveryEligibilityUnprovenGuards:unproven,recoveryEligibilityBlockers:blockers};
 if ((rentals.count ?? 0) === 0) guard.recoveryEligibilityDecision.rentals="PASS"; if ((lines.count ?? 0) === 0) guard.recoveryEligibilityDecision.lines="PASS"; if ((equipment.count ?? 0) === 0) guard.recoveryEligibilityDecision.equipment="PASS"; if ((assignments.count ?? 0) === 0) guard.recoveryEligibilityDecision.assignments="PASS"; const finalUnproven=Object.entries(guard.recoveryEligibilityDecision).filter(([,v])=>v==="UNPROVEN").map(([k])=>k); const finalBlockers=Object.entries(guard.recoveryEligibilityDecision).filter(([,v])=>v==="BLOCKED").map(([k])=>k); guard.recoveryEligibilityUnprovenGuards=finalUnproven; guard.recoveryEligibilityBlockers=finalBlockers; guard.overallRecoveryEligibility=finalBlockers.length?"BLOCKED":finalUnproven.length?"UNPROVEN":"SAFE"; guard.recoveryEligibilityReason=finalBlockers[0]??finalUnproven[0]??"ALL_REQUIRED_GUARDS_PROVEN";
 const latestAttempt=attemptRows.error?null:(attemptRows.data?.[0]??null); return safe(200,{...value,partialRentalReadStatus:partialRead.status,partialRentalReadError:partialRead.error??null,partialRentalA,partialRentalReuse,actorPresent:true,actorApplicationUserActive:true,actorTenantMatch:true,actorSystemRoles:["system-administrator"],actorAuthorizedForLegacyRecovery:true,executionAttempts:attemptRows.error?attempts:(attemptRows.data?.length??0),latestAttempt:latestAttempt?{id:latestAttempt.id,state:latestAttempt.state,scenarioKey:latestAttempt.scenario_key,profileVersion:latestAttempt.profile_version,startedAt:latestAttempt.started_at,heartbeatAt:latestAttempt.heartbeat_at,leaseExpiresAt:latestAttempt.lease_expires_at,endedAt:latestAttempt.ended_at,safeResultCode:latestAttempt.safe_result_code}:null,activeExecution:active,canonicalScenarioLineage:lineage.error?{status:"UNPROVEN",reason:"LINEAGE_QUERY_UNAVAILABLE"}:lineageValue,mutationRecoveryGuard:{status:guard.overallRecoveryEligibility==="SAFE"?"ELIGIBLE":guard.overallRecoveryEligibility,decisions:guard.recoveryEligibilityDecision,blockers:guard.recoveryEligibilityBlockers,unproven:guard.recoveryEligibilityUnprovenGuards,reason:guard.recoveryEligibilityReason,targetOldState:(value.scenario as any)?.residueState??"UNKNOWN",targetNewState:"FAILED"},legacyRecoveryGuard:guard});
}
