import { createClient } from "@supabase/supabase-js";
import type { GroupedReviewWorkerEnvironment } from "./configuration";
type Row=Record<string,any>; type Safe={status:number;body:Row};
const username="uat.me.operator.001", expectedOperatorId="e6bf4e8b-8e3a-4c65-a05e-ee4ed281e876";
const out=(status:number,body:Row):Safe=>({status,body:{inspectionImplementationVersion:"uat-user1-linkage-rpc-v2",...body}});
export async function inspectUatUserLinkage(request:Request,env:GroupedReviewWorkerEnvironment):Promise<Safe>{
 if(env.ENABLE_UAT_SYNTHETIC_PROVISIONER!=="true"||!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)return out(503,{success:false,code:"UAT_PROVISIONER_DISABLED"});
 const token=request.headers.get("authorization")?.match(/^Bearer (.+)$/i)?.[1]; if(!token)return out(401,{success:false,code:"UNAUTHENTICATED"});
 const service=createClient(env.SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}); const identity=await service.auth.getUser(token); if(identity.error||!identity.data.user)return out(401,{success:false,code:"UNAUTHENTICATED"}); const actor=identity.data.user.id;
 const [permission,admin,app]=await Promise.all([service.schema("erp").from("effective_user_permissions").select("permission_code").eq("user_id",actor).eq("permission_code","settings.update").maybeSingle(),service.schema("erp").from("user_roles").select("role_id,app_roles!inner(code,active,deprecated_at)").eq("user_id",actor).eq("app_roles.code","system-administrator").eq("app_roles.active",true).is("app_roles.deprecated_at",null).maybeSingle(),service.schema("erp").from("users").select("company_id,status").eq("id",actor).maybeSingle()]);
 if(permission.error||!permission.data||admin.error||!admin.data||app.error||!app.data||app.data.status!=="active")return out(403,{success:false,code:"FORBIDDEN"}); const companyId=String(app.data.company_id);
 const body=await request.json().catch(()=>null) as Row|null; if(!body||Object.keys(body).length!==2||body.username!==username||body.expectedOperatorId!==expectedOperatorId)return out(400,{success:false,code:"VALIDATION_REJECTED"});
 const linkage=await service.schema("erp").rpc("inspect_isolated_uat_multi_operator_user_linkage",{command:{companyId,scenarioKey:"MULTI-EQUIPMENT-RUNTIME-CERT-2026-08-29",profileVersion:"UAT_MULTI_EQUIPMENT_PER_WORKDAY_V1",operatorIds:[expectedOperatorId,"cac542f6-2d18-4275-8c26-0728d858c912","584df24a-c104-4001-b175-c141903f12d5"]}});
 if(linkage.error)return out(503,{success:false,code:"READ_FAILED",phase:"USER1_READ",operation:"inspect_isolated_uat_multi_operator_user_linkage",safeResultCode:"UPSTREAM_UNAVAILABLE"});
 const row=((linkage.data as Row)?.operators??[]).find((r:Row)=>r.operatorId===expectedOperatorId); const count=Number(row?.linkedApplicationUserCount??0);
 if(count!==1)return out(200,{success:true,username,usernameCardinality:count,classification:count===0?"USER1_NOT_LINKED":"USER1_DUPLICATE_OPERATOR_LINK",authIdentityPresent:false});
 if(row.username!==username)return out(200,{success:true,username,usernameCardinality:1,applicationUserId:row.applicationUserId,classification:"USER1_WRONG_LINKED_USER",authIdentityPresent:false});
 const roles=await service.schema("erp").from("user_roles").select("app_roles(code)").eq("user_id",row.applicationUserId); const roleNames=(roles.data??[]).map((x:Row)=>x.app_roles?.code).filter(Boolean) as string[]; const auth=await service.auth.admin.getUserById(String(row.applicationUserId)); const authPresent=!auth.error&&!!auth.data.user; const classification=String(row.status).toLowerCase()!=="active"?"USER1_INACTIVE":row.companyId!==companyId?"USER1_TENANT_MISMATCH":!roleNames.includes("operator")?"USER1_ROLE_MISSING":!authPresent?"USER1_AUTH_IDENTITY_MISSING":"USER1_PERSISTED_LINK_GREEN";
 const user={id:row.applicationUserId,username:row.username,display_name:row.displayName,status:row.status,operator_id:row.operatorId,company_id:row.companyId};
 return out(200,{success:true,username,usernameCardinality:1,applicationUserId:user.id,displayName:user.display_name,status:user.status,companyId:user.company_id,operatorId:user.operator_id,roleNames,authIdentityPresent:authPresent,authIdentityActive:authPresent?auth.data.user?.aud==="authenticated":false,classification});
}
