BEGIN;
SET search_path TO erp, public;

CREATE OR REPLACE FUNCTION erp.command_reserve_rental(command jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE tenant text=erp.current_company_id();actor text=auth.uid()::text;target erp.rentals;line_row erp.rental_equipment_lines;contract_row erp.rental_contracts;prep jsonb;metadata jsonb;snapshot jsonb;idem jsonb;payload_hash text;response jsonb;expected bigint;now_at timestamptz=clock_timestamp();
BEGIN
 IF tenant IS NULL OR NOT erp.current_user_has_permission('rental.update') THEN RETURN jsonb_build_object('success',false,'code','FORBIDDEN');END IF;SELECT * INTO target FROM erp.rentals WHERE id=command->>'rentalId' AND company_id=tenant FOR UPDATE;IF target.id IS NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF;
 idem=erp.begin_operational_command(command,'RESERVE_RENTAL','RENTAL',target.id,tenant,actor);IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH');ELSIF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED');END IF;payload_hash=idem->>'payloadHash';
 BEGIN expected=(command->>'expectedVersion')::bigint;EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END;IF expected<>target.row_version THEN RETURN jsonb_build_object('success',false,'code','CONFLICT','currentVersion',target.row_version);END IF;IF target.status<>'Draft' OR target.approval_status<>'Approved' THEN RETURN jsonb_build_object('success',false,'code','INVALID_TRANSITION');END IF;
 PERFORM a.id FROM erp.assignments a JOIN erp.rental_equipment_lines l ON l.assignment_id=a.id WHERE l.rental_id=target.id ORDER BY a.id FOR UPDATE;PERFORM e.id FROM erp.equipment e JOIN erp.rental_equipment_lines l ON l.equipment_id=e.id WHERE l.rental_id=target.id ORDER BY e.id FOR UPDATE;
 IF EXISTS(SELECT 1 FROM erp.rental_equipment_lines l LEFT JOIN erp.assignments a ON a.id=l.assignment_id AND a.company_id=tenant LEFT JOIN erp.equipment e ON e.id=l.equipment_id AND e.company_id=tenant LEFT JOIN erp.operators o ON o.id=l.operator_id AND o.company_id=tenant WHERE l.rental_id=target.id AND (a.id IS NULL OR a.status<>'Active' OR a.equipment_id<>l.equipment_id OR a.operator_id<>l.operator_id OR a.project_id<>target.project_id OR e.id IS NULL OR NOT e.active OR o.id IS NULL OR o.status<>'Active' OR NOT l.operational_metadata?'draftPreparation' OR NOT EXISTS(SELECT 1 FROM erp.rental_contracts c WHERE c.rental_equipment_line_id=l.id AND c.status='Draft'))) THEN RETURN jsonb_build_object('success',false,'code','MISSING_RELATIONSHIP');END IF;
 FOR line_row IN SELECT * FROM erp.rental_equipment_lines WHERE rental_id=target.id ORDER BY id LOOP SELECT * INTO contract_row FROM erp.rental_contracts WHERE rental_equipment_line_id=line_row.id AND status='Draft';prep=line_row.operational_metadata->'draftPreparation';
  INSERT INTO erp.commercial_snapshots(id,rental_id,rental_equipment_line_id,source_contract_id,billing_method,unit_rate,minimum_billable_hours,overtime_rate,standby_rate,mobilization_fee,demobilization_fee,fuel_charge,operator_included,operator_rate,tax_rate,withholding_tax,contract_amount,currency,captured_at,created_by,snapshot_hash) VALUES(gen_random_uuid()::text,target.id,line_row.id,contract_row.id,contract_row.billing_method,contract_row.unit_rate,contract_row.minimum_billable_hours,contract_row.overtime_rate,contract_row.standby_rate,contract_row.mobilization_fee,contract_row.demobilization_fee,contract_row.fuel_charge,contract_row.operator_included,contract_row.operator_rate,contract_row.tax_rate,contract_row.withholding_tax,contract_row.contract_amount,contract_row.currency,now_at,actor,encode(digest(to_jsonb(contract_row)::text,'sha256'),'hex'));
  metadata=jsonb_build_object('costCode',(SELECT jsonb_build_object('id',c.id,'code',c.code,'name',c.name) FROM erp.cost_codes c WHERE c.id=prep->>'costCodeId'),'activityCode',(SELECT jsonb_build_object('id',a.id,'code',a.code,'name',a.name) FROM erp.activity_codes a WHERE a.id=prep->>'activityCodeId'),'workDescription',(SELECT jsonb_build_object('id',w.id,'code',w.code,'name',w.name,'requiresRemarks',w.requires_remarks) FROM erp.work_descriptions w WHERE w.id=prep->>'workDescriptionId'))||CASE WHEN nullif(btrim(prep->>'operationalRemarks'),'') IS NULL THEN '{}'::jsonb ELSE jsonb_build_object('operationalRemarks',prep->>'operationalRemarks') END;
  snapshot=jsonb_build_object('rentalEquipmentLineId',line_row.id,'rentalId',target.id,'equipmentId',line_row.equipment_id,'assignmentId',line_row.assignment_id,'operatorId',line_row.operator_id,'projectId',target.project_id,'customerId',target.customer_id,'policy',prep->'deurPolicy','shiftWindows',coalesce(prep->'shiftWindows','[]'::jsonb),'workDescription',metadata->'workDescription','operationalRemarks',metadata->>'operationalRemarks','workDateRule','RENTAL_DATE_OUT','workDate',coalesce(prep->>'workDate',target.date_out::text),'meterRequirement',coalesce(prep->>'meterRequirement','none'),'billingMethod',contract_row.billing_method::text,'fuelEvidenceRequired',coalesce(contract_row.fuel_charge,0)>0,'operationalMetadata',metadata-'workDescription'-'operationalRemarks','sourceFingerprint','PENDING','capturedAt',now_at);
  UPDATE erp.rental_equipment_lines SET status='Reserved',commercial_snapshot_required=true,operational_metadata=metadata||jsonb_build_object('deurExpectationSnapshot',snapshot),updated_by=actor WHERE id=line_row.id;
  UPDATE erp.rental_contracts SET status='Active',updated_by=actor WHERE id=contract_row.id;
 END LOOP;
 UPDATE erp.rentals SET status='Reserved',reserved_at=now_at,commercial_snapshot_required=true,deur_expectation_policy_required=true,deur_expectation_frequency=(SELECT operational_metadata#>>'{deurExpectationSnapshot,policy,frequency}' FROM erp.rental_equipment_lines WHERE rental_id=target.id ORDER BY id LIMIT 1),deur_expectation_effective_from=coalesce((SELECT nullif(operational_metadata#>>'{deurExpectationSnapshot,policy,effectiveFrom}','')::date FROM erp.rental_equipment_lines WHERE rental_id=target.id ORDER BY id LIMIT 1),target.date_out),expected_shift_codes=(SELECT ARRAY(SELECT value->>'code' FROM jsonb_array_elements(coalesce(l.operational_metadata#>'{deurExpectationSnapshot,shiftWindows}','[]'::jsonb)) ORDER BY value->>'code') FROM erp.rental_equipment_lines l WHERE l.rental_id=target.id ORDER BY l.id LIMIT 1),timezone=(SELECT l.operational_metadata#>>'{deurExpectationSnapshot,shiftWindows,0,timezone}' FROM erp.rental_equipment_lines l WHERE l.rental_id=target.id ORDER BY l.id LIMIT 1),deur_expectation_captured_at=now_at,deur_expectation_frozen_at=now_at,updated_by=actor WHERE id=target.id RETURNING * INTO target;
 UPDATE erp.rental_equipment_lines SET operational_metadata=jsonb_set(operational_metadata,'{deurExpectationSnapshot,sourceFingerprint}',to_jsonb(erp.current_deur_expectation_fingerprint(id)),true) WHERE rental_id=target.id AND deleted_at IS NULL;
 INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(gen_random_uuid()::text,tenant,'Rental',target.id,'RENTAL_RESERVED',actor,now_at,command->>'commandId',jsonb_build_object('status','Reserved','version',target.row_version));response=jsonb_build_object('success',true,'disposition','ACCEPTED','value',jsonb_build_object('rentalId',target.id,'rentalNumber',target.rental_number,'status','Reserved','approvalStatus',target.approval_status,'version',target.row_version));RETURN erp.finish_operational_command(command,'RESERVE_RENTAL','RENTAL',target.id,tenant,actor,payload_hash,response,target.row_version);
EXCEPTION WHEN unique_violation THEN RETURN jsonb_build_object('success',false,'code','EQUIPMENT_UNAVAILABLE');WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');END $$;

COMMIT;
