BEGIN;
SET LOCAL search_path=erp,auth,extensions,pg_catalog;
CREATE OR REPLACE FUNCTION erp.inspect_uat_limited_pilot_scenarios(command jsonb)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE tenant text:=trim(command->>'companyId'); k text:=trim(command->>'scenarioKey'); p text:=trim(command->>'profileVersion'); s erp.uat_limited_operational_pilot_scenarios; rows jsonb; total integer; submitted integer; equipment_count integer; operator_count integer; duplicates integer;
BEGIN
 IF tenant<>'TENANT-LOCAL-001' OR k<>'LIMITED-OPERATIONAL-PILOT-2026-09' OR p<>'UAT_LIMITED_PILOT_V1' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
 SELECT * INTO s FROM erp.uat_limited_operational_pilot_scenarios x WHERE x.company_id=tenant AND x.scenario_key=k; IF s.scenario_key IS NULL THEN RETURN jsonb_build_object('success',false,'code','SCENARIO_NOT_FOUND'); END IF;
 SELECT count(*) INTO total FROM erp.deurs d WHERE d.company_id=tenant AND d.rental_equipment_line_id IN(s.scenario->>'line1Id',s.scenario->>'line2Id',s.scenario->>'line3Id');
 SELECT count(*) INTO submitted FROM erp.deurs d WHERE d.company_id=tenant AND d.rental_equipment_line_id IN(s.scenario->>'line1Id',s.scenario->>'line2Id',s.scenario->>'line3Id') AND d.status='Submitted';
 SELECT count(DISTINCT d.equipment_id),count(DISTINCT d.operator_id) INTO equipment_count,operator_count FROM erp.deurs d WHERE d.company_id=tenant AND d.rental_equipment_line_id IN(s.scenario->>'line1Id',s.scenario->>'line2Id',s.scenario->>'line3Id');
 SELECT greatest(count(*)-count(DISTINCT d.rental_equipment_line_id),0) INTO duplicates FROM erp.deurs d WHERE d.company_id=tenant AND d.rental_equipment_line_id IN(s.scenario->>'line1Id',s.scenario->>'line2Id',s.scenario->>'line3Id');
 SELECT coalesce(jsonb_agg(jsonb_build_object('deurId',d.id,'deurNumber',d.deur_number,'workDate',d.work_date,'status',d.status,'version',d.row_version,'rentalId',d.rental_id,'rentalEquipmentLineId',d.rental_equipment_line_id,'equipmentId',d.equipment_id,'assignmentId',d.assignment_id,'operatorId',d.operator_id,'currentActivity',(SELECT e.activity_type FROM erp.deur_events e WHERE e.deur_id=d.id AND e.activity_type<>'shift' AND e.action='start' AND NOT EXISTS(SELECT 1 FROM erp.deur_events x WHERE x.deur_id=e.deur_id AND x.activity_type=e.activity_type AND x.action='end' AND x.sequence>e.sequence) ORDER BY e.sequence DESC LIMIT 1),'operationalTimelineCount',(SELECT count(*) FROM erp.deur_events e WHERE e.deur_id=d.id AND e.activity_type<>'shift'),'activityOverlapCount',greatest((SELECT count(*) FROM erp.deur_events e WHERE e.deur_id=d.id AND e.activity_type<>'shift' AND e.action='start' AND NOT EXISTS(SELECT 1 FROM erp.deur_events x WHERE x.deur_id=e.deur_id AND x.activity_type=e.activity_type AND x.action='end' AND x.sequence>e.sequence))-1,0),'endShiftCount',(SELECT count(*) FROM erp.deur_events e WHERE e.deur_id=d.id AND e.activity_type='shift' AND e.action='end'),'submit',jsonb_build_object('submitSuccessCount',CASE WHEN (SELECT count(*) FROM erp.audit_log a WHERE a.company_id=tenant AND a.aggregate_type='DEUR' AND a.aggregate_id=d.id AND a.action='SUBMIT_DEUR')>0 THEN 1 ELSE 0 END,'duplicateSubmitMutationCount',greatest((SELECT count(*) FROM erp.audit_log a WHERE a.company_id=tenant AND a.aggregate_type='DEUR' AND a.aggregate_id=d.id AND a.action='SUBMIT_DEUR')-1,0)),'postSubmitReadable',d.status='Submitted','duplicateDailyDeurCount',0) ORDER BY d.deur_number),'[]'::jsonb) INTO rows FROM erp.deurs d WHERE d.company_id=tenant AND d.rental_equipment_line_id IN(s.scenario->>'line1Id',s.scenario->>'line2Id',s.scenario->>'line3Id');
 RETURN jsonb_build_object('success',true,'state',s.state,'scenarioKey',k,'profileVersion',p,'deurs',rows,'scenarioDeurCount',total,'submittedDeurCount',submitted,'coveredEquipmentCount',equipment_count,'coveredOperatorCount',operator_count,'duplicateDailyDeurCount',duplicates,'crossOperatorExposure','[]'::jsonb,'externalEmailBlocked',true,'notificationCount',0,'billingInvoiceMutationBlocked',true,'billingStatementCount',0,'invoiceCount',0,'returnMutationBlocked',true,'returnMutationPresent',false);
END $$;
ALTER FUNCTION erp.inspect_uat_limited_pilot_scenarios(jsonb) OWNER TO postgres;
REVOKE ALL ON FUNCTION erp.inspect_uat_limited_pilot_scenarios(jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION erp.inspect_uat_limited_pilot_scenarios(jsonb) TO service_role;
COMMIT;
