BEGIN;
SET LOCAL search_path=erp,auth,extensions,pg_catalog;
-- Permit the existing narrow Activity Code amendment under the established assignment.manage permission.
-- Preserve all existing validation and reject edits when any linked Rental has been approved.
CREATE OR REPLACE FUNCTION erp.command_amend_assignment_activity_code(command jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE
  tenant text=erp.current_company_id(); actor text=auth.uid()::text; now_at timestamptz=clock_timestamp();
  target erp.assignments%ROWTYPE; activity erp.activity_codes%ROWTYPE; idem jsonb; payload_hash text; response jsonb; prior text;
BEGIN
  IF auth.uid() IS NULL OR tenant IS NULL OR NOT EXISTS(SELECT 1 FROM erp.users u JOIN erp.companies c ON c.id=u.company_id WHERE u.id=auth.uid() AND u.status='active' AND u.company_id=tenant AND c.active) THEN RETURN jsonb_build_object('success',false,'code','UNAUTHENTICATED'); END IF;
  IF NOT erp.current_user_has_permission('assignment.manage') THEN RETURN jsonb_build_object('success',false,'code','FORBIDDEN'); END IF;
  IF command ?| ARRAY['companyId','company_id','tenantId','tenant_id','actor','actorId','userId','equipmentId','operatorId','projectId','status','assignedDate','expectedReturn']
    OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL
    OR nullif(btrim(command->>'assignmentId'),'') IS NULL OR nullif(btrim(command->>'activityCodeId'),'') IS NULL
    OR command->>'assignmentId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    OR command->>'expectedVersion' !~ '^[0-9]+$' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
  SELECT * INTO target FROM erp.assignments WHERE id=command->>'assignmentId' AND company_id=tenant AND deleted_at IS NULL FOR UPDATE;
  IF target.id IS NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND'); END IF;
  IF EXISTS(SELECT 1 FROM erp.rentals r WHERE r.company_id=tenant AND r.assignment_id=target.id AND r.approval_status='Approved') OR EXISTS(SELECT 1 FROM erp.rental_equipment_lines l JOIN erp.rentals r ON r.id=l.rental_id WHERE l.company_id=tenant AND l.assignment_id=target.id AND r.approval_status='Approved') THEN RETURN jsonb_build_object('success',false,'code','APPROVED_LOCKED'); END IF;
  idem=erp.begin_operational_command(command,'AMEND_ASSIGNMENT_ACTIVITY_CODE','ASSIGNMENT',target.id,tenant,actor);
  IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); ELSIF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); ELSIF idem->>'state'<>'NEW' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
  payload_hash=idem->>'payloadHash';
  IF target.row_version<>(command->>'expectedVersion')::bigint THEN RETURN jsonb_build_object('success',false,'code','CONFLICT','currentVersion',target.row_version); END IF;
  IF target.status<>'Active' OR target.activity_code_id IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code','INVALID_TRANSITION'); END IF;
  SELECT * INTO activity FROM erp.activity_codes WHERE id=command->>'activityCodeId' AND active AND deleted_at IS NULL;
  IF activity.id IS NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND'); END IF;
  IF EXISTS(SELECT 1 FROM erp.deurs d WHERE d.company_id=tenant AND d.assignment_id=target.id)
    OR EXISTS(SELECT 1 FROM erp.rentals r WHERE r.company_id=tenant AND r.assignment_id=target.id AND r.status<>'Draft')
    OR EXISTS(SELECT 1 FROM erp.rental_equipment_lines l JOIN erp.rentals r ON r.id=l.rental_id WHERE l.company_id=tenant AND l.assignment_id=target.id AND r.status<>'Draft') THEN RETURN jsonb_build_object('success',false,'code','DEPENDENCY_CONFLICT'); END IF;
  prior=target.activity_code_id;
  UPDATE erp.assignments SET activity_code_id=activity.id,updated_by=actor WHERE id=target.id AND company_id=tenant RETURNING * INTO target;
  INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,previous_values,new_values)
  VALUES(gen_random_uuid()::text,tenant,'Assignment',target.id,'ASSIGNMENT_ACTIVITY_CODE_AMENDED',actor,now_at,command->>'commandId',jsonb_build_object('activityCodeId',prior),jsonb_build_object('activityCodeId',target.activity_code_id,'idempotencyKey',command->>'idempotencyKey','reason',nullif(btrim(command->>'reason'),'')));
  response=jsonb_build_object('success',true,'disposition','ACCEPTED','serverOccurredAt',now_at,'refresh',jsonb_build_array(target.id),'value',jsonb_build_object('id',target.id,'activityCodeId',target.activity_code_id,'rowVersion',target.row_version));
  RETURN erp.finish_operational_command(command,'AMEND_ASSIGNMENT_ACTIVITY_CODE','ASSIGNMENT',target.id,tenant,actor,payload_hash,response,target.row_version);
END $$;
ALTER FUNCTION erp.command_amend_assignment_activity_code(jsonb) OWNER TO postgres;
REVOKE ALL ON FUNCTION erp.command_amend_assignment_activity_code(jsonb) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION erp.command_amend_assignment_activity_code(jsonb) TO authenticated;

-- Keep pre-approval preparation revisions open while enforcing the Approved-state lock server-side.
CREATE OR REPLACE FUNCTION erp.command_update_draft_rental_terms(command jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE tenant text=erp.current_company_id();actor text=auth.uid()::text;target erp.rentals;line_row erp.rental_equipment_lines;item jsonb;terms jsonb;idem jsonb;payload_hash text;response jsonb;expected bigint;now_at timestamptz=clock_timestamp();
BEGIN
 IF tenant IS NULL OR NOT erp.current_user_has_permission('rental.commercialTerms.update') THEN RETURN jsonb_build_object('success',false,'code','FORBIDDEN');END IF;
 IF command ?| ARRAY['companyId','actorId','status'] OR jsonb_typeof(command->'lines') IS DISTINCT FROM 'array' OR jsonb_array_length(command->'lines')=0 THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
 SELECT * INTO target FROM erp.rentals WHERE id=command->>'rentalId' AND company_id=tenant FOR UPDATE;
 IF target.id IS NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF;
 IF target.approval_status='Approved' THEN RETURN jsonb_build_object('success',false,'code','APPROVED_LOCKED');END IF;
 idem=erp.begin_operational_command(command,'UPDATE_DRAFT_RENTAL_TERMS','RENTAL',target.id,tenant,actor);IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH');ELSIF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED');END IF;payload_hash=idem->>'payloadHash';
 BEGIN expected=(command->>'expectedVersion')::bigint;EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END;
 IF target.status<>'Draft' THEN RETURN jsonb_build_object('success',false,'code','INVALID_TRANSITION');ELSIF expected<>target.row_version THEN RETURN jsonb_build_object('success',false,'code','CONFLICT','currentVersion',target.row_version);END IF;
 IF (SELECT array_agg(value->>'lineId' ORDER BY value->>'lineId') FROM jsonb_array_elements(command->'lines')) IS DISTINCT FROM (SELECT array_agg(id ORDER BY id) FROM erp.rental_equipment_lines WHERE rental_id=target.id AND company_id=tenant AND deleted_at IS NULL) THEN RETURN jsonb_build_object('success',false,'code','LINE_SET_MISMATCH');END IF;
 FOR item IN SELECT value FROM jsonb_array_elements(command->'lines') LOOP
  terms=item->'commercialTerms';SELECT * INTO line_row FROM erp.rental_equipment_lines WHERE id=item->>'lineId' AND rental_id=target.id AND company_id=tenant FOR UPDATE;
  IF jsonb_typeof(terms) IS DISTINCT FROM 'object' OR terms->>'billingMethod' NOT IN('Per Hour','Per Day','Per Week','Per Month','Per Trip','Per Kilometer','Per Cubic Meter','One Lot','Per Lot') OR length(terms->>'currency')<>3 OR jsonb_typeof(terms->'operatorIncluded') IS DISTINCT FROM 'boolean' OR nullif(terms->>'unitRate','') IS NULL OR (terms->>'unitRate')::numeric<0 OR (terms ? 'idleRate' AND (terms->>'idleRate')::numeric<0) OR coalesce(terms->>'discountType','NONE') NOT IN ('NONE','PERCENTAGE','FIXED_AMOUNT') OR coalesce((terms->>'discountValue')::numeric,0)<0 OR (terms->>'discountType'='PERCENTAGE' AND (terms->>'discountValue')::numeric>100) OR (coalesce(terms->>'discountType','NONE')='NONE' AND coalesce((terms->>'discountValue')::numeric,0)<>0) OR coalesce(terms->>'vatApplicability','Applicable') NOT IN ('Applicable','Not Applicable') OR (coalesce(terms->>'transactionRelationship','Non-Affiliate')='Affiliate' AND coalesce(terms->>'vatApplicability','Applicable')<>'Not Applicable') OR (coalesce(terms->>'transactionRelationship','Non-Affiliate')='Non-Affiliate' AND coalesce(terms->>'vatApplicability','Applicable')<>'Applicable') OR (terms->>'vatApplicability'='Applicable' AND coalesce((terms->>'taxRate')::numeric,0)<=0) OR nullif(item->>'costCodeId','') IS NULL OR nullif(item->>'activityCodeId','') IS NULL OR nullif(item->>'workDescriptionId','') IS NULL OR jsonb_typeof(item->'deurPolicy') IS DISTINCT FROM 'object' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
  IF NOT EXISTS(SELECT 1 FROM erp.equipment e WHERE e.id=line_row.equipment_id AND e.company_id=tenant AND e.cost_code_id=item->>'costCodeId') OR NOT EXISTS(SELECT 1 FROM erp.assignments a WHERE a.id=line_row.assignment_id AND a.company_id=tenant AND a.activity_code_id=item->>'activityCodeId') OR NOT EXISTS(SELECT 1 FROM erp.work_descriptions w WHERE w.id=item->>'workDescriptionId' AND w.active AND w.deleted_at IS NULL) THEN RETURN jsonb_build_object('success',false,'code','MISSING_RELATIONSHIP');END IF;
 END LOOP;
 DELETE FROM erp.rental_contracts WHERE rental_id=target.id AND status='Draft';
 FOR item IN SELECT value FROM jsonb_array_elements(command->'lines') LOOP terms=item->'commercialTerms';SELECT * INTO line_row FROM erp.rental_equipment_lines WHERE id=item->>'lineId';
  INSERT INTO erp.rental_contracts(id,rental_id,rental_equipment_line_id,contract_no,customer_id,equipment_id,project_id,rental_type,billing_method,currency,unit_rate,minimum_billable_hours,overtime_rate,standby_rate,idle_rate,discount_type,discount_value,mobilization_fee,demobilization_fee,fuel_charge,operator_included,operator_rate,contract_amount,tax_rate,withholding_tax,transaction_relationship,vat_applicability,remarks,start_date,expected_end_date,status,created_by,updated_by)
  VALUES(gen_random_uuid()::text,target.id,line_row.id,'DRAFT-'||target.rental_number,target.customer_id,line_row.equipment_id,target.project_id,target.rental_type,(terms->>'billingMethod')::erp.billing_method,upper(terms->>'currency'),(terms->>'unitRate')::numeric,nullif(terms->>'minimumBillableHours','')::numeric,nullif(terms->>'overtimeRate','')::numeric,nullif(terms->>'standbyRate','')::numeric,nullif(terms->>'idleRate','')::numeric,coalesce(terms->>'discountType','NONE'),coalesce((terms->>'discountValue')::numeric,0),nullif(terms->>'mobilizationFee','')::numeric,nullif(terms->>'demobilizationFee','')::numeric,nullif(terms->>'fuelCharge','')::numeric,(terms->>'operatorIncluded')::boolean,nullif(terms->>'operatorRate','')::numeric,nullif(terms->>'contractAmount','')::numeric,nullif(terms->>'taxRate','')::numeric,nullif(terms->>'withholdingTax','')::numeric,coalesce(terms->>'transactionRelationship','Non-Affiliate'),coalesce(terms->>'vatApplicability','Applicable'),terms->>'remarks',target.date_out,coalesce(target.expected_return,target.date_out),'Draft',actor,actor);
  UPDATE erp.rental_equipment_lines SET operational_metadata=operational_metadata||jsonb_build_object('draftPreparation',item-'commercialTerms'),updated_by=actor WHERE id=line_row.id;
 END LOOP;
 UPDATE erp.rentals SET approval_status='NotSubmitted',approval_requested_at=NULL,approval_requested_by=NULL,approval_decided_at=NULL,approval_decided_by=NULL,approval_decision_remarks=NULL,updated_by=actor WHERE id=target.id RETURNING * INTO target;
 INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(gen_random_uuid()::text,tenant,'Rental',target.id,'RENTAL_TERMS_UPDATED',actor,now_at,command->>'commandId',jsonb_build_object('lineCount',jsonb_array_length(command->'lines'),'version',target.row_version));
 response=jsonb_build_object('success',true,'disposition','ACCEPTED','value',jsonb_build_object('rentalId',target.id,'status',target.status,'approvalStatus',target.approval_status,'version',target.row_version));RETURN erp.finish_operational_command(command,'UPDATE_DRAFT_RENTAL_TERMS','RENTAL',target.id,tenant,actor,payload_hash,response,target.row_version);
EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');END $$;
-- Require Activity Code at the canonical creation boundary as well as in the UI.
CREATE OR REPLACE FUNCTION erp.command_create_assignment(command jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE
 tenant text=erp.current_company_id(); actor text=auth.uid()::text; now_at timestamptz=clock_timestamp(); assigned_on date; expected_on date; target_equipment erp.equipment; target_operator erp.operators; target_project erp.projects; target_activity erp.activity_codes; created_assignment erp.assignments; idem jsonb; payload_hash text; response jsonb; violated_constraint text;
BEGIN
 IF auth.uid() IS NULL OR tenant IS NULL OR NOT EXISTS(SELECT 1 FROM erp.users u JOIN erp.companies c ON c.id=u.company_id WHERE u.id=auth.uid() AND u.status='active' AND u.company_id=tenant AND c.active) THEN RETURN jsonb_build_object('success',false,'code','UNAUTHENTICATED');END IF;
 IF NOT erp.current_user_has_permission('assignment.create') THEN RETURN jsonb_build_object('success',false,'code','FORBIDDEN');END IF;
 IF command ?| ARRAY['companyId','company_id','tenantId','tenant_id','actor','actorId','actor_id','userId','user_id','status','rowVersion'] OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL OR nullif(btrim(command->>'assignmentId'),'') IS NULL OR command->>'assignmentId'<>btrim(command->>'assignmentId') OR command->>'assignmentId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' OR nullif(btrim(command->>'equipmentId'),'') IS NULL OR nullif(btrim(command->>'operatorId'),'') IS NULL OR nullif(btrim(command->>'projectId'),'') IS NULL OR nullif(btrim(command->>'assignedDate'),'') IS NULL OR nullif(btrim(command->>'activityCodeId'),'') IS NULL THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
 BEGIN assigned_on=(command->>'assignedDate')::date; expected_on=nullif(command->>'expectedReturn','')::date; EXCEPTION WHEN invalid_datetime_format OR datetime_field_overflow THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END;
 IF expected_on IS NOT NULL AND expected_on<assigned_on THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
 idem=erp.begin_operational_command(command,'CREATE_ASSIGNMENT','ASSIGNMENT',command->>'assignmentId',tenant,actor);
 IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); ELSIF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); ELSIF idem->>'state'<>'NEW' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF; payload_hash=idem->>'payloadHash';
 SELECT * INTO target_equipment FROM erp.equipment WHERE id=command->>'equipmentId' AND company_id=tenant FOR UPDATE; SELECT * INTO target_operator FROM erp.operators WHERE id=command->>'operatorId' AND company_id=tenant FOR UPDATE; SELECT * INTO target_project FROM erp.projects WHERE id=command->>'projectId' AND company_id=tenant;
 IF target_equipment.id IS NULL OR NOT target_equipment.active OR target_equipment.deleted_at IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF;
 IF NOT EXISTS(SELECT 1 FROM erp.equipment_statuses s WHERE s.id=target_equipment.status_id AND lower(s.code)='available' AND s.active AND s.deleted_at IS NULL) THEN RETURN jsonb_build_object('success',false,'code','EQUIPMENT_UNAVAILABLE');END IF;
 IF target_operator.id IS NULL OR target_operator.status<>'Active' OR target_operator.deleted_at IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF;
 IF target_project.id IS NULL OR NOT target_project.active OR target_project.deleted_at IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF;
 IF nullif(btrim(command->>'activityCodeId'),'') IS NOT NULL THEN SELECT * INTO target_activity FROM erp.activity_codes WHERE id=command->>'activityCodeId' AND active AND deleted_at IS NULL; IF target_activity.id IS NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF; END IF;
 IF EXISTS(SELECT 1 FROM erp.assignments WHERE company_id=tenant AND id=command->>'assignmentId') THEN RETURN jsonb_build_object('success',false,'code','CONFLICT');END IF;
 IF EXISTS(SELECT 1 FROM erp.assignments WHERE company_id=tenant AND equipment_id=target_equipment.id AND status='Active' AND deleted_at IS NULL) THEN RETURN jsonb_build_object('success',false,'code','EQUIPMENT_UNAVAILABLE');END IF;
 IF EXISTS(SELECT 1 FROM erp.assignments WHERE company_id=tenant AND operator_id=target_operator.id AND status='Active' AND deleted_at IS NULL) THEN RETURN jsonb_build_object('success',false,'code','CONFLICT');END IF;
 INSERT INTO erp.assignments(id,equipment_id,operator_id,project_id,activity_code_id,assigned_date,expected_return,remarks,status,created_by,updated_by,company_id) VALUES(command->>'assignmentId',target_equipment.id,target_operator.id,target_project.id,target_activity.id,assigned_on,expected_on,coalesce(command->>'remarks',''),'Active',actor,actor,tenant) RETURNING * INTO created_assignment;
 UPDATE erp.equipment SET status_id=(SELECT id FROM erp.equipment_statuses WHERE lower(code)='assigned' AND active AND deleted_at IS NULL ORDER BY sort_order,id LIMIT 1),project_id=target_project.id,operator_id=target_operator.id,updated_by=actor WHERE id=target_equipment.id AND company_id=tenant;
 INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(gen_random_uuid()::text,tenant,'Assignment',created_assignment.id,'ASSIGNMENT_CREATED',actor,now_at,command->>'commandId',jsonb_build_object('equipmentId',created_assignment.equipment_id,'operatorId',created_assignment.operator_id,'projectId',created_assignment.project_id,'status','Active'));
 response=jsonb_build_object('success',true,'disposition','ACCEPTED','serverOccurredAt',now_at,'refresh',jsonb_build_array(created_assignment.id,created_assignment.equipment_id),'value',jsonb_build_object('id',created_assignment.id,'companyId',created_assignment.company_id,'equipmentId',created_assignment.equipment_id,'operatorId',created_assignment.operator_id,'projectId',created_assignment.project_id,'activityCodeId',created_assignment.activity_code_id,'assignedDate',created_assignment.assigned_date,'expectedReturn',created_assignment.expected_return,'remarks',created_assignment.remarks,'status',created_assignment.status,'createdAt',created_assignment.created_at,'updatedAt',created_assignment.updated_at,'rowVersion',created_assignment.row_version));
 RETURN erp.finish_operational_command(command,'CREATE_ASSIGNMENT','ASSIGNMENT',created_assignment.id,tenant,actor,payload_hash,response,created_assignment.row_version);
EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS violated_constraint=CONSTRAINT_NAME; IF violated_constraint='uq_assignment_active_equipment' THEN RETURN jsonb_build_object('success',false,'code','EQUIPMENT_UNAVAILABLE'); ELSIF violated_constraint='uq_assignment_active_operator' THEN RETURN jsonb_build_object('success',false,'code','CONFLICT'); ELSIF violated_constraint='assignments_pkey' THEN RETURN jsonb_build_object('success',false,'code','CONFLICT');END IF; RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');
WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');END $$;
COMMIT;
