BEGIN;
SET LOCAL search_path=erp,auth,extensions,pg_catalog;

CREATE OR REPLACE FUNCTION erp.command_create_project(command jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE
 tenant text=erp.current_company_id(); actor text=auth.uid()::text; now_at timestamptz=clock_timestamp();
 project_code_value text=nullif(btrim(command->>'projectCode'),''); project_name_value text=nullif(btrim(command->>'name'),'');
 customer_id_value text=nullif(btrim(command->>'customerId'),''); location_value text=nullif(btrim(command->>'location'),'');
 target_customer erp.customers; created_project erp.projects; idem jsonb; payload_hash text; response jsonb; violated_constraint text;
BEGIN
 IF auth.uid() IS NULL OR tenant IS NULL OR NOT EXISTS(SELECT 1 FROM erp.users u JOIN erp.companies c ON c.id=u.company_id WHERE u.id=auth.uid() AND u.status='active' AND u.company_id=tenant AND c.active) THEN RETURN jsonb_build_object('success',false,'code','UNAUTHENTICATED');END IF;
 IF NOT erp.current_user_has_permission('project.create') THEN RETURN jsonb_build_object('success',false,'code','FORBIDDEN');END IF;
 IF command ?| ARRAY['companyId','company_id','tenantId','tenant_id','actor','actorId','actor_id','userId','user_id','createdBy','created_by','updatedBy','updated_by','active','deletedAt','deleted_at','rowVersion','row_version','status','projectManager','client','legacyPayload','legacy_payload'] OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL OR nullif(btrim(command->>'projectId'),'') IS NULL OR command->>'projectId'<>btrim(command->>'projectId') OR command->>'projectId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' OR project_code_value IS NULL OR project_name_value IS NULL THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
 idem=erp.begin_operational_command(command,'CREATE_PROJECT','PROJECT',command->>'projectId',tenant,actor);
 IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); ELSIF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); ELSIF idem->>'state'<>'NEW' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
 payload_hash=idem->>'payloadHash';
 IF customer_id_value IS NOT NULL THEN SELECT * INTO target_customer FROM erp.customers WHERE id=customer_id_value AND company_id=tenant; IF target_customer.id IS NULL OR NOT target_customer.active OR target_customer.deleted_at IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code','CUSTOMER_INVALID');END IF; END IF;
 INSERT INTO erp.projects(id,project_code,name,customer_id,location,active,deleted_at,created_by,updated_by,company_id) VALUES(command->>'projectId',project_code_value,project_name_value,target_customer.id,location_value,true,NULL,actor,actor,tenant) RETURNING * INTO created_project;
 INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(gen_random_uuid()::text,tenant,'Project',created_project.id,'PROJECT_CREATED',actor,now_at,command->>'commandId',jsonb_strip_nulls(jsonb_build_object('projectCode',created_project.project_code,'name',created_project.name,'customerId',created_project.customer_id,'location',created_project.location,'active',created_project.active)));
 response=jsonb_build_object('success',true,'disposition','ACCEPTED','serverOccurredAt',now_at,'refresh',jsonb_build_array(created_project.id),'value',jsonb_build_object('id',created_project.id,'companyId',created_project.company_id,'projectCode',created_project.project_code,'name',created_project.name,'customerId',created_project.customer_id,'location',created_project.location,'active',created_project.active,'deletedAt',created_project.deleted_at,'createdAt',created_project.created_at,'updatedAt',created_project.updated_at,'rowVersion',created_project.row_version));
 RETURN erp.finish_operational_command(command,'CREATE_PROJECT','PROJECT',created_project.id,tenant,actor,payload_hash,response,created_project.row_version);
EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS violated_constraint=CONSTRAINT_NAME; IF violated_constraint='uq_projects_code_active' THEN RETURN jsonb_build_object('success',false,'code','PROJECT_CODE_CONFLICT'); ELSIF violated_constraint='projects_pkey' THEN RETURN jsonb_build_object('success',false,'code','CONFLICT');END IF; RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');
WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');END $$;

CREATE OR REPLACE FUNCTION erp.command_create_operator(command jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE
 tenant text=erp.current_company_id(); actor text=auth.uid()::text; now_at timestamptz=clock_timestamp(); name_value text=nullif(btrim(command->>'name'),''); email_value text=nullif(btrim(command->>'email'),''); license_number_value text=nullif(btrim(command->>'licenseNumber'),''); certification_type_value text=coalesce(nullif(btrim(command->>'certificationType'),''),'None'); joined_date_value date; created_operator erp.operators; idem jsonb; payload_hash text; response jsonb; violated_constraint text;
BEGIN
 IF auth.uid() IS NULL OR tenant IS NULL OR NOT EXISTS(SELECT 1 FROM erp.users u JOIN erp.companies c ON c.id=u.company_id WHERE u.id=auth.uid() AND u.status='active' AND u.company_id=tenant AND c.active) THEN RETURN jsonb_build_object('success',false,'code','UNAUTHENTICATED');END IF;
 IF NOT erp.current_user_has_permission('operator.create') THEN RETURN jsonb_build_object('success',false,'code','FORBIDDEN');END IF;
 IF command ?| ARRAY['companyId','company_id','tenantId','tenant_id','actor','actorId','actor_id','status','deletedAt','deleted_at','rowVersion','row_version','createdBy','created_by','updatedBy','updated_by','userId','user_id','applicationUserId','authUserId','username','password','pin','pinVerifier','operatorUserLink','linkedUser','legacyPayload','legacy_payload','certificationTypes'] OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL OR nullif(btrim(command->>'operatorId'),'') IS NULL OR command->>'operatorId'<>btrim(command->>'operatorId') OR command->>'operatorId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' OR name_value IS NULL OR certification_type_value NOT IN ('Heavy Machinery','Forklift','Crane Logistics','None') OR (command ? 'joinedDate' AND nullif(btrim(command->>'joinedDate'),'') IS NOT NULL AND command->>'joinedDate' !~ '^\d{4}-\d{2}-\d{2}$') THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
 BEGIN joined_date_value=nullif(btrim(command->>'joinedDate'),'')::date; EXCEPTION WHEN invalid_datetime_format OR datetime_field_overflow THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END;
 idem=erp.begin_operational_command(command,'CREATE_OPERATOR','OPERATOR',command->>'operatorId',tenant,actor);
 IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); ELSIF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); ELSIF idem->>'state'<>'NEW' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF; payload_hash=idem->>'payloadHash';
 INSERT INTO erp.operators(id,name,email,license_number,certification_type,status,joined_date,deleted_at,created_by,updated_by,company_id) VALUES(command->>'operatorId',name_value,email_value,license_number_value,certification_type_value,'Active',joined_date_value,NULL,actor,actor,tenant) RETURNING * INTO created_operator;
 INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(gen_random_uuid()::text,tenant,'Operator',created_operator.id,'OPERATOR_CREATED',actor,now_at,command->>'commandId',jsonb_strip_nulls(jsonb_build_object('name',created_operator.name,'email',created_operator.email,'licenseNumber',created_operator.license_number,'certificationType',created_operator.certification_type,'joinedDate',created_operator.joined_date,'status',created_operator.status)));
 response=jsonb_build_object('success',true,'disposition','ACCEPTED','serverOccurredAt',now_at,'refresh',jsonb_build_array(created_operator.id),'value',jsonb_build_object('id',created_operator.id,'companyId',created_operator.company_id,'name',created_operator.name,'email',created_operator.email,'licenseNumber',created_operator.license_number,'certificationType',created_operator.certification_type,'status',created_operator.status,'joinedDate',created_operator.joined_date,'deletedAt',created_operator.deleted_at,'createdAt',created_operator.created_at,'updatedAt',created_operator.updated_at,'rowVersion',created_operator.row_version));
 RETURN erp.finish_operational_command(command,'CREATE_OPERATOR','OPERATOR',created_operator.id,tenant,actor,payload_hash,response,created_operator.row_version);
EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS violated_constraint=CONSTRAINT_NAME; IF violated_constraint='operators_pkey' THEN RETURN jsonb_build_object('success',false,'code','OPERATOR_ID_CONFLICT');END IF; RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');
WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');END $$;

CREATE OR REPLACE FUNCTION erp.command_create_assignment(command jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE
 tenant text=erp.current_company_id(); actor text=auth.uid()::text; now_at timestamptz=clock_timestamp(); assigned_on date; expected_on date; target_equipment erp.equipment; target_operator erp.operators; target_project erp.projects; target_activity erp.activity_codes; created_assignment erp.assignments; idem jsonb; payload_hash text; response jsonb; violated_constraint text;
BEGIN
 IF auth.uid() IS NULL OR tenant IS NULL OR NOT EXISTS(SELECT 1 FROM erp.users u JOIN erp.companies c ON c.id=u.company_id WHERE u.id=auth.uid() AND u.status='active' AND u.company_id=tenant AND c.active) THEN RETURN jsonb_build_object('success',false,'code','UNAUTHENTICATED');END IF;
 IF NOT erp.current_user_has_permission('assignment.create') THEN RETURN jsonb_build_object('success',false,'code','FORBIDDEN');END IF;
 IF command ?| ARRAY['companyId','company_id','tenantId','tenant_id','actor','actorId','actor_id','userId','user_id','status','rowVersion'] OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL OR nullif(btrim(command->>'assignmentId'),'') IS NULL OR command->>'assignmentId'<>btrim(command->>'assignmentId') OR command->>'assignmentId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' OR nullif(btrim(command->>'equipmentId'),'') IS NULL OR nullif(btrim(command->>'operatorId'),'') IS NULL OR nullif(btrim(command->>'projectId'),'') IS NULL OR nullif(btrim(command->>'assignedDate'),'') IS NULL THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
 BEGIN assigned_on=(command->>'assignedDate')::date; expected_on=nullif(command->>'expectedReturn','')::date; EXCEPTION WHEN invalid_datetime_format OR datetime_field_overflow THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END;
 IF expected_on IS NOT NULL AND expected_on<assigned_on THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF;
 idem=erp.begin_operational_command(command,'CREATE_ASSIGNMENT','ASSIGNMENT',command->>'assignmentId',tenant,actor);
 IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); ELSIF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); ELSIF idem->>'state'<>'NEW' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED');END IF; payload_hash=idem->>'payloadHash';
 SELECT * INTO target_equipment FROM erp.equipment WHERE id=command->>'equipmentId' AND company_id=tenant FOR UPDATE; SELECT * INTO target_operator FROM erp.operators WHERE id=command->>'operatorId' AND company_id=tenant FOR UPDATE; SELECT * INTO target_project FROM erp.projects WHERE id=command->>'projectId' AND company_id=tenant;
 IF target_equipment.id IS NULL OR NOT target_equipment.active OR target_equipment.deleted_at IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF;
 IF NOT EXISTS(SELECT 1 FROM erp.equipment_statuses s WHERE s.id=target_equipment.status_id AND lower(s.code)='available' AND s.active AND s.deleted_at IS NULL) THEN RETURN jsonb_build_object('success',false,'code','EQUIPMENT_UNAVAILABLE');END IF;
 IF target_operator.id IS NULL OR target_operator.status<>'Active' OR target_operator.deleted_at IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF;
 IF target_project.id IS NULL OR NOT target_project.active OR target_project.deleted_at IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF;
 IF nullif(btrim(command->>'activityCodeId'),'') IS NOT NULL THEN SELECT * INTO target_activity FROM erp.activity_codes WHERE id=command->>'activityCodeId' AND active AND deleted_at IS NULL; IF target_activity.id IS NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND');END IF; END IF;
 IF EXISTS(SELECT 1 FROM erp.assignments WHERE company_id=tenant AND id=command->>'assignmentId') THEN RETURN jsonb_build_object('success',false,'code','CONFLICT');END IF;
 IF EXISTS(SELECT 1 FROM erp.assignments WHERE company_id=tenant AND equipment_id=target_equipment.id AND status='Active' AND deleted_at IS NULL) THEN RETURN jsonb_build_object('success',false,'code','EQUIPMENT_UNAVAILABLE');END IF;
 IF EXISTS(SELECT 1 FROM erp.assignments WHERE company_id=tenant AND operator_id=target_operator.id AND status='Active' AND deleted_at IS NULL) THEN RETURN jsonb_build_object('success',false,'code','CONFLICT');END IF;
 INSERT INTO erp.assignments(id,equipment_id,operator_id,project_id,activity_code_id,assigned_date,expected_return,remarks,status,created_by,updated_by,company_id) VALUES(command->>'assignmentId',target_equipment.id,target_operator.id,target_project.id,target_activity.id,assigned_on,expected_on,coalesce(command->>'remarks',''),'Active',actor,actor,tenant) RETURNING * INTO created_assignment;
 UPDATE erp.equipment SET status_id=(SELECT id FROM erp.equipment_statuses WHERE lower(code)='assigned' AND active AND deleted_at IS NULL ORDER BY sort_order,id LIMIT 1),project_id=target_project.id,operator_id=target_operator.id,updated_by=actor WHERE id=target_equipment.id AND company_id=tenant;
 INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(gen_random_uuid()::text,tenant,'Assignment',created_assignment.id,'ASSIGNMENT_CREATED',actor,now_at,command->>'commandId',jsonb_build_object('equipmentId',created_assignment.equipment_id,'operatorId',created_assignment.operator_id,'projectId',created_assignment.project_id,'status','Active'));
 response=jsonb_build_object('success',true,'disposition','ACCEPTED','serverOccurredAt',now_at,'refresh',jsonb_build_array(created_assignment.id,created_assignment.equipment_id),'value',jsonb_build_object('id',created_assignment.id,'companyId',created_assignment.company_id,'equipmentId',created_assignment.equipment_id,'operatorId',created_assignment.operator_id,'projectId',created_assignment.project_id,'activityCodeId',created_assignment.activity_code_id,'assignedDate',created_assignment.assigned_date,'expectedReturn',created_assignment.expected_return,'remarks',created_assignment.remarks,'status',created_assignment.status,'createdAt',created_assignment.created_at,'updatedAt',created_assignment.updated_at,'rowVersion',created_assignment.row_version));
 RETURN erp.finish_operational_command(command,'CREATE_ASSIGNMENT','ASSIGNMENT',created_assignment.id,tenant,actor,payload_hash,response,created_assignment.row_version);
EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS violated_constraint=CONSTRAINT_NAME; IF violated_constraint='uq_assignment_active_equipment' THEN RETURN jsonb_build_object('success',false,'code','EQUIPMENT_UNAVAILABLE'); ELSIF violated_constraint='uq_assignment_active_operator' THEN RETURN jsonb_build_object('success',false,'code','CONFLICT'); ELSIF violated_constraint='assignments_pkey' THEN RETURN jsonb_build_object('success',false,'code','CONFLICT');END IF; RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');
WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE');END $$;

CREATE OR REPLACE FUNCTION erp.command_create_reserved_rental(command jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth AS $$
DECLARE
  tenant text; actor text; idem jsonb; payload_hash text; response jsonb; customer erp.customers; project erp.projects; line jsonb; now_at timestamptz=clock_timestamp(); requested_count integer; valid_count integer;
BEGIN
  tenant=(SELECT company_id FROM erp.users WHERE id=auth.uid() AND status='active'); actor=auth.uid()::text;
  IF tenant IS NULL THEN RETURN jsonb_build_object('success',false,'code','UNAUTHENTICATED','message','Authentication is required.','retryable',false,'refreshRequired',false); END IF;
  IF NOT erp.current_user_has_permission('rental.create') THEN RETURN jsonb_build_object('success',false,'code','FORBIDDEN','message','Rental management permission is required.','retryable',false,'refreshRequired',false); END IF;
  IF nullif(command->>'rentalId','') IS NULL OR nullif(command->>'rentalNumber','') IS NULL OR nullif(command->>'customerId','') IS NULL OR nullif(command->>'projectId','') IS NULL OR nullif(command->>'dateOut','') IS NULL OR coalesce(jsonb_typeof(command->'lines'),'null')<>'array' OR coalesce(jsonb_array_length(command->'lines'),0)=0 OR command->>'rentalType' NOT IN('Bare Rental','Operated Rental') THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED','message','Required Rental details are incomplete.','retryable',false,'refreshRequired',false); END IF;
  IF command ? 'companyId' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED','message','Company scope is derived from authentication.','retryable',false,'refreshRequired',false); END IF;
  IF command ? 'expectedReturn' AND nullif(command->>'expectedReturn','') IS NOT NULL AND (command->>'expectedReturn')::date < (command->>'dateOut')::date THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED','message','Expected return cannot precede date out.','retryable',false,'refreshRequired',false); END IF;
  idem=erp.begin_operational_command(command,'CREATE_RESERVED_RENTAL','RENTAL',command->>'rentalId',tenant,actor);
  IF idem->>'state'='INVALID' THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED','message','An idempotency key is required.','retryable',false,'refreshRequired',false); END IF; IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH','message','Idempotency key payload mismatch.','retryable',false,'refreshRequired',false); END IF; IF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); END IF; payload_hash=idem->>'payloadHash';
  SELECT * INTO customer FROM erp.customers WHERE id=command->>'customerId' AND company_id=tenant AND active AND deleted_at IS NULL; SELECT * INTO project FROM erp.projects WHERE id=command->>'projectId' AND company_id=tenant AND active AND deleted_at IS NULL;
  IF customer.id IS NULL OR project.id IS NULL THEN RETURN jsonb_build_object('success',false,'code','NOT_FOUND','message','A required Rental relationship is unavailable.','retryable',false,'refreshRequired',false); END IF; IF project.customer_id IS DISTINCT FROM customer.id THEN RETURN jsonb_build_object('success',false,'code','MISSING_RELATIONSHIP','message','Project and Customer relationship is invalid.','retryable',false,'refreshRequired',false); END IF;
  IF EXISTS(SELECT 1 FROM erp.rentals WHERE company_id=tenant AND (id=command->>'rentalId' OR lower(rental_number)=lower(command->>'rentalNumber'))) THEN RETURN jsonb_build_object('success',false,'code','RENTAL_CONFLICT','message','Rental identity is already in use.','retryable',false,'refreshRequired',false); END IF;
  SELECT count(*),count(DISTINCT item->>'equipmentId') INTO requested_count,valid_count FROM jsonb_array_elements(command->'lines') item;
  IF requested_count<>valid_count OR EXISTS(SELECT 1 FROM jsonb_array_elements(command->'lines') item WHERE nullif(item->>'id','') IS NULL OR nullif(item->>'equipmentId','') IS NULL OR nullif(item->>'assignmentId','') IS NULL OR nullif(item->>'operatorId','') IS NULL) THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED','message','Rental equipment lines are incomplete or duplicated.','retryable',false,'refreshRequired',false); END IF;
  PERFORM e.id FROM erp.equipment e JOIN jsonb_array_elements(command->'lines') item ON item->>'equipmentId'=e.id WHERE e.company_id=tenant ORDER BY e.id FOR UPDATE;
  SELECT count(*) INTO valid_count FROM jsonb_array_elements(command->'lines') item JOIN erp.equipment e ON e.id=item->>'equipmentId' AND e.company_id=tenant AND e.active AND e.deleted_at IS NULL JOIN erp.operators o ON o.id=item->>'operatorId' AND o.company_id=tenant AND o.status='Active' AND o.deleted_at IS NULL JOIN erp.assignments a ON a.id=item->>'assignmentId' AND a.company_id=tenant AND a.status='Active' AND a.deleted_at IS NULL AND a.equipment_id=e.id AND a.operator_id=o.id AND a.project_id=project.id;
  IF valid_count<>requested_count THEN RETURN jsonb_build_object('success',false,'code','MISSING_RELATIONSHIP','message','A Rental line relationship is unavailable or invalid.','retryable',false,'refreshRequired',false); END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(command->'lines') item JOIN erp.rental_equipment_lines existing_line ON existing_line.equipment_id=item->>'equipmentId' AND existing_line.deleted_at IS NULL JOIN erp.rentals existing_rental ON existing_rental.id=existing_line.rental_id AND existing_rental.company_id=tenant AND existing_rental.status IN('Draft','Assigned','Reserved','Released','Active')) THEN RETURN jsonb_build_object('success',false,'code','EQUIPMENT_UNAVAILABLE','message','Equipment is unavailable for this Rental.','retryable',false,'refreshRequired',false); END IF;
  INSERT INTO erp.rentals(id,rental_number,customer_id,project_id,customer_snapshot,project_snapshot,date_out,expected_return,rental_type,status,reserved_at,created_by,updated_by,company_id,legacy_payload) VALUES(command->>'rentalId',trim(command->>'rentalNumber'),customer.id,project.id,customer.name,project.name,(command->>'dateOut')::date,nullif(command->>'expectedReturn','')::date,command->>'rentalType','Reserved',now_at,actor,actor,tenant,jsonb_build_object('approvalStatus','Approved'));
  FOR line IN SELECT value FROM jsonb_array_elements(command->'lines') LOOP INSERT INTO erp.rental_equipment_lines(id,rental_id,equipment_id,assignment_id,operator_id,status,commercial_snapshot_required,created_by,updated_by,company_id) VALUES(line->>'id',command->>'rentalId',line->>'equipmentId',line->>'assignmentId',line->>'operatorId','Reserved',true,actor,actor,tenant); END LOOP;
  UPDATE erp.equipment e SET status_id=coalesce((SELECT id FROM erp.equipment_statuses WHERE lower(code)='assigned' LIMIT 1),e.status_id),project_id=project.id,operator_id=(SELECT item->>'operatorId' FROM jsonb_array_elements(command->'lines') item WHERE item->>'equipmentId'=e.id),updated_by=actor WHERE e.company_id=tenant AND e.id IN(SELECT item->>'equipmentId' FROM jsonb_array_elements(command->'lines') item);
  INSERT INTO erp.audit_log(id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values,metadata,company_id) VALUES(extensions.gen_random_uuid()::text,'Rental',command->>'rentalId','RENTAL_RESERVED',actor,now_at,command->>'commandId',jsonb_build_object('status','Reserved','lineCount',requested_count),jsonb_build_object('source','command_create_reserved_rental'),tenant);
  response=jsonb_build_object('success',true,'disposition','ACCEPTED','serverOccurredAt',now_at,'refresh',jsonb_build_array(command->>'rentalId'),'value',jsonb_build_object('rentalId',command->>'rentalId','rentalNumber',trim(command->>'rentalNumber'),'status','Reserved','version',1)); RETURN erp.finish_operational_command(command,'CREATE_RESERVED_RENTAL','RENTAL',command->>'rentalId',tenant,actor,payload_hash,response,1);
EXCEPTION WHEN unique_violation THEN RETURN jsonb_build_object('success',false,'code','RENTAL_CONFLICT','message','Rental or equipment identity conflicts with an active record.','retryable',false,'refreshRequired',true);
WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'code','PERSISTENCE_FAILURE','message','Rental creation could not be completed.','retryable',false,'refreshRequired',true);
END $$;

CREATE OR REPLACE FUNCTION erp.command_activate_rental(command jsonb) RETURNS jsonb
LANGUAGE sql SECURITY DEFINER SET search_path=erp,auth AS
$$ SELECT erp.execute_rental_lifecycle_transition(command,'ACTIVATE_RENTAL','Released','Active','rental.activate') $$;

COMMIT;
