BEGIN;
SET LOCAL search_path=erp,auth,extensions,pg_catalog;
-- Manual transcription is an encoding workflow.  Its operational timeline is
-- anchored to the DEUR work date, while created_at/audit timestamps continue
-- to express when the office encoder recorded the evidence.
CREATE OR REPLACE FUNCTION erp.validate_manual_deur_physical_occurrence(
  target erp.deurs,
  client_at timestamptz,
  now_at timestamptz
)
RETURNS text LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE rental_record erp.rentals%ROWTYPE; assignment_record erp.assignments%ROWTYPE; timezone_name text;
BEGIN
  IF client_at IS NULL THEN RETURN 'VALIDATION_REJECTED'; END IF;
  SELECT * INTO rental_record FROM erp.rentals WHERE id=target.rental_id AND company_id=target.company_id;
  SELECT * INTO assignment_record FROM erp.assignments WHERE id=target.assignment_id AND company_id=target.company_id;
  IF rental_record.id IS NULL OR rental_record.status<>'Active' THEN RETURN 'RENTAL_INACTIVE'; END IF;
  IF assignment_record.id IS NULL OR assignment_record.status<>'Active' THEN RETURN 'ASSIGNMENT_INACTIVE'; END IF;
  timezone_name:=coalesce(nullif(rental_record.timezone,''),nullif((SELECT operational_metadata#>>'{deurExpectationSnapshot,policy,timezone}' FROM erp.rental_equipment_lines WHERE id=target.rental_equipment_line_id AND company_id=target.company_id),''),'Asia/Manila');
  IF NOT EXISTS(SELECT 1 FROM pg_catalog.pg_timezone_names WHERE name=timezone_name) THEN RETURN 'VALIDATION_REJECTED'; END IF;
  IF timezone(timezone_name,client_at)::date<>target.work_date THEN RETURN 'VALIDATION_REJECTED'; END IF;
  IF client_at>now_at+interval '5 minutes' THEN RETURN 'CLIENT_OCCURRENCE_IN_FUTURE'; END IF;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION erp.manual_deur_has_only_encoding_bootstrap(target erp.deurs)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
SET search_path=erp,auth,extensions,pg_catalog AS $$
  SELECT count(*)=2
    AND bool_and(
      source='manual-web' AND action='start' AND is_open
      AND activity_type IN ('shift','operation')
      AND occurred_at=target.created_at AND server_accepted_at=target.created_at
    )
  FROM erp.deur_events
  WHERE deur_id=target.id;
$$;
CREATE OR REPLACE FUNCTION erp.command_record_manual_deur_activity(command jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE
  tenant text:=erp.current_company_id(); scope jsonb; idem jsonb; payload_hash text;
  now_at timestamptz:=erp.deur_operational_clock(); target erp.deurs%ROWTYPE;
  open_activity text; next_activity text; next_sequence integer; client_at timestamptz;
  effective_at timestamptz; predecessor timestamptz; response jsonb; chronology_code text;
  bootstrap_only boolean;
BEGIN
  IF erp.reject_manual_transcription_authority(command,ARRAY['commandId','idempotencyKey','deurId','expectedVersion','action','clientOccurredAt','clientCreatedAt','deviceId']) OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL OR nullif(btrim(command->>'expectedVersion'),'') IS NULL THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
  scope:=erp.validate_manual_deur_transcription_scope(command); IF scope->>'code'<>'OK' THEN RETURN jsonb_build_object('success',false,'code',scope->>'code'); END IF;
  idem:=erp.begin_deur_command(command,'MANUAL_ACTIVITY_TRANSITION'); IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); END IF; IF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); END IF; payload_hash:=idem->>'payloadHash';
  SELECT * INTO target FROM erp.deurs WHERE id=command->>'deurId' AND company_id=tenant FOR UPDATE;
  IF target.creation_source<>'MANUAL_WEB' THEN RETURN jsonb_build_object('success',false,'code','MANUAL_DEUR_REQUIRED'); END IF;
  IF target.row_version<>(command->>'expectedVersion')::bigint THEN RETURN jsonb_build_object('success',false,'code','CONFLICT','aggregateId',target.id,'expectedVersion',(command->>'expectedVersion')::bigint,'currentVersion',target.row_version,'refreshRequired',true); END IF;
  IF target.status<>'In Progress' THEN RETURN jsonb_build_object('success',false,'code','INVALID_TRANSITION'); END IF;
  BEGIN client_at:=nullif(command->>'clientOccurredAt','')::timestamptz; EXCEPTION WHEN invalid_text_representation OR datetime_field_overflow THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END;
  chronology_code:=erp.validate_manual_deur_physical_occurrence(target,client_at,now_at); IF chronology_code IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code',chronology_code); END IF;
  bootstrap_only:=erp.manual_deur_has_only_encoding_bootstrap(target);
  SELECT activity_type INTO open_activity FROM erp.deur_events WHERE deur_id=target.id AND is_open AND activity_type<>'shift' FOR UPDATE;
  next_activity:=CASE command->>'action' WHEN 'START_OPERATION' THEN 'operation' WHEN 'RESUME_OPERATION' THEN 'operation' WHEN 'START_IDLE' THEN 'idle' WHEN 'START_STANDBY' THEN 'standby' WHEN 'START_MEAL_BREAK' THEN 'mealBreak' WHEN 'START_BREAKDOWN' THEN 'breakdown' WHEN 'END_ACTIVITY' THEN NULL ELSE 'INVALID' END;
  IF next_activity='INVALID' OR (next_activity IS NOT DISTINCT FROM open_activity AND NOT (bootstrap_only AND next_activity='operation' AND open_activity='operation')) THEN RETURN jsonb_build_object('success',false,'code','INVALID_TRANSITION'); END IF;
  IF bootstrap_only AND next_activity IS NULL THEN RETURN jsonb_build_object('success',false,'code','INVALID_TRANSITION'); END IF;
  SELECT max(occurred_at) INTO predecessor FROM erp.deur_events WHERE deur_id=target.id AND NOT (bootstrap_only AND source='manual-web' AND action='start' AND is_open AND activity_type IN ('shift','operation') AND occurred_at=target.created_at AND server_accepted_at=target.created_at);
  IF predecessor IS NOT NULL AND client_at<predecessor THEN RETURN jsonb_build_object('success',false,'code','CLIENT_OCCURRENCE_BEFORE_PREDECESSOR'); END IF;
  effective_at:=client_at;
  IF bootstrap_only THEN
    UPDATE erp.deur_events SET occurred_at=effective_at,client_created_at=coalesce(client_at,client_created_at)
    WHERE deur_id=target.id AND source='manual-web' AND action='start' AND is_open AND activity_type IN ('shift','operation') AND occurred_at=target.created_at AND server_accepted_at=target.created_at;
  END IF;
  IF bootstrap_only AND next_activity='operation' AND open_activity='operation' THEN
    UPDATE erp.deurs SET updated_at=now_at,updated_by=auth.uid()::text WHERE id=target.id RETURNING * INTO target;
    INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(extensions.gen_random_uuid()::text,tenant,'DEUR',target.id,'ACTIVITY_TRANSITION',auth.uid()::text,now_at,command->>'commandId',jsonb_build_object('manualWeb',true,'encoderUserId',auth.uid()::text,'operatorId',target.operator_id,'action',command->>'action','clientOccurredAt',client_at,'bootstrapRebased',true));
    response:=jsonb_build_object('success',true,'disposition','ACCEPTED','record',to_jsonb(target),'version',target.row_version,'serverOccurredAt',now_at); RETURN erp.finish_deur_command(command,'MANUAL_ACTIVITY_TRANSITION',target.id,payload_hash,response);
  END IF;
  UPDATE erp.deur_events SET is_open=false WHERE deur_id=target.id AND is_open AND activity_type<>'shift'; SELECT coalesce(max(sequence),0)+1 INTO next_sequence FROM erp.deur_events WHERE deur_id=target.id;
  IF open_activity IS NOT NULL THEN INSERT INTO erp.deur_events(id,deur_id,activity_type,action,occurred_at,sequence,source,actor_id,server_accepted_at,client_created_at,command_id,idempotency_key,device_id,is_open,company_id) VALUES(extensions.gen_random_uuid()::text,target.id,open_activity,'end',effective_at,next_sequence,'manual-web',auth.uid()::text,now_at,client_at,command->>'commandId',command->>'idempotencyKey',command->>'deviceId',false,tenant); next_sequence:=next_sequence+1; END IF;
  IF next_activity IS NOT NULL THEN INSERT INTO erp.deur_events(id,deur_id,activity_type,action,occurred_at,sequence,source,actor_id,server_accepted_at,client_created_at,command_id,idempotency_key,device_id,is_open,company_id) VALUES(extensions.gen_random_uuid()::text,target.id,next_activity,'start',effective_at,next_sequence,'manual-web',auth.uid()::text,now_at,client_at,command->>'commandId',command->>'idempotencyKey',command->>'deviceId',true,tenant); END IF;
  UPDATE erp.deurs SET updated_at=now_at,updated_by=auth.uid()::text WHERE id=target.id RETURNING * INTO target;
  INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(extensions.gen_random_uuid()::text,tenant,'DEUR',target.id,'ACTIVITY_TRANSITION',auth.uid()::text,now_at,command->>'commandId',jsonb_build_object('manualWeb',true,'encoderUserId',auth.uid()::text,'operatorId',target.operator_id,'action',command->>'action','clientOccurredAt',client_at));
  response:=jsonb_build_object('success',true,'disposition','ACCEPTED','record',to_jsonb(target),'version',target.row_version,'serverOccurredAt',now_at); RETURN erp.finish_deur_command(command,'MANUAL_ACTIVITY_TRANSITION',target.id,payload_hash,response);
END $$;
CREATE OR REPLACE FUNCTION erp.command_record_manual_deur_travel_checkpoint(command jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE tenant text:=erp.current_company_id(); scope jsonb; idem jsonb; payload_hash text; now_at timestamptz:=erp.deur_operational_clock(); target erp.deurs%ROWTYPE; line erp.rental_equipment_lines%ROWTYPE; checkpoint erp.deur_meter_checkpoints%ROWTYPE; odometer numeric; predecessor numeric; next_sequence integer; latitude numeric; longitude numeric; client_at timestamptz; location jsonb; response jsonb; chronology_code text;
BEGIN
  IF erp.reject_manual_transcription_authority(command,ARRAY['commandId','idempotencyKey','deurId','expectedVersion','odometer','locationName','latitude','longitude','clientOccurredAt']) OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL OR nullif(btrim(command->>'expectedVersion'),'') IS NULL OR nullif(btrim(command->>'odometer'),'') IS NULL THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
  scope:=erp.validate_manual_deur_transcription_scope(command); IF scope->>'code'<>'OK' THEN RETURN jsonb_build_object('success',false,'code',scope->>'code'); END IF; idem:=erp.begin_deur_command(command,'MANUAL_RECORD_DEUR_TRAVEL_CHECKPOINT'); IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); END IF; IF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); END IF; payload_hash:=idem->>'payloadHash';
  SELECT * INTO target FROM erp.deurs WHERE id=command->>'deurId' AND company_id=tenant FOR UPDATE; SELECT * INTO line FROM erp.rental_equipment_lines WHERE id=target.rental_equipment_line_id AND company_id=tenant;
  BEGIN odometer:=(command->>'odometer')::numeric; latitude:=nullif(command->>'latitude','')::numeric; longitude:=nullif(command->>'longitude','')::numeric; client_at:=nullif(command->>'clientOccurredAt','')::timestamptz; EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END;
  chronology_code:=erp.validate_manual_deur_physical_occurrence(target,client_at,now_at); IF chronology_code IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code',chronology_code); END IF;
  IF target.creation_source<>'MANUAL_WEB' THEN RETURN jsonb_build_object('success',false,'code','MANUAL_DEUR_REQUIRED'); END IF; IF target.row_version<>(command->>'expectedVersion')::bigint THEN RETURN jsonb_build_object('success',false,'code','CONFLICT','currentVersion',target.row_version,'refreshRequired',true); END IF; IF target.status<>'In Progress' OR odometer<0 OR line.operational_metadata#>>'{deurExpectationSnapshot,meterRequirement}' NOT IN ('odometer','both') OR (latitude IS NULL)<>(longitude IS NULL) OR (latitude IS NOT NULL AND (latitude<-90 OR latitude>90 OR longitude<-180 OR longitude>180)) OR (nullif(btrim(command->>'locationName'),'') IS NOT NULL AND (length(btrim(command->>'locationName'))>200 OR command->>'locationName'~'[[:cntrl:]]')) THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
  SELECT reading INTO predecessor FROM erp.deur_meter_checkpoints WHERE deur_id=target.id AND kind='checkpoint' AND meter_dimension='odometer' ORDER BY sequence_no DESC LIMIT 1; predecessor:=coalesce(predecessor,coalesce(target.opening_odometer,target.opening_meter)); IF predecessor IS NOT NULL AND odometer<predecessor THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED','message','Odometer rollback is not allowed.'); END IF; SELECT coalesce(max(sequence_no),0)+1 INTO next_sequence FROM erp.deur_meter_checkpoints WHERE deur_id=target.id AND kind='checkpoint' AND meter_dimension='odometer'; location:=CASE WHEN latitude IS NULL THEN NULL ELSE jsonb_build_object('latitude',latitude,'longitude',longitude) END;
  INSERT INTO erp.deur_meter_checkpoints(company_id,deur_id,rental_equipment_line_id,equipment_id,operator_id,kind,reading,client_occurred_at,location,created_by,sequence_no,meter_dimension,location_name,custodian_operator_id) VALUES(tenant,target.id,target.rental_equipment_line_id,target.equipment_id,target.operator_id,'checkpoint',odometer,client_at,location,auth.uid(),next_sequence,'odometer',nullif(btrim(command->>'locationName'),''),target.operator_id) RETURNING * INTO checkpoint;
  UPDATE erp.deurs SET updated_at=now_at,updated_by=auth.uid()::text WHERE id=target.id RETURNING * INTO target; INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(extensions.gen_random_uuid()::text,tenant,'DEUR',target.id,'RECORD_DEUR_TRAVEL_CHECKPOINT',auth.uid()::text,now_at,command->>'commandId',jsonb_build_object('manualWeb',true,'encoderUserId',auth.uid()::text,'operatorId',target.operator_id,'checkpointId',checkpoint.id,'sequence',checkpoint.sequence_no,'odometer',checkpoint.reading,'clientOccurredAt',client_at)); response:=jsonb_build_object('success',true,'disposition','ACCEPTED','record',to_jsonb(target),'version',target.row_version,'serverOccurredAt',now_at,'value',jsonb_build_object('checkpointId',checkpoint.id,'sequence',checkpoint.sequence_no,'odometer',checkpoint.reading)); RETURN erp.finish_deur_command(command,'MANUAL_RECORD_DEUR_TRAVEL_CHECKPOINT',target.id,payload_hash,response);
END $$;
CREATE OR REPLACE FUNCTION erp.command_record_manual_deur_refuel(command jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE tenant text:=erp.current_company_id(); scope jsonb; idem jsonb; payload_hash text; now_at timestamptz:=erp.deur_operational_clock(); target erp.deurs%ROWTYPE; line erp.rental_equipment_lines%ROWTYPE; created erp.deur_refuels%ROWTYPE; odometer numeric; liters numeric; predecessor numeric; client_at timestamptz; response jsonb; chronology_code text;
BEGIN
  IF erp.reject_manual_transcription_authority(command,ARRAY['commandId','idempotencyKey','deurId','expectedVersion','odometer','liters','locationName','clientOccurredAt']) OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL OR nullif(btrim(command->>'expectedVersion'),'') IS NULL OR nullif(btrim(command->>'odometer'),'') IS NULL OR nullif(btrim(command->>'liters'),'') IS NULL THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
  scope:=erp.validate_manual_deur_transcription_scope(command); IF scope->>'code'<>'OK' THEN RETURN jsonb_build_object('success',false,'code',scope->>'code'); END IF; idem:=erp.begin_deur_command(command,'MANUAL_RECORD_DEUR_REFUEL'); IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); END IF; IF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); END IF; payload_hash:=idem->>'payloadHash'; SELECT * INTO target FROM erp.deurs WHERE id=command->>'deurId' AND company_id=tenant FOR UPDATE; SELECT * INTO line FROM erp.rental_equipment_lines WHERE id=target.rental_equipment_line_id AND company_id=tenant;
  BEGIN odometer:=(command->>'odometer')::numeric; liters:=(command->>'liters')::numeric; client_at:=nullif(command->>'clientOccurredAt','')::timestamptz; EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END;
  chronology_code:=erp.validate_manual_deur_physical_occurrence(target,client_at,now_at); IF chronology_code IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code',chronology_code); END IF;
  IF target.creation_source<>'MANUAL_WEB' THEN RETURN jsonb_build_object('success',false,'code','MANUAL_DEUR_REQUIRED'); END IF; IF target.row_version<>(command->>'expectedVersion')::bigint THEN RETURN jsonb_build_object('success',false,'code','CONFLICT','currentVersion',target.row_version,'refreshRequired',true); END IF; IF target.status<>'In Progress' OR odometer<0 OR liters<=0 OR line.operational_metadata#>>'{deurExpectationSnapshot,meterRequirement}' NOT IN ('odometer','both') OR (nullif(btrim(command->>'locationName'),'') IS NOT NULL AND (length(btrim(command->>'locationName'))>200 OR command->>'locationName'~'[[:cntrl:]]')) THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
  SELECT max(candidate.reading) INTO predecessor FROM (SELECT r.odometer reading FROM erp.deur_refuels r WHERE r.company_id=tenant AND r.equipment_id=target.equipment_id UNION ALL SELECT c.reading FROM erp.deur_meter_checkpoints c WHERE c.company_id=tenant AND c.equipment_id=target.equipment_id AND c.kind='checkpoint' AND c.meter_dimension='odometer' UNION ALL SELECT coalesce(target.opening_odometer,target.opening_meter)) candidate WHERE candidate.reading IS NOT NULL; IF predecessor IS NOT NULL AND odometer<predecessor THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED','message','Odometer rollback is not allowed.'); END IF;
  INSERT INTO erp.deur_refuels(company_id,equipment_id,rental_id,rental_equipment_line_id,assignment_id,deur_id,custodian_operator_id,odometer,liters,location_name,client_occurred_at,server_accepted_at,created_by,command_id,idempotency_key) VALUES(tenant,target.equipment_id,target.rental_id,target.rental_equipment_line_id,target.assignment_id,target.id,target.operator_id,odometer,liters,nullif(btrim(command->>'locationName'),''),client_at,now_at,auth.uid(),command->>'commandId',command->>'idempotencyKey') RETURNING * INTO created; UPDATE erp.deurs SET updated_at=now_at,updated_by=auth.uid()::text WHERE id=target.id RETURNING * INTO target; INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(extensions.gen_random_uuid()::text,tenant,'DEUR',target.id,'RECORD_DEUR_REFUEL',auth.uid()::text,now_at,command->>'commandId',jsonb_build_object('manualWeb',true,'encoderUserId',auth.uid()::text,'operatorId',target.operator_id,'refuelId',created.id,'odometer',created.odometer,'liters',created.liters,'clientOccurredAt',client_at)); response:=jsonb_build_object('success',true,'disposition','ACCEPTED','record',to_jsonb(target),'version',target.row_version,'serverOccurredAt',now_at,'value',jsonb_build_object('refuelId',created.id,'odometer',created.odometer,'liters',created.liters)); RETURN erp.finish_deur_command(command,'MANUAL_RECORD_DEUR_REFUEL',target.id,payload_hash,response);
END $$;
CREATE OR REPLACE FUNCTION erp.command_complete_manual_deur_shift(command jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=erp,auth,extensions,pg_catalog AS $$
DECLARE tenant text:=erp.current_company_id(); scope jsonb; idem jsonb; payload_hash text; now_at timestamptz:=erp.deur_operational_clock(); target erp.deurs%ROWTYPE; policy text; closing_hour numeric; closing_odo numeric; latest_odo numeric; open_activity text; next_sequence integer; client_at timestamptz; effective_at timestamptz; predecessor timestamptz; response jsonb; chronology_code text; bootstrap_only boolean;
BEGIN
  IF erp.reject_manual_transcription_authority(command,ARRAY['commandId','idempotencyKey','deurId','expectedVersion','closingHourMeter','closingOdometer','clientOccurredAt','clientCreatedAt','deviceId']) OR nullif(btrim(command->>'commandId'),'') IS NULL OR nullif(btrim(command->>'idempotencyKey'),'') IS NULL OR nullif(btrim(command->>'expectedVersion'),'') IS NULL THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF; scope:=erp.validate_manual_deur_transcription_scope(command); IF scope->>'code'<>'OK' THEN RETURN jsonb_build_object('success',false,'code',scope->>'code'); END IF; idem:=erp.begin_deur_command(command,'MANUAL_COMPLETE_SHIFT'); IF idem->>'state'='MISMATCH' THEN RETURN jsonb_build_object('success',false,'code','IDEMPOTENCY_MISMATCH'); END IF; IF idem->>'state'='REPLAY' THEN RETURN (idem->'response')||jsonb_build_object('disposition','REPLAYED'); END IF; payload_hash:=idem->>'payloadHash'; SELECT * INTO target FROM erp.deurs WHERE id=command->>'deurId' AND company_id=tenant FOR UPDATE;
  IF target.creation_source<>'MANUAL_WEB' THEN RETURN jsonb_build_object('success',false,'code','MANUAL_DEUR_REQUIRED'); END IF; IF target.row_version<>(command->>'expectedVersion')::bigint THEN RETURN jsonb_build_object('success',false,'code','CONFLICT','currentVersion',target.row_version,'refreshRequired',true); END IF; IF target.status<>'In Progress' THEN RETURN jsonb_build_object('success',false,'code','INVALID_TRANSITION'); END IF; SELECT operational_metadata#>>'{deurExpectationSnapshot,meterRequirement}' INTO policy FROM erp.rental_equipment_lines WHERE id=target.rental_equipment_line_id AND company_id=tenant; BEGIN closing_hour:=nullif(trim(command->>'closingHourMeter'),'')::numeric; closing_odo:=nullif(trim(command->>'closingOdometer'),'')::numeric; client_at:=nullif(command->>'clientOccurredAt','')::timestamptz; EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END; chronology_code:=erp.validate_manual_deur_physical_occurrence(target,client_at,now_at); IF chronology_code IS NOT NULL THEN RETURN jsonb_build_object('success',false,'code',chronology_code); END IF;
  SELECT max(reading) INTO latest_odo FROM erp.deur_meter_checkpoints WHERE company_id=tenant AND deur_id=target.id AND meter_dimension='odometer'; latest_odo:=greatest(coalesce(target.opening_odometer,target.opening_meter),coalesce(latest_odo,0)); IF (closing_hour IS NOT NULL AND (closing_hour<0 OR (target.opening_hour_meter IS NOT NULL AND closing_hour<target.opening_hour_meter))) OR (closing_odo IS NOT NULL AND (closing_odo<0 OR closing_odo<latest_odo)) THEN RETURN jsonb_build_object('success',false,'code','CLOSING_METER_BELOW_OPENING'); END IF; IF ((policy IN ('odometer','both')) AND closing_odo IS NULL) OR (policy='odometer' AND closing_hour IS NOT NULL) OR (policy='hourMeter' AND closing_odo IS NOT NULL) OR (policy='none' AND (closing_hour IS NOT NULL OR closing_odo IS NOT NULL)) THEN RETURN jsonb_build_object('success',false,'code','VALIDATION_REJECTED'); END IF;
  bootstrap_only:=erp.manual_deur_has_only_encoding_bootstrap(target); IF bootstrap_only THEN RETURN jsonb_build_object('success',false,'code','INVALID_TRANSITION'); END IF;
  SELECT activity_type INTO open_activity FROM erp.deur_events WHERE deur_id=target.id AND is_open AND activity_type<>'shift' FOR UPDATE; SELECT max(occurred_at) INTO predecessor FROM erp.deur_events WHERE deur_id=target.id; IF predecessor IS NOT NULL AND client_at<predecessor THEN RETURN jsonb_build_object('success',false,'code','CLIENT_OCCURRENCE_BEFORE_PREDECESSOR'); END IF; effective_at:=client_at;
  UPDATE erp.deur_events SET is_open=false WHERE deur_id=target.id AND is_open; SELECT coalesce(max(sequence),0)+1 INTO next_sequence FROM erp.deur_events WHERE deur_id=target.id; IF open_activity IS NOT NULL THEN INSERT INTO erp.deur_events(id,deur_id,activity_type,action,occurred_at,sequence,source,actor_id,server_accepted_at,client_created_at,command_id,idempotency_key,device_id,is_open,company_id) VALUES(extensions.gen_random_uuid()::text,target.id,open_activity,'end',effective_at,next_sequence,'manual-web',auth.uid()::text,now_at,client_at,command->>'commandId',command->>'idempotencyKey',command->>'deviceId',false,tenant); next_sequence:=next_sequence+1; END IF; INSERT INTO erp.deur_events(id,deur_id,activity_type,action,occurred_at,sequence,source,actor_id,server_accepted_at,client_created_at,command_id,idempotency_key,device_id,is_open,company_id) VALUES(extensions.gen_random_uuid()::text,target.id,'shift','end',effective_at,next_sequence,'manual-web',auth.uid()::text,now_at,client_at,command->>'commandId',command->>'idempotencyKey',command->>'deviceId',false,tenant); UPDATE erp.deurs SET closing_hour_meter=CASE WHEN closing_hour IS NOT NULL THEN closing_hour ELSE closing_hour_meter END,closing_odometer=CASE WHEN policy IN ('odometer','both') THEN closing_odo ELSE NULL END,closing_meter=CASE WHEN policy='hourMeter' THEN closing_hour WHEN policy='odometer' THEN closing_odo ELSE NULL END,updated_at=now_at,updated_by=auth.uid()::text WHERE id=target.id RETURNING * INTO target; INSERT INTO erp.audit_log(id,company_id,aggregate_type,aggregate_id,action,actor_id,occurred_at,correlation_id,new_values) VALUES(extensions.gen_random_uuid()::text,tenant,'DEUR',target.id,'COMPLETE_SHIFT',auth.uid()::text,now_at,command->>'commandId',jsonb_build_object('manualWeb',true,'encoderUserId',auth.uid()::text,'operatorId',target.operator_id,'clientOccurredAt',client_at)); response:=jsonb_build_object('success',true,'disposition','ACCEPTED','record',to_jsonb(target)||erp.canonical_deur_meter_evidence(policy,target.opening_hour_meter,target.closing_hour_meter,target.opening_odometer,target.closing_odometer,target.opening_meter,target.closing_meter),'version',target.row_version,'serverOccurredAt',now_at); RETURN erp.finish_deur_command(command,'MANUAL_COMPLETE_SHIFT',target.id,payload_hash,response);
END $$;
ALTER FUNCTION erp.validate_manual_deur_physical_occurrence(erp.deurs,timestamptz,timestamptz) OWNER TO postgres;
ALTER FUNCTION erp.manual_deur_has_only_encoding_bootstrap(erp.deurs) OWNER TO postgres;
ALTER FUNCTION erp.command_record_manual_deur_activity(jsonb) OWNER TO postgres;
ALTER FUNCTION erp.command_record_manual_deur_travel_checkpoint(jsonb) OWNER TO postgres;
ALTER FUNCTION erp.command_record_manual_deur_refuel(jsonb) OWNER TO postgres;
ALTER FUNCTION erp.command_complete_manual_deur_shift(jsonb) OWNER TO postgres;
REVOKE ALL ON FUNCTION erp.validate_manual_deur_physical_occurrence(erp.deurs,timestamptz,timestamptz),erp.manual_deur_has_only_encoding_bootstrap(erp.deurs) FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION erp.command_record_manual_deur_activity(jsonb),erp.command_record_manual_deur_travel_checkpoint(jsonb),erp.command_record_manual_deur_refuel(jsonb),erp.command_complete_manual_deur_shift(jsonb) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION erp.command_record_manual_deur_activity(jsonb),erp.command_record_manual_deur_travel_checkpoint(jsonb),erp.command_record_manual_deur_refuel(jsonb),erp.command_complete_manual_deur_shift(jsonb) TO authenticated;
COMMENT ON FUNCTION erp.validate_manual_deur_physical_occurrence(erp.deurs,timestamptz,timestamptz) IS 'MANUAL_WEB-only physical-occurrence validation: work date is authoritative, while server encoding timestamps remain immutable.';
COMMENT ON FUNCTION erp.command_record_manual_deur_activity(jsonb) IS 'Office-only, MANUAL_WEB-only activity transcription. The first physical activity can rebase creation bootstrap events without backdating server acceptance or audit timestamps.';
COMMIT;
