import type { RentalEquipmentLine } from "@/features/rental/equipment-line";
import type { RentalRecord } from "@/features/rental/types";
import type { WorkDescriptionRecord } from "@/features/masters/work-description/types";

export function frozenDeurLine(input: { rental: RentalRecord; id?: string; equipmentId: string; operatorId: string; assignmentId?: string; work?: WorkDescriptionRecord; billingMethod?: "Per Hour" | "Per Day" | "Per Week" | "Per Month" | "Per Kilometer" | "Per Trip" | "Per Cubic Meter" | "One Lot"; unitRate?: number }): RentalEquipmentLine {
  const capturedAt = "2026-07-20T00:00:00.000Z"; const id = input.id ?? `rental-line:${input.rental.id}:${input.equipmentId}`;
  const metadata = input.rental.operationalMetadata ?? { costCode: { code: "C", name: "Cost" }, activityCode: { code: "A", name: "Activity" } };
  const work = input.work ?? { id: "work-1", code: "WORK", name: "Work", active: true, operatorSelectable: true, requiresRemarks: false };
  const billingMethod = input.billingMethod ?? input.rental.billingMethod ?? "Per Hour";
  return { id, rentalId: input.rental.id, equipmentId: input.equipmentId, assignmentId: input.assignmentId, operatorId: input.operatorId, status: input.rental.status, operationalMetadata: structuredClone(metadata), commercialSnapshotRequired: input.unitRate !== undefined || input.rental.commercialSnapshotRequired === true, ...(input.unitRate !== undefined ? { commercialSnapshot: { billingMethod, unitRate: input.unitRate, operatorIncluded: true, currency: "PHP", capturedAt } } : {}), deurWorkDescriptionId: work.id, deurExpectationSnapshot: { rentalEquipmentLineId: id, rentalId: input.rental.id, equipmentId: input.equipmentId, assignmentId: input.assignmentId ?? "assignment", operatorId: input.operatorId, projectId: input.rental.projectId ?? "project-1", ...(input.rental.customerId ? { customerId: input.rental.customerId } : {}), policy: input.rental.deurExpectationPolicy ?? { frequency: "ON_DEMAND", effectiveFrom: input.rental.dateOut, capturedAt }, shiftWindows: input.rental.deurShiftWindowSnapshots ?? [], workDescription: { id: work.id, code: work.code, name: work.name, requiresRemarks: work.requiresRemarks === true }, workDateRule: "RENTAL_DATE_OUT", workDate: input.rental.dateOut, meterRequirement: billingMethod === "Per Kilometer" ? "odometer" : "none", fuelEvidenceRequired: false, billingMethod, operationalMetadata: structuredClone(metadata), sourceFingerprint: "test-fixture", capturedAt }, createdAt: capturedAt, updatedAt: capturedAt };
}
